--· EN_US/Villages.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_IMPROVEMENT_TRADING_POST', 'Village', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADING_POST_TEXT', 'A village is a clustered human settlement or community with a population ranging from a few hundred to a few thousands. These small settlements add to your society''s economy.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CIV5_IMPROVEMENTS_TRADINGPOST', 'Village', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GOLD_TRADINGPOST_ADV_QUEST', 'Does the village provide gold?', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_BODY', 'Construct a village improvement in a tile to increase its gold output.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GOLD_TRADINGPOST_HEADING3_TITLE', 'The Village', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WORKERS_TRADINGPOST_HEADING3_BODY', 'The Village increases output of a tile by 1 gold. It doesn''t access a resource.[NEWLINE]Technology Required: Trapping[NEWLINE]Construction Time: 5 Turns[NEWLINE]May Be Constructed On: Any land tile but ice', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[COLOR_POSITIVE_TEXT]Free Thought[ENDCOLOR][NEWLINE]+1 [ICON_RESEARCH] Science on Villages.[NEWLINE]+17% [ICON_RESEARCH] Science from Universities.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILD_TRADING_POST', 'Construct a [LINK=IMPROVEMENT_TRADING_POST]Village[\LINK]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BUILD_GOLD_REC', 'It will increase the amount of [ICON_GOLD] Gold provided by this tile, boosting the amount of money we will have to spend!', '', '');
