/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Черты  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Вы получите дополнительную шпиона. Великих полководцев видеть дальше и дать больше сил. [NEWLINE] Начинается с Воина и Великой Генерального.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Выделение', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Ваша столица получает бесплатный сильное копии каждого нового блока линии вы исследуете.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Единицы двигаться быстрее вдоль рек, и начать с продвижения амфибии.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' +10% [ICON_GREAT_PEOPLE] Отличный тариф Люди из каждой Альянса, и +20% [ICON_STRENGTH] Боевой против цивилизаций с нескольких городов.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Холодное и авангардные подразделения стоить на 50% меньше технического обслуживания. Все блоки требуют на 25% меньше опыта, чтобы заработать себе на следующий продвижение по службе.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Производство к зданиям, которые уже существуют в [ICON_CAPITAL] Capital. Начинается с [ICON_RES_IRON] железа в первых 5 городах.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', '25% более высокие награды от дружественной и союзной городов-государств.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Эллинизация', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' +2 [ICON_CULTURE] Культура в каждом городе. Город-государство [ICON_INFLUENCE] Влияние деградирует в половине и восстанавливает в два раза с нормальной скоростью.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Внутренние торговые пути обеспечивают 10 [ICON_GOLD] Золото до места назначения.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Доходы [ICON_CULTURE] Культура от убийства вражеских юнитов.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' +50% [ICON_CULTURE] Культура и +1 [ICON_MOVES] Движение во [ICON_GOLDEN_AGE] Золотого Века. [NEWLINE] Начинается с уникальной Spearman.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' +1 [ICON_PEACE] Вера от незастроенных лесах и непроходимых джунглях, и 150% доходность от природных чудес. [NEWLINE] Начинается с Spearman.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Поврежденные единицы бороться в полную силу. Рыбацкие лодки и острова дают [ICON_CULTURE] Культура.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Гао милиции', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Vanguard единиц видеть дальше и двигаться быстрее.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Единицы двигаться быстрее на холмах. Дороги и железные дороги не стоят никакого обслуживания на холмах, половина стоить в другом месте.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Гражданские двигаться быстрее в пустыне. Ваши исходящие торговые пути с различными цивилизациями заработать больше [ICON_GOLD] Золото и [ICON_CULTURE] Культура и входящие торговые пути заработать больше [ICON_GOLD] для владельца маршрута.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Быстрее движение в лесах и непроходимых джунглях, которые считаются дорог в дружественной территории после исследования The Wheel. [NEWLINE] Запуск с уникальным Фехтовальщик.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Великие ученые появляются на 25% быстрее, и вы получите один в письменной форме. [NEWLINE] Начинается с Боуман.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert Караваны', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Единицы двигаться быстрее в пустыне, караваны достичь дальше, и торговые пути распространяться религия быстрее от ваших городах.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'После исследования богословие, получать бонус великий человек в конце каждого Майя Лонг календарного Граф цикла (каждые 394 лет). [NEWLINE] Запуск с уникальным Арчер.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Каждый увеличивается роскошь ресурсов [ICON_GOLD] Золото доход на 5%.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' +20% [ICON_PRODUCTION] Производство к Wonder строительства.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' +30 [ICON_WAR] Опыт для судов.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Выберите еще один Вера, чем обычно, когда вы нашли Религия.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Порты получить бесплатную Харбор, и единицы могут пересечь горы. Начинается с парусный спорт, в бирема и воинов.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Плановая экономика', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Единицы см. дальше, гражданские двигаться быстрее, а вы получаете 1 меньше [ICON_HAPPINESS_4] Национальный Несчастье за ​​город.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Пищевые здания добавить 1 [ICON_CITIZEN] Население, когда строится. [NEWLINE] Начинается с работника.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Варварские лагеря сдаться, когда победил за двухместный [ICON_GOLD] Gold. [NEWLINE] Запуск с лошадью Арчер.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'Американская мечта', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Иммигранты переехать сюда из цивилизаций с низким счастья и высокой американской культурного влияния. Ваши граждане мигрируют вдоль внутренних [ICON_FOOD] Еда торговых путей.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Династия Чосон', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' +2 [ICON_RESEARCH] Наука из ферм. [NEWLINE] Начинается с работника.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Двойные выходы из природных чудес, плюс 100 [ICON_GOLD], когда обнаружил. [NEWLINE] Начинается с Scout, и получает Caravel на компас.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Ганзейский союз', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Двойное количество из стратегических ресурсов, и 3 дополнительных голосов в World Congress.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Быстрее и сильнее посадочных по воде, и рукопашных юнитов грабить быстрее.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Монгол Террор', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'Город-государства можно хулиган сдаться в страхе, как марионетками. Установленный и перестрелка единиц двигаться быстрее. Начинается с Scout.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Дань', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Внутренние торговые пути между ваших городов обеспечивают 10 [ICON_GOLD] Золото до места назначения.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Реконкиста', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Покоряя города увеличивает [ICON_PEACE] Веру.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Бич Божий', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Варварские лагеря сдаться, когда победил, и земельных единиц стоить меньше [ICON_GOLD] обслуживание. [NEWLINE] Запуск с лошадью Арчер.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Бич Божий', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Варварские лагеря сдаться, когда победил, и земельных единиц стоить меньше [ICON_GOLD] обслуживание. [NEWLINE] Запуск с уникальным Колесницы.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Амстердам Биржа', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' +5% [ICON_GOLD] национальный доход от каждого типа Luxury ресурс под вашим контролем или импорта.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] Гражданин мигрировали из {1} по {2}.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] иммигрант из {1} прибыл в {2}.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] Гражданин эмигрировал из {1} по {2}.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Вы получили {1} {2} {3} из захвата {4}!', '', '');


/*  Кол-во  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Императорский-Royal Горные Войска', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Современность блок, что только австрийцы могут построить. Он является более мощным и добавил акции, что обычный блок не.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Это устройство имеет мощные преимущества во всех холодную погоду местности. Боевые действия в тундре, снег, холмы и даже горы.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'The Imperial-Royal Горные Войска (нем. Kaiserlich-Königlich Gebirgstruppe). Были основаны в 1906 году как часть австрийской Ландвер, территориальной армии Cisleithanian половине Австро-Венгерской империи [NEWLINE] Предлагаемый в меморандуме Конрада фон Hötzendorf , в феврале 1906 военное министерство в Вене созвал заседание по безопасности Alpine границы. Фельдмаршал Tunk, согласился с ним и выдвинул концепцию, основы которой затем были проведены. [NEWLINE] Существующие государственные стрелковые полки были быть обучены как горные войск и вместе с Пограничной службы компаний Ландштурм и жандармерии ведомств были сформировать костяк территориальной обороны, силы с местными знаниями на границе Тироля [NEWLINE] [NEWLINE] батальонов и рот были даны вьючных животных и были выпущены с дополнительной установкой, приспособленной к требованиям горной войны;. включая лыжи, канаты, кошки и ледорубы. Полки были подкреплены пушки разделе гора машины из четырех пулеметов, которые, по улучшению мобильности, могут быть реализованы с помощью вьючных животных или в manportable пакеты на самых высоких высотах. То же самое касается приемной кроме горных пушек. Портативные полевые печи (Schwarmöfen) и подогревом палатки помощь войска работать в суровых условиях. [NEWLINE] Когда лыжах подход две палки заменил метод одной палкой. Связывания Bilgeri был туристическим связывания, которые могут быть использованы с нормальным походы загрузки. Винтовка была заменена (короткий) 8мм Маннлихера M 95 карабин.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Уникальный сонгаи установлен блок. Mandekalu кавалерийский начинается с продвижения Siege, в отличие от Рыцаря он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Мощный Средневековый воин уникальными для японцев. Самурай может атаковать дважды в свою очередь, и сильнее, чем Longswordsmen они заменяют.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Уникальная вавилонская лучник блок. Боуман сильнее Арчер он заменяет, и двигаться быстрее в пустынях.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Солдат эпоху средневековья уникальной в Данию. Берсерк начинается с продвижения заряда, в отличие от Longswordsman он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Мобильная установка уникальна для Германии. Panzer имеет более высокую прочность, скорость и видимость, чем танк он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Рано-игра солдат уникальным для ацтеков. Jaguar лечит повреждения, когда он убивает врага, и борется более эффективно в джунглях, чем Воина он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Ренессанс Авангард Единица уникальным для американцев. Это сильнее, чем Skirmisher он заменяет, видит дальше, и движется быстрее в пересеченной местности.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'Одним из первых пороховых единиц игры, уникальные для французов. Мушкетеры есть боевой бонус за пределами своей территории, в отличие от Musketman он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Солдат уникальным для ирокезов. Mohawk Воин борется сильнее в лесу и джунглях, чем Фехтовальщик он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Солдат уникальным для османов. Янычары гораздо сильнее в атаку и заживает после убийств, в отличие от Musketman он заменяет.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Единицы в течение 1 плитки [COLOR_POSITIVE_TEXT] Лечение 4 Дополнительная HP [ENDCOLOR] за ход.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'Уникальная монгольский замена для рыцаря движется быстрее, колеблется, и не разделяет уязвимости Рыцарским в городах или копейщиков. Кешик также зарабатывает опыт быстрее.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Мощный римский солдат классической эпохи с бонуса против городов. Легион имеет более высокую прочность, чем Фехтовальщик он заменяет, дополнительная защита от дальних атак, и может строить дороги с удвоенной скоростью работников.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'Liburna был тип небольшой камбуз используется для рейдов и патрулей, в частности римского флота. [NEWLINE] [NEWLINE] В своем первоначальном виде, Liburna была одна скамья с 25 веслами на каждой стороне, в то время как в конце Римской республики, он был оснащен двумя рядами весел (бирема), оставшихся быстрее, легче и проворнее, чем триер. Liburnian дизайн был принят римлянами и стал ключевой частью флота древнего Рима по 2-й половине 1-го века до нашей эры. Liburnians сыграл ключевую роль в битве при Акции в Греции, который видел создание Августа в качестве бесспорного правителя римского мира. [NEWLINE] Liburnians отличались от боевых триер, quadriremes и quinqueremes не из-за гребле а скорее из-за его конструктивных особенностей. [NEWLINE] [NEWLINE] После того, как римляне приняли Liburnian, они продолжили бы сделать несколько приспособлений для улучшения использования кораблей "в рамках военно-морского флота. Преимущества получила от добавления баранов и защиты от ракет больше, чем готовых для небольшой потерей скорости. Кроме строительства, корабли требуется, что регулярное римский военный блок упростить, чтобы функционировать более гладко. Каждое судно работает как отдельного субъекта, так что сложнее организация обычно используется не было необходимости. В военно-морском флоте, было, вероятно, Liburnian из нескольких различных размеров, все ставится на конкретных задач, таких как разведку и патрулирование римские воды с пиратством. Римляне использовали Liburnian особенно в провинциях империи, где корабли основу парка флотов. [NEWLINE] Постепенно Liburnians стал общим названием для различных типов римских кораблей, прилагается также к грузовым судам в конце Античность. Тацит и Светоний использовали его в качестве синонима для боевой корабль. В надписях было отмечено, как последний в классе боевых кораблей: hexeres, penteres, quadrieres, trieres, Liburna.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'Liburna является первой военно-морской блок Рима. Это устройство Ближний бой без дальнего боя силы. Liburna полезно для очистки варварские корабли из домашних водах и для ограниченного разведки.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Рим использовал эти сосуды контролировать воды и защищать свои торговые пути.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Мощный мобильный блок уникальный в Индию. В отличие от всадника его заменяет, Боевой слон колеблется, не требует лошадей и не имеет уязвимость к Копьеносцы.', '', '');
/*  Разное  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Управление торговли', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Османская Дань', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' +3 [ICON_CULTURE] Культура. [NEWLINE] +1 [ICON_CULTURE] Культура в соседней моаи. [NEWLINE] [ICON_LOCKED] Должен быть рядом с побережья.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' +3 [ICON_CULTURE] Культура. [NEWLINE] +1 [ICON_CULTURE] Культура в соседней моаи. [NEWLINE] [ICON_LOCKED] Должен быть рядом с побережья.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' +3 [ICON_CULTURE] Культура. [NEWLINE] +1 [ICON_CULTURE] Культура в соседней моаи. [NEWLINE] [ICON_LOCKED] Должен быть рядом с побережья.', '', '');
/*  Амстердам Биржа  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Амстердам Биржа', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'Амстердам фондовая биржа считается старейшим в мире. Она была создана в 1602 г. голландской Ост-Индской компании для операций с ее печатных акции и облигации. Впоследствии она была переименована в Амстердам Биржа и был первым, кто официально начать торговать ценными бумагами.', '', '');
/*  Jelling Камни  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Еллинге Stones', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'В JELLING камни массивные резные Руна из 10-го века, найденные у города Еллинге в Дании. Старший из двух камней JELLING был поднят королем Горм в память о своей жене Тире. Больший из двух камней был поднят Харальд Bluetooth, сына короля Горм автора. Харальд построил второй камень в память о его родителях, празднования его завоевания Дании и Норвегии, а также его конверсии датчан в христианство. В рунические надписи на этих камнях считаются наиболее хорошо известны в Дании.', '', '');
/*  Джейд зал  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Джейд зал', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'Король Sejong курировал развитие Chiphyonjon, Нефритового зале ученых, профессиональных ученых, которые помогли исследования социальных и политических вопросов для короля и правительства. Нефритовый зал будет считаться "мозговой центр" правительствами сегодня.', '', '');
/*  Инд санитарии  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Инда санитарии', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'Хараппская цивилизация долине реки Инд ориентирован в первую известные городских систем канализации в мире вокруг 2600 до нашей эры. Отдельные дома или группы домов получены воду из колодцев. Сточные воды был направлен из комнаты, отведенных для купания в охваченных канализацию, выстилающих главные улицы. Массивные стены Harappan городах были предположил, чтобы защитить от затопления. Эти хараппские гидротехнические системы были еще более эффективной, чем у многих районах Пакистана и Индии сегодня, достижения больших городских городов с относительно небольшим развития сельского хозяйства.', '', '');
/*  Pioneer  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Пионер', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Основывает новые города, чтобы расширить свою империю. [NEWLINE] [NEWLINE] [ICON_FOOD] рост города останавливается, когда это устройство строится. [NEWLINE]', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'Pioneer является американский Уникальный блок. Она движется быстрее, чем в отстойник он заменяет. [NEWLINE] [NEWLINE] использовать данный прибор для строительства новых городов. Это не может защитить себя, поэтому сопровождать его с боевой единицы.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Американские пионеры любой из людей в истории США, которые мигрировали на запад от побережья Атлантического океана для проведения расчетов и развивать новые направления. Термин особенно относится к тем, кто собирался поселиться территорию новое европейского или американского общества, хотя территория, возможно, была заселена или используются коренными народами. [NEWLINE] [NEWLINE] Пионером концепция и дух значительно предшествуют миграции в части Соединенных Штатов в настоящее время называется «западных» государств, как много мест в настоящее время рассматриваются как Востока также были урегулированы пионеров от берега. Например, Дэниел Бун, ключевой фигурой в американской истории пионерской, поселился в Кентукки, когда это "Кентукки" была еще не разработаны. [NEWLINE] [NEWLINE] Важным событием в Западной урегулирования был Закон усадьба, в котором содержится формальное законодательство, которое регулирует процесс урегулирования.', '', '');
/*  Паровая мельница  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Паровая мельница', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Начался переход к основе машин, заводов в экономике Великобритании в 1700-х годах, ранее зависящих от ручного труда и рабочего скота. Эти прекурсоры промышленной революции началось с механизации текстильной промышленности. Расширение торговли стало возможным благодаря внедрению каналов, улучшенных дорог, и железных дорог. Более широкое использование водных колес и внедрения паровой энергии толкнул резкое увеличение производственных мощностей. Развитие цельнометаллических станков в начале 1800-х годов способствовал строительству более изысканных производственных машин для изготовления в самых различных отраслях.', '', '');
/*  Додзе  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Додзе', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Японский додзе ("место пути '') является местом сбора для проведения подготовки, экзамены, и других связанных с встречи для" делать "искусства. Додзе были первоначально дополнением к вискам. В Японии любая физическая учебный центр, в том числе профессиональных школ борцовских, можно назвать додзе, потому что из его близких корней боевых искусств.', '', '');
/*  Храм  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Синтоистский храм', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'В Японии синтоистских святынь существуют бок о бок с буддийских храмов, и самые многочисленные, известные и важные религиозные сайты в Японии. Синтоистский храм представляет собой структуру или объект основной целью которого является в дом один или несколько Синто ками (духи, природных сил, или сущность). Ками может находиться в почти ничего естественного или техногенного, от Mt. Fuji к небольшой драгоценный камень. Как таковые, эти святыни являются общими и отличаются друг от друга по своим масштабам. Сам Храм может быть большое здание или небольшой объект, вдоль дороги, или, возможно, даже быть осуществлено людьми. [NEWLINE] [NEWLINE] Как буддийских храмов, синтоистских святынь в первую очередь не местом поклонения. Наиболее важные здания Храме используются для хранения священных предметов. Существуют специализированные здания для определенных обрядов, но они, как правило, открыты только для ограниченного числа участников. Религиозные массовых скоплений в стиле христианских церквей не происходят с регулярностью и не проводятся внутри святыни. Если многие люди участвуют в церемонии, она возьмет на себя праздничный характер и будет проходить на открытом воздухе.', '', '');
/*  Folkskola  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'В 1842 году парламент Швеции представила четыре года начальной школы для детей в Швеции, "Folkskola" (школа народный). Это был один из самых ранних государственных школ в мире. [NEWLINE] [NEWLINE] шведские дети обязаны посещать grundskola, обязательное школу, в возрасте от 7 до 16, где grundskola является комбинацией начальной и средней школы. После grundskola, многие шведы присутствовать на выборную gymnasieskolan, гимназии, выбирая либо университетский-подготовительная программа или программы профессионального. Студенты, которые выбирают программы профессионального обычно прекратить свое образование после gymnasieskolan а студенты, которые заканчивают высшее-подготовительная программа обычно поступают в высшее образование в университете или университетском колледже. Студенты, закончившие программы профессионального могут поступить в высшее образование, но, возможно, потребуется принять дополнительные курсы, прежде чем право применять.', '', '');
/*  Базилика  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Базилика', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'Латинское слово базилика (происходит от греческого Стоа Трибунал палаты царя) был первоначально использовался для описания римского общественного здания, расположенного в форуме римского города. В более широком смысле, она была применена к христианских зданий того же вида. [NEWLINE] [NEWLINE] В 4 веке, после того, как Imperial власти декриминализация христианство с 313 Миланского эдикта, христиане были готовы строить более крупные и красивые сооружения для поклонение, чем украдкой конференц-мест они были с использованием. Традиционные архитектурные формулы для храмов были непригодны из-за ассоциаций с не-христианских верований. Старый храм церемонии произошло на улице под открытым небом в глазах богов, с храмом, как фон. Модель Константин хотел memorialise за его императорского благочестия был архитектура (ранее светских) базилик, держа церемонии в помещении.', '', '');
/*  Cothon  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'Cothon (греч. "сосуд для питья") представляет собой искусственный, защищены внутренняя гавань распространены в Карфагене во время c.200 до н.э. Пунических войн [NEWLINE] Cothons, как правило, найти в финикийского мира.. Примеры включают Мотя (Сицилия) с 6-го века до нашей эры, который выполняется с неопределенным цель, (размером 35 м х 51 метров), хотя было высказано предположение, это cothon Возможно даже, замыкаем и осушаемыми сформировать сухой док. Махдия (Тунис) с 7-го века до нашей эры, (который измерил 72 м х 56 м) и один из Китиона на Кипре.', '', '');
/*  Веди  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Веди', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Веди это термин для "изменить" в ведической религии, старейший религия до сих пор практикуется в наше время. Такие алтари повышенный корпус, как правило, сыплется с травой куша, и имеющие сосуды для жертвенного огня.', '', '');
/*  НАСА Центр  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'НАСА Центр', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'НАСА Центр Современность исследовательский центр, который предоставляет увеличение технологии. Она также обеспечивает ресурсов бесплатно Космический корабль Factory.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'С момента своего создания в 1958 году, НАСА совершил много великих научных и технологических подвиги в воздушно-космическом пространстве. Технология НАСА также была адаптирована для многих применений nonaerospace в частном секторе. НАСА остается ведущей силой в научных исследованиях и в стимулировании общественного интереса к аэрокосмической разведки, а также науки и техники в целом. Возможно, более важно, наша разведка пространства учит нас, чтобы посмотреть в Землю, себя и Вселенную по-новому. В то время как огромные технические и научные достижения НАСА демонстрируют ярко, что люди могут достичь ранее немыслимые подвиги, мы также унижен осознанию того, что Земля является лишь малая "голубой мрамор" в космосе.', '', '');
/*  Abbey  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Аббатство', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'Аббатство имеет в своем сердце практике поклонения, с идеей, чтобы не получить всех на одной услуги, но и обеспечить возможности для поклонения, что Abbey приверженцы могут участвовать в регулярно, если не еженедельно. С помощью своих услуг, процветали искусства как выражение хвалы "Творца". Кроме того монастырей были самонесущие, занимается культивирования полей, животноводства, работающих публичных рынках, и давая возможности трудоустройства для сообщества. В монастыри Кельтские стал центры обучения, сохранения священных и литературных рукописей и школ обучения.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'Аббатство Селтик духовным и культурным центром каждой общины. Она производит 1 [ICON_FOOD] Продукты питания, [ICON_RESEARCH] Наука, [ICON_CULTURE] Культура, [ICON_GOLD] Золото и [ICON_PRODUCTION] производства.', '', '');
/*  Одеон  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Одеон', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Одеон, от древнегреческого ᾨδεῖον, Ōideion, буквально "петь место", или "строит для музыкальных конкурсов". [NEWLINE] Самый роскошный Одеон был Одеон Ирода Аттика на юго-западном утесе Акрополя в Афинах, построенной примерно в 160 н.э. на богатом софиста и ритора Ирода Аттика в память о своей жене. Он имел жилье для 8000 человек, а потолок был построен красиво вырезанными лучами из кедрового дерева, вероятно, с открытым пространством в центре признать свет. Было также обильно украшены картинами и другими произведениями искусства.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'Odeon является источником мгновенного [ICON_CULTURE] культуры. Строительство них поможет распространить границы вашего империи.', '', '');
/*  Барбари Порт  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Барбари Порт', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'Барбари пираты, иногда называемые корсары Барбэри или османские пираты, пираты и частников, которые действовали из Северной Африки, основывается главным образом в портах Тунисе, Триполи и Алжир. [NEWLINE] [NEWLINE] Этот район был известен в Европе как Барбари побережье , термин происходит от имени его обитателей берберских. [NEWLINE] В дополнение к захвату кораблей, они занимались набегами, налетов на европейских прибрежных городов и поселков, в основном в Италии, Франции, Испании и Португалии, но и в англичан Острова, Нидерланды и так далеко, как Исландия. Основная цель их атак было захватить рабов-христиан для мусульманского рынка в Северной Африке и на Ближнем Востоке.', '', '');
/*  Бассейна орошения  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Бассейна орошения', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Древние египтяне практиковали бассейна орошения с использованием разливы Нила к затоплению земельных участков, которые были окружены дамб. Паводковых вод был проведен до плодородная осадок не поселились перед профицит был возвращен водотока. [NEWLINE] Существует свидетельство древнего египетского фараона Аменемхета III в двенадцатом династии (около 1800 г. до н.э.), используя естественное озеро Фаюме Oasis в качестве резервуара для хранения излишков воды для использования во время сухих сезонов, озеро ежегодно увеличилось с разлива Нила.', '', '');





UPDATE Loaded File SET Value=1, RU_RU=1 Where Type='Leaders.sql';




