/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Призыв на военную службу', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' +10 [COLOR_POSITIVE_TEXT] Лечение Оценить [ENDCOLOR].', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Профессиональная армия', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Открывает передовые рекламные акции.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Меркантилизм', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' +2 [ICON_MOVES] Движение.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Свобода', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' +25% [ICON_STRENGTH] Сила на дружественной территории.', '', '');
/*  Свобода  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Культура: +1 во всех городах [NEWLINE] [ICON_PRODUCTION] Производство: +1 во всех городах [NEWLINE] [ICON_WORKER] Открывает: Терракотовая Армия [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Великий лицо: +1 выбора', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] поселенец: +1 [NEWLINE] [ICON_PRODUCTION] Производство: +25% для Settlers', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Золото: +200 х Эра [NEWLINE] [ICON_CULTURE] Новые города увеличить Политика расходы 33% меньше.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Работники: +1 [NEWLINE] [ICON_WORKER] работник Улучшение Цена: +25%', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 национального счастья за [ICON_CONNECTED] подключенного города. [NEWLINE] [ICON_HAPPINESS_4] -5% Несчастье от [ICON_CITIZEN] населения в городах, которые не [ICON_OCCUPIED] оккупированных.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] Бесплатный здание Город обороны во всех городах (текущий, новый, и завоевал). С соответствующей технологии исследовал. [NEWLINE] [ICON_PRODUCTION] +1 Производство за градостроительства обороны.', '', '');
/*  Традиция  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Культура: +3 в Капитал [NEWLINE] [ICON_WORKER] разблокирует: Banaue рисовые террасы [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR ] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Великий гостя:. +50% [NEWLINE] [ICON_CULTURE] удваивает культурного пограничный экспансию на плитки далеко от городов [NEWLINE] [ICON_PEACE] Можно приобрести замечательные инженеры с Вера, начиная с промышленной эпохи.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Рассказчиков', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Культура: +2 за деревня и дворец', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'Устная традиция является культурный материал и традиции передавались устно от одного поколения к другому. Сообщения или свидетельство устно передается в речи или песни и может принимать форму, например, сказок, поговорок, баллады, песни, или песнопения. Таким образом, это возможно для того, чтобы общество передавать вербальное историю, устное литературу, устное судами, и другие знания из поколения в поколение без системы письма.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Ритуальные обряды', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Культура: +1 за культуры Building [NEWLINE] [ICON_CULTURE] 1 бесплатно Культурный Строительство в ваших старейших 4 городах.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Церемония является событием ритуальное значение выполненной по особому случаю. Церемонии может иметь физическое дисплей или театральный компонент: танец, шествие, возложение рук. Декларативный словесное высказывание может быть связано с случаю. [NEWLINE] [NEWLINE] Церемония может отметить обряд посвящения в человеческой жизни, отмечая значимость рождения, взрослой жизни, посвящения в составе группы или смерти. Иногда церемония может быть проведена только лицо с определенным органом. Общество всей церемонии могут отмечать ежегодно или сезонные или периодические события, такие как день весеннего равноденствия, зимнего солнцестояния и другие ежегодные астрономические позиции.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Излишки продуктов питания: +25% за город [NEWLINE] [ICON_FOOD] Еда: +2 за город', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Город атаки: +50% от гарнизонов [NEWLINE] [ICON_GOLD] Нет обслуживания для гарнизон единиц.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Производство: +15% для чудес [NEWLINE] [ICON_HAPPINESS_1] Счастье: +1 в 10 [ICON_CITIZEN] Граждане', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Граждане в столице создать 0,5 [ICON_GOLD] Золото и 0,5 [ICON_HAPPINESS_1] Счастье.', '', '');
/*  Честь  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Способности:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] показывает варварские лагеря [NEWLINE] [ICON_STRENGTH] +10% Сила против варваров [NEWLINE] [ICON_CULTURE] Убийство варвары дает 2 Культура в . Сила поверженных врагов [NEWLINE] [ICON_WORKER] Открывает: Храм Артемиды [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Город Счастье: +1 за Бараки', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] обороны Единицы в столице. [NEWLINE] +20% [ICON_PRODUCTION] Производственные для военных юнитов и строений.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Трофеи', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] бабло золота из оборудования поверженных врагов. [NEWLINE] [ICON_CITY_STATE] +25% награды от захвата города-государства.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Мародерство по победоносной армии во время войны был обычной практикой на протяжении всей истории. Для пехотинцев, это рассматривалось как способ пополнить свой зачастую скудный доход и был частью празднования победы. На более высоких уровнях, гордый выставка добычи является неотъемлемой частью типичной римской триумфа, и Чингисхан не было ничего необычного в провозгласив, что самое большое счастье было "победить ваших врагов ... их ограбить их богатства ..." [NEWLINE] [NEWLINE] В войне в древние времена, военная добыча включены побежденных населения, которые часто порабощенных, а женщин и детей, которые часто всасываться в популяции победившего страны. Другими предварительно современных обществах, предметы из драгоценных металлов были предпочтительным объектом войны грабежей, в основном из-за их удобства транспортировки. Во многих случаях грабежей была возможность получить сокровища, которые в противном случае не были бы доступны. С 18-го века, произведения искусства все чаще становятся популярным объектом. В 1930-х и даже более того во время Второй мировой войны, нацистская Германия занимается больших масштабах и организовал разграбление искусства и имущества.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Гладиаторы', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Город Счастье: +1 за Arena [NEWLINE] 2 [ICON_TEAM_2] обороны единиц в столице..', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'Военные эпопеи', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' +1 [ICON_HAPPINESS_1] Город Счастье от культуры зданий.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Эпическая (от древнегреческого прилагательного ἐπικός (epikos), от ἔπος (эпос) "слово, история, поэма") является длительным поэма, обычно относительно серьезный предмет, содержащий подробную информацию о подвигах и событиях значительная к культуре или нации . [NEWLINE] [NEWLINE] Военные эпопеи являются эпические поэмы или литературные произведения эпического характера, которые стремятся или, как полагают, чтобы захватить и выразить суть или дух той или иной нации или этнической или языковой группе с стремлений к независимости или автономии. Национальные эпосы часто рассказывают о происхождении нации, часть ее истории, или на важнейшее мероприятие, таких как решающих побед или победить горьких противников, в развитии национальной идентичности', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Город Счастье: +1 за Гаррисон [NEWLINE] [ICON_CULTURE] Культура: +2 за Гаррисон', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Великий Общие сведения: +1 [NEWLINE] [ICON_MOVES] Движение:. +1 Для великих полководцев [NEWLINE] [ICON_STRENGTH] +15% Сила для всех ИБП, прилегающих к других дружественных воинских частей.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% при [COLOR_POSITIVE_TEXT] рядом [ENDCOLOR] для дружественных воинских частей.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] Обновление стоимость: -50% для блоков [NEWLINE] [ICON_PRODUCTION] Производство: +15% для всех подразделений', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Воин код [ENDCOLOR] [NEWLINE]', '', '');
/*  Благочестие  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Способности:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Культура +1 [NEWLINE] [ICON_PEACE] Вера +1 [NEWLINE] [ICON_PRODUCTION] Двойной Продукция для святынь [ICON_WORKER] Открывает: Стоунхендж [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] Выберите один новый Благочестивый веру.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Благотворительность', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Золото: +25% от храмов [NEWLINE] [ICON_GOLD] Золото: +2 от храмов [NEWLINE] [ICON_GOLD] Золото: 3 святые места.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'Слово "благотворительность" происходит от старого французского слова "Шарите", который, в свою очередь, происходит от латинского «Каритас». [NEWLINE] [NEWLINE] Практика благотворительности означает добровольную дачу помощью нуждающимся, кто не имеет отношения к дарителю, хотя первоначальное значение является более сложным с понятиями драгоценность, дороговизны, высокой цене. Благотворительные пожертвования осуществляется непосредственно или с помощью благотворительному фонду или другой достойной причине. Эти учреждения развивались, чтобы выполнять труд оказание помощи бедному населению, и стали называть, называемые «благотворительные». В "благотворительных" Modern Times обеспечивают основную часть благотворительных пожертвований, в денежном выражении. Типы благотворительных включают детские дома, продовольственных банков, религиозные институты, посвященные заботиться о бедных, больницы, организаций, которые посещают выходящих из дома и заключен в тюрьму, и многие другие.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Вдохновение', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Бесплатный Великий Пророк: +1', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'Слово "вдохновение" происходит от латинского существительного Inspiratio и от глагола inspirare. Inspirare это термин, соединение в результате от латинского префикса в (внутрь, в) и глагола spirare (дышать). [NEWLINE] [NEWLINE] В классических римских времен, inspirare уже стало означать "глубоко дышать" и предполагается также переносном смысле "привить [что-то] в сердце или в уме кого-то". [NEWLINE] [NEWLINE] Следовательно ''вдохновение'' относится к бессознательном порыве творчества в литературных, музыкальных или других художественного творчества. Концепция имеет истоки в обоих эллинизма и гебраизма. Греки верили, что вдохновение пришло из муз, а также богов Аполлон и Дионис. Аналогичным образом, в древних скандинавских религий, вдохновение происходит от богов, таких как Одина. Вдохновение также божественное дело на иврите поэтики. В Книге Amosthe пророка говорит о быть раздавленными голос Бога и вынужден говорить. В христианстве, вдохновение есть дар Святого Духа.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Толерантность', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Город Счастье: +1 за Культовые здания и сооружения [NEWLINE] [ICON_PEACE] Города с несколькими религиями также получить бонус пантеоне второй самой популярной религией города.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Толерантность или терпимость "практика намеренно позволяя или разрешение вещь, одна из которых не одобряет. Можно осмысленно говорить о терпимо, то есть разрешение или разрешений, только если он находится в состоянии запретить". Кроме того, было определено как " принести или вытерпеть »или« питать, поддерживать или сохранить ". Терпимость не может означать" не больше, чем терпение и разрешения данного сторонниками доминирующей религии к другим религиям существовать, хотя последний смотрятся на с неодобрением, как уступает, ошибочно или вредным "[NEWLINE] [NEWLINE] Толерантность отношение виду, что подразумевает непредвзятое принятие различных образов жизни или убеждений, в то время как терпимость предполагает мирятся с чем-то, что один не одобряет. [NEWLINE] [NEWLINE] Исторические примеры из "терпимости" предостаточно. Например в акте толерантности, персидский царь Кир Великий, как полагали, выпущен евреев из плена в 539-530 г. до н.э., и разрешается их возвращения на родину.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Единство', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Золотой век Включает: 10 [NEWLINE] [ICON_GOLDEN_AGE] Золотой век требует на 50% меньше [ICON_HAPPINESS_1] национального счастья', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Единство относится к связей в обществе, которые связывают людей друг с другом. Термин обычно используется в социологии и других общественных наук. [NEWLINE] [NEWLINE] В простых обществах он может быть в основном базируется на родстве и общих ценностей. В более сложных обществах существуют различные теории относительно того, что способствует формированию чувства социальной солидарности [NEWLINE] [NEWLINE] Это приводит в соответствующем срока ''солидарности », о котором сказано:. [NEWLINE]" Солидарность не предполагает, что Наша борьба те же борьба, или, что наша боль такая же боль, или, что наша надежда на то же время. Солидарность предполагает приверженность, и работать, а также признание того, что, даже если мы не имеем те же самые чувства, или те же жизнь, или те же органы, мы живем на общих основаниях ". - Сара Ахмед', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Медитация', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Вера: +1 Святыни, храмы [NEWLINE] [ICON_PEACE] Вера Затраты: -33%', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Преданность', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'х', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'Преданность может быть определена как: пылкой, часто самоотверженный любви и преданности, как к человеку, или принципа. Поклонение, от старого английского worthscipe, то есть достоинство или стоит корабль является актом религиозной преданности, как правило, направлены на божества. Тесно связан с понятием любви, преданность часто надеялся быть взаимностью с некоторой формой благо или благословения. [NEWLINE] [NEWLINE] Преданные, как те, кто практикует преданность называются желая получить эти благословения, часто целеустремленной, чтобы точка фанатизма. Таким образом в то время как понятие «преданность» является доброкачественной, многие исторические примеры религиозной преданности часто экстремальных и кровавый, как преданные соперничают за любовь преданный с более возмутительных проявлений.', '', '');
/*  Богатство  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Богатство', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'БОГАТСТВО', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'Богатство является обилие ценных ресурсов или материальных ценностей. Понятие богатства является значительным во всех областях экономики, но смысл богатства зависит от контекста и нет универсально согласованного определения. На богатства наиболее общий уровень является "ничего ценного", который захватывает как субъективный характер слова, и идея, что это не фиксированная или статическое понятие.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'Какова социальная политика филиал Богатство о?', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'Филиал богатства фокусируется на развитии обширную территорию, с национальной поставку [ICON_GOLD] Золото созданной основных городах на приобретение новых единиц и зданий в неразвитых городах приграничных.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'Филиал богатства фокусируется на развитии обширную территорию, с национальной поставку [ICON_GOLD] Золото созданной основных городах на приобретение новых единиц и зданий в неразвитых городах приграничных. Ознакомиться с правилами в области социальной политики для деталей.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'Богатство Отрасль', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_GOLD] Золото: +10% {TXT} [NEWLINE] [ICON_PRODUCTION] Производство: +10% {TXT} [NEWLINE] [ICON_WORKER] Открывает : Панамский канал [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Счастье: +1 за рынок, кузница [NEWLINE] [ICON_PEACE] Можно приобрести замечательные Merchants с Верой при входе в индустриальную эпоху.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' +2 [ICON_MOVES] Движение за небоевых подразделений. [NEWLINE] +25% [ICON_GOLD] Доходы от [ICON_CONNECTED] Внутренняя торговля. [NEWLINE] -25% [ICON_GOLD] Стоимость для автомобильных и железных дорог.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Золото: +1 за Village [NEWLINE] [ICON_PRODUCTION] Производство: +1 за Mine, лесопилки', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Можно приобрести ландскнехтов. [NEWLINE] [ICON_TEAM_2] 2 ландскнехтов появляются в столице.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Бесплатный Великий Торговец: +1 [NEWLINE] [ICON_GREAT_PEOPLE] Великий Торговец Цена: +25% [NEWLINE] [ICON_GREAT_MERCHANT] двойное золото из Великих Торговец торговых миссий.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Караваны', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Золото: +3 за Торговый путь', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Производство: +4 за прибрежный город [NEWLINE] [ICON_GOLD] Золото: +4 за Маяк, гавань, порт', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Гильдии', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' +1 [ICON_TEAM_7] Великий Торговец в столице. [NEWLINE] +100% [ICON_GOLD] Золото от Великих Торговец торговых миссий.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Гильдия является ассоциацией мастеров в данной отрасли торговли. Самые ранние виды гильдии образовались братств работников. Они были организованы таким образом, нечто среднее между профсоюзом, картеля, и тайного общества. Они часто зависит от грантов грамот монархом или другого органа для обеспечения соблюдения поток торговли к своим самозанятых членов, и, чтобы сохранить право собственности на средства и поставка материалов.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] Стоимость Покупка юнитов и строений.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Патентный закон', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' +1 [ICON_GOLD] Золото от деревни. [NEWLINE] +2 [ICON_GOLD] Золото от гаваней.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Патент набор эксклюзивных прав, предоставленных государством (национального правительства) изобретателю или их правопреемнику в течение ограниченного периода времени в обмен на публичное раскрытие изобретения. [NEWLINE] [NEWLINE] Патенты в современном понимании возник в 1474 г., когда Венецианская республика был принят указ, что новые и изобретательные устройства, как только претворяются в жизнь, должна была быть доведена до Республики для получения права запрещать другим лицам использовать их. [NEWLINE] [NEWLINE] Англия следуют с Закон о монополиях в 1623 под короля Джеймса I, который заявил, что патенты могут быть предоставлены только для "проектов нового изобретения." Во время правления королевы Анны (1702-14), адвокаты английском суде разработаны требования, что письменное описание изобретения должны быть представлены. Патентная система во многих других странах на основе британского законодательства и могут быть прослежены в Устав монополий.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] Перемещение и +1 Зрение для военных кораблей. [NEWLINE] +2 [ICON_RESEARCH] Наука для прибрежных городах. [NEWLINE] +2 [ICON_RESEARCH] Наука для Военно-морских зданий.', '', '');
/*  Патронат  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_GOLD] [ICON_WORKER] Открывает [NEWLINE] +2 Золото за город-государство торгового пути [NEWLINE] [ICON_VIEW_CITY] Показывает все города-государства.. : Ангкор-Ват [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_PLUS] +100% количество стратегическим ресурсом и +50% [ICON_HAPPINESS_1] Национальный Счастье от роскошных ресурсов подаренной Города-Государства союзников.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] +20 мгновенный Влияние с городов-государств. [NEWLINE] [ICON_INFLUENCE] +33% Влияние от [ICON_GOLD] Золотые подарки городов-государств.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Особые отношения', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Влияние с городов-государств ухудшает 33% медленнее, чем обычно. [NEWLINE] [ICON_INFLUENCE] Влияние других игроков с городов-государств уменьшается на 10% быстрее.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] +20 отдыхает влияние с городов-государств.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] +2 Наука за эры для каждого города-государства другу, и +3 для каждого союзника.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] Город-государство союзники подарочные замечательные люди. [ICON_GREAT_PEOPLE] +10% Великий Люди курс.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Торговля пакт', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' +2 [ICON_PRODUCTION] Производство за эпоху для каждого города-государства другу, и +3 для каждого союзника (сплит среди ваших городах).', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Свободная торговля является система торговой политики, что позволяет трейдерам торговать через национальные границы без вмешательства соответствующих органов власти. В связи с экономическим принципом сравнительных преимуществ, это обеспечивает торговых партнеров с взаимной прибыли. В рамках этой политики цены единственным фактором, определяющим распределение ресурсов, и близкий отражением спроса и предложения.', '', '');
/*  Эстетика  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] +50% Производство культурных зданий [NEWLINE] [ICON_WORKER] Открывает:. Уффици [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR ] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] показывает скрытые сайты древности. [NEWLINE] [ICON_TEAM_7] Позволяет покупку культурных великих людей с [ICON_PEACE] веры при входе в индустриальную эпоху.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Культура: +1 за 2 прибавочной счастья.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Культура: +2 за национальное чудо [NEWLINE] [ICON_CULTURE] Культура: +33% в городах с чудо света', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Великий художник: 1 [NEWLINE] [ICON_TEAM_7] Культурное Великий гостя: +25%', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Археологи производятся в два раза быстрее', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Парный здание-тема туризма. [NEWLINE] [ICON_TOURISM] +25% туризм от общей религии, открытых границ и торговых путей.', '', '');
/*  Разведка  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_MOVES] Ходы: 2 для приступил единиц [NEWLINE] [ICON_MOVES] Ходы: 2 для Великих адмиралов [NEWLINE] [ICON_SIGHT_SEA] Зрение: + 1 для военных кораблей [NEWLINE] [ICON_WORKER] Открывает: Красный форт [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] +2 национальных Счастье за ​​Luxury ресурс. [NEWLINE] [ICON_TEAM_7] Позволяет покупку Великих адмиралов с верой при входе в индустриальную эпоху.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Город Счастье: +1 за Маяк, гавань, порт', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Покупка Стоимость: -25% для зданий [NEWLINE] [ICON_GOLD] Обслуживание: -25% для зданий', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Колонизация', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Города начать с 3 населения. [NEWLINE] [ICON_TEAM_2] 2 Поселенцы, 2 Работники и 2 отряды обороны появится в столице.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Pioneer Дух', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 движение для гражданских лиц. [NEWLINE] [ICON_GOLD] -50% затрат на дорогах. [NEWLINE] [ICON_PRODUCTION] +100% производства для строительства гавани.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Закон усадьба', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Города получить бесплатную уровня 1 здания.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(Осталось)', '', '');
/*  Знание  */
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Знание', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'ЗНАНИЯ', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'Знание является знакомство с кем-то или чем-то, что может включать в себя факты, информацию, описания, или навыки, приобретенные через опыт или образование. Это может относиться к теоретического или практического понимания предмета. Это может быть практический навык или опыт, или теоретическое понимание предмета.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Благочестие увеличивает счастье, культуры и Веру, принимающей CIV. Благочестие становится доступным после того, как классическая эра будет достигнута. Это идеальное место, чтобы приобрести политики для игроков, стремящихся создать или расширить религии.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'Какова Знание социальная политика филиал о?', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'Филиал знаний улучшает способность цивилизации использовать и генерировать Наука, становятся доступными при входе эпохи Возрождения.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'Знание филиал социальной политики полна политики, которые могут увеличить ваши исследования. Эта отрасль становится доступным в эпоху Возрождения. Ознакомиться с правилами в области социальной политики для деталей.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'Отрасль знаний', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Способности: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] открывалка [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Великий ученый: +1 [NEWLINE] [ICON_WORKER] Открывает: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] финишер [ENDCOLOR] [ COLOR_GREY] (закончить все политики в этом дереве) [ENDCOLOR] [NEWLINE] +1 мгновенно [ICON_TEAM_5] технологии. [NEWLINE] [ICON_PEACE] Можно приобрести великих ученых с [ICON_PEACE] веры только вы входите в индустриальную эпоху.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[ICON_RESEARCH] +50% Исследования соглашение награды.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Контрразведка', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] +25% шанс поймать вражеских шпионов. [NEWLINE] [ICON_SPY] -25% эффективность шпион враг.', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(Осталось)', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Наука: +10% в то время как нация [ICON_HAPPINESS_1] счастлив', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Наука: +1 за Village [NEWLINE] [ICON_RESEARCH] науки: +2 за Маяк', '', '');
REPLACE INTO Language_RU_RU (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Наука: +2 за специалист', '', '');







UPDATE Loaded File SET Value=1, RU_RU=1 Where Type='Policies.sql';



