/* The sql commands and text below were formulated in the TW_BuildingStats tab of the Google Spreadsheet 'CAT_Language'.
https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGtjX2JldHBzdXhRbGNxVFgxT1E2OHc&usp=drive_web#gid=1
If you make any changes be sure to update the spreadsheet also.*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOOLTIP_GOOD_FOR', '适合：', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOOLTIP_ABILITIES', '能力：', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOOLTIP_REQUIREMENTS', '要求：', '', '');
/*单位*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_MAINTENANCE', '[ICON_GOLD]维护：{1_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_HURRY_COST_MODIFIER', '[ICON_GOLD]采购：{1_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HURRY_COST_MODIFIER', '[ICON_GOLD]采购：{3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_CATEGORY', '[ICON_BULLET]分类：{1_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_FOUND', '[ICON_TRADE]各项垫付款城市扩张你的帝国。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_FOOD', '[ICON_BULLET]转动[ICON_FOOD]食品进入[ICON_PRODUCTION]生产构建更快的高增长城市。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_WORK_RATE', '[ICON_WORKER]好率：{1_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_OBSOLETE_TECH', '[ICON_PIRATE]过时：{1_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_CARGO', '[ICON_AIR]怀揣：{1_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_SUICIDE', '[ICON_PIRATE]一个使用', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_UNIT_NUKE_RADIUS', '[ICON_RES_URANIUM] [COLOR_POSITIVE_TEXT]核范围：{1_value} [ENDCOLOR]', '', '');
/*建筑*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_COST', '[ICON_PRODUCTION]成本：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NUM_CITY_COST_MOD', '[ICON_PRODUCTION]成本：{2_sign} {3_value}为每个城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_POP_COST_MOD', '[ICON_PRODUCTION]项目[ICON_CITIZEN]西铁城成本：{2_sign} {3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GOLD_MAINTENANCE', '[ICON_GOLD]维护：{3_value}', '', '');
/*收益率*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_IN_ALL_CITIES', '在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MILITARY_UNITS', '军事单位', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_INSTANT', '{1_prefix}瞬间：{2_sign} {3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_CHANGE', '{1_prefix}：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_CHANGE_FROM', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD', '{1_prefix}：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_FOR', '{1_prefix}：{2_sign}在{4_extra} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_MILITARY', '{1_prefix}：{2_sign} {3_value}％用于军事单位', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_DOMAIN', '{1_prefix}：{2_sign}在{4_extra} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_COMBAT', '{1_prefix}：{2_sign}在{4_extra} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_BUILDING', '{1_prefix}：{2_sign} {3_value}％用于建筑', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_WONDER', '{1_prefix}：{2_sign} {3_value}％的奇迹', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_SPACE', '{1_prefix}：{2_sign} {3_value}％用于飞船零件', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_SURPLUS', '{1_prefix}盈余：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_FROM_BUILDINGS', '{1_prefix}：{2_sign} {3_value}％{4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_IN_ALL_CITIES', '{1_prefix}：{2_sign} {3_value}％{TXT_KEY_IN_ALL_CITIES}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_STORAGE', '{1_prefix}存储：{3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_PER_POP', '{1_prefix}每[ICON_CITIZEN]公民：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_LAKES', '{1_prefix}：{3_value}湖瓷砖', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_SEA', '{1_prefix}：{3_value}海瓷砖', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RIVERS', '{1_prefix}：{3_value}河瓷砖', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_PLOTS', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_TERRAIN', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_FEATURES', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RESOURCES', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RELIGION', '{1_prefix}：{3_value} {4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_TECH', '{1_prefix}：{3_value}以{4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_SPECIALISTS', '{1_prefix}：{3_value} {4_extra}在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_BUILDINGS', '{1_prefix}：{3_value}在{4_extra}等', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_FROM_USING_GREAT_PEOPLE', '{1_prefix}使用大人们：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_YIELD_MOD_HURRY', '{1_prefix}成本：{2_sign {}} 3_value％在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MEDIAN_TECH_PERCENT_CHANGE', '[ICON_RESEARCH]研究协议奖励：{2_sign} {3_value}％', '', '');
/*其他*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_SPECIALIST_TYPE', '{1_prefix}：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_SPECIALIST_POINTS', '{1_prefix}：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_PERSON_POINTS', '{1_prefix}大{4_extra}积分：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_PEOPLE_RATE_MODIFIER', '[ICON_GREAT_PEOPLE]大人们率：{3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_GREAT_PEOPLE_RATE_MODIFIER', '[ICON_GREAT_PEOPLE]大人们率：{3_value}％在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_UNMODDED_HAPPINESS', '[ICON_HAPPINESS_1]国家幸福：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HAPPINESS', '[ICON_HAPPINESS_1]城市幸福：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HAPPINESS_FOOT', '一个城市不能创造更多的[ICON_HAPPINESS_1]城市幸福比[ICON_CITIZEN]人口。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HAPPINESS_PER_CITY', '[ICON_HAPPINESS_1]城市幸福：{3_value}在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HAPPINESS_PER_X_POLICIES', '[ICON_HAPPINESS_1]国民幸福：1元{3_value}政策', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_UNHAPPINESS_MODIFIER', '{2_sign} {3_value}％[ICON_HAPPINESS_4]从[ICON_CITIZEN]人口非自住的城市不快。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NO_OCCUPIED_UNHAPPINESS', '[ICON_OCCUPIED]结束职业在这个城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NO_OCCUPIED_UNHAPPINESS_FOOT', '[ICON_OCCUPIED]占用和[ICON_PUPPET]木偶城市有产量比正常低城-25％。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_DEFENSE', '[ICON_STRENGTH]防御：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_DEFENSE_MOD', '[ICON_STRENGTH]防御：{3_value}在所有城市％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXPERIENCE', '[ICON_WAR]经验：{3_value}为所有单位', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXPERIENCE_DOMAIN', '[ICON_WAR]经验：{3_value}在{4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXPERIENCE_COMBAT', '[ICON_WAR]经验：{3_value}在{4_extra}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_EXPERIENCE', '[ICON_WAR]经验：{3_value}在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXPERIENCE_PER_TURN', '[ICON_WAR]经验：每回合在这个城市{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_PROMOTION', '{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_PROMOTION_ALL_COMBAT_UNITS', '{3_value}（所有单位）', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRAINED_FREE_PROMOTION', '{3_value}（单位受训这里）', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_UNITS', '[ICON_TEAM_2]免费{4_extra}：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_GREAT_PERSON', '[ICON_TEAM_7]免费{4_extra}：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_GREAT_PEOPLE', '[ICON_TEAM_7]免费伟人：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CAPITAL', '[ICON_CAPITAL]首都', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CAPITAL_FOOT', '{TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES_FOOT}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE', '[ICON_GOLDEN_AGE]开始一个黄金时代', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MAP_CENTERING', '[ICON_BULLET]中心的世界地图', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES', '[ICON_CONNECTED]连接水公路和铁路', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES_FOOT', '到京城[ICON_CONNECTED]公路，铁路，或水的连接提供[ICON_GOLD]黄金[NEWLINE] [NEWLINE]到京城[ICON_CONNECTED_RAILROAD]铁路或水的连接提供了25％[ICON_PRODUCTION]生产（[ COLOR_POSITIVE_TEXT]铁路[ENDCOLOR]技术）。[NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT]港口[ENDCOLOR]水连接公路和铁路。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXTRA_LUXURIES', '[ICON_CONNECTED]双打供应奢侈品城附近', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_DIPLOMATIC_VOTING', '[ICON_FLOWER] [COLOR_POSITIVE_TEXT]触发外交胜利投票！[/ COLOR]', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_GENERAL_RATE_MODIFIER', '[ICON_WAR]大将军率：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE_MODIFIER', '[ICON_GOLDEN_AGE]黄金时代：{2_sign} {3_value}％持续时间', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_UNIT_UPGRADE_COST_MOD', '[ICON_GOLD]升级成本：{2_sign} {3_value}％所有单元', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CITY_COUNT_UNHAPPINESS_MOD', '[ICON_HAPPINESS_4] {2_sign} {3_value}％来自城市的数量不快乐', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_WORKER_SPEED_MODIFIER', '[ICON_WORKER]工人改善速度：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CITY_CONNECTION_TRADE_ROUTE_MODIFIER', '[ICON_GOLD]从[ICON_CONNECTED]城市连接黄金：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CAPTURE_PLUNDER_MODIFIER', '[ICON_RESISTANCE]敌人掠夺得到额外的金钱：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_POLICY_COST_MODIFIER', '政策[ICON_CULTURE]文化成本：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_PLOT_CULTURE_COST_MODIFIER', '[ICON_CULTURE]边境扩张成本：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_PLOT_CULTURE_COST_MODIFIER', '[ICON_CULTURE]边境扩张成本：{2_sign} {3_value}在所有城市％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_PLOT_BUY_COST_MODIFIER', '[ICON_GOLD]边境扩张成本：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_PLOT_BUY_COST_MODIFIER', '[ICON_GOLD]边境扩张成本：{2_sign} {3_value}在所有城市％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_POPULATION_INSTANT', '[ICON_CITIZEN]人口：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_POPULATION_CHANGE', '[ICON_CITIZEN]人口：{3_value}在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_TECHS', '[ICON_TEAM_5]免费技术：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_POLICIES', '[ICON_TEAM_6]自由社会政策：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_BORDER_OBSTACLE', '[ICON_MOVES]减慢敌人在友好的疆土', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_AIR_MODIFIER', '[ICON_RANGE_STRENGTH]伤害：从空中单位{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NUKE_MODIFIER', '[ICON_RANGE_STRENGTH]伤害：{2_sign} {3_value}％从核弹', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_BUILDING', '[ICON_TEAM_9]免费建筑：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_BUILDING_THIS_CITY', '[ICON_TEAM_9]免费建筑：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_WATER', '[ICON_LOCKED]要紧挨着海岸。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_RIVER', '[ICON_LOCKED]必须是在一条河。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FRESH_WATER', '[ICON_LOCKED]必须是旁边的河流或湖泊。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MOUNTAIN', '[ICON_LOCKED]必须被旁边的一个山区。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NEARBY_TERRAIN_REQUIRED', '[ICON_LOCKED]必须上或旁边{3_value}。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_PROHIBITED_CITY_TERRAIN', '[ICON_LOCKED]不能对{3_value}。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NEARBY_MOUNTAIN_REQUIRED', '[ICON_LOCKED]必须在2瓦的文化边界的山。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HILL', '[ICON_LOCKED]必须是在一个小山。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FLAT', '[ICON_LOCKED]不能在一个山。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING', '[ICON_LOCKED]需要：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING_IN_CITIES', '[ICON_LOCKED]需要：{3_value} {中} 4_extra城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING_IN_PERCENT_CITIES', '[ICON_LOCKED]需要：城市{3_value} {中} 4_extra％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_NEAR_ALL', '[ICON_LOCKED]需要周边设施：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_NEAR_ANY', '[ICON_LOCKED]需要任何附近：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_RESOURCE_CONSUMPTION', '[ICON_LOCKED]用途：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_RESOURCES_REQUIRED', '[ICON_LOCKED]用途：', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_OBSOLETE_TECH', '[ICON_PIRATE]过时：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NATIONAL_LIMIT', '[ICON_LOCKED]国家限制：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TEAM_LIMIT', '[ICON_LOCKED队伍限制：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_WORLD_LIMIT', '[ICON_LOCKED]世界极限：{3_value}', '', '');
/*添加了千金藤*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NOT_FEATURE', '[ICON_MINUS]不健全{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HEAL_RATE_CHANGE', '[ICON_PLUS]治愈率：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MINOR_FRIENDSHIP_CHANGE', '[ICON_INFLUENCE]影响：+ {3_value}与所有城邦％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MINOR_FRIENDSHIP_FLAT_CHANGE', '[ICON_INFLUENCE]影响：+ {3_value}与所有市州的国', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REQUIRES_TECH', '[ICON_LOCKED]需要：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CULTURE_FROM_LAKES', '[ICON_CULTURE]文化：{3_value}湖瓷砖', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_INSTANT_BORDER_RADIUS', '[ICON_CULTURE]边境扩展：{3_value}瓦范围', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_INSTANT_BORDER_RADIUS', '[ICON_CULTURE]边境扩展：{3_value}在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MOUNTAIN_IMPROVEMENT', '[ICON_WORKER]改善了山区', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CITY_CAPTURE_CULTURE', '[ICON_CULTURE]文化活动从征服的城市掠夺', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_GENERAL_RATE_CHANGE', '[ICON_GREAT_PEOPLE]大将军积分：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_DEAL_MODIFIER', '[ICON_TRADE]贸易新政奖励：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HAPPINESS_INSTANT', '[ICON_GOLDEN_AGE]即时黄金时代积分：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE_POINTS', '[ICON_GOLDEN_AGE]盛世积分：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALREADY_BUILT', '[ICON_LOCKED]已建成', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REPLACES', '[ICON_PLUS]替换：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_INSTANT_BORDER_PLOTS', '[ICON_CULTURE]边境扩展：{3_value}', '', '');
/*扩展*/
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FOUNDS_RELIGION', '[ICON_RELIGION]各项垫付款宗教：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_IS_RELIGIOUS', '[ICON_RELIGION]是宗教：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_PLAYER_BORDER_OBSTACLE', '[ICON_BULLET]玩家边境障碍：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NUKE_IMMUNE', '[ICON_RES_URANIUM]免疫核弹：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_AFFECT_SPIES_NOW', '[ICON_SPY]影响现在的间谍：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_UNLOCKED_BY_BELIEF', '[ICON_PEACE]可以购买与宗教', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_MIN_AREA_SIZE', '[ICON_LOCKED]最小海面积：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_CITIES_PREREQ', '[ICON_LOCKED]需要城市：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_LEVEL_PREREQ', '[ICON_LOCKED]需要等级：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_AIRLIFT', '[ICON_AIR]允许空运或从这个城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NUKE_EXPLOSION_RAND', '[ICON_RES_URANIUM]，可能造成核爆炸', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALLOWS_RANGE_STRIKE', '[ICON_RANGE_STRENGTH]允许攻击城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ESPIONAGE', '[ICON_SPY]间谍：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXTRA_CITY_HIT_POINTS', '[ICON_HEAL]城市生命值：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXTRA_MISSIONARY_SPREADS', '[ICON_MISSIONARY] {3_value}额外价差传教士从这里', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ESPIONAGE_MODIFIER', '[ICON_SPY]间谍窃取率：{2_sign} {3_value}％在这个城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GLOBAL_ESPIONAGE_MODIFIER', '[ICON_SPY]间谍窃取率：{2_sign} {3_value}％在所有城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXTRA_SPIES', '[ICON_SPY]额外的间谍：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_SPY_RANK_CHANGE', '[ICON_SPY]间谍排名：{2_sign {}} 3_value', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_INSTANT_SPY_RANK_CHANGE', '[ICON_SPY]即时间谍排名：{2_sign} {3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_REPLACEMENT_BUILDING_CLASS', '[ICON_CHECKBOX]替代对象建筑：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_SPECIALIST_EXTRA_CULTURE', '[ICON_CULTURE]专家特文化：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_RELIGIOUS_PRESSURE_MODIFIER', '[ICON_PEACE]宗教压力：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_HOLY_CITY', '[ICON_LOCKED]需要：圣城', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_RESOURCES', '{1_prefix} {免4_extra}：{3_value}', '', '');
/* Expansion2 */
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_THEMING_BONUS_HELP', '[ICON_GREAT_WORK] {3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NULLIFY_INFLUENCE_MODIFIER', '[ICON_TOURISM]求反从其他玩家的互联网技术的旅游奖金。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_LEAGUE_COST', '[ICON_TROPHY_GOLD]国会成本：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_UNLOCKED_BY_LEAGUE', '[ICON_TROPHY_GOLD]解锁国会：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_AIRLIFT', '[ICON_AIR]允许空运或从这个城市', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALLOWS_FOOD_TRADE_ROUTES', '[ICON_INTERNATIONAL_TRADE]是否可以买卖粮食友好城市。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_ALLOWS_PRODUCTION_TRADE_ROUTES', '[ICON_INTERNATIONAL_TRADE]是否可以买卖生产友好城市。', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_RECIPIENT_BONUS', '[ICON_GOLD]黄金：{3_value}从这里商路', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_TARGET_BONUS', '[ICON_GOLD]黄金：{} 3_value贸易路线在这里', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_NUM_TRADE_ROUTE_BONUS', '[ICON_INTERNATIONAL_TRADE]最大贸易航线：{2_sign} {3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_INSTANT_MILITARY_INCREASE', '[ICON_WAR]复制你拥有的所有单位', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_LANDMARKS_TOURISM_PERCENT', '[ICON_TOURISM]旅游：{2_sign}奇观和改进的在这个城市[ICON_CULTURE]文化{3_value}％增加至旅游', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_WORKS_TOURISM_MODIFIER', '[ICON_TOURISM]旅游：{2_sign} {3_value}％来自大工程', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_X_BUILT_TRIGGERS_IDEOLOGY_CHOICE', '[ICON_CULTURE]大厦{3_value}意识形态解锁', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_SEA_DISTANCE_MODIFIER', '[ICON_INTERNATIONAL_TRADE]海贸距离：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_SEA_GOLD_BONUS', '[ICON_GOLD]海贸易黄金：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_LAND_DISTANCE_MODIFIER', '[ICON_INTERNATIONAL_TRADE]土地交易距离：{2_sign} {3_value}％', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_LAND_GOLD_BONUS', '[ICON_GOLD]土地交易黄金：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_SCIENTIST_BEAKER_MODIFIER', '[ICON_RESEARCH]伟大的科学家烧杯修改：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_TECH_ENHANCED_TOURISM', '[ICON_TOURISM]旅游：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_POLICY_BRANCH_TYPE', '[ICON_LOCKED]需要政策：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_WORK_SLOT_TYPE', '{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_GREAT_WORK_COUNT', '{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_FREE_GREAT_WORK', '[ICON_GREAT_WORK]免费了不起的工作：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXTRA_LEAGUE_VOTES', '[ICON_CHECKBOX]美国国会投票：{3_value}', '', '');
REPLACE INTO Language_ZH_HANT_HK (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_EFFECT_EXPERIENCE_PER_GREAT_WORK', '[ICON_WAR]经验：每了不起的工作{3_value}', '', '');




UPDATE LoadedFile SET Value=1, ZH_HANT_HK=1 Where Type ='Text_TW_BuildingStats.sql';