/* The sql commands and text below were formulated in the Cities tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=2135453389
If you make any changes be sure to update the spreadsheet also.*/

/*  일반  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CEP_VERSION', 'CEP의 V3. {1}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_GOLDEN_AGE_EFFECT', '도시는 황금 시대 [ICON_GOLDEN_AGE] 동안 20 %의 수율을 생산하고 있습니다. [NEWLINE] [ICON_FOOD] 20 %의 잉여 식품 [NEWLINE] [ICON_PRODUCTION] 20 % 생산 [NEWLINE] [ICON_GOLD] 20 % 골드 [NEWLINE] [ICON_RESEARCH] 20 % 과학 [NEWLINE] [ICON_CULTURE] 20 %의 문화 [NEWLINE] [ICON_PEACE] 20 % 믿음 [NEWLINE] [NEWLINE] 잉여 행복 동안 황금 시대의 황금 시대 카운터에 추가하고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRADE_ROUTE_INCOME_INFO', '{1}베이스 [ICON_GOLD] 골드 노선 당 [NEWLINE]의 수도에서 {2} [ICON_GOLD] 골드 [ICON_CITIZEN] 당 시민 [NEWLINE] {3} [ICON_GOLD] 골드 [ICON_CITIZEN] 당 시민', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISSION_HURRY_PRODUCTION_HELP', '도시의 현재 노력 (200 + 30 * [ICON_CITIZEN] 인구) [ICON_PRODUCTION] 생산을 제공합니다. 그것은 위대한 사람을 소모합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCTION_BUILDING_ALLOWS_WATER_ROUTES_EXTRA', '자본에 도로, 철도, 또는 물 [ICON_CONNECTED] 경로는 [ICON_GOLD] 금을 제공한다. [NEWLINE] [NEWLINE] 자본에 철도 또는 물 [ICON_CONNECTED_RAILROAD] 경로로 ([ICON_PRODUCTION] 생산 25퍼센트을 제공한다 [ COLOR_POSITIVE_TEXT] [ENDCOLOR] 기술 철도 선로). [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] 등대 [ENDCOLOR] 물과 땅의 무역로를 사이에 안전한 연결을 제공합니다.', '', '');
/*  건물  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMPHITHEATER', '극장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMPHITHEATER_HELP', '[ICON_CULTURE] 문화 : +1 [ICON_RES_SILK] [ICON_RES_COTTON] [ICON_RES_FUR] [ICON_RES_DYE] [NEWLINE] [NEWLINE] 의상 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMPHITHEATER_PEDIA', '그것은 오늘날 서구에서 알려진대로 그리스 극장을 발명했습니다. 원래 극장은 종종 언덕의 측면에 건설 야외 원형 극장이었다. 공연이 언덕 기슭에 오픈 무대에 근무하는 동안 관객들은 언덕으로 잘라 벤치에 앉아 있었다. 시간이 지남에 따라 단계 (특히 궂은 날씨의 많은 위험과 위치에) 실내에서 움직였다. 현대 극장은 여전히​​ 무대와 관객을위한 좌석을 가지고 있지만, 그것은 또한 정교한 음향 및 조명 장비, 오케스트라 피트, 그리고 소품과 풍경에 대한 광범위한 무대 영역을 포함한다. 그러나 고대 극장가는 사람은 (휴식 시간 동안 판매 된 음식과 음료의 가능성 비용 제외) 현대 극장 내에서 발견 아무것도에 의해 완전히 놀라지 않을 것이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AQUEDUCT_HELP', '[ICON_FOOD] 식품 보관 : 40 % [NEWLINE] [ICON_FOOD] 음식 : +1 [ICON_RES_CITRUS] [ICON_RES_TRUFFLES] [ICON_RES_SALT] [ICON_RES_BANANA] [NEWLINE] [NEWLINE] 이국적인 음식을 향상시킵니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ARENA', '투기장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ARENA_PEDIA', '경기장은 종종 원형 또는 타원형, 자주 스포츠 이벤트를 선보일 수 있도록 설계, 밀폐 된 지역입니다. 이 단어는 라틴어 harena, 로마의 콜로세움 같은 고대 경기장에서 혈액을 흡수하는 데 특히 좋은 / 부드러운 모래에서 파생됩니다. [NEWLINE] [NEWLINE] 아레나스가에 대한 계층 된 좌석에 의해 대부분 또는 모든면에 둘러싸인 큰 열린 공간으로 구성되어있다 관중. 경기장의 주요 기능은 이벤트 공간이 최대의 가시성을 허용, 가장 낮은 지점입니다 것입니다. 경기장은 일반적으로 관중의 상당히 많은 수를 수용 할 수 있도록 설계되어 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ARMORY_HELP', '[ICON_WAR] 경력 : 20 [NEWLINE] [ICON_PRODUCTION] 생산 : +10 % 대지의 단위에 대한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ARSENAL_STRATEGY', '아스날은 도시의 방어력을 증가시키고 체력을 캡처하는 도시가 더 어려워 중간 게임 군사 건물입니다. 이 아스날을 구성하기 전에이 도시는 성을 가지고 있어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_WALLS_STRATEGY', '바빌론의 벽은 표준 성벽을 교체, 바빌로니아의 독특한 건물입니다. 바빌론의 벽은 표준 벽보다 모두 훨씬 더 (도시의 방어 강도와 체력을 증가시킵니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARRACKS_HELP', '[ICON_WAR] 경력 : 10 [NEWLINE] [ICON_PRODUCTION] 생산 : +1 전략적 자원에', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BAZAAR_HELP', '[ICON_TRADE] 근처의 고급 공급을 두 배로 [NEWLINE] [ICON_GOLD] 골드 : [ICON_RES_OIL] [NEWLINE] [ICON_GOLD] 골드에 +2 : 여기에서 무역 루트 당 +2 [NL 오아시스 [NEWLINE] [ICON_GOLD] 골드에 +2 】 【ICON_GOLD] 골드 : +1 럭셔리 자원에는 [NEWLINE] [NEWLINE] 고급 자원을 증가합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAPITAL_BUILDING', '자본', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAPITAL_BUILDING_PEDIA', '정부의 좌석은 정부가 권한을 행사되는 건물, 건물이나 도시의 복잡합니다. 정부의 좌석은 일반적으로 자본에 있습니다. 일부 국가에서는 정부의 좌석은 예를 들어, 자본 다르다 헤이그는 정부의 좌석과 암스테르담은 네덜란드의 도리 수도 네덜란드. 대부분은 러시아 정부의 자본 및 좌석 등의 예를 들어 모스크바를 들어, 같은 도시입니다. 영국에서는, 정부의 좌석은 런던, 수도, 또는 웨스트 민스터 더 구체적으로 도시입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CARAVANSARY_HELP', '[ICON_TRADE] 캐러밴 범위 : 50퍼센트 [NEWLINE] [ICON_GOLD] 골드 : 여기에서 캐러밴 당 +2 [NEWLINE] [ICON_GOLD] 골드 : 럭셔리 자원에 +1이 [NEWLINE] [NEWLINE] 고급 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CASTLE_STRATEGY', '성이 도시의 방어 강도와 체력을 증가시키는 중세 시대의 건물입니다. 성이 건설되기 전에이 도시는 벽을 소유해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FACTORY_HELP', '[ICON_CULTURE] 3를 구축하는 [NEWLINE] [ICON_LOCKED] 이데올로기의 잠금을 해제 요구 : 1 [ICON_RES_COAL] 석탄', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_DESC', 'Chinampa', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOATING_GARDENS_STRATEGY', 'Chinampa는 워터를 교체, 아즈텍 독특한 건물입니다. 그것은 도시의 음식 출력을 증가하고, 도시는 호수 나 강 근처에있는 경우 작성해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_PEDIA', 'Chinampa 농업에 사용할 수있는 땅을 높이기 위해 민물 호수에 건설 작은 인공 섬입니다. 호수는 섬을 관개와 매우 비옥 한 성장 환경의 결과로, 신선한 유기농 재료로 제공합니다. 아즈텍은 농업이 양식의 주인이었고, ''소 치밀 코의 공중 정원''오늘 유명한 남아있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FORGE_HELP', '[ICON_PRODUCTION] 제작 : 대지의 단위 [NEWLINE] [ICON_PRODUCTION] 생산 +15 % +1 [ICON_RES_IRON] [ICON_RES_COAL] [ICON_RES_COPPER] [NEWLINE] [NEWLINE] 철광석 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_GARDEN_STRATEGY', '정원은 [ICON_GREAT_PEOPLE] 좋은 사람들이 도시에서 발생되는 속도를 증가시킨다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_GRANARY_HELP', '+1 [ICON_RES_WHEAT] [ICON_RES_SPICES] [ICON_RES_SUGAR] [NEWLINE] [NEWLINE] 곡물 자원을 강화 : [ICON_FOOD]시 푸드 [NEWLINE] [ICON_FOOD] 음식이 거래 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_GREAT_HALL', '그레이트 홀', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_GREAT_HALL_PEDIA', '시청은 최고 행정 도시의 건물, 도시, 또는 다른 지방 자치 단체이다. 그것은 일반적으로 도시 또는 마을 협의회, 관련 부서와 직원을 전시하고 있습니다. 또한 일반적으로 도시, 마을, 자치구 또는 군의 시장의 거점으로 기능을 수행합니다. [NEWLINE] [NEWLINE] 지방 정부는 지역 사회의 삶의 질을 증진하고 강화하기 위해 타운 홀 건물을 사용하기 위해 노력할 수 있습니다. 대부분의 경우, " ''타운 홀''정부 기능의 건물로뿐만 아니라 제공뿐만 아니라, 다양한 시민의 문화 활동을위한 시설이 있습니다.이 예술 쇼, 무대 공연, 전시, 축제를 포함 할 수있다. 지방 정부, 도시의 상징으로 타운 홀은 독특한 구조를 가지고 있고, 건물은 큰 역사적 의미를 가질 수있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_LABORATORY_HELP', '[ICON_RESEARCH] 과학 : 정글에서 +1은 [NEWLINE] [ICON_LOCKED] 요구 사항 : 공립 학교를', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MARKET_HELP', '[ICON_GOLD] 골드 : 여기에서 +2 당 무역 루트.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MILITARY_ACADEMY_HELP', '[ICON_WAR] 경력 : 30 [NEWLINE] [ICON_PRODUCTION] 생산 : 20 % 대지의 단위에 대한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MILITARY_BASE_HELP', '[ICON_AIR] 에어 손상 : -25 % [NEWLINE] [ICON_URANIUM] 핵 손상 : -50 % [NEWLINE] [ICON_LOCKED] 요구 사항 : 아스날', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MILITARY_BASE_STRATEGY', '군사 기지는 도시의 방어 강도와 체력을 증가 중반 게임 건물입니다. 군사 기지가 건설되기 전에이 도시는 아스날을 가지고 있어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MINT_HELP', '[ICON_GOLD] 골드 :에 +1은 [ICON_RES_COPPER] [ICON_RES_SILVER] [ICON_RES_GOLD] [ICON_RES_GEMS] [NEWLINE] [NEWLINE] 통화 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MUGHAL_FORT_STRATEGY', '무굴 요새 도시의 방어력, 체력을 증가시키는 중세 시대의 건물, 그리고 모든 회전을 몇 가지 [ICON_CULTURE] 문화를 제공합니다. 그것은 성을 교체, 인도의 독특한 건물입니다. 비행을 배운 후, 그것은뿐만 아니라 도시로 [ICON_GOLD] 골드 보너스를 제공합니다. 벽을 구축하는 것은 무굴 요새를 구축하기위한 필수 조건이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PALACE', '궁전', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PALACE_PEDIA', '궁전은 ​​주교 나 대주교로 그랜드 레지던스, 국가 원수 또는 다른 고위 고관 특히 왕가의 거주지 또는 집입니다. [NEWLINE] [NEWLINE] 단어를 들어, 라틴어 이름 Palatium에서 파생 팔라티노 언덕, 로마의 일곱 언덕 중 하나. 유럽​​의 많은 지역에서,이 용어는 귀족의 야심 찬 개인 저택에 적용됩니다. 많은 역사적인 궁전은 지금과 같은 의회, 박물관, 호텔이나 오피스 빌딩 등 다른 용도로 배치됩니다. 단어는 또한 때때로 공개 오락 또는 전시회에 사용 아낌없이 화려한 건물을 설명하는 데 사용된다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SANITATION_SYSTEM', '위생 시스템', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SANITATION_SYSTEM_PEDIA', '위생은 폐기물의 위험과 인간의 접촉 방지를 통해 건강을 증진의 위생 수단입니다. [NEWLINE] [NEWLINE] 위험이 실제 미생물, 생물 학적 또는 질병의 화학 물질이 될 수 있습니다. 예방 위생 수단 (하수 및 폐수 처리 등) 엔지니어링 솔루션, 간단한 기술 (변소, 정화조), 또는 개인 위생 관리 기준 (비누와 간단한 손씻기)에 의해를 사용하여 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SEAPORT_HELP', '[ICON_PRODUCTION] 제작 : 해군 단위 +50 % 【NL] [ICON_PRODUCTION] 생산 :. 바다 자원에 +1 [NEWLINE] [ICON_GOLD] 골드 : 바다 자원에 +1.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STABLE_HELP', '[ICON_PRODUCTION] 생산 : 마운트 유닛에 대한 15 %는 [NEWLINE] [ICON_PRODUCTION] 제작 : +1 [ICON_RES_HORSE] [ICON_RES_SHEEP] [ICON_RES_COW] [ICON_RES_DEER] [ICON_RES_IVORY] [NEWLINE] [NEWLINE] 가축 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STABLE_STRATEGY', '안정 마운트 유닛의 생산 속도를 증가 및 특정 자원에 대한 생산을 추가합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STONE_WORKS_STRATEGY', '돌 작품은 개선 [ICON_RES_STONE] 돌 또는 [ICON_RES_MARBLE] 대리석 자원 근처 도시에서 구성 할 수있다. 돌 작품은 도시의 [ICON_PRODUCTION] 생산을 증가.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SUPERMAX_PRISON_HELP', '모든 도시에서 -25 % : [ICON_SPY] 스파이 평가 훔쳐', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SUPERMAX_PRISON', 'SUPERMAX 감옥', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SUPERMAX_PRISON_PEDIA', 'SUPERMAX ( "최고 최대의 보안"의 줄임말) 특정 국가의 감옥 시스템에서 구금의 가장 안전한 수준을 나타내는 교도소 내에서 "제어 장치"감옥, 또는 단위를 설명하는 데 사용되는 이름입니다. 범죄자 "최악의 최악의"국가 및 국제 안보에 위협을 제기하는 사람들 -이 게임의 목적은 장기, 감옥 시스템에서 가장 높은 보안 위험으로 분류 된 수감자에 대한 분리 된 주택을 제공하는 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TEMPLE_HELP', '[ICON_PEACE] 믿음 : +2 [ICON_RES_WINE] [ICON_RES_INCENSE] [NEWLINE] [NEWLINE] 종교 자원을 강화한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VACCINATIONS', '예방 접종', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VACCINATIONS_PEDIA', '백신은 특정 질병에 대한 면역력을 향상시키는 생물학적 제제이다. 백신은 면역 체계가 더 쉽게 인식하고 나중에 발생 이러한 미생물의 파괴 할 수 있도록, 질병 인자를 인식 파괴하고, 그것을 "기억"할 신체의 면역 체계를 자극한다. 예방 접종은 전염성 질환을 예방하는 가장 효과적인 방법입니다. [NEWLINE] [NEWLINE] 인류의 글로벌 예방 접종 노력이 천연두를 근절하고, 소아마비, 홍역, 파상풍 등의 치명적인 질병을 제한. 천연두는 1500 년대에있는 유라시아와의 접촉 후 아메리카 원주민의 약 90 %를 죽였다. 마지막으로 1979 년에 근절 할 때, 천연두 이상의 모든 20 세기의 전쟁이 결합 된, 단지 지난 세기에 전 세계적으로 300 ~ 500 만 명 살해했다. 천연두 백신이 1796 년 생산 된에 대한 첫 번째 질병이었다. 이 소 (: - 소 Vacca의 라틴어)에 영향을 미치는 바이러스에서 유래하기 때문에 예방 접종은 예방 접종을 불렀다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_WALLS_STRATEGY', '벽이 도시의 방어력을 증가시키고 체력을 캡처 할 도시가 더 어려워. 벽은 문명의 국경을 따라 위치한 도시에 매우 유용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_WAREHOUSE', '창고', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_WAREHOUSE_PEDIA', '웨어 하우스는 제품의 저장을위한 상업 건물입니다. 창고는 제조 업체, 수입, 수출, 도매업자, 수송 기업, 세관에서 사용하는 등의 저장 제품은 농업, 제조, 또는 상거래와 관련된 원료, 포장 재료, 예비 부품, 구성 요소, 또는 완제품을 포함 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_UNIVERSITY_HELP', '[ICON_RESEARCH] 과학 : 정글에서 +1 [NEWLINE] [ICON_RES_ARTIFACTS] [NEWLINE] [ICON_LOCKED] 고고학자를 구축 할 수는 요구 사항 : 도서관', '', '');
/*  국립 불가사의  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HEROIC_EPIC_HELP', '이 도시에 새로 교육을받은 단위는 15 % [ICON_STRENGTH] 전투의 강도를 향상, [COLOR_POSITIVE_TEXT] 사기 [ENDCOLOR] 승진을받을 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_OXFORD_UNIVERSITY', '하이델베르크 대학', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HOLY_PALACE', '거룩한 궁전', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HOLY_PALACE_HELP', '이 안으로 구성되어 도시에서 +8 25 %의 믿음을 제공합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HOLY_PALACE_STRATEGY', '거룩한 궁전은 도시에 상당한 믿음을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HOLY_PALACE_PEDIA', '도도', '', '');
/*  불가사의 : 이름을 변경하거나 추가  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_GREATWALL_DESC', '중국의 만리 장성은 전 세계에서 가장 크고 가장 유명한 사람이 만든 구조물 중 하나입니다. 중국어 통치자 현대 만주와 몽골에 살고있는 유목민의 공격을 떨어져 병동에 만리 장성을 구축. 흥미롭게도, 만리장성은 유목민을 유지하도록 설계되지 않았습니다 - 그것은 따라서 공습을하고, 어려운 해적 전리품을 수행 할 수 있도록하는 것이 훨씬 수익성이 낮은 설계되었습니다 - 중국은 거의 불가능 같은 긴 국경을 방어하기 위해 알고 있었다 따라서 적은 관련된 위험의 가치. [NEWLINE] [NEWLINE] 실제로 다른 중국어 왕조에 의해 만들어진 다섯 가지 "위대한 벽"이 있었다. 몇몇 벽은 이미 7 세기 BCE로 건설되고 있었다. 이들은 나중에 합류 강한, 더 큰, 통일은 이제 공동으로 만리장성이라고합니다했다. 기존 벽의 대부분은 1368 1640 AD 사이에 명나라 시대에 재건되었다. 이 벽 (돌 같은) 더 영구적 인 재료를 사용하여, 웅대 한 규모로 건설되었다. 명나라 벽은 서쪽에있는 신장의 위구르어 자치구의 남동쪽 부분에를 Nur을 로프에 동쪽에서 발해만에 Shanhai 패스에서 3천9백48마일 뻗어. 이 실크로드가 처음 중국에 진입, 화재 신호를 통해 통신 할 수 망루의 일련의 빠른 속도로 벽의 방대한 길이에 따라 메시지를 전달하기위한 한 지역이었다. [NEWLINE] [NEWLINE] 순수 군사적 측면에서, 만리장성이 켜져 중 고장이 뭔가. 만주족은 그 벽을 통과 할 수있는 중국의 일반 뇌물 할 수 있었다, 그래서 큰 야만인의 공격을 막는데 작은 값으로 밝혀졌다. 만주족이 중국을 정복 한 후, 국가의 경계는 관련이없는 벽을 렌더링, 멀리 북쪽으로 확장. 벽의 깎아 지른듯한 금전적 비용도 엇갈리게하고, 인간의 삶의 비용은 백만 이상의 영혼을 초과했다고한다. 만리장성은 때때로 ". 긴 묘지"[NEWLINE] [NEWLINE] 오늘 만리장성의 대부분은 파손의 상태에 별명 - 관광 지역이 잘 보존되어 있지만, 구조의 나머지의 대부분은 붕괴되고, 아마도 벽의 20 %는 좋은 상태입니다. 그것의 붕괴에도 불구하고, 만리 장성은 중국에서 가장 인기있는 관광 명소 중 하나와 세계의 진정한 궁금 남아있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PENTAGON_HELP', '모든 객실에는 모든 회전을 치유.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_LEANING_TOWER', '두오모', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_LEANING_TOWER_QUOTE', '[NEWLINE] [TAB] [TAB] "15 세기의 르네상스, 많은 것들에, 오히려 그것이 달성 것에 의해 다음 설계 무엇으로 좋았어요."[NEWLINE] [TAB] [TAB] - 월터 페이터 [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_LEANING_TOWER_DESC', '두오모 (대성당 디 산타 마리아 델 피오레)는 이탈리아 피렌체의 중심부에있는 큰 성당입니다. 그것은 1436 년 마무리, 건설 140 년이 걸렸다. 건설하는 동안, 피렌체 시간 동안, 이탈리아의 많은 도시 국가의 일부 공화국이었다. 성당은 공화국의 핵심 역할을하고 르네상스를 시작했다고한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HUBBLE', '벨 연구소', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HUBBLE_QUOTE', '[NEWLINE] [TAB] [TAB] "창조적 인 기술 연구소는 아이디어의 바쁜 교환을 육성하는 인재의 임계 질량이 필요합니다."[NEWLINE] [TAB] [TAB] - Mervin 켈리, 벨 연구소의 사장 [NL ] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HUBBLE_DESC', '트랜지스터 :이 연구 기관은 20 세기의 가장 중요한 기술의 경이로움을 포함하여 현대 컴퓨터의 기본 구성 요소를 발명하여 세계를 혁명. 이러한 장치는 크게 자신의 능력을 증가하고있는 동안 컴퓨터는 포켓 사이즈로 집 크기에서 축소 할 수있었습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MAUSOLEUM_HALICARNASSUS', '콜로세움', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_DESC', '일반적으로 알려진 콜로세움, 로마의 도시의 중앙에있는 플라 비우스 원형 극장은 로마 제국에 내장 가장 큰 것입니다. 그것은 로마의 건축과 로마 공학의 가장 위대한 작품 중 하나 간주됩니다. [NEWLINE] [NEWLINE] 동쪽에 로마 포럼의 사이트를 점령, 그것의 건축은, 황제 베스파시아누스에서 72 AD에서 시작 디도에서 80 AD에 완료되었습니다 추가 수정은 도미 티안의 통치 (81-96 AD) 동안 만들어지고으로. 이름 Amphitheatrum Flavium 모두 베스파시아누스의 디도서의 가족 이름 (플라 비우스, 씨족 플라비아에서)에서 파생됩니다. [NEWLINE] [NEWLINE] 좌석 가능 5 만 관중, 콜로세움이 같은 모의 해전, 동물 등의 검투 대회 및 공공 안경에 사용 된 사냥, 처형, 유명한 전투의 재연, 드라마는 고전 신화를 기반으로. 이 건물은 초기 중세 시대의 엔터테인먼트를 위해 사용되는 정지했다. 그것은 나중에 주택, 워크샵, 종교 단체에 대한 분기, 요새, 채석장, 그리고 기독교 신사 등의 목적을 위해 재사용되었다. [NEWLINE] [NEWLINE] 이름 콜로세움 긴의 거대한 동상에서 파생 된 것으로 생각 된 인근 네로. 이 동상은 나중에 적절한 태양 왕관을 추가하여, 헬리오스 아폴로, 태양신의 형상에 Nero의 후계자로 리모델링했다. Nero의 머리는 황제를 성공의 머리를 여러 번 교체하기로 결정했습니다. 거상은 결국 가능성은 청동을 다시 아래로 끌려 가고, 가을 않았다. 1000 년 이름 콜로세움 원형 극장을 참조 주장했다. 동상 자체가 거의 잊혀졌다 단지 그것의 기초가 남아, 콜로세움과 비너스와 로마의 인근 사원 사이에 위치해 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_MAUSOLEUM_HALICARNASSUS_QUOTE', '[NEWLINE] [TAB] [TAB] "내가 그 두려운 장소에 대해 말하고있어, 원형 극장도 위증은 국회 의사당 자체보다 그것이 더 이름에 최선을 다하고 있습니다은 현실을 직시하고, 더 무서운 이름이 없습니다;? 그것은이다. 모든 악마의 성전은 사​​람을 수용 할만큼 더러운 귀신이 모여 있습니다 "[NEWLINE] [TAB] [TAB] -.. 테르 툴 리아 누스 (드 Spectaculis, XII)는 [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ITAIPU_DAM', '이타이 댐', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_ITAIPU_DAM_HELP', '모든 도시에서 생산을 제공합니다. [NEWLINE] 무료 엔지니어 전문가를 제공합니다. [NEWLINE] 도시에서 무료로 수력 발전소를 제공합니다. [NEWLINE] 강에 건설해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_ITAIPU_DAM_QUOTE', '[NEWLINE] [TAB] [TAB] "여성 엔지니어가 댐을 구축 엉덩이 부츠 사람이라고 생각합니다. 그들은 엔지니어링의 95 %가 좋은 에어컨이 사무실에서 수행되는 것을 인식하지 않습니다."[NEWLINE] [ TAB] [TAB] -. 베아트리체 앨리스 힉스, 웨스턴 일렉트릭에서 최초의 여성 엔지니어 [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_ITAIPU_DAM_DESC', '파라나 강이 거대한 댐은 파라과이에서 소비하는 전력의 90 %, 브라질에서 소비가 20 %를 공급하는 세계에서 모든 운영 수력 발전 시설의 대부분의 연간 전기를 생성합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_LARGE_HADRON_COLLIDER', '대형 하드론 충돌기', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_HELP', '2 무료 기술.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_QUOTE', '[NEWLINE] [TAB] [TAB] "나는 힉스 보손이 LHC의 판매 포인트로 압수 강조 오버하는 것은 현명했다 생각합니다. 물리학 훨씬 더 기계가 할 것이라는 것을이 있다는 것을 알고있다. 그들은 보손을 찾을 수없는 경우, 누가 무엇을 위해 돈을 제공 할 것 "[NEWLINE] [TAB] [TAB] -? 피터웨어 힉스 [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_LARGE_HADRON_COLLIDER_DESC', '대형 하드론 충돌기 (LHC)는 세계에서 가장 크고 가장 높은 에너지 입자 가속기입니다. 물리학 자들은 LHC가 초등학교 객체 간의 상호 작용과 힘을 지배하는 기본 법칙에 관한 물리학의 근본적인 질문 중 일부를 답변 도움이되기를 바랍니다, 공간과 시간의 깊은 구조 및 양자 역학과 일반 상대성 특히 교차 현재의 이론과 지식이 불분명하거나 아예 분해 곳. 데이터는 과학적 모델의 버전이 정확하고 자신의 예측을 확인하고 더 이론적 인 개발을 허용하는 가능성. [NEWLINE] [NEWLINE] LHC는 둘레에있는 터널 27km에 놓여 있는지를 나타 내기 위해서 (때문에) 고 에너지 입자 실험에서 필요 스위스 제네바 부근 프랑스 - 스위스 국경 아래 많은 175으로 떨어져 있습니다. 이 싱크로는 핵 당 574 TEV의 에너지의 7 입자 당 teraelectronvolts (TEV), 또는 리드 핵 에너지에 하나의 양성자 입자 빔을 반대 충돌하도록 설계되었습니다. 용어의 강 입자는 쿼크로 이루어진 입자를 의미한다. 대형 하드론 충돌기가가 100 개국뿐만 아니라, 대학 및 연구소의 수백 만 명이 넘는 과학자와 엔지니어와 공동으로 지어진 핵 연구를위한 유럽기구 (CERN에 의해​​ 지어졌다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CHURCHES_LALIBELA', '랄리 벨라의 교회', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_CHURCHES_LALIBELA_HELP', '전체 25 % 더 믿음 제국을 제공합니다. [NEWLINE] 근처의 언덕에 믿음을 제공합니다. 국경 근처의 언덕에 확장합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_CHURCHES_LALIBELA_QUOTE', '[NEWLINE] [TAB] [TAB] "우리는 우리가 도구로 무엇을해야하며, 작업을 완료?"[NEWLINE] [TAB] [TAB] - Halie 셀라시에 [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_CHURCHES_LALIBELA_DESC', '랄리 벨라의 교회는 현대 에티오피아, 랄리 벨라의 마을 근처 단단한 바위에서 조각 교회의 모음입니다. 이 지역은 100 ~ 940 CE 1 ~ 8 백 년 동안 존재 악숨 왕국, 로마와 인도양 사이에 지배적 인 거래 파트너 동안 가능성이 종교 사이트이었다. Aksumites는 기독교를 채택하는 세계 최초의 주요 문명이었다. 종교는 대륙에서 가장 큰 믿음이되어, Aksumites 가능성이 아프리카 전역의 확산에 영향을 미치는 요인이되었습니다. [NEWLINE] [NEWLINE] 여러 교회가 많은 사람들이 그 거룩한의 비유로 생각하는 방식으로 배치되어 예루살렘의 도시입니다. 이것은 1197에있는 살라딘 예루살렘의 약 정복에 일부 건설 추정으로 이어질했다. 따라서, 건물의 대부분은 예루살렘에 관련된 이름이 있습니다. 이전 Roha로 알려진이 마을은, 이름으로 더 crediability을 제공하는 12 세기 동안 지배 Abysinnia의 왕 후 이름이 바뀌 었습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BANAUE_RICE_TERRACES', '바 나우에 라이스 테라스', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_BANAUE_RICE_TERRACES_HELP', '근처의 언덕에 음식을 제공합니다. 국경 근처의 언덕에 확장합니다. [NEWLINE] 언덕의 도시를 건설해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_BANAUE_RICE_TERRACES_QUOTE', '[NEWLINE] [TAB] [TAB] "당신이 정말 배고픈 뭔가의 이천을 먹고 싶다면 밥이 좋은 것입니다."[NEWLINE] [TAB] [TAB] - 미치 Hedberg [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_BANAUE_RICE_TERRACES_DESC', '바 나우에 라이스 테라스 필리핀이 푸가 오의 산에 새겨진 2000 년 이전 계단 테라스입니다. 그것은 일반적으로 테라스가 크게 손으로, 최소한의 장비로 구​​축 된 것으로 생각됩니다. 관중석은 산의 약 4000 평방 마일을 커버합니다. 그들은 테라스 위의 열대 우림에서 고대의 관개 시스템에 의해 공급된다. 단계가 끝과 끝을 넣어하는 경우, 그들은 반 지구를 둘러싸는 것이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PANAMA_CANAL', '파나마 운하', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PANAMA_CANAL_HELP', '증가 된 무역로의 보너스를 제공합니다. [NEWLINE] +1 배의 움직임을 제공합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PANAMA_CANAL_QUOTE', '[NEWLINE] [TAB] [TAB] "남자의 미세한 몸은 파나마 운하를 구축하는 작업을 수행 한 사람들보다 국가에 의해 수집 된 적이있다."[NEWLINE] [TAB] [TAB] - 시어 도어 루스벨트 [ NL] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PANAMA_CANAL_DESC', '파나마 운하의 바로 가기가 가능 배송 이전에 필요한 시간을 반으로 대서양과 태평양 바다 사이에 여행하는 것을했다. 태평양과 함께 미국 서부 해안 및 국가에 대한 짧은, 빠르고, 안전한 경로는 그 장소가 세계 경제에 더 통합 될 수있었습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_HOLLYWOOD', '할리우드', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HOLLYWOOD_HELP', '4 거래 가능한 무료 영화, 고급 리소스를 제공합니다. [NEWLINE] [ICON_TEAM_7] 무료 위대한 아티스트를 제공합니다. [NEWLINE]를', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HOLLYWOOD_QUOTE', '[NEWLINE] [TAB] [TAB] "할리우드는 당신의 영혼에 대한 사랑의 키스와 50 센트를위한 당신에게 수천 달러를 지불해야하는 곳입니다."[NEWLINE] [TAB] [TAB] - 마릴린 먼로 [NEWLINE] [ TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HOLLYWOOD_PEDIA', '할리우드는 미국 로스 앤젤레스의 도시 지역입니다. 그것의 명성과 영화 스튜디오와 영화 배우의 역사를 중심으로 문화 정체성, 단어 "할리우드는"자주 전반적으로 미국의 영화 산업을 나타내는 데 사용됩니다. [NEWLINE] [NEWLINE] 지역은 "이상적으로 생활을 시작했다 미국의 교외는 "영화 제작자가 도착하기 시작했을 때, 그러나 그것은 빨리 1909에서 성장하고, 지금은 미국의 영화 산업과 동의어입니다. 오늘, 할리우드의 꿈이 이루어과 소원이 실현되는 곳, 부자들과 유명한 사람의 땅 것에 대해 glamourised입니다. 그것은 할리우드 보울 및 가우 만 스 차이 중국어 극장 등 여러 가지 상징적 인 건물에 가정이다. 대부분의 사람들이 할리우드의 생각 그러나, 그들은 할리우드 언덕 꼭대기에 큰 기호 생각합니다. 이 기호는 "헐리웃"라는, 교외 결제 빌보드로 생활을 시작했다. 1949 년, "토지"가 업데이트 계약의 한 부분으로 제거 하였다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_WAT_PHRA_KAEW', '왓 프라 깨우', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_WAT_PHRA_KAEW_HELP', ' 모든 신사와 사원에서 +10 % 골드와 문화.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_WAT_PHRA_KAEW_QUOTE', '[NEWLINE] [TAB] [TAB] "당신은 습관에 의해 존중하면 지속적으로 가치, 네 가지의 증가 기리는 : 장수, 아름다움, 행복, 힘을."[NEWLINE] [TAB] [TAB] - 석가모니 부처님 [ NL] [TAB]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_WAT_PHRA_KAEW_DESC', '이 장엄한 사원은 태국에서 가장 신성한 불교 사원 (wat)으로 간주된다. 주요 건물은 에메랄드 불상의 동상을 전시하고 있습니다. 이 불상의 전설적인 역사는 인도로 추적, 그것은 마침내 1782 년에 왓 프라 깨우 사원 방콕에 안치되었다 때까지 주님 부처님은 열반을 달성 5 세기 이후. [NEWLINE] [NEWLINE] 방콕의 역사적인 중심부에 위치한 프라 깨우 모라 꼿 (에메랄드 불상), 꼼꼼하게 비취의 단일 블록에서 조각 매우 존경 불상 그랜드 팰리스의 경내, 그것은 모셔져. 에메랄드 불상 (프라 Putta 마하 마니 타나 Patimakorn)는 15 세기에서 데이트하는 북쪽의 란나 학교의 스타일로 명상 위치에서 부처님 이미지입니다. [NEWLINE] [NEWLINE] 플랫폼의 일련의 높은 발생 아무도는 왕을 제외하고 부처님 근처에 허용되지 않습니다. 계절 망토, 여름, 겨울에 해당하는 일년에 세번 변경, 장마가 동상을 다룹니다. 매우 중요한 의식, 가운의 변화는 각 기간 동안 국가에 행운을 가져다 왕에 의해서만 수행됩니다. 왕 부처 Yodfa Chulaloke (라마)가 움직일 때 [NEWLINE] [NEWLINE] 성전의 건축이 시작 1785 방콕 톤 부리에서 자본. 다른 사원과 달리 수도사 거처 포함되어 있지 않습니다 오히려, 그것은 단지 정교 거룩한 건물, 동상과 탑을 장식하고있다. 주요 건물은 에메랄드 불상을 전시 중심 ''ubosot''(안수 홀)입니다.', '', '');
/*  불가사의 : 수정  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_CHICHEN_ITZA_HELP', '1 무료 개척자 그것을 빌드시에 나타납니다. 작업자 개선 속도 +25 % 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COLOSSUS_HELP', '[ICON_TEAM_2] 화물선 : +1 [NEWLINE] [ICON_TRADE] 최대 무역 경로 : +1 [NEWLINE] [ICON_GOLD] 골드 : 여기에서 무역 루트 당 +2는 [NEWLINE] [ICON_LOCKED] 요구 사항 : 해안 도시', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_HAGIA_SOPHIA_HELP', '이 안으로 구성되어 도시로 cathderal 보너스를 추가합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MACHU_PICHU_HELP', '도시의 이익 근처 산 : [NEWLINE] [ICON_FOOD] 식품 : 5 [NEWLINE] [ICON_GOLD] 골드 : 5 [NEWLINE] [ICON_CULTURE] 문화 : 5 [NEWLINE] [ICON_PEACE] 믿음 : 5', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_STONEHENGE_HELP', '즉시 [ICON_PEACE] +5 믿음 차례 당 [ICON_PEACE] +20 믿음.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_TERRA_COTTA_ARMY_HELP', '가 내장되어있는 도시에서 즉시 +3 경계 확장.', '', '');








UPDATE Loaded File SET Value=1, KO_KR=1 Where Type='Cities.sql';




