/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/*  프로모션  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] 33퍼센트 [COLOR_POSITIVE_TEXT] 갑옷 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', '북극 전원', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 눈과 툰드라 [ENDCOLOR]의 빠른', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', '포격 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 랜드 [ENDCOLOR] 및 [COLOR_POSITIVE_TEXT] 바다 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', '폭격 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 랜드 [ENDCOLOR] 및 [COLOR_POSITIVE_TEXT] 바다 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', '사격 III', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 랜드 [ENDCOLOR] 및 [COLOR_POSITIVE_TEXT] 바다 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] +6 범위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] +6 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] 차단 장치를 취소 스윕을 말릴 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] 33퍼센트 대 [COLOR_POSITIVE_TEXT] 해군은 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', '할당', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] +10 %의 힘 [NEWLINE] [ICON_GOLD] -100 % [COLOR_POSITIVE_TEXT] 업그레이드 비용 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] 전체 바다를 건너 공격 해 손상이나 강 [NEWLINE] [ICON_STRENGTH] +100 % 때 [COLOR_POSITIVE_TEXT] 나섰다 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[COLOR_POSITIVE_TEXT] [ENDCOLOR] 장착 [COLOR_POSITIVE_TEXT] 갑옷 [ENDCOLOR] 단위 대 [ICON_STRENGTH] 25퍼센트 강도', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[COLOR_POSITIVE_TEXT] [ENDCOLOR] 장착 [COLOR_POSITIVE_TEXT] 갑옷 [ENDCOLOR] 단위 대 [ICON_STRENGTH] 25퍼센트 강도', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', '공기 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] VS 항공 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] 150% [COLOR_POSITIVE_TEXT] 대 폭격기와 헬기 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', '기병 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 기병 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', '보너스 전투기 대 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', '헬리콥터 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 헬기 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', '마운트 보너스 대 (10)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] 근접 대비 +10 %는 [COLOR_POSITIVE_TEXT] 마운트 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', '마운트 보너스 대 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] 근접 대 50퍼센트는 [COLOR_POSITIVE_TEXT] 마운트 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', '잠수함 대 공격 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] [COLOR_POSITIVE_TEXT] 잠수함 [ENDCOLOR] 대 [ENDCOLOR] 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', '탱크 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 탱크 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', '천문학', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 아이스 [의 ENDCOLOR]을 통과 할 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', '공격에 보너스 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', '공격에 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] 러프 [ENDCOLOR] 지형 (언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] 러프 [ENDCOLOR] 지형 (언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_RANGE_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] 러프 [ENDCOLOR] 지형 (언덕, 숲이나 정글) 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR]를 두 번 공격 할 수있다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 선박 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 선박 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 선박 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', '우정', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] 15 % 때 [COLOR_POSITIVE_TEXT] 아군 유닛에 [ENDCOLOR 인접한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] 공격 [COLOR_POSITIVE_TEXT] 1 이동 [ENDCOLOR]를 사용', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 아이스 [ENDCOLOR]을 통해 이동할 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', '자본 선박 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] 50퍼센트 대 [COLOR_POSITIVE_TEXT] 전함 [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 50퍼센트 대 [COLOR_POSITIVE_TEXT] 미사일 순양함 [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 캐리어 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] [COLOR_POSITIVE_TEXT] 1 [ENDCOLOR]화물을 운반 할 수 있습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] [COLOR_POSITIVE_TEXT 2 [ENDCOLOR]화물을 운반 할 수 있습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] [COLOR_POSITIVE_TEXT] 3 [ENDCOLOR]화물을 운반 할 수 있습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] [COLOR_POSITIVE_TEXT] 4 [ENDCOLOR]화물을 운반 할 수 있습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] +1 운동 [NEWLINE] [ICON_STRENGTH] 20 % [COLOR_POSITIVE_TEXT] 대 상처 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] 30퍼센트 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 강화 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', '도시 대 공격 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] [COLOR_POSITIVE_TEXT] 도시 [ENDCOLOR] 대 [ENDCOLOR] 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', '도시 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', '도시 대 보너스 (200)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] 200퍼센트 [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', '도시 대 보너스 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', '상인 레이더 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 항구 도시는 [ENDCOLOR] [NEWLINE] [ICON_GOLD] 피해의 33 %에 해당 금을 훔치는 대는 포트 처리', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', '상인 레이더 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 항구 도시는 [ENDCOLOR] [NEWLINE] [ICON_GOLD] 피해의 33 %에 해당 금을 훔치는 대는 포트 처리', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', '상인 레이더 III', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 항구 도시는 [ENDCOLOR] [NEWLINE] [ICON_GOLD] 피해의 34 %에 해당 금을 훔치는 대는 포트 처리', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 방어 [ENDCOLOR] VS [COLOR_POSITIVE_TEXT] 원거리 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 방어 [ENDCOLOR] VS [COLOR_POSITIVE_TEXT] 원거리 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', '원거리 페널티 대 (10)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] 10 % [COLOR_NEGATIVE_TEXT] 국방 [ENDCOLOR] 모든 [COLOR_NEGATIVE_TEXT] 원거리 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '10 % [COLOR_NEGATIVE_TEXT] 원거리 [ENDCOLOR] 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH]에 30퍼센트 [COLOR_POSITIVE_TEXT] 자본금 [ENDCOLOR] 장치가 떨어져 추가수록 보너스가 떨어진다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', '국방에 대한 페널티 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50 % [COLOR_NEGATIVE_TEXT] 국방 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] 물 타일 [COLOR_POSITIVE_TEXT]에 착수 할 수 [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +100 % [COLOR_POSITIVE_TEXT] 나섰다 [ENDCOLOR] 동안.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', '방어에 보너스 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', '방어에 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', '국방에 대한 페널티 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25 % [COLOR_NEGATIVE_TEXT] 국방 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', '사막 전원', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] 사막 [COLOR_POSITIVE_TEXT]에 빠른 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] 15 % 때 [COLOR_POSITIVE_TEXT] 아군 유닛에 [ENDCOLOR 인접한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] 33퍼센트 [COLOR_POSITIVE_TEXT] 에어 스윕 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] 33퍼센트 [COLOR_POSITIVE_TEXT] 에어 스윕 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] 34퍼센트 [COLOR_POSITIVE_TEXT] 에어 스윕 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS_HELP', '[ICON_WORKER] +100 % 빠르게 개선 구축', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS', '두 배의 작업 속도', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 거칠게 [ENDCOLOR] 지형 (언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 거칠게 [ENDCOLOR] 지형 (언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 거칠게 [ENDCOLOR] 지형 (언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 물 타일 [ENDCOLOR]에 착수 할 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', '착수 국방 (100)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] +100 % 때 [COLOR_POSITIVE_TEXT] 착수 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] +1 시력 범위 때 [COLOR_POSITIVE_TEXT] 나섰다 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50 %의 확률로 [COLOR_POSITIVE_TEXT] 피하다 [ENDCOLOR] 차단', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100 %의 확률로 [COLOR_POSITIVE_TEXT] 피하다 [ENDCOLOR] 차단', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT] 운동 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT] 운동 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH 인접한 적 유닛 [COLOR_POSITIVE_TEXT] -10 % [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', '먼저 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT] 무료 공격 [ENDCOLOR] 전투 전에', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] 50퍼센트 때 [COLOR_POSITIVE_TEXT]의 측면에 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] 모든 운동은 [COLOR_PLAYER_ORANGE_TEXT] 1 이동 [ENDCOLOR]를 사용하여', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', '외국 땅 보너스 (20)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', '형성', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] 35퍼센트 [COLOR_POSITIVE_TEXT] 마운트 [ENDCOLOR] 및 [COLOR_POSITIVE_TEXT] 기갑 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] 33퍼센트 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 마운트 유닛 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', '무료 업그레이드', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', '무료 업그레이드', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] 50 % 더 빠른 경험을 벌고', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] 15 %와 [COLOR_POSITIVE_TEXT] 위대한 장군은 [ENDCOLOR] 같은 타일', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', '골든', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '전투에서 [ICON_GOLDEN_AGE] 황금 시대 포인트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] 근처 [COLOR_POSITIVE_TEXT] 선박 [ENDCOLOR]의 전투 효율성을 향상', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] 근처 [COLOR_POSITIVE_TEXT] 지상 유닛의 전투 효과 [ENDCOLOR]을 향상', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1', '게릴라 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR] 거친 지형에 [NEWLINE] [ICON_DETECT] +1 사이트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2', '게릴라 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 거친 지형에 방어 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3', '게릴라 III', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3_HELP', '[ICON_STRENGTH] 20 % [COLOR_POSITIVE_TEXT] 거친 지형에 방어 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI 핸디캡', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'AI 핸디캡 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] +1 가시성 [NEWLINE] [ICON_WAR] +10 % 경험 [NEWLINE] [ICON_STRENGTH] +10 % [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI 핸디캡 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] +2 가시성 [NEWLINE] [ICON_WAR] 25퍼센트 체험 [NEWLINE] [ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] +2 가시성 [NEWLINE] [ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 도시 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '비 야만인 유닛을 죽이면 [ICON_HEAL] [COLOR_POSITIVE_TEXT] 50 손상 [ENDCOLOR] 고치 심', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] [ENDCOLOR] 이렇게 50 HP는 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 승진을 선택하는 기회를 소비하는 기기를 치유', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', '힐 파이터', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] 힐스 [COLOR_POSITIVE_TEXT]에 빠른 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] 친절한 지역 [COLOR_POSITIVE_TEXT]의 15 % [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', '모든 지형', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 이동할 수 산 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] 지형 비용을 무시', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] 장애물 [COLOR_POSITIVE_TEXT] 공격 할 수있다 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] 33퍼센트 강한 [COLOR_POSITIVE_TEXT] 도청 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] 33퍼센트 강한 [COLOR_POSITIVE_TEXT] 도청 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] 34퍼센트 강한 [COLOR_POSITIVE_TEXT] 도청 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[COLOR_POSITIVE_TEXT] 차단 [ENDCOLOR] 항공기 [ICON_AIR] 20 %의 확률로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[COLOR_POSITIVE_TEXT] 차단 [ENDCOLOR] 항공기 [ICON_AIR] 40 %의 확률로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[COLOR_POSITIVE_TEXT] 차단 [ENDCOLOR] 항공기 [ICON_AIR] 50 %의 확률로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[COLOR_POSITIVE_TEXT] 차단 [ENDCOLOR] 항공기 [ICON_AIR] 100 %의 확률로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', '차단', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] [COLOR_POSITIVE_TEXT] 공기 단위 [ENDCOLOR]를 차단하는 100 %의 확률로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] 문화 테두리 [NEWLINE] [ICON_DETECT] 만 떨어져 수중 음파 탐지기 또는 1 타일 단위로 볼 수있다을 무시하고', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] [COLOR_POSITIVE_TEXT] 숲 / 정글 [ENDCOLOR]에 33퍼센트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', '토지 대 보너스 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', '토지 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', '토지 대 페널티 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH] -50 % [COLOR_NEGATIVE_TEXT] 토지 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] 공​​격 및 이동하는 치유를 방지하지 않습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +10 치유 [ENDCOLOR] 1 타일 내에서 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT 인접한 타일 단위 턴에 +5 치유 [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT]이 유닛의 턴에 +5 치유 [ENDCOLOR] 할 때 [COLOR_POSITIVE_TEXT] 친절한 지역의 외부 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', '용병', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50 % [COLOR_POSITIVE_TEXT] 업그레이드 비용 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT] 운동 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] [COLOR_POSITIVE_TEXT] 숲 / 정글 [ENDCOLOR]에 33퍼센트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] 20 %의 힘', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', '등산가', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 산을 넘어갈 수 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', '마운트 페널티 대 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '그들은 차례 [COLOR_POSITIVE_TEXT] 적층 [ENDCOLOR]를 시작하면 [ICON_MOVES] [COLOR_POSITIVE_TEXT] 위대한 장군은 [ENDCOLOR] 본 기기의 속도로 이동', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] 원거리 공격에 설정해야합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 친절한 영토에 [ENDCOLOR] 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', '국립 보호', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 대 선박 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', '페널티 킥 공격 배 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', '해군 정찰기 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] +1 시력 [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] [ENDCOLOR] 외부 친화적 인 영토를 치유 할 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', '해군 정찰기 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] +1 운동에 [NEWLINE] [ICON_MOVES] 시도 [COLOR_POSITIVE_TEXT] 근접 전투에서 [ENDCOLOR] 철수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', '해군 포위 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] 30퍼센트 대 [COLOR_POSITIVE_TEXT] 도시 [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 30퍼센트 [COLOR_POSITIVE_TEXT] 강화 단위 대 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT] 운동 [ENDCOLOR] [NEWLINE] [ICON_DETECT] +1 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', '새로운 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', '새로운 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] 없습니다 도시를 캡처하는', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', '더 방어 지형 보너스 없음', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] 어떤 방어 지형 보너스 없음', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] 천문학 때까지 깊은 바다를 입력 할 수 없습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] 깊은 바다를 입력 할 수 없습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] 친절한 지역 [COLOR_POSITIVE_TEXT] +33 % 【ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] 단위는 [COLOR_NEGATIVE_TEXT] 단위 [ENDCOLOR] 만 도시를 공격 할 수있다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] 공격 근접하지 않을 수있다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', '파나마 운하', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '선박에 대한 [ICON_MOVES] +1 운동', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', '파르테논 신전', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '위대한 장군과 제독의 [ICON_STRENGTH] +10 %의 힘', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] 수 [COLOR_POSITIVE_TEXT] Paradrop [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '단위를 처치하면 [ICON_HEAL] 25 손상을 고치 심', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', '방진', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 마운트 [ENDCOLOR] 및 [COLOR_POSITIVE_TEXT] 군인 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] 캡처 [ENDCOLOR] 패배 적 [COLOR_POSITIVE_TEXT] 선박 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] +1 [COLOR_POSITIVE_TEXT] 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] 공격을 두 번 [ENDCOLOR] 90 %에 [ICON_RANGE_STRENGTH] 강도 원거리 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', '원거리 방어 대 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 방어 [ENDCOLOR] [COLOR_POSITIVE_TEXT] 원거리 공격력 VS [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 라이벌 지역을 입력 할 수 있습니다 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', '정찰 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] +2 사이트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', '정찰 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] +1 운동 [NEWLINE] [ICON_MOVES] 적 도로를 사용할 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', '정찰 III', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] 10 타일을 paradrop 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', '바다 대 보너스 (25)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 바다 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', '바다 대 보너스 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] 바다 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', '소나', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] [COLOR_POSITIVE_TEXT] 볼 수 잠수함 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] +1 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT]에 OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT]에 OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT]에 OPEN [ENDCOLOR] 지형 (NO 언덕, 숲이나 정글)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] 50퍼센트 대 [COLOR_POSITIVE_TEXT] 도시 [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 30퍼센트 [COLOR_POSITIVE_TEXT] 강화 단위 대 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', '작은 논쟁', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] 근접에서 철수하거나하는 시도는 전투를 착수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] +1 추가 [COLOR_POSITIVE_TEXT] 차단은 [ENDCOLOR] 턴에 만들어 질 수있다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] 전투 [COLOR_POSITIVE_TEXT] 위대한 장군을 만들 수있는 가능성 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] 전투 [COLOR_POSITIVE_TEXT] 위대한 장군을 만들 수있는 가능성이 매우 높다 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] 15 %는 [COLOR_POSITIVE_TEXT] 도시를 공격 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] 50퍼센트 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 부상 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +20 치유 [ENDCOLOR] 턴에 [COLOR_POSITIVE_TEXT] 외부 친절한 지역을 치유 수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] +5 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 외부 친화적 인 영토를 치유 [NEWLINE] [ICON_STRENGTH] 25퍼센트 [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] 단위는 [COLOR_POSITIVE_TEXT]은 [NEWLINE] [ICON_MOVES] 단위는 근접 공격에 직면했을 때 인출을 시도합니다 작업을 수행하는 경우에도, 각 회전 [ENDCOLOR]을 치유합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', '억압', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] 35퍼센트 [COLOR_POSITIVE_TEXT] 뱅가드는 [ENDCOLOR] 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', '생존 주의자', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '약탈에 [ICON_HEAL] +20 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 외부 친화적 인 영토를 치유 [NEWLINE] [ICON_MOVES] 어떤 이동 비용 없음', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] +1 시력 [NEWLINE] [ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 해군 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] +1 운동 [NEWLINE] [ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 해군 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] +1 시력 [NEWLINE] [ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 대 해군 [ENDCOLOR] 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1', '트렌치 I', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR] 열린 지형에 [NEWLINE] [ICON_DETECT] +1 사이트', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2', '트렌치 II', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2_HELP', '[ICON_STRENGTH] 15 % [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR] 열린 지형에', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3', '트렌치 III', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3_HELP', '[ICON_STRENGTH] 20 % [COLOR_POSITIVE_TEXT] 국방 [ENDCOLOR] 열린 지형에', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', '열린 국경없는 경쟁의 영토를 입력하지만, 그들은 같은 타일에 종료 각 차례 원래 종교적인 힘의 25 %를 손실 할 수 있습니다. 종교적 강도가 0 인 경우 단위는 제거된다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] 30퍼센트 [COLOR_POSITIVE_TEXT] [ENDCOLOR] 강화 단위 대', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] +100 % 때 [COLOR_POSITIVE_TEXT] 나섰다 [ENDCOLOR] [NEWLINE] +1 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR] 할 때 [COLOR_POSITIVE_TEXT] 착수 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', '지상 공격 페널티 (50)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[COLOR_NEGATIVE_TEXT] 지상과 선박 [ENDCOLOR] VS [ICON_RANGE_STRENGTH] -50 % 공격', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] 산림 빠르고 정글 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1 운동', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT 2 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT] 시력 범위 [ENDCOLOR]', '', '');





UPDATE LoadedFile SET Value=1, KO_KR=1 Where Type='Promotions.sql';

