/* The sql commands and text below were formulated in the Stories tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1563932649
If you make any changes be sure to update the spreadsheet also.*/

/*  지형  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING', '강 홍수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_DESC', '이 강 자주 계절 홍수는 농업에 대한 비정상적으로 비옥 한 표토를 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_1', '강을 따라 새로운 관개 수로를 지불.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_2', '홍수로부터 가정을 보호하기 위해 더 나은 방법을 연구하십시오.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_1', '[ICON_TEAM_3] 새로운 강 관개 {1}에 [ICON_FOOD] 음식을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_2', '[ICON_TEAM_3] 새로운 [ICON_RESEARCH] 연구 홍수에서 {1}의 시민을 보호하기 위해 진행되고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_3', '[ICON_TEAM_3] 새로운 강 관개 {1}에 대한 [ICON_GOLD] 경제 소득을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE', '사막 어도비', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_DESC', '점토 어도비 건축 비정상적으로 견고하고 아름다운 형태는 외부 개발 된 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_1', '우리의 문화 유적을 향상시키기 위해 독특한 스타일을 사용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_2', '실제 건설을위한 벽돌을 사용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_1', '[ICON_TEAM_3] 어도비 벽돌의 새로운 스타일은 {2}의 [ICON_CULTURE] 문화를 강화했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_2', '[ICON_TEAM_3] 어도비 건설 혁신은 {2} 근처에 [ICON_PRODUCTION] 생산을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_3', '[ICON_TEAM_3] 어도비 건설의 새로운 형태는 {2} 근처에 [ICON_GOLD] 경제 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS', '눈 썰매', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_DESC', '고산 여행의 혁신은 {2} 더 접근 근처 지형을했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_1', '레크리에이션 인종의 썰매를 사용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_2', '새로운 자원을 이용하기 위해 썰매를 사용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_1', '[ICON_TEAM_3] 눈 썰매의 혁신은 {2} 근처에있는 경주를 자극했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_2', '[ICON_TEAM_3] 눈 썰매의 혁신 개발에 {2} 근처에있는 자원을 열었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_3', '[ICON_TEAM_3] 눈 썰매의 혁신은 {2} 근처에 [ICON_GOLD] 경제 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE', '산 피난처', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_DESC', '{2} 근처 경치 산 꼭대기는 인간의 거주를 위해 비정상적으로 적합하다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_1', '휴식과 명상을위한 영적인 성소를 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_2', '별과 계절을 연구하는 학술 퇴각을 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_1', '[ICON_TEAM_3] 산 꼭대기 영적 피난처는 {2} 근처에 [ICON_CULTURE] 문화 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_2', '[ICON_TEAM_3] 산 꼭대기 학술 후퇴 {2} 근처에 [ICON_RESEARCH] 과학 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_3', '[ICON_TEAM_3] 상인 {2} 근처의 산 꼭대기 방문자에게 상품을 판매하고 있습니다.', '', '');
/* 를 개선  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING', '상업 농업', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_DESC', '부유 한 개인은 지역 농민들의 수익을 증가하지 않는 한, {2} 근처에 작은 농장을 구입하고 상용화 할 계획이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_1', '전통 농업의 문화에 투자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_2', '자기 인센티브와 합병을 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_3', '간섭없이 구매를 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_1', '[ICON_TEAM_3] 전통 농부 {2} 근처의 [ICON_CULTURE] 문화의 강한 부분입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_2', '{2} 근처 [ICON_TEAM_3] 상용화 향상 농장 [ICON_FOOD] 음식.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_3', '[ICON_TEAM_3] 매수는 {2} 근처 농장 [ICON_GOLD] 골드 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION', '광산 확장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_DESC', '{2} 근처 광산 운영자는 귀중한 광석을 발견하지만, 노동자는 새 분기 샤프트에 위험한 상황을 항의하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_1', '광산 안전을 개선하기 위해 국가의 지원을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_2', '파업 차단기를 고용하는 자기 자금을 사용합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_3', '광산 운영자가이 문제를 해결할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_1', '[ICON_TEAM_3] 광부 근처 {2} 안전한 노동 조건에 대한 [ICON_HAPPINESS_1] 행복하다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_2', '[ICON_TEAM_3] 신속히 {2}의 광산 확장 [ICON_PRODUCTION] 생산의 파업을 종료.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_3', '[ICON_TEAM_3] {2} 근처의 광산 [ICON_GOLD] 수익성 새로운 광석 정맥을 발견했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS', '마을 시위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_DESC', '{2} 근처 마을에있는 시민들은 높은 빈곤과 범죄에서 어려움을 겪고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_1', '더 나은 일을 위해 자격을 가난한 사람들을위한 교육을 향상시킬 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_2', '낮은 범죄율에 경찰을 향상시킬 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_3', '마을의 시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_1', '가난한 {2} [ICON_RESEARCH] 개선 교육 근처 [ICON_TEAM_3] 마을.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_2', '[ICON_TEAM_3] {2} 근처 마을은 낮은 범죄율에 대한 [ICON_HAPPINESS_1] 행복하다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_3', '[ICON_TEAM_3] 강한 경찰의 존재는 {2} 근처 마을의 [ICON_GOLD] 경제 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND', '농장 수요', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_DESC', '노동자가 저임금에 대한 필드를 수확 곳에 수요가 {2} 근처 농장의 작물 증가하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_1', '근로자의 임금 및 근로 조건을 개선하기 위해 법률을 제정.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_2', '수출 경제를 강화하기 위해 낮은 무역 장벽.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_3', '농장 주인이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_1', '[ICON_TEAM_3] 플랜테이션 선택기 근처 {2} 더 나은 근로 조건에 대한 [ICON_HAPPINESS_1] 행복하다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_2', '[ICON_TEAM_3] 낮은 무역 장벽은 {2} 근처 농장 [ICON_FOOD] 음식을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_3', '[ICON_TEAM_3] 근처의 수요 증가 향상 농장 [ICON_GOLD] 손익 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS', '이국적인 캠프 동물', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_DESC', '이국적인 동물은 {2} 근처의 캠프 밖에서 발견되었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_1', '동물을 만들어 관광을 개선하기 위해 유지.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_2', '사치스러운 사냥 별장을 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_1', '[ICON_TEAM_3] 이국적인 자연 {2} 근처에 개선 된 관광 [ICON_CULTURE] 문화를 보존.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_2', '[ICON_TEAM_3] 사냥 별장은 {2} 근처 이국적인 동물에서 [ICON_FOOD] 음식을 증가 시켰습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_3', '[ICON_TEAM_3] {2} 근처에 발견 이국적인 동물들 [ICON_GOLD] 금 사냥 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY', '품질 채석장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_DESC', '비정상적으로 높은 품질의 바위 정맥이 외부 채석장에서 발견 된 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_1', '바위에서 조각을 기술하는 장인을 고용.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_2', '속도 채광 작업에 별도의 기계를 투자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_3', '채석장 관리자가이 문제를 해결할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_1', '[ICON_TEAM_3] 장엄한 조각은 {2} 근처에 [ICON_CULTURE] 문화 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_2', '{2} [ICON_PRODUCTION] 확장 된 생산 근처 [ICON_TEAM_3] 채석장.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_3', '[ICON_TEAM_3] {2} 근처 채석장 [ICON_GOLD] 수익성 바위 정맥을 발견했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER', '이국적인 목재', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_DESC', '이국적인 나무는 외부 벌목장 근처에 발견 된 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_1', '관광을 개선하기 위해 국립 공원을 만듭니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_2', '목재 수출을위한 새로운 인프라를 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_3', '목재 사업이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_1', '[ICON_TEAM_3] 이국적인 국립 공원은 {2} 근처에 관광 [ICON_CULTURE] 문화 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_2', '[ICON_TEAM_3] {2} 근처 넓은 [ICON_PRODUCTION] 생산 인프라는 가치있는 나무를 내 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_3', '{2} 향상 목재 [ICON_PRODUCTION] 이익 근처에 발견 [ICON_TEAM_3] 이국적인 나무.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING', '목장 울타리', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_DESC', '농부는 근처 {2} 가축을 유지하기 위해 울타리를 구축하고자하지만, 목축업은 목초지의 손실에 대해 우려하고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_1', '울타리 농민의 노력 땅을 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_2', '개방 범위를 유지하는 목장 노동자의 노력을 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_3', '지역 주민이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_1', '[ICON_TEAM_3] 주변 농지에서 {2} [ICON_FOOD] 개선 된 음식 근처 목장 펜싱.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_2', '[ICON_TEAM_3] 목축업 근처 {2} 개방 범위에서 [ICON_PRODUCTION] 생산 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_3', '[ICON_TEAM_3] 근처 목장 노동자와 농민 사이의 타협은 {2} 로컬 [ICON_PRODUCTION] 경제 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND', '낚시 수요', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_DESC', '수요는 {2} 근처 바다에서 발견 된 해양 생물에 상승하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_1', '이국적인 바다 생물을 볼 시민을위한 도시 수족관을 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_2', '지역 어업을 확장하는 인프라를 구축 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_3', '지역 어업이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_1', '[ICON_TEAM_3] 희귀 한 해양 생물의 수조가있는 문화를 증가 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_2', '{2} 확장 [ICON_FOOD] 음식 출력 근처 [ICON_TEAM_3] 어부.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_3', '낚시에서 {2} [ICON_GOLD] 개선 골드 근처 [ICON_TEAM_3] 희귀 해양 생물.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION', '그럼 확장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_DESC', '석유 사업은 인근 {2}을 확장하고자하지만 관광 산업은 경관에 미치는 영향에 대해 우려하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_1', '새로운 국가 기념물과 관광 사업을 지원한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_2', '새로운 도로 및 인프라와 석유 개발을 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_3', '기업이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_1', '{2} 개선 관광 [ICON_CULTURE] 문화 인근의 아름다운 땅에 [ICON_TEAM_3] 기념물입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_2', '[ICON_TEAM_3] 새로운 인프라 확장 오일 [ICON_PRODUCTION] 생산 근처 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_3', '[ICON_TEAM_3] 오일 [ICON_GOLD] 이익 근처 {2} 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING', '플랫폼 해체', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_DESC', '오일 필드에있는 여러 해양 플랫폼은 근처 {2} 자신의 석유 공급을 소진.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_1', '인공 암초로 리그를 변환하여 어업을 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_2', '분해 및 다른 유전의 굴착을위한 재사용 부품.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_3', '사업이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_1', '[ICON_TEAM_3] 석유 굴 착은 {2} 근처에 낚시 [ICON_FOOD] 음식을 향상 인공 암초로 변환.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_2', '[ICON_TEAM_3] 재사용 고갈 오일 장비의 구성 요소는 {2} 근처에 [ICON_PRODUCTION] 생산을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_3', '[ICON_TEAM_3] 부근 [ICON_GOLD] 골드를 제기 폐기 석유 굴착 판매 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION', '포트 확장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_DESC', '요새의 담당 일반 근처 {2} 새로운 건설 노력을 시작하고자합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_1', '요새에서 새로운 군사 기술을 연구.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_2', '요새에 요새의 방어 능력을 업그레이드합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_3', '일반적으로이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_1', '[ICON_GOLD] 골드 : +6', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_2', '요새는 요새됩니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_1', '[ICON_TEAM_3] 요새 근처 {2} 확장 인력과 연구 시설.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_2', '[ICON_TEAM_3] 요새는 근처 {2} 요새로 확장.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_3', '[ICON_TEAM_3] 요새 외부 근처 제조업체는 {2} 새로운 무기 기술을 판매하고있다.', '', '');
/*  BUILDINGS  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM', '곡창 인구 붐', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_DESC', '{2}에있는 창고에 개선이 도시에 시민을 끌고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_1', '살 수있는 새로운 장소를 찾는 시민을위한 자금을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_2', '공공 프로그램에 대한 시민을 고용.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_1', '[ICON_TEAM_2] 세틀러 : +1', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_2', '[ICON_TEAM_2] 노동자 : +2', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_1', '[ICON_TEAM_3] {2}의 정부는 새로운 결제 프로그램에 자금을 지원.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_2', '[ICON_TEAM_3] {2}의 정부는 새로운 공공 프로그램에 자금을 지원.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_3', '[ICON_TEAM_3] 인구는 {2}에 호황을 누리고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT', '대장간 개발', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_DESC', '{2}에있는 대장간에서 개발 한 새로운 제련 과정은 노동자에게 잠재적으로 위험합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_1', '프로세스가 안전하기 위해 연구를 투자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_2', '즉시 생산에 프로세스를 넣어 자원을 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_1', '[ICON_TEAM_3] 광대 [ICON_RESEARCH] 연구는 {2}에 안전 제련 공정을 만들 수있는 방법을 받고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_2', '[ICON_TEAM_3] 새로운 제련 공정을 신속하게 {2}에 [ICON_PRODUCTION] 생산에 투입되었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_3', '[ICON_TEAM_3] 새로운 제련 과정은 {2}에 [ICON_GOLD] 이익 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY', '시장 독점', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_DESC', '지역 학교에 큰 기부를 제공하는 사업은 가격을 운전, {2}에있는 시장에서 독점을 형성한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_1', '가격을 낮추기 위해 독점을 깰.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_2', '자기 인센티브와 교육 기부를 지원합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_3', '높은 수익에 대한 세금을 수집합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_1', '[ICON_TEAM_3] {2}에 시민 [ICON_HAPPINESS_1] 가격 하락으로 행복하다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_2', '[ICON_TEAM_3] {2}의 새로운 독점 교육 [ICON_RESEARCH]에 많이 기부.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_3', '[ICON_TEAM_3] {2}의 시장 독점은 [ICON_GOLD] 골드 이익을 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY', '도서관 논쟁', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_DESC', '{2}의 역사에서 인종 차별에 대한 논란이 책은 폭동을 촉발한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_1', '도시의 난류 과거에 깊은 연구를 투자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_2', '폭동이 사라질 때까지 책을 금지.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_3', '이 책의 판매를 제기해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] 논란이 책은 {2}의 역사에 더 [ICON_RESEARCH] 연구를 시작합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_2', '[ICON_TEAM_3]에서 폭동 {2} [ICON_HAPPINESS_4] 분노가 금지 된 원인이되는 책으로 페이드.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] 논란이 책은 {2}에서 잘 판매 [ICON_GOLD]입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY', '기념물 논쟁', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_DESC', '{2}에있는 시민들은 제국주의 팽창 된 기념물 항의됩니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_1', '평화로운 문화를 홍보 연설을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_2', '군사적 확장을 지원하는 선전을 배포합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] 평화로운 [ICON_CULTURE] 문화 시위는 {2}을 통해 청소.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_2', '제국주의에​​ 대한 {2} [ICON_HAPPINESS_4] 감소 화에 [ICON_TEAM_3] 선전.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] 논란이 기념물은 {2}에 관광 [ICON_GOLD] 경제를 개선하고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS', '벽으로 둘러싸인 빈민가', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_DESC', '{2} 내부 지구가 빈민가에 악화와 함께, 오래 된 도시 벽을 넘어 확장의 개발.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_1', '문화 프로그램과 오래 된 도시를 활성화합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_2', '생산 기업을위한 공간을 확보하기 위해 빈민가를 철거.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_1', '[ICON_TEAM_3] {2}의 내부 도시는 [ICON_CULTURE] 문화를 소생.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_2', '[ICON_TEAM_3] 빈민가는 [ICON_PRODUCTION] 생산적인 기업에 대한 {2} 삭제 방에 철거.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_3', '[ICON_TEAM_3] 신규 사업은 {2}에 [ICON_GOLD] 골드 수익을 증가 시켰습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT', '병영 모집', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_DESC', '{2}의 시민들은 강제로 군대 징병에 대해 화가입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_1', '도시에서 낮은 징병 요금 정보를 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_2', '군 입대를 높이기 위해 전국의 선전에 투자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_TIP_2', '[ICON_WAR] 새로운 군 단위 : 2', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_1', '[ICON_TEAM_3] 감소 징병 비율은 {2}에 [ICON_HAPPINESS_4] 분노를 낮췄다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_2', '[ICON_TEAM_3] {2}에있는 막사 새로운 사병.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_3', '[ICON_TEAM_3] 전쟁 채권 선전 [ICON_GOLD] {2}의 수익을 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE', '콜로세움 출석', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_DESC', '{2}에있는 콜로세움은 기록적인 인파를 끌고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_1', '대중을 즐겁게하기 위해 정교한 대회를 표시합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_2', '애국 선전의 대규모 쇼 호스트.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_3', '시장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_1', '[ICON_TEAM_3] 대회는 {2} 콜로세움에서 [ICON_HAPPINESS_1] 해피 관중을 유치 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_2', '[ICON_TEAM_3] {2}의 콜로세움은 [ICON_CULTURE] 문화 선전의 거대한 쇼를 개최합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_3', '[ICON_TEAM_3] {2} 콜로세움 개선 [ICON_GOLD] 금의 수익을 올렸다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED', '안정 품종', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_DESC', '{2}의 마구간 말의 비정상적, 민첩 강한 자신감 품종을 올렸다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_1', '경마에 그들을 훈련.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_2', '전쟁 말대로 그들을 훈련.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_3', '안정 소유자가 결정하자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_TIP_2', '[ICON_WAR] 새로운 말 단위 : 2', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_1', '[ICON_TEAM_3] 경주마의 새로운 유형은 {2}에 [ICON_HAPPINESS_1] 행복을 향상.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_2', '[ICON_TEAM_3] {2}의 군대는 전쟁 말의 새로운 품종을 올렸다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_3', '[ICON_TEAM_3] 새로운 말 품종은 [ICON_GOLD] {2}의 수익을 개선.', '', '');
/*  CITYSTATES  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION', '도시 국가 이민', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_DESC', '일부 근로자는 {2}의 도시 국가에서 이민자가 멀리 문명의 시민들 작업을 복용하는 느낌.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_1', '프로그램은 시민권 이민자에게 경로를 제공하기 위해 비용을 지불합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_2', '이민자를 추방하고 자신의 집을 압수.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_3', '민족 관념을 폐기.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_1', '[ICON_INFLUENCE]에 미치는 영향 : +70', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_2', '[ICON_INFLUENCE]에 미치는 영향 : -70 [NEWLINE] [ICON_GOLD] 골드 : +200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_3', '[ICON_INFLUENCE]에 미치는 영향 : +10', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_1', '[ICON_TEAM_3] {2}에서 이민자는 {1}의 제국 시민권에 대한 경로를 얻을 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_2', '[ICON_TEAM_3] {1}의 정부는 {2_target)에서 이민자를 추방.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_3', '[ICON_TEAM_3] {1}의 정부는 {2}의 시민에 대한 고정 관념을 비난했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE', '환전', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_DESC', '통화의 가치는 상승하고, 그 결과 무역 불균형은 {2}에 대한 수출을 아프게 위험이 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_1', '수출이 방해받지 않고 계속 할 수 있도록 고정 된 환율을 설정합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_2', '시티 스테이트의 비용으로, 더 이상 통화를 강화하는 법률을 제정.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_3', '금융의 당신의 장관이이 문제를 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_1', '[ICON_INFLUENCE]에 미치는 영향 : +70', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_2', '[ICON_INFLUENCE]에 미치는 영향 : -70 [NEWLINE] [ICON_GOLD] 골드 : +200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_3', '[ICON_INFLUENCE]에 미치는 영향 : +10', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_1', '[ICON_TEAM_3] 고정 된 통화의 환율은 [ICON_INFLUENCE] 관계를 증폭, {2}에서 {1} (으)로부터 수출을 개선.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_2', '[ICON_TEAM_3] {1}의 통화는 {2}의 경제를 희생 [ICON_GOLD] 금을 제공, 가치를 극적으로 상승했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_3', '[ICON_TEAM_3]에 {1}의 통화 환율 개선 수출에 대한 변경 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT', '외교 사건', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_DESC', '방문에 {2} 당신으로 인해 문화적 오해로, 외교 이벤트 기간 동안 심각한 가짜 싶어서 최선을 다하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_1', '선물을 보내고 다시 일어나게 결코 약속, 실수에 대한 공식 사과를합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_2', '동작 사회에서 허용되는, 당신은 당신의 문명의 뿌리에 대해 사과하지 않습니다 설명한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_3', '당신의 외교관들은이 문제를 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_1', '[ICON_INFLUENCE]에 미치는 영향 : +70 [NEWLINE] [ICON_CULTURE] 문화 : -200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_2', '[ICON_INFLUENCE]에 미치는 영향 : -70 [NEWLINE] [ICON_CULTURE] 문화 : +200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_3', '[ICON_INFLUENCE]에 미치는 영향 : +10', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_1', '[ICON_TEAM_3] 외교 사건 이후 사과는 [ICON_INFLUENCE] {1}과의 관계를 개선 {2}.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_2', '[ICON_TEAM_3] {1}의 [ICON_CULTURE] 문화의 단점에 대해 사과하는 거절 {2}과 외교적 사건을했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_3', '[ICON_TEAM_3] 방문에 {1}의 외교 사건은 {2} 두 나라 사이의 문화적 이해를 높일 수있었습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME', '수학 명예의 전당', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_DESC', '제국의 존경하는 학교에서 공부하는 응용 프로그램은 {2}의 외국인 학생에서 급증하고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_1', '학생들을위한 이민 제한을 완화합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_2', '국내 학생들에게 등록을 제한합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_3', '학교 학장이 처리 할 수​​ 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_1', '[ICON_INFLUENCE]에 미치는 영향 : +70 [NEWLINE] [ICON_RESEARCH] 과학 : -200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_2', '[ICON_INFLUENCE]에 미치는 영향 : -70 [NEWLINE] [ICON_RESEARCH] 과학 : +200', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_3', '[ICON_INFLUENCE]에 미치는 영향 : +10', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_1', '[ICON_TEAM_3] 교육의 질은 {1}와 {2} [ICON_INFLUENCE] 관계 개선에서 외국 학생들에게 제공했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_2', '[ICON_TEAM_3] 새로운 [ICON_RESEARCH] 교육 법률은 {2}에서 이민자에 {1}의 국내 학생을 선호.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_3', '[ICON_TEAM_3] {2}에서의 외국인 학생들은 {1}의 학교에 몰려 들고있다.', '', '');
/*  단위  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR', '스카우트 구주', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_DESC', '귀하의 스카우트는 치명적인 짐승에서 유목민 족장의 아이를 구출. 감사 사냥꾼은 자신의 캠프에서 당신의 환대를 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_1', '탐사에 참여하기 위해 몇 유목민을 부탁드립니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_2', '사냥 리본으로 빠르게 이동하는 기차.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_3', '잠시 동안 캠프에서 휴식.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_1', '중복 및 치유 스카우트.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_2', '빠르게 이동 아처로 대체합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_3', '스카우트을 치유하고, 이익이 5 [ICON_WAR] 체험.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_1', '[ICON_TEAM_3] {2} 유목민의 부족에서 {1}에 합류했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_2', '[ICON_TEAM_3] {2} {1} 사냥 활을 사용하는 학습의.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_3', '[ICON_TEAM_3] {2}의 {1} 유목민 아이를 저장 한 후 휴식.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES', '스카우트 이야기', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_DESC', '귀하의 스카우트는 수많은 위험을 무릅 쓰고 많은 놀라운 땅을 발견, 먼 곳까지 여행했다. 자본의 시민들이 이야기를 듣고 싶어합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_1', '그들의 여행의 서사시를 기술하는 작가를 고용.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_2', '새로운 교육과 새로운 무기와 정찰을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_3', '스카우트 이동 한 후, 자신의 이야기를 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_1', '[ICON_CULTURE] 문화 : +100', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_2', '센티넬에 대한 치유 및 업그레이드.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_3', '[ICON_CULTURE] 문화 : +30', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_1', '[ICON_TEAM_3] 스카우트의 여행의 서사시는 {1}의 [ICON_CULTURE] 문화 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_2', '[ICON_TEAM_3]의 스카우트는 {1} 새로운 갑옷과 무기로 업그레이드.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_3', '[ICON_TEAM_3] 스카우트의 여행의 이야기는 {1}의 [ICON_CULTURE] 문화 증가했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR', '유명한 전사', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_DESC', '귀하의 전사는 용기의 노래 이야기와 함께, 제국에서 인기를 얻고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_1', '그들이 민간인으로 돌아 가자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_2', '그들에게 새로운 무기를 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_3', '그들에게 신선한 공급을 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_1', '지형 비용을 무시하는 노동자로 변환합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_2', '검객으로 변환합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_3', '치유 이익 5 [ICON_WAR] 체험.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_1', '[ICON_TEAM_3] {1}의 전사 민간인으로 돌아.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_2', '[ICON_TEAM_3] {1}의 전사가 새로운 무기를 받았다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_3', '[ICON_TEAM_3] {1}의 전사 신선한 공급을 받았다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER', '유명한 아처', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_DESC', '귀하의 사수는 사격의 이야기 이야기로, 제국에서 인기를 얻고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_1', '그들이 민간인으로 은퇴하자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_2', '그들에게 새로운 무기를 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_3', '그들에게 신선한 공급을 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_1', '지형 비용을 무시하는 노동자로 변환합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_2', '복합 보먼로 변환합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_3', '치유 이익 5 [ICON_WAR] 체험.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_1', '[ICON_TEAM_3]의 궁수 {1} 민간인으로 은퇴했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_2', '[ICON_TEAM_3] {1}의 궁수는 새로운 무기를 받았다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_3', '[ICON_TEAM_3] {1}의 궁수 신선한 공급을 받았다.', '', '');
/*  커스텀  */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB', '토지 잡아', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_DESC', '시민은 {2} 일을 더 나은 땅을 요구한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_1', '제국에 더 많은 토지를 합병하기 위해 금액을 지불합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_2', '반체제 인사를 징집하고 작업을했습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_3', '시장이 처리하자', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_1', '[ICON_TEAM_6] 새로운 타일 : 3', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_2', '[ICON_TEAM_2] 새 작업자 : 1', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_3', '[ICON_TEAM_6] 새로운 타일 : 1', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_1', '[ICON_TEAM_3] {2}의 시민들은 큰 새로운 영토를 합병.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_2', '[ICON_TEAM_3] {2}에있는 반체제 인사는 인력에 징집되었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_3', '[ICON_TEAM_3]의 시민은 {2} 새로 부속 토지를 작동합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES', '바바리안 용병', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_DESC', '당신의 국경에 적대적인 침입자의 그룹 측면을 전환 할 수도 있습니다 - 가격.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_1', '당신의 민간 인력을 위해 그들을 고용.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_2', '그들에게 군사 용병을 고용.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_3', '반역자를 매복 자신의 물품을 약탈.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_1', '[ICON_TEAM_2] 새로운 노동자 : 1', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_2', '[ICON_TEAM_2] 새로운 군 단위 : 2', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_3', '[ICON_GOLD] 골드 : +25', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_1', '[ICON_TEAM_3] 야만인은 {1}의 민간 인력을 합류했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_2', '[ICON_TEAM_3] 바바리안 용병 {1}의 군대에 합류했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_3', '[ICON_TEAM_3] 바바리안 용병은 {1} 습격했다.', '', '');







UPDATE LoadedFile SET Value=1, KO_KR=1 Where Type='Stories.sql';


