--· EN_US/GreatWorks.sql
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_MISSION_CULTURE_BOMB_DISABLED_COOLDOWN', 'You have created a Great Work recently, and may not do so again for another {1_Num} turns.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_ADV_QUEST', 'What does the great work special ability do?', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_HEADING4_BODY', 'A Great Artist can create a Great Work in any city you own. Great Works give the city a large amount of [ICON_CULTURE] Culture.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SPECIALISTSANDGP_CULTUREBOMB_HEADING4_TITLE', 'Special Ability: Create Great Work', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_MISSION_GREAT_WORK', 'Create Great Work', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_MISSION_GREAT_WORK_HELP', 'A Great Work gives a city a large amount of [ICON_CULTURE] Culture.[NEWLINE][NEWLINE]Creating a Great Work consumes the Great Person.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_MISSION_GREAT_WORK_ALERT', '{1_greatperson} created {2_work}. You gained {3_culture} [ICON_CULTURE] Culture in {4_city}!', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DEFAULT', 'a magnum opus', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_HOMER', 'the Iliad', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_THESPIS', 'the first tragedy performance', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_LING_LUN', 'the five-tone music scale', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_WANG_XIZH', 'the Preface to the Poems Composed at the Orchid Pavilion', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_VALMIKI', 'the Ramayana', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_VIRGIL', 'the Aeneid', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_KALIDAS', 'Of Shakuntala recognised by a token', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_LI_PO', 'Waking From Drunkenness on a Spring Day', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DU_FU', 'The Song of the Wagons', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JALAL_ALDIN_RUMI', 'his Spiritual Couplets', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DANTE_ALIGHIERI', 'the Divine Comedy', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_YUNUS_EMRE', 'his poems of Sultan Yunu Emre', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_AMIR_KHUSRO', 'The Tale of the Four Dervishes', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_IBN_MUQLAH', 'the thuluth script', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_MICHAELANGELO', 'the Statue of David', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_RAPHAEL', 'the Stanza della Segnatura', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_WILLIAM_SHAKESPEARE', 'Hamlet', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_MIGUEL_DE_CERVANTES', 'Don Quixote', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_REMBRANDT', 'The Night Watch', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JOHANNES_VERMEER', 'Girl With a Pearl Earring', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JS_BACH', 'the Brandenburg Concertos', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_WOLFGANG_MOZART', 'The Magic Flute', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JOHANN_GOETHE', 'Faust', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_LUDWIG_VAN_BEETHOVEN', 'his Fifth Symphony', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_VICTOR_HUGO', 'Les Misérables', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_VINCENT_VAN_GOGH', 'Café Terrace at Night', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JOHANNES_BRAHMS', 'the Hungarian Dances', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DVORAK', 'his Symphony From the New World', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_MARK_TWAIN', 'The Adventures of Tom Sawyer', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_CLAUDE_MONET', 'Impression, Sunrise', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_JOSEPH_CONRAD', 'Victory', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_FRANK_KAFKA', 'The Trial', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_LOUIS_ARMSTRONG', 'What a Wonderful World', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DUKE_ELLINGTON', 'Take the ''A'' Train', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_PABLO_PICASSO', 'Guernica', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_MILES_DAVIS', 'Kind of Blue', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_PERSON_TOLSTOY', 'Leo Tolstoy', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_TOLSTOY', 'War and Peace', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_PERSON_DOSTOEVSKY', 'Fyodor Dostoevsky', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_GREAT_WORK_DOSTOEVSKY', 'Crime and Punishment', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='GreatWorks.sql';
