--· EN_US/Policies.sql
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_CONSCRIPTION', 'Conscription', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_CONSCRIPTION_HELP', '+10 [COLOR_POSITIVE_TEXT]Heal Rate[ENDCOLOR].', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Professional Army', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Unlocks advanced promotions.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_MERCANTILISM', 'Mercantilism', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_MERCANTILISM_HELP', '+2 [ICON_MOVES] Movement.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_FREEDOM', 'Freedom', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_FREEDOM_HELP', '+25% [ICON_STRENGTH] Strength in friendly territory.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICIES_CULTURAL_VICTORY', 'Upon completing 6 Policy branches, you may construct the [COLOR_POSITIVE_TEXT]Utopia Project[ENDCOLOR] in one of your Cities, triggering a [COLOR_POSITIVE_TEXT]Cultural Victory[ENDCOLOR]!', '', '');
/* Liberty */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Good for quickly claiming early territory.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+1 Palace in oldest 3 cities.[NEWLINE]+1 [ICON_CULTURE] Culture in all cities.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+3 [ICON_PRODUCTION] Production in cities with a Specialist.[NEWLINE]+1 [ICON_TEAM_2] Great Person of choice.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '+1 [ICON_TEAM_2] Settler at the Capital.[NEWLINE]+20% [ICON_PRODUCTION] Production for Settlers.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MERITOCRACY_HELP', 'Gives a lump sum of [ICON_GOLD] Gold.[NEWLINE][NEWLINE]Reduces policy costs in large empires, so cities with Theaters are revenue-neutral for policy rate.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CITIZENSHIP_HELP', '+2 [ICON_TEAM_2] Workers at the Capital.[NEWLINE]+25% [ICON_WORKER] worker improvement speed.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_REPRESENTATION_HELP', '+1 [ICON_HAPPINESS_1] National Happiness in [ICON_CONNECTED] Connected cities.[NEWLINE]-5% [ICON_HAPPINESS_4] Unhappiness from [ICON_CITIZEN] Population in cities that are not [ICON_OCCUPIED] Occupied.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_REPUBLIC_HELP', '+2 [ICON_PRODUCTION] Production from [ICON_STRENGTH] Defense buildings.[NEWLINE]Constructs 1 [ICON_STRENGTH] Defense Building in current and future cities.', '', '');
/*  Tradition */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Good for developing a few big cities.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+3 [ICON_CULTURE] Culture in the [ICON_CAPITAL] Capital.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]200% [ICON_CULTURE] cultural border expansion rate to tiles far from cities.[NEWLINE]Can purchase Great Engineers with [ICON_PEACE] Faith once you enter the Industrial era.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_ORAL_HISTORY', 'Storytellers', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_ORAL_HISTORY_HELP', '+2 [ICON_CULTURE] Culture for the Palace and Villages.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'Oral tradition is cultural material and tradition transmitted orally from one generation to another. The messages or testimony are verbally transmitted in speech or song and may take the form, for example, of folktales, sayings, ballads, songs, or chants. In this way, it is possible for a society to transmit verbal history, verbal literature, verbal law and other knowledge across generations without a writing system.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CEREMONIAL_RITES', 'Ceremonial Rites', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '+2 [ICON_CULTURE] Culture from Cultural Buildings.[NEWLINE]Constructs 1 [ICON_CULTURE] Culture Building in your oldest 5 cities.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'A ceremony is an event of ritual significance performed on a special occasion. Ceremonies may have a physical display or theatrical component: dance, a procession, the laying on of hands. A declaratory verbal pronouncement may be associated with the occasion.[NEWLINE][NEWLINE]A ceremony may mark a rite of passage in a human life, marking the significance of birth, adulthood, initiation into a group, or death. Sometimes a ceremony may only be performed by a person with certain authority. Society-wide ceremonies may mark annual or seasonal or recurrent events, such as the vernal equinox, winter solstice and other annual astronomical positions.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_LANDED_ELITE_HELP', '+15% [ICON_FOOD] Surplus Food and +2 [ICON_FOOD] Food in each city.[NEWLINE]Unlocks the Banaue Rice Terraces.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_OLIGARCHY_HELP', '+50% [ICON_RANGE_STRENGTH] Strength for garrisoned cities.[NEWLINE]Garrisoned units cost 0 [ICON_GOLD] Maintenance.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_ARISTOCRACY_HELP', '+15% [ICON_PRODUCTION] Production for building Wonders.[NEWLINE]+1 [ICON_HAPPINESS_1] Happiness per 10 [ICON_CITIZEN] Citizens.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_MONARCHY_HELP', '+1 [ICON_GOLD] Gold and -1 [ICON_HAPPINESS_4] Unhappiness per 2 [ICON_CITIZEN] Citizens in the [ICON_CAPITAL] Capital.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-11-18'), 'TXT_KEY_POLICY_LEGALISM_HELP', '1 free culture building in your first 4 cities.[NEWLINE]Unlocks the Oracle.', '', '');
/* Honor */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Good for fighting barbarians, and conquering enemies.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]Reveals Barbarian camps.[NEWLINE]+10% Strength against Barbarians.[NEWLINE]Killing barbarians gives 5 [ICON_CULTURE] Culture per 1[ICON_STRENGTH] Strength.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+1 [ICON_HAPPINESS_1] City Happiness and +2 [ICON_CULTURE] Culture for cities with a Garrison or Barracks.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MILITARY_TRADITION_HELP', '+2 [ICON_TEAM_2] Defense Units at the Capital.[NEWLINE]+20% [ICON_PRODUCTION] Production for military units and buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SPOILS_OF_WAR', 'Spoils of War', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', 'You salvage [ICON_GOLD] Gold from the equipment of defeated enemies.[NEWLINE]+25% instant rewards from capturing [ICON_CITY_STATE] City-States.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Looting by a victorious army during war has been common practice throughout recorded history. For foot soldiers, it was viewed as a way to supplement their often meagre income and was part of the celebration of victory. On higher levels, the proud exhibition of loot was an integral part of the typical Roman triumph, and Genghis Khan was not unusual in proclaiming that the greatest happiness was "to vanquish your enemies... to rob them of their wealth..."[NEWLINE][NEWLINE]In warfare in ancient times, the spoils of war included the defeated populations, which were often enslaved, and the women and children, who were often absorbed into the victorious country''s population. In other pre-modern societies, objects made of precious metals were the preferred target of war looting, largely because of their easy portability. In many cases looting was an opportunity to obtain treasures that otherwise would not have been obtainable. Since the 18th century, works of art have increasingly become a popular target. In the 1930s and even more so during World War II, Nazi Germany engaged in large scale and organized looting of art and property.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_WAR_EPICS', 'War Epics', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_WAR_EPICS_HELP', '+1 [ICON_HAPPINESS_1] City Happiness from Culture buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_WAR_EPICS_TEXT', 'An epic (from the Ancient Greek adjective ἐπικός (epikos), from ἔπος (epos) "word, story, poem") is a lengthy narrative poem, ordinarily concerning a serious subject containing details of heroic deeds and events significant to a culture or nation.[NEWLINE][NEWLINE]War epics are epic poems or a literary works of epic scope which seek or are believed to capture and express the essence or spirit of a particular nation, or an ethnic or linguistic group with aspirations to independence or autonomy. National epics frequently recount the origin of a nation, a part of its history, or a crucial event such as decisive victories or the vanquishing of bitter foes, in the development of national identity.
', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MILITARY_CASTE_HELP', '+1 [ICON_HAPPINESS_1] City Happiness and +2 [ICON_CULTURE] Culture for each city with a garrison.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_DISCIPLINE_HELP', '+1 [ICON_TEAM_7] Great General at the Capital.[NEWLINE]+1[ICON_MOVES] Movement for Great Generals.[NEWLINE]+15% [ICON_STRENGTH] Strength for units adjacent to friendly military units.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% when [COLOR_POSITIVE_TEXT]adjacent[ENDCOLOR] to friendly military units.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '-25% [ICON_GOLD] Maintenance cost for units.[NEWLINE]-50% [ICON_GOLD] Upgrade cost for units.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT]Warrior Code[ENDCOLOR][NEWLINE]', '', '');
/* Piety */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-22'), 'TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Good for Happiness and Religion.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+5 [ICON_HAPPINESS_1] National Happiness.[NEWLINE]+50 [ICON_PEACE] Faith.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]-25% [ICON_PEACE] Faith purchase costs.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CHARITY', 'Charity', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CHARITY_HELP', '+5% [ICON_GOLD] Gold from religious buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CHARITY_PEDIA', 'The word "charity" comes from the Old French word "charité" which, in turn, was derived from the Latin "caritas".[NEWLINE][NEWLINE]The practice of charity means the voluntary giving of help to those in need who are not related to the giver, though the original meaning is more involved with the concepts of preciousness, dearness, high price. Charitable giving is done directly or by means of a charitable trust or other worthy cause. These institutions evolved to carry out the labor of assisting the poor, and came to be called, called ''charities''. In modern times ''charities'' provide the bulk of charitable giving, in terms of monetary value. The types of charities include orphanages, food banks, religious institutes dedicated to care of the poor, hospitals, organizations that visit the homebound and imprisoned, and many others.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_INSPIRATION', 'Inspiration', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_INSPIRATION_HELP', '+1 [ICON_TEAM_7] Free Policy.[NEWLINE]+2 [ICON_CULTURE] Culture from religious buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_INSPIRATION_PEDIA', 'The word "inspiration" comes from the Latin noun inspiratio and from the verb inspirare. Inspirare is a compound term resulting from the Latin prefix in (inside, into) and the verb spirare (to breathe).[NEWLINE][NEWLINE]In classic Roman times, inspirare had already come to mean "to breathe deeply" and assumed also the figurative sense of "to instill [something] in the heart or in the mind of someone".[NEWLINE][NEWLINE]Hence ''inspiration'' refers to an unconscious burst of creativity in a literary, musical, or other artistic endeavour. The concept has origins in both Hellenism and Hebraism. The Greeks believed that inspiration came from the muses, as well as the gods Apollo and Dionysus. Similarly, in the Ancient Norse religions, inspiration derives from the gods, such as Odin. Inspiration is also a divine matter in Hebrew poetics. In the Book of Amosthe prophet speaks of being overwhelmed by God''s voice and compelled to speak. In Christianity, inspiration is a gift of the Holy Spirit.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TOLERANCE', 'Tolerance', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TOLERANCE_HELP', '+1 [ICON_HAPPINESS_1] City Happiness from Shrines and Temples.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Tolerance or toleration is "the practice of deliberately allowing or permitting a thing of which one disapproves. One can meaningfully speak of tolerating, ie of allowing or permitting, only if one is in a position to disallow”. It has also been defined as "to bear or endure" or "to nourish, sustain or preserve". Toleration may signify “no more than forbearance and the permission given by the adherents of a dominant religion for other religions to exist, even though the latter are looked on with disapproval as inferior, mistaken or harmful”[NEWLINE][NEWLINE]Tolerance is an attitude of mind that implies non-judgmental acceptance of different lifestyles or beliefs, whereas toleration implies putting up with something that one disapproves of.[NEWLINE][NEWLINE]Historic examples of ''tolerance'' abound. For instance in an act of tolerance, the Persian king Cyrus the Great was believed to have released the Jews from captivity in 539–530 BC, and permitted their return to their homeland.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_UNITY', 'Unity', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_UNITY_HELP', '10 turn [ICON_GOLDEN_AGE] Golden Age.[NEWLINE]25% less [ICON_HAPPINESS_1] National Happiness required for [ICON_GOLDEN_AGE] Golden Ages.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_UNITY_PEDIA', 'Unity refers to the ties in a society that bind people to one another. The term is generally employed in sociology and the other social sciences.[NEWLINE][NEWLINE]In simple societies it may be mainly based around kinship and shared values. In more complex societies there are various theories as to what contributes to a sense of social solidarity.[NEWLINE][NEWLINE]This brings in the associated term of ''solidarity'' of which it is said:[NEWLINE]"Solidarity does not assume that our struggles are the same struggles, or that our pain is the same pain, or that our hope is for the same future. Solidarity involves commitment, and work, as well as the recognition that even if we do not have the same feelings, or the same lives, or the same bodies, we do live on common ground." - Sara Ahmed', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_DEVOTION', 'Devotion', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-22'), 'TXT_KEY_POLICY_DEVOTION_HELP', '+3 [ICON_PEACE] faith per turn.[NEWLINE]+1 [ICON_PEACE] faith per city.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_DEVOTION_PEDIA', 'Devotion may be defined as: ardent, often selfless affection and dedication, as to a person or principle. Worship, from the Old English worthscipe, meaning worthiness or worth-ship is an act of religious devotion usually directed towards a deity. Closely allied to the concept of love, devotion is often hoped to be reciprocated with some form of boon or blessing.[NEWLINE][NEWLINE]Devotees, as those who practice devotion are called wanting to receive these blessings, are often single-minded to the point of fanaticism. Thus whilst the concept of ''devotion'' is benign, many historical examples of religious devotion are often extreme and bloody, as devotees vie for the affection of the devoted with more outrageous displays.', '', '');
/* Wealth */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_COMMERCE', 'Wealth', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'WEALTH', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT_KEY_POLICY_BRANCH_COMMERCE}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT_KEY_POLICY_BRANCH_COMMERCE}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_COMMERCE_TEXT', 'Wealth is the abundance of valuable resources or material possessions. The concept of wealth is significant in all areas of economics, yet the meaning of wealth is context-dependent and there is no universally agreed upon definition. At the most general level wealth is &quot;anything of value&quot;, which captures both the subjective nature of the word, and the idea that it is not a fixed or static concept.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'What is the Wealth social policy branch about?', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'The branch of Wealth focuses on developing wide territory, with a national supply of [ICON_GOLD] Gold created by core cities to purchase new units and buildings in undeveloped frontier cities.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'The branch of Wealth focuses on developing wide territory, with a national supply of [ICON_GOLD] Gold created by core cities to purchase new units and buildings in undeveloped frontier cities. See the rules on Social Policies for details.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'The Wealth Branch', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Good for building things faster in cities.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+15% [ICON_GOLD] gross national income.[NEWLINE]Can purchase Great Merchants with [ICON_PEACE] Faith once you enter the Industrial era.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+1 [ICON_HAPPINESS_1] National Happiness from each Luxury resource, including surplus copies.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MERCANTILISM_HELP', '+2[ICON_MOVES] Movement for non-combat units.[NEWLINE]+25% [ICON_GOLD] Income from [ICON_CONNECTED] Domestic Trade.[NEWLINE]-25% [ICON_GOLD] Cost for roads and railroads.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_GUILDS', 'Guilds', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_GUILDS_HELP', '+1 [ICON_TEAM_7] Great Merchant at the Capital.[NEWLINE]+100% [ICON_GOLD] Gold from Great Merchant trade missions.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_GUILDS_TEXT', 'A guild is an association of craftsmen in a particular trade. The earliest types of guild were formed as confraternities of workers. They were organized in a manner something between a trade union, a cartel, and a secret society. They often depended on grants of letters patent by a monarch or other authority to enforce the flow of trade to their self-employed members, and to retain ownership of tools and the supply of materials.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PROTECTIONISM_HELP', '-20% [ICON_GOLD] Purchase cost for units and buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PATENT_LAW', 'Patent Law', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PATENT_LAW_HELP', '+1 [ICON_GOLD] Gold from Villages.[NEWLINE]+2 [ICON_GOLD] Gold from Harbors.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PATENT_LAW_TEXT', 'A patent is a set of exclusive rights granted by a state (national government) to an inventor or their assignee for a limited period of time in exchange for the public disclosure of an invention.[NEWLINE][NEWLINE]Patents in the modern sense originated in 1474, when the Republic of Venice enacted a decree that new and inventive devices, once put into practice, had to be communicated to the Republic to obtain the right to prevent others from using them.[NEWLINE][NEWLINE]England followed with the Statute of Monopolies in 1623 under King James I, which declared that patents could only be granted for "projects of new invention."  During the reign of Queen Anne (1702–14), the lawyers of the English Court developed the requirement that a written description of the invention must be submitted.  The patent system in many other countries is based on British law and can be traced back to the Statute of Monopolies.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MERCHANT_NAVY_HELP', '+1[ICON_MOVES] Moves and +1 Sight for military ships.[NEWLINE]+2 [ICON_RESEARCH] Science for Coastal Cities.[NEWLINE]+2 [ICON_RESEARCH] Science for Naval Buildings.', '', '');
/* Patronage */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Good for interacting with City-States.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]City-States resting influence is 20 [ICON_INFLUENCE].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+2 [ICON_HAPPINESS_1] National Happiness for each City-State friend, and +3 for each ally.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PHILANTHROPY_HELP', '+33% [ICON_INFLUENCE] Influence from [ICON_GOLD] Gold gifts to City-States.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_INFLUENCE] Influence with City-States degrades 33% slower than normal.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_AESTHETICS_HELP', '+20 instant [ICON_INFLUENCE] Influence with City-States.[NEWLINE]Other players'' [ICON_INFLUENCE] Influence with City-States decreases 25% faster.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SCHOLASTICISM_HELP', '+2 [ICON_RESEARCH] Science per era for each City-State friend, and +3 for each ally (split among your cities).', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TRADE_PACT', 'Trade Pact', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TRADE_PACT_HELP', '+2 [ICON_PRODUCTION] Production per era for each City-State friend, and +3 for each ally (split among your cities).', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Free trade is a system of trade policy that allows traders to trade across national boundaries without interference from the respective governments. Due to the economic principle of comparative advantage, this provides trading partners with mutual gains. Under this policy prices are the sole determinant of resource allocation, and a close reflection of supply and demand.', '', '');
/* Order */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_ORDER_HELP', 'Good for expanding and developing modern cities.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+10% [ICON_PRODUCTION] Production in all cities.[NEWLINE]+1 [ICON_TEAM_7] Great Engineer at the Capital.[NEWLINE]Can purchase Great Engineers with [ICON_PEACE] Faith.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]Gives 10 turns of [ICON_PRODUCTION] Production in all cities.[NEWLINE]+10% [ICON_PRODUCTION] Production from factories and power plants.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_PLANNED_ECONOMY_HELP', 'Construct Production buildings at double speed.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SOCIALISM_HELP', '-25% [ICON_GOLD] Maintenance cost for Buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_LABOR_UNIONS', 'Labor Unions', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_LABOR_UNIONS_HELP', '+1 [ICON_PRODUCTION] Production from Mines, Quarries, Lumbermills, and Fishing Boats.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_LABOR_UNIONS_TEXT', 'A labor union, or trade union, is an organization of workers who have banded together to achieve common goals such as protecting the integrity of its trade, achieving higher pay, increasing the number of employees an employer hires, and better working conditions.[NEWLINE][NEWLINE]Originating in Europe, labor unions became popular in many countries during the Industrial Revolution, when the lack of skill necessary to perform most jobs shifted employment bargaining power almost completely to the employers'' side, causing many workers to be mistreated and underpaid. The labor union, through its leadership, bargains with the employer on behalf of union members (rank and file members) and negotiates labor contracts (collective bargaining) with employers. The most common purpose of these associations or unions is "maintaining or improving the conditions of their employment". This may include the negotiation of wages, work rules, complaint procedures, rules governing hiring, firing and promotion of workers, benefits, workplace safety and policies.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_COMMUNISM_HELP', '+1 [ICON_HAPPINESS_1] City Happiness and +10% [ICON_RESEARCH] Science from Smithies and Factories.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_UNITED_FRONT_HELP', '+25% chance to catch spies.[NEWLINE]-25% enemy spy tech steal rate.[NEWLINE]+5 [ICON_PRODUCTION] Production from Espionage buildings.', '', '');
/* Knowledge */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Knowledge', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'KNOWLEDGE', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT_KEY_POLICY_BRANCH_RATIONALISM}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT_KEY_POLICY_BRANCH_RATIONALISM}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_RATIONALISM_TEXT', 'Knowledge is a familiarity with someone or something, which can include facts, information, descriptions, or skills acquired through experience or education. It can refer to the theoretical or practical understanding of a subject. It can be practical skill or expertise, or the theoretical understanding of a subject.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Piety increases the Happiness, Culture, and Faith of the adopting civ. Piety becomes available once the Classical Era is reached. This is an ideal place to acquire policies for players seeking to create or expand religions.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'What is the Knowledge social policy branch about?', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'The branch of Knowledge improves the civilization''s ability to use and generate Science, becoming available upon entering the Renaissance Era.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'The Knowledge branch of social policies is full of policies which can increase your research. This branch becomes available in the Renaissance era. See the rules on Social Policies for details.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'The Knowledge Branch', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Good for researching new things to build.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+1 [ICON_TEAM_7] Great Scientist at the Capital.[NEWLINE]+1 [ICON_RESEARCH] Science on Science buildings.[NEWLINE]Can purchase Great Scientists with [ICON_PEACE] Faith once you enter the Industrial era.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+2 instant [ICON_TEAM_5] Technologies.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '+15% [ICON_RESEARCH] Science from Public Schools.[NEWLINE]Constructs a Science building in your oldest 4 cities.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SOVEREIGNTY_HELP', '+15% [ICON_RESEARCH] Science when the nation is [ICON_HAPPINESS_1] Happy.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_HUMANISM_HELP', '+1 [ICON_HAPPINESS_1] City Happiness from Universities, Public Schools, and Research Labs.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FREE_THOUGHT_HELP', '+1 [ICON_RESEARCH] Science from Villages.[NEWLINE]+2 [ICON_RESEARCH] Science from Harbors.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_SECULARISM_HELP', '+2 [ICON_RESEARCH] Science from Specialists.', '', '');
/* Nationalism */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_AUTOCRACY', 'Nationalism', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_AUTOCRACY_CAP', 'NATIONALISM', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_CIV5_POLICY_AUTOCRACY_HEADING', '{TXT_KEY_POLICY_BRANCH_AUTOCRACY}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_TITLE', '{TXT_KEY_POLICY_BRANCH_AUTOCRACY}', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_AUTOCRACY_TEXT', 'Nationalism emphasizes the importance and uniqueness of the state. The state is the mother and father of the people, and the people love the state. Everybody has the national flag flying from their home, and everybody attends the founding day parade of military personnel and hardware. Nationalist states are often strong, as the people work tirelessly for the state''s advancement. However, internal criticism of the state may be stifled, which can limit the state''s ability to correct itself if goes off course.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_ADV_QUEST', 'What is the Nationalism social policy about?', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_BODY', 'This branch is well suited for those struggling to keep their empire happy. It is ideal for players who seek a Domination Victory. This policy unlocks upon entering the Renaissance Era, and cannot be active at the same time as Freedom.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_AUTOCRACY_HELP', 'Good for happiness and conquest.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+1 [ICON_HAPPINESS_1] City Happiness from Monuments.[NEWLINE]Can purchase Great Generals and Admirals with [ICON_PEACE] Faith.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+30 [ICON_WAR] Experience for units.[NEWLINE][NEWLINE][COLOR_WARNING_TEXT]Nationalism cannot be active with Freedom.[ENDCOLOR]', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_POLICE_STATE_HELP', '+2 [ICON_HAPPINESS_1] City Happiness from Espionage buildings.[NEWLINE]+100% [ICON_PRODUCTION] Production for building Espionage buildings.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_MILITARISM_HELP', '-25% [ICON_GOLD] Purchase and Maintenance costs for units.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_NATIONALISM_HELP', '+0.5 [ICON_HAPPINESS_1] City Happiness from each Specialist.[NEWLINE]+3 [ICON_HAPPINESS_1] City Happiness from Courthouses.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FASCISM_HELP', 'Your empire plunders [ICON_CULTURE] Cultural treasures from captured cities.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CONSCRIPTION', 'Conscription', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CONSCRIPTION_HELP', '+10 heal rate for units.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_CONSCRIPTION_TEXT', 'Conscription is the compulsory enlistment of people in some sort of national service, most often military service. Around the reign of Hammurabi (1791-1750 BC), the Babylonian Empire used a system of conscription called Ilkum. In medieval times, under the feudal conditions for holding land, most peasants and freemen were liable to provide one man of suitable age per family for military duty when required by either the king or the local lord. The levies raised in this way fought as infantry under local superiors. Although the exact laws varied greatly depending on the country and the period, generally these levies were only obliged to fight for one to three months. Most were subsistence farmers, and it was in everyone''s interest to send the men home for harvest-time. Under this system those eligible were required to serve in the royal army in time of war. During times of peace they were instead required to provide labour for other activities of the state. In return for this service, people subject to it gained the right to hold land.[NEWLINE][NEWLINE]The modern system of near-universal national conscription for young men dates to the French Revolution in the 1790s, where it became the basis of a very large and powerful military. Most European nations later copied the system in peacetime, so that men at a certain age would serve 1–3 years on active duty and then transfer to the reserve force. ', '', '');
/* Freedom */
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_BODY', 'Freedom provides bonuses for large cities. Freedom becomes available upon entering the Renaissance Era, and cannot be active at the same time as Nationalism.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_BRANCH_FREEDOM_HELP', 'Good for peaceful empires with high population.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE]+25% [ICON_STRENGTH] Combat Strength for cities and units in friendly territory.[NEWLINE]Can purchase Great Artists with [ICON_PEACE] Faith.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]Double effects from National Wonders.[NEWLINE]+1 [ICON_CITIZEN] Population in your cities.[NEWLINE][NEWLINE][COLOR_WARNING_TEXT]Freedom cannot be active with Nationalism.[ENDCOLOR]', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FREE_TRADE', 'Free Trade', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FREE_TRADE_HELP', '+100%[ICON_GOLD] Gold from Mutual Open Borders.[NEWLINE]+50% [ICON_RESEARCH] Science from Research Agreements.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FREE_TRADE_TEXT', '(todo)', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_UNIVERSAL_SUFFRAGE_HELP', '+1 [ICON_FOOD] Food from Farms.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_FREE_SPEECH_HELP', '+1 [ICON_CULTURE] Culture from Villages and Moai Statues.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_DEMOCRACY_HELP', '-1 [ICON_FOOD] Food consumed per Specialist.[NEWLINE]+100% [ICON_GREAT_PEOPLE] Great Person creation rate.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_IMMIGRATION', 'Immigration', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_IMMIGRATION_HELP', 'City-State friends and allies gift [ICON_GREAT_PEOPLE] Great People.', '', '');
INSERT INTO CEP_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-20'), 'TXT_KEY_POLICY_IMMIGRATION_TEXT', 'Immigration is the movement of people into a country or region to which they are not native in order to settle there. Immigration is made for many reasons, including temperature, breeding, economic, political, family re-unification, natural disaster, poverty or the wish to change one''s surroundings voluntarily.[NEWLINE][NEWLINE]The reasons may be social environment (in source countries: lack of opportunities, political instability, economic depression, health risks, etc.; in host countries: rich opportunities, political stability and freedom, developed economy, better living conditions, etc.). In terms of individual reasons, there are family influence (overseas relatives), and personal preference: preference for exploring, ambition for an improved career, etc.[NEWLINE][NEWLINE]One specific type of immigration may be termed ''brain-drain''. This term was coined by the Royal Society to describe the emigration of "scientists and technologists" to North America from post-war Europe.', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='Policies.sql';
