/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LEGENDS', 'Legends', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LEGENDS_HELP', ' +15% [COLOR_POSITIVE_TEXT]Melee Strength[ENDCOLOR].', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Conscripts', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' [COLOR_POSITIVE_TEXT]Units heal 10 HP per turn[ENDCOLOR].', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_POWER', 'Naval Power', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_POWER_HELP', ' +15% [COLOR_POSITIVE_TEXT]Naval Surface Strength[ENDCOLOR].', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Mercantilism', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' +2 [ICON_MOVES] Movement.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Freedom', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' +25% [ICON_STRENGTH] Strength in friendly territory.', '', '');
/* Liberty */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_CULTURE] Culture: +1 in all cities[NEWLINE][ICON_PRODUCTION] Production: +1 in all cities[NEWLINE][ICON_WORKER] Unlocks: Terracotta Army[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE][ICON_TEAM_7] Great Person: +1 of choice', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Settler: +1[NEWLINE][ICON_PRODUCTION] Production: +25% for Settlers', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Gold: +200 x Era[NEWLINE][ICON_CULTURE] New cities increase Policy costs 33% less.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Workers: +1[NEWLINE][ICON_WORKER] Worker Improvement Rate: +25%', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 National Happiness per [ICON_CONNECTED] connected city.[NEWLINE][ICON_HAPPINESS_4] -5% Unhappiness from [ICON_CITIZEN] Population in cities that are not [ICON_OCCUPIED] Occupied.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] Free City Defense building in all cities (current, new, and conquered). With the appropriate tech researched.[NEWLINE][ICON_PRODUCTION] +10% Production for constructing buildings.[NEWLINE][ICON_HAPPINESS_1]+4 National Happiness', '', '');
/* Tradition */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_CULTURE] Culture: +3 in Capital[NEWLINE][ICON_FOOD] Food: +2 in Capital[NEWLINE][ICON_WORKER] Unlocks: Banaue Rice Terraces[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE][ICON_GREAT_PEOPLE] Great Person Rate: +25%[NEWLINE][ICON_CULTURE] Doubles cultural border expansion to tiles far from cities.[NEWLINE][ICON_PEACE] Can purchase Great Engineers with Faith starting in the Industrial era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Surplus Food: +15% per city[NEWLINE][ICON_FOOD] Food: +2 per city[NEWLINE][ICON_FOOD] Food: +1 per 5 population in the capital', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] City Attack: +50% from garrisons[NEWLINE][ICON_GOLD] No maintenance for garrisoned units.[NEWLINE][ICON_CULTURE] Culture: +2 for garrisoned units.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Production: +15% for Wonders[NEWLINE][ICON_HAPPINESS_1] Happiness: +1 per 10 [ICON_CITIZEN] Citizens', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Citizens in the Capital create +1 [ICON_GOLD] Gold and +0.5 [ICON_HAPPINESS_1] Happiness.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MENTORS', 'Mentors', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MENTORS_HELP', '+5 [ICON_RESEARCH] Science per turn.[NEWLINE]+5% [ICON_RESEARCH] Science from Science Buildings.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MENTORS_TEXT', 'Mentoring is an organized process for the transmission of knowledge, social capital, and the psychosocial support perceived by the recipient as relevant to work, career, or professional development. Mentoring entails informal communication, usually face-to-face and during a sustained period of time, between a person who is perceived to have greater relevant knowledge, wisdom, or experience (the mentor) and a person who is perceived to have less (the protégé).', '', '');
/* Honor */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_VIEW_CITY] Reveals barbarian camps.[NEWLINE][ICON_STRENGTH] +10% Strength against barbarians.[NEWLINE][ICON_CULTURE] Killing barbarians gives 2 Culture per strength of defeated enemies.[NEWLINE][ICON_WORKER] Unlocks: Temple of Artemis[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE] +15% Strength for Melee Units. [NEWLINE] +25% Great General Rate', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' +2 [ICON_TEAM_2] Defense Units at the Capital.[NEWLINE]+20% [ICON_PRODUCTION] Production for military units and buildings.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Spoils of War', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Salvage gold from the equipment of defeated enemies (3 times the unit strength).[NEWLINE][ICON_CITY_STATE] +25% rewards from capturing City-States.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Looting by a victorious army during war has been common practice throughout recorded history. For foot soldiers, it was viewed as a way to supplement their often meagre income and was part of the celebration of victory. On higher levels, the proud exhibition of loot was an integral part of the typical Roman triumph, and Genghis Khan was not unusual in proclaiming that the greatest happiness was "to vanquish your enemies... to rob them of their wealth..."[NEWLINE][NEWLINE]In warfare in ancient times, the spoils of war included the defeated populations, which were often enslaved, and the women and children, who were often absorbed into the victorious country''s population. In other pre-modern societies, objects made of precious metals were the preferred target of war looting, largely because of their easy portability. In many cases looting was an opportunity to obtain treasures that otherwise would not have been obtainable. Since the 18th century, works of art have increasingly become a popular target. In the 1930s and even more so during World War II, Nazi Germany engaged in large scale and organized looting of art and property.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiators', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] City Happiness: Free Arena in every city.[NEWLINE][ICON_TEAM_2] +2 Defense Units at the Capital.[NEWLINE][ICON_GOLD] 2 military units cost no maintenance.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_PRODUCTION] Production: + on XP buildings [NEWLINE][ICON_PRODUCTION] Production: 50% cost for XP Buildings. [NEWLINE] +25% faster promotions', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Great General: +1[NEWLINE][ICON_MOVES] Movement: +1 for Great Generals.[NEWLINE][ICON_STRENGTH] +15% Strength for all Units adjacent to other friendly military units.[NEWLINE] Bonus to Citadel', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% when [COLOR_POSITIVE_TEXT]adjacent[ENDCOLOR] to friendly military units.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] Upgrade cost: -50% for units[NEWLINE][ICON_PRODUCTION] Production: +15% for All units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT]Warrior Code[ENDCOLOR][NEWLINE]', '', '');
/* Piety */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_PEACE] Faith +2[NEWLINE][ICON_PEACE] Constructs Shrines and Temples faster.[NEWLINE][ICON_WORKER] Unlocks: Stonehenge[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]Choose one new Pious belief.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Charity', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Gold: +25% from Temples[NEWLINE][ICON_GOLD] Gold: +2 from Temples[NEWLINE][ICON_GOLD] Gold: +3 Holy Sites.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'The word "charity" comes from the Old French word "charité" which, in turn, was derived from the Latin "caritas".[NEWLINE][NEWLINE]The practice of charity means the voluntary giving of help to those in need who are not related to the giver, though the original meaning is more involved with the concepts of preciousness, dearness, high price. Charitable giving is done directly or by means of a charitable trust or other worthy cause. These institutions evolved to carry out the labor of assisting the poor, and came to be called, called ''charities''. In modern times ''charities'' provide the bulk of charitable giving, in terms of monetary value. The types of charities include orphanages, food banks, religious institutes dedicated to care of the poor, hospitals, organizations that visit the homebound and imprisoned, and many others.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Inspiration', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Free Great Prophet: +1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'The word "inspiration" comes from the Latin noun inspiratio and from the verb inspirare. Inspirare is a compound term resulting from the Latin prefix in (inside, into) and the verb spirare (to breathe).[NEWLINE][NEWLINE]In classic Roman times, inspirare had already come to mean "to breathe deeply" and assumed also the figurative sense of "to instill [something] in the heart or in the mind of someone".[NEWLINE][NEWLINE]Hence ''inspiration'' refers to an unconscious burst of creativity in a literary, musical, or other artistic endeavour. The concept has origins in both Hellenism and Hebraism. The Greeks believed that inspiration came from the muses, as well as the gods Apollo and Dionysus. Similarly, in the Ancient Norse religions, inspiration derives from the gods, such as Odin. Inspiration is also a divine matter in Hebrew poetics. In the Book of Amosthe prophet speaks of being overwhelmed by God''s voice and compelled to speak. In Christianity, inspiration is a gift of the Holy Spirit.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Tolerance', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] City Happiness: +1 per Religious Building[NEWLINE][ICON_PEACE] Cities with multiple religions also get the Pantheon bonus of the city''s second most popular religion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Tolerance or toleration is "the practice of deliberately allowing or permitting a thing of which one disapproves. One can meaningfully speak of tolerating, ie of allowing or permitting, only if one is in a position to disallow”. It has also been defined as "to bear or endure" or "to nourish, sustain or preserve". Toleration may signify “no more than forbearance and the permission given by the adherents of a dominant religion for other religions to exist, even though the latter are looked on with disapproval as inferior, mistaken or harmful”[NEWLINE][NEWLINE]Tolerance is an attitude of mind that implies non-judgmental acceptance of different lifestyles or beliefs, whereas toleration implies putting up with something that one disapproves of.[NEWLINE][NEWLINE]Historic examples of ''tolerance'' abound. For instance in an act of tolerance, the Persian king Cyrus the Great was believed to have released the Jews from captivity in 539–530 BC, and permitted their return to their homeland.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Unity', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Golden Age Turns: 10[NEWLINE][ICON_GOLDEN_AGE] Golden Ages require 50% less [ICON_HAPPINESS_1] National Happiness', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Unity refers to the ties in a society that bind people to one another. The term is generally employed in sociology and the other social sciences.[NEWLINE][NEWLINE]In simple societies it may be mainly based around kinship and shared values. In more complex societies there are various theories as to what contributes to a sense of social solidarity.[NEWLINE][NEWLINE]This brings in the associated term of ''solidarity'' of which it is said:[NEWLINE]"Solidarity does not assume that our struggles are the same struggles, or that our pain is the same pain, or that our hope is for the same future. Solidarity involves commitment, and work, as well as the recognition that even if we do not have the same feelings, or the same lives, or the same bodies, we do live on common ground." - Sara Ahmed', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Meditation', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Faith: +1 Shrines, Temples[NEWLINE][ICON_PEACE] Faith Costs: -25%', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Devotion', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'Devotion may be defined as: ardent, often selfless affection and dedication, as to a person or principle. Worship, from the Old English worthscipe, meaning worthiness or worth-ship is an act of religious devotion usually directed towards a deity. Closely allied to the concept of love, devotion is often hoped to be reciprocated with some form of boon or blessing.[NEWLINE][NEWLINE]Devotees, as those who practice devotion are called wanting to receive these blessings, are often single-minded to the point of fanaticism. Thus whilst the concept of ''devotion'' is benign, many historical examples of religious devotion are often extreme and bloody, as devotees vie for the affection of the devoted with more outrageous displays.', '', '');
/* Wealth */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Wealth', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'WEALTH', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT_KEY_POLICY_BRANCH_COMMERCE}', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT_KEY_POLICY_BRANCH_COMMERCE}', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'Wealth is the abundance of valuable resources or material possessions. The concept of wealth is significant in all areas of economics, yet the meaning of wealth is context-dependent and there is no universally agreed upon definition. At the most general level wealth is &quot;anything of value&quot;, which captures both the subjective nature of the word, and the idea that it is not a fixed or static concept.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'What is the Wealth social policy branch about?', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'The branch of Wealth focuses on developing wide territory, with a national supply of [ICON_GOLD] Gold created by core cities to purchase new units and buildings in undeveloped frontier cities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'The branch of Wealth focuses on developing wide territory, with a national supply of [ICON_GOLD] Gold created by core cities to purchase new units and buildings in undeveloped frontier cities. See the rules on Social Policies for details.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'The Wealth Branch', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_GOLD] Gold: +15% {TXT_KEY_IN_ALL_CITIES}[NEWLINE][ICON_WORKER] Unlocks: Panama Canal[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE][ICON_HAPPINESS_1] Happiness: +1 National Happiness per Luxury Resource[NEWLINE][ICON_PEACE] Can purchase Great Merchants with Faith upon entering the Industrial era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[NEWLINE]+25% [ICON_GOLD] Income from [ICON_CONNECTED] Domestic Trade.[NEWLINE][ICON_GOLD] Gold: +2 on Gold buildings.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '-20% [ICON_GOLD] Purchase cost for units and buildings.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Can purchase Landsknechts.[NEWLINE][ICON_TEAM_2] 2 Landsknechts appear at the Capital.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Free Great Merchant: +1[NEWLINE][ICON_GREAT_PEOPLE] Great Merchant Rate: +25%[NEWLINE][ICON_GREAT_MERCHANT] Double Gold from Great Merchant trade missions. [NEWLINE]+3 [ICON_GOLD] on Customs Houses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Caravans', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Gold: +3 per Trade Route. [NEWLINE]-50% [ICON_GOLD] Cost for roads and railroads.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Production: +4 per Coastal City[NEWLINE][ICON_GOLD] Gold: +4 per Lighthouse, Harbor, Seaport', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Guilds', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', '[ICON_GOLD] Gold: +1 on Villages. [NEWLINE][ICON_GOLD] Gold: +1 on Plantations.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'A guild is an association of craftsmen in a particular trade. The earliest types of guild were formed as confraternities of workers. They were organized in a manner something between a trade union, a cartel, and a secret society. They often depended on grants of letters patent by a monarch or other authority to enforce the flow of trade to their self-employed members, and to retain ownership of tools and the supply of materials.', '', '');
/* Patronage */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_GOLD] +2 Gold per City-State Trade Route.[NEWLINE][ICON_WORKER] Unlocks: Angkor Wat[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE][ICON_PLUS] +100% strategic resource quantity and +50% [ICON_HAPPINESS_1] National Happiness from luxury resources gifted by City-State allies.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] +20 instant Influence with City-States.[NEWLINE][ICON_INFLUENCE] +33% Influence from [ICON_GOLD] Gold gifts to City-States.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Special Relationship', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Influence with City-States degrades 33% slower than normal.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] +20 resting influence with City-States.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] +2 Science per era for each City-State friend, and +3 for each ally.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] City-State allies gift Great People. [ICON_GREAT_PEOPLE] +10% Great People Rate.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Trade Pact', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' +2 [ICON_PRODUCTION] Production per era for each City-State friend, and +3 for each ally (split among your cities).', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Free trade is a system of trade policy that allows traders to trade across national boundaries without interference from the respective governments. Due to the economic principle of comparative advantage, this provides trading partners with mutual gains. Under this policy prices are the sole determinant of resource allocation, and a close reflection of supply and demand.', '', '');
/* Aesthetics */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_PRODUCTION] +50% Production for Cultural buildings.[NEWLINE][ICON_WORKER] Unlocks: Uffizi[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]Reveals Hidden Antiquity sites.[NEWLINE][ICON_TEAM_7] Allows the purchase of Cultural Great People with [ICON_PEACE] Faith upon entering the Industrial Era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Culture: +1 per surplus happiness.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Culture: +2 per National Wonder[NEWLINE][ICON_CULTURE] Culture: +33% in cities with a World Wonder', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Great Artist: 1[NEWLINE][ICON_TEAM_7] Cultural Great Person rate: +25%', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', '[ICON_CULTURE] +1 Culture from Villages.[NEWLINE][ICON_PRODUCTION] +100% Production for Archaeologists.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Doubles building-theme tourism.[NEWLINE][ICON_TOURISM] +25% tourism from shared religion, open borders, and trade routes.', '', '');
/* Exploration */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_MOVES] Moves: +2 for Embarked Units[NEWLINE][ICON_MOVES] Moves: +2 for Great Admirals[NEWLINE][ICON_MOVES] +1 Move[ICON_SIGHT_SEA] and Sight: +1 for Military Ships[NEWLINE][ICON_WORKER] Unlocks: Red Fort[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+[ICON_STRENGTH] +15% for surface ships [NEWLINE][ICON_PRODUCTION] +15% production for surface ships.[NEWLINE][ICON_TEAM_7] Allows the purchase of Great Admirals with faith upon entering the Industrial Era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] City Happiness: +1 per Lighthouse, Harbor, Seaport', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Colonization', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Cities start with 3 population.[NEWLINE][ICON_TEAM_2] 2 Settlers, 2 Workers, and 2 Defense Units appear at the Capital.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Pioneer Spirit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 movement for civilians.[NEWLINE][ICON_FOOD]+1 on Lighthouses and Harbors. [NEWLINE][ICON_PRODUCTION] +100% production for building harbors.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Homestead Act', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Cities can build several tier 1 buildings twice as fast. [NEWLINE] [ICON_GOLD]+1 yields on Granaries, Smiths, Caravansary, and Stables', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(todo)', '', '');
/* Knowledge */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Knowledge', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'KNOWLEDGE', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT_KEY_POLICY_BRANCH_RATIONALISM}', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT_KEY_POLICY_BRANCH_RATIONALISM}', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'Knowledge is a familiarity with someone or something, which can include facts, information, descriptions, or skills acquired through experience or education. It can refer to the theoretical or practical understanding of a subject. It can be practical skill or expertise, or the theoretical understanding of a subject.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Piety increases the Happiness, Culture, and Faith of the adopting civ. Piety becomes available once the Classical Era is reached. This is an ideal place to acquire policies for players seeking to create or expand religions.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'What is the Knowledge social policy branch about?', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'The branch of Knowledge improves the civilization''s ability to use and generate Science, becoming available upon entering the Renaissance Era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'The Knowledge branch of social policies is full of policies which can increase your research. This branch becomes available in the Renaissance era. See the rules on Social Policies for details.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'The Knowledge Branch', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Abilities:[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Opener[ENDCOLOR][NEWLINE][ICON_TEAM_7] Great Scientist: +1[NEWLINE][ICON_RESEARCH]+4 on National Wonders.[NEWLINE][ICON_WORKER] Unlocks: Bell Labs[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Finisher[ENDCOLOR] [COLOR_GREY](finish all policies in this tree)[ENDCOLOR][NEWLINE]+1 instant [ICON_TEAM_5] Technologies.[NEWLINE][ICON_PEACE] Can purchase Great Scientists with [ICON_PEACE] Faith once you enter the Industrial era.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[ICON_RESEARCH] +50% Research Agreement rewards. [NEWLINE][ICON_RESEARCH]+3 on Academies. [NEWLINE][ICON_RESEARCH]+25% Great Scientist Rate. [NEWLINE][ICON_TEAM_7] Great Engineer: +1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Science: +10% while nation is [ICON_HAPPINESS_1] happy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Science: +1 per Village[NEWLINE][ICON_RESEARCH] Science: +15% per University', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Science: +2 per Specialist', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SOVEREIGNTY_HELP', '[ICON_HAPPINESS_1] Happiness: +1 per National Wonder.', '', '');

REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OPEN_SOCIETY_HELP', '[COLOR_POSITIVE_TEXT]Avant Garde[ENDCOLOR][NEWLINE]The rate at which [ICON_GREAT_PEOPLE] Great People are born is increased by 75%.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TREATY_ORGANIZATION_HELP', '[COLOR_POSITIVE_TEXT]Treaty Organization[ENDCOLOR][NEWLINE]Gain 4 more [ICON_INFLUENCE] Influence per turn (at Standard speed) with City-States you have a trade route with.[NEWLINE][ICON_GOLD] +5 Gold from all your trade routes with other civilizations following the Freedom Ideology.[NEWLINE] ', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ECONOMIC_UNION_HELP', '[COLOR_POSITIVE_TEXT]Economic Union[ENDCOLOR][NEWLINE][ICON_GOLD]+10% Gold from Stock Exchanges, Airports, and Hotels.[ICON_FOOD]+1 Food from Farms and Pastures.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NEW_DEAL_HELP', '[COLOR_POSITIVE_TEXT]New Deal[ENDCOLOR][NEWLINE]Landmarks, Academies, and Customs Houses improvements produce +6 of the appropriate yield.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HERO_OF_THE_PEOPLE_HELP', '[COLOR_POSITIVE_TEXT]Hero of the People[ENDCOLOR][NEWLINE]The rate at which [ICON_GREAT_PEOPLE] Great People are born is increased by 25%.[ICON_GREAT_PEOPLE] Free Great Person of your choice.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DOUBLE_AGENTS_HELP', '[COLOR_POSITIVE_TEXT]Double Agents[ENDCOLOR][NEWLINE]Spies twice as likely to capture enemy spies attempting to steal a technology. Construct Constables and Police faster', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PARTY_LEADERSHIP_HELP', '[COLOR_POSITIVE_TEXT]Party Leadership[ENDCOLOR][NEWLINE][ICON_PRODUCTION] Production: +15% in all cities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RESETTLEMENT_HELP', '[COLOR_POSITIVE_TEXT]Resettlement[ENDCOLOR][NEWLINE]+1 [ICON_FOOD] Food, [ICON_PRODUCTION] Production, [ICON_RESEARCH] Science, [ICON_GOLD] Gold, and [ICON_CULTURE] Culture per city.[NEWLINE][ICON_GOLD] Maintenance: -20% for Buildings', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WORKERS_FACULTIES_HELP', '[COLOR_POSITIVE_TEXT]Workers'' Faculties[ENDCOLOR][NEWLINE]Factories increase a City''s [ICON_RESEARCH] Science output by 25%. Build Factories and Power Plants in half the usual time.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FIVE_YEAR_PLAN_HELP', '[COLOR_POSITIVE_TEXT]Five-Year Plan[ENDCOLOR][NEWLINE]+2 [ICON_PRODUCTION] Production per City and +1 [ICON_PRODUCTION] Production for every Mine, Quarry, Well, and Mill.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CREATIVE_EXPRESSION_HELP', '[COLOR_POSITIVE_TEXT]Creative Expression[ENDCOLOR][NEWLINE]+1 [ICON_CULTURE] Culture from each Great Work (but [ICON_TOURISM] Tourism is unchanged).[ICON_GOLD]+4 Gold from Broadcast Towers and Guilds.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_URBANIZATION_HELP', '[COLOR_POSITIVE_TEXT]Urbanization[ENDCOLOR][NEWLINE]+1 [ICON_HAPPINESS_1] Local Happiness from every Aqueduct, Hospital, and Medical Lab.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ELITE_FORCES_HELP', '[COLOR_POSITIVE_TEXT]Elite Forces[ENDCOLOR][NEWLINE]Wounded Military Units inflict 25% more damage than normal. Units heal 10 HP every turn. Aircraft receive +15XP.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INDUSTRIAL_ESPIONAGE_HELP', '[COLOR_POSITIVE_TEXT]Industrial Espionage[ENDCOLOR][NEWLINE]Spies steal technologies at twice the normal rate. +1 [ICON_HAPPINESS_1] Local Happiness from every Constable and Police Station.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_O_HELP', '[COLOR_POSITIVE_TEXT]Public Infrastructure[ENDCOLOR][NEWLINE][ICON_PRODUCTION] Iron Works Production: +4 and +25%. +6 to Manufactories. +1 [ICON_HAPPINESS_1] Local Happiness from every Hospital and Med Lab.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_A_HELP', '[COLOR_POSITIVE_TEXT]Party Machine[ENDCOLOR][NEWLINE]Increases the effects of the National Epic, Heroic Epic, and Circus Maximus National Wonders.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_F_HELP', '[COLOR_POSITIVE_TEXT]Endowment of Sciences[ENDCOLOR][NEWLINE]Significantly increases the effects of the East India, National College, Heidelberg, and Hermitage National Wonders.', '', '');









UPDATE LoadedFile SET Value=1, en_US=1 Where Type='Policies.sql';



