--· EN_US/Research.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRAINING', 'Training', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRAINING_PEDIA', 'Military training is a process which establishes and improve the capabilities of military personnel. Military education can be voluntary or compulsory duty.[NEWLINE]Recruit training attempts to teach the basic information and training in techniques necessary to be an effective service member. To achieve this, service members are drilled physically, technically and psychologically.[NEWLINE]After finishing basic training, many service members undergo advanced training more in line with their chosen or assigned specialties. In advanced training, military technology and equipment is often taught.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRAINING_QUOTE', '[NEWLINE][TAB][TAB]"Conscription if necessary, but not necessarily conscription."[NEWLINE][TAB][TAB] - William Lyon Mackenzie King [NEWLINE]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_POLITICAL_SCIENCE', 'Political Science', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_POLITICAL_SCIENCE_PEDIA', 'During the Italian Renaissance, Niccolò Machiavelli established the emphasis of modern political science on direct empirical observation of political institutions and actors.[NEWLINE][NEWLINE]Later European philosophers like Voltaire, Rousseau, Thomas Hobbes and John Locke applied principles from the material sciences to society as a whole, creating the social sciences. These paved the way for policies that emphasized a social contract between government and governed, a need for a separation of church and state, and the gradual diminishing of the divine right of kings.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_POLITICAL_SCIENCE_QUOTE', '[NEWLINE][TAB][TAB]"Politics have no relation to morals."[NEWLINE][TAB][TAB] - Niccolo Machiavelli[NEWLINE][TAB]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRADE_TITLE', 'Trade', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRADE_DESC', 'Trade originated with the start of communication in prehistoric times. It spurred common curiosity, ingenuity, and the learning of languages. As such, trade and the specialization that it engendered has been credited with accelerating the growth of human consciousness and humans'' triumph over the Neanderthal species.[NEWLINE][NEWLINE]There is evidence of the exchange of obsidian and flint during the Stone Age. Egypt traded for materials used for creating jewelry since 3000 BCE. Long-range trade routes first appeared when the Sumerians in Mesopotamia traded with the Harappan civilization of the Indus Valley. The Phoenicians - noted sea traders - traveled across the Mediterranean Sea, and as far north as Britain for sources of tin to manufacture bronze. They established trade colonies the Greeks called emporia.[NEWLINE][NEWLINE]Trade continued to drive the human tendency to explore long after the demise of the ancient Mediterranean maritime empires. Long-distance trade spread even farther with the Zheng He''s huge fleet, which reached India, Arabia and East Africa before Columbus crossed the ocean.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE][TAB][TAB]"No reason exists today to discount either the presence or potential impact of economics in the pre-historic dawning of humanity."[NEWLINE][TAB][TAB] - Jason Shogren[NEWLINE][TAB]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE][NEWLINE]Neither player yet has the Technology to trade this item (Trade).', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_CARVEL_HULLS', 'Carvel Hulls', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'Carvel ship design was one of the critical developments that enabled the dominance of Western European naval powers from 1400 to the present. The wooden planks in carvel hulls line up against each other, edge to edge, instead of the overlapping plank design of clinker hulls. This stronger hull design supports much larger ships and sails.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE][TAB][TAB]"A ship is safe in harbor, but that''s not what ships are for."[NEWLINE][TAB][TAB] - William Shedd[NEWLINE]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Mass Media', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_MEDIA_DESC', 'The term "mass media" was coined in the 1920''s with the advent of the radio, but the idea of media for large audience consumption has been around since the dramas and plays of the Ancient World. Mass media has been directly driven by technology, with greater advances in publishing techniques and communications leading to even larger possible audiences being reached.[NEWLINE][NEWLINE]Originally just applied to communication devices like radio, newspapers, and magazines, mass media now encompasses television, movies, music, paperback books, video games, and the Internet.  With the advent of these globe-spanning media types has also arisen the ability to reach the masses like never before, and not always in a good way. The attempt to bias or control large amounts of information, either through nefariously minded propaganda or more innocent personal opinions being injected into facts, is becoming a large problem for some governments and organizations to deal with.  Invasive advertising techniques are also a byproduct of mass media, much to the annoyance of consumers everywhere.  While the message may be worthwhile and it''s increasingly easier for the common person to publish their ideas and artworks, getting heard in the torrential output of information now available can really be like searching for that proverbial needle in the haystack.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE][TAB][TAB]"The speed of communications is wondrous to behold. It is also true that speed can multiply the distribution of information that we know to be untrue."[NEWLINE][TAB][TAB]  - Edward R. Murrow[NEWLINE][TAB][TAB][TAB]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Mass Production', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'Modern mass production is the construction of large amounts of standardized products on assembly lines. Important ingredients for mass production are industrial machine tools, interchangeable parts, scientific management, and electric power.[NEWLINE][NEWLINE]Mass production was popularized in the 1910s and 1920s by Henry Ford''s Ford Motor Company, which introduced electric motors to the well-known technique of chain or sequential production. Ford also bought or designed and built special purpose machine tools and fixtures. All of these machine tools were arranged systematically in the production flow.  Ford management performed time studies and experiments to mechanize their factory processes, focusing on minimizing worker movements.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE][TAB][TAB]"There is one rule for the industrialist and that is: Make the best quality of goods possible at the lowest cost possible, paying the highest wages possible."[NEWLINE][TAB][TAB] - Henry Ford[NEWLINE][TAB]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Ion Propulsion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_ION_PROPULSION_DESC', 'The propulsion of choice for science fiction writers has become the propulsion of choice for scientists and engineers at NASA. The ion propulsion system''s efficient use of fuel and electrical power enable modern spacecraft to travel farther, faster, and cheaper than any other propulsion technology currently available. Ion thrusters are currently used for stationkeeping on communication satellites and for main propulsion on deep space probes. Ion thrusters expel ions to create thrust and can provide higher spacecraft top speeds than any other rocket currently available.[NEWLINE]An ion is simply an atom or molecule that is electrically charged. In an ion thruster, ions are accelerated by electrostatic forces. The electric fields used for acceleration are generated by electrodes positioned at the downstream end of the thruster.[NEWLINE]Modern ion thrusters use inert gases for propellant. The majority of thrusters use xenon, which is chemically inert, colorless, odorless, and tasteless. The propellant is injected from the downstream end of the thruster and flows toward the upstream end.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE][TAB][TAB]"All civilizations become either spacefaring or extinct."[NEWLINE][TAB][TAB] - Carl Sagan[NEWLINE][TAB]', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='Research.sql';
