/* The sql commands and text below were formulated in the Stories tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1563932649
If you make any changes be sure to update the spreadsheet also.*/

/* Terrain */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING', 'River Flooding', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_DESC', 'Frequent seasonal floods of this river provide unusually fertile topsoil for farming.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_1', 'Pay for new irrigation canals along the river.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_2', 'Research better ways to protect homes from floods.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_3', 'Let the locals handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_1', '[ICON_TEAM_3] New river irrigation improved [ICON_FOOD] Food for {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_2', '[ICON_TEAM_3] New [ICON_RESEARCH] Research is underway to protect citizens of {1_player} from floods.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_3', '[ICON_TEAM_3] New river irrigation improved [ICON_GOLD] Economic income for {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE', 'Desert Adobe', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_DESC', 'An unusually sturdy and beautiful form of clay adobe construction was developed outside {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_1', 'Use the distinctive style to enhance our cultural monuments.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_2', 'Use the brick for practical construction.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_3', 'Let the locals handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_1', '[ICON_TEAM_3] A new style of adobe bricks enhanced the [ICON_CULTURE] Culture of {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_2', '[ICON_TEAM_3] Innovations in adobe construction improved [ICON_PRODUCTION] Production near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_3', '[ICON_TEAM_3] A new form of adobe construction improved the [ICON_GOLD] Economy near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS', 'Snow Sleds', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_DESC', 'Innovations in alpine travel made terrain near {2_city} more accessible.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_1', 'Use the sleds for recreational races.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_2', 'Use the sleds to exploit new resources.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_3', 'Let the locals handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_1', '[ICON_TEAM_3] Innovations in snow sleds prompted new races near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_2', '[ICON_TEAM_3] Innovations in snow sleds opened up new resources near {2_city} to exploitation.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_3', '[ICON_TEAM_3] Innovations in snow sleds improved the [ICON_GOLD] Economy near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE', 'Mountain Refuge', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_DESC', 'A scenic mountaintop near {2_city} is unusually suitable for human habitation.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_1', 'Build a spiritual sanctuary for rest and meditation.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_2', 'Build a scholarly retreat to study the stars and seasons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_3', 'Let the locals handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_1', '[ICON_TEAM_3] A mountaintop spiritual refuge increased [ICON_CULTURE] Culture near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_2', '[ICON_TEAM_3] A mountaintop scholarly retreat increased [ICON_RESEARCH] Science near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_3', '[ICON_TEAM_3] Merchants are selling goods to visitors of a mountaintop near {2_city}.', '', '');
/* IMPROVEMENTS */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING', 'Commercial Farming', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_DESC', 'Wealthy individuals plan to buy and commercialize small farms near {2_city}, unless local farmers can increase their revenues.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_1', 'Invest in a culture of traditional farming.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_2', 'Support the mergers with treasury incentives.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_3', 'Allow the purchases without interference.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_1', '[ICON_TEAM_3] Traditional farmers are a strong part of the [ICON_CULTURE] Culture near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_2', '[ICON_TEAM_3] Commercialization improved farm [ICON_FOOD] Food near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_3', '[ICON_TEAM_3] Buyouts improved farm [ICON_GOLD] Gold near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION', 'Mine Expansion', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_DESC', 'Mine operators near {2_city} discovered valuable ore, but workers are protesting hazardous conditions in the new branch shafts.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_1', 'Give national support to improve mine safety.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_2', 'Use treasury funds to hire strike breakers.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_3', 'Let the mine operator handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_1', '[ICON_TEAM_3] Miners near {2_city} are [ICON_HAPPINESS_1] Happy about safer working conditions.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_2', '[ICON_TEAM_3] Swiftly ending a strike of {2_city}''s mine expanded [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_3', '[ICON_TEAM_3] A mine near {2_city} discovered a [ICON_GOLD] Profitable new ore vein.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS', 'Village Protests', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_DESC', 'Citizens in a village near {2_city} are struggling under high poverty and crime.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_1', 'Improve education for the poor to qualify for better work.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_2', 'Improve the police force to lower crime rates.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_3', 'Let the village mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_1', '[ICON_TEAM_3] A village near {2_city} improved [ICON_RESEARCH] Education for the poor.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_2', '[ICON_TEAM_3] Villagers near {2_city} are [ICON_HAPPINESS_1] Happy about lower crime rates.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_3', '[ICON_TEAM_3] A stronger police presence improved the [ICON_GOLD] Economy of a village near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND', 'Plantation Demand', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_DESC', 'Demand is rising for the crops of a plantation near {2_city}, where workers harvest the fields for low pay.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_1', 'Enact laws to improve pay and conditions for workers.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_2', 'Lower trade barriers to strengthen the export economy.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_3', 'Let the plantation owners handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_1', '[ICON_TEAM_3] Plantation pickers near {2_city} are [ICON_HAPPINESS_1] Happy about better work conditions.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_2', '[ICON_TEAM_3] Lower trade barriers improved plantation [ICON_FOOD] Food near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_3', '[ICON_TEAM_3] Rising demand improved plantation [ICON_GOLD] Income near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS', 'Exotic Camp Animals', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_DESC', 'Exotic animals were discovered outside the camp near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_1', 'Create an animal preserve to improve tourism.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_2', 'Build an extravagant hunting lodge.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_3', 'Let the locals handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_1', '[ICON_TEAM_3] An exotic nature preserve improved tourism [ICON_CULTURE] Culture near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_2', '[ICON_TEAM_3] A hunting lodge increased [ICON_FOOD] Food from exotic animals near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_3', '[ICON_TEAM_3] Exotic animals discovered near {2_city} improved hunting [ICON_GOLD] Gold.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY', 'Quality Quarry', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_DESC', 'An unusually high quality rock vein was discovered in the quarry outside {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_1', 'Hire artisans to craft sculptures from the rock.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_2', 'Fund extra machinery to speed mining operations.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_3', 'Let the quarry manager handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_1', '[ICON_TEAM_3] Magnificent sculptures improved [ICON_CULTURE] Culture near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_2', '[ICON_TEAM_3] A quarry near {2_city} expanded [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_3', '[ICON_TEAM_3] A quarry near {2_city} discovered a [ICON_GOLD] Profitable rock vein.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER', 'Exotic Lumber', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_DESC', 'Exotic trees were discovered near the lumbermill outside {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_1', 'Create a national park to improve tourism.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_2', 'Build new infrastructure for lumber exports.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_3', 'Let the lumber business handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_1', '[ICON_TEAM_3] An exotic national park improved tourism [ICON_CULTURE] Culture near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_2', '[ICON_TEAM_3] Extensive [ICON_PRODUCTION] Production infrastructure near {2_city} exports valuable trees.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_3', '[ICON_TEAM_3] Exotic trees discovered near {2_city} improved lumber [ICON_PRODUCTION] Profits.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING', 'Pasture Fencing', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_DESC', 'Farmers near {2_city} want to build fences to keep out livestock, but ranchers are concerned about the loss of grazing land.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_1', 'Support the efforts of farmers to fence the land.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_2', 'Support the efforts of ranchers to keep an open range.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_3', 'Let the local citizens handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_1', '[ICON_TEAM_3] Fencing a pasture near {2_city} improved [ICON_FOOD] Food from surrounding farmland.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_2', '[ICON_TEAM_3] Ranchers near {2_city} increased [ICON_PRODUCTION] Production from an open range.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_3', '[ICON_TEAM_3] A compromise between ranchers and farmers near {2_city} improved the local [ICON_PRODUCTION] Economy.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND', 'Fishing Demand', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_DESC', 'Demand is rising for the marine life found in seas near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_1', 'Build a city aquarium for citizens to see the exotic sea creatures.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_2', 'Build infrastructure to expand the local fishing industry.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_3', 'Let local fisheries handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_1', '[ICON_TEAM_3] An acquarium of rare marine life increased culture in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_2', '[ICON_TEAM_3] Fishermen near {2_city} expanded [ICON_FOOD] Food output.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_3', '[ICON_TEAM_3] Rare marine life near {2_city} improved [ICON_GOLD] Gold from fishing.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION', 'Well Expansion', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_DESC', 'An oil business wishes to expand near {2_city}, but the tourism industry is concerned about impact on the landscape.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_1', 'Support the tourism business with a new national monument.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_2', 'Support oil development with new roads and infrastructure.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_3', 'Let the businesses handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_1', '[ICON_TEAM_3] A monument to beautiful land near {2_city} improved tourism [ICON_CULTURE] Culture.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_2', '[ICON_TEAM_3] New infrastructure expanded oil [ICON_PRODUCTION] Production near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_3', '[ICON_TEAM_3] Oil [ICON_GOLD] Profits increased near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING', 'Platform Decommissioning', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_DESC', 'Several offshore platforms in the oil field near {2_city} exhausted their oil supply.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_1', 'Support commercial fishing by converting the rigs into artificial reefs.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_2', 'Dismantle and reuse components for rigs elsewhere in the oil field.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_3', 'Let the business handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_1', '[ICON_TEAM_3] Oil rigs converted to artificial reefs improved fishing [ICON_FOOD] Food near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_2', '[ICON_TEAM_3] Reusing depleted oil rig components improved [ICON_PRODUCTION] Production near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_3', '[ICON_TEAM_3] Selling decommissioned oil rigs raised [ICON_GOLD] Gold near {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION', 'Fort Expansion', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_DESC', 'The general in charge of the fort near {2_city} wishes to start new construction efforts.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_1', 'Research new military technologies at the fort.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_2', 'Upgrade the defensive capabilities of the fort into a Citadel.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_3', 'Let the general handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_1', '[ICON_GOLD] Gold: +6', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_2', 'The fort becomes a Citadel.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_1', '[ICON_TEAM_3] A fort near {2_city} expanded personnel and research facilities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_2', '[ICON_TEAM_3] A fort near {2_city} expanded to a Citadel.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_3', '[ICON_TEAM_3] A manufacturer near a fort outside {2_city} sells new weapon technologies.', '', '');
/* BUILDINGS */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM', 'Granary Population Boom', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_DESC', 'Improvements to the granary in {2_city} are attracting citizens to the city.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_1', 'Provide funds for citizens to find a new place to live.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_2', 'Hire citizens for a public works program.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_1', '[ICON_TEAM_2] Settler: +1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_2', '[ICON_TEAM_2] Workers: +2', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_1', '[ICON_TEAM_3] The government of {2_city} funded a new settlement program.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_2', '[ICON_TEAM_3] The government of {2_city} funded a new public works program.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_3', '[ICON_TEAM_3] Population is booming in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT', 'Smithy Development', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_DESC', 'A new smelting process developed by the smithy at {2_city} is potentially hazardous to workers.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_1', 'Fund research to make the process safer.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_2', 'Send resources to immediately put the process into production.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_1', '[ICON_TEAM_3] Extensive [ICON_RESEARCH] Research is under way to create a safer smelting process in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_2', '[ICON_TEAM_3] A new smelting process was quickly put into [ICON_PRODUCTION] Production in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_3', '[ICON_TEAM_3] A new smelting process improved [ICON_GOLD] Profits in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY', 'Market Monopoly', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_DESC', 'A business providing large donations to local schools is forming a monopoly on the market in {2_city}, driving up prices.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_1', 'Break up the monopoly to lower prices.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_2', 'Support the educational donations with treasury incentives.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_3', 'Collect taxes on the higher profits.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_1', '[ICON_TEAM_3] Citizens in {2_city} are [ICON_HAPPINESS_1] Happy as prices drop.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_2', '[ICON_TEAM_3] A new monopoly in {2_City} donates heavily to [ICON_RESEARCH] Education.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_3', '[ICON_TEAM_3] A monopoly on {2_city}''s market increased [ICON_GOLD] Gold profits.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY', 'Library Controversy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_DESC', 'A controversial book about racism in the history of {2_city} is sparking riots.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_1', 'Fund deeper research into the city''s turbulent past.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_2', 'Ban the book until the riots fade.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_3', 'This should raise book sales.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] A controversial book starts further [ICON_RESEARCH] Research into the history of {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Riots in {2_city} fade as a book causing [ICON_HAPPINESS_4] Anger was banned.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] A controversial book is [ICON_GOLD] Selling well in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY', 'Monument Controversy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_DESC', 'Citizens in {2_city} are protesting an old monument to imperialist expansion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_1', 'Give speeches promoting a peaceful culture.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_2', 'Distribute propaganda supporting militaristic expansion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] Peaceful [ICON_CULTURE] Cultural demonstrations sweep through {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Propaganda in {2_city} reduced [ICON_HAPPINESS_4] Anger about imperialism.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] A controversial monument is improving the tourism [ICON_GOLD] economy in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS', 'Walled Slums', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_DESC', 'Development of {2_city} expanded beyond the old city wall, with the inner districts deteriorating to slums.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_1', 'Revitalize the old city with cultural programs.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_2', 'Tear down the slums to make room for productive businesses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_1', '[ICON_TEAM_3] The inner city of {2_city} revitalized its [ICON_CULTURE] Culture.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_2', '[ICON_TEAM_3] Slums torn down in {2_city} cleared room for [ICON_PRODUCTION] Productive businesses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_3', '[ICON_TEAM_3] New businesses increased [ICON_GOLD] Gold revenues in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT', 'Barracks Recruitment', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_DESC', 'Citizens of {2_city} are angry about forced military conscription.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_1', 'Lower conscription rates in the city.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_2', 'Invest in nationwide propaganda to increase military enlistment.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_TIP_2', '[ICON_WAR] New Military Units: 2', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_1', '[ICON_TEAM_3] Reducing conscription rates lowered [ICON_HAPPINESS_4] Anger in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_2', '[ICON_TEAM_3] A barracks in {2_city} enlisted new military personnel.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_3', '[ICON_TEAM_3] War bond propaganda improved [ICON_GOLD] Revenues in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE', 'Colosseum Attendance', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_DESC', 'The colosseum in {2_city} is drawing record-breaking crowds.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_1', 'Show elaborate competitions to entertain the public.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_2', 'Host massive shows of patriotic propaganda.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_3', 'Let the mayor handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_1', '[ICON_TEAM_3] Competitions attract [ICON_HAPPINESS_1] Happy crowds in the {2_city} colosseum.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_2', '[ICON_TEAM_3] The colosseum of {2_city} hosts massive shows of [ICON_CULTURE] Cultural propaganda.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_3', '[ICON_TEAM_3] Improvements to the {2_city} colosseum raised [ICON_GOLD] Gold revenues.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED', 'Stable Breed', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_DESC', 'The stables in {2_city} raised an unusually agile, strong, and confident breed of horses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_1', 'Train them for horse races.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_2', 'Train them as war horses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_3', 'Let the stable owners decide.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_TIP_2', '[ICON_WAR] New Horse Units: 2', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_1', '[ICON_TEAM_3] A new breed of racehorse improved [ICON_HAPPINESS_1] Happiness in {2_city}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_2', '[ICON_TEAM_3] The military of {2_city} raised a new breed of war horses.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_3', '[ICON_TEAM_3] A new horse breed improved [ICON_GOLD] Revenues in {2_city}.', '', '');
/* CITYSTATES */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION', 'City-State Immigration', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_DESC', 'Some workers feel recent immigrants from the city-state of {2_player} are taking jobs away from citizens of your civilization.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_1', 'Pay for programs to give the immigrants a path to citizenship.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_2', 'Deport the immigrants and confiscate their homes.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_3', 'Denounce ethnic stereotyping.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_1', '[ICON_INFLUENCE] Influence: +70', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_2', '[ICON_INFLUENCE] Influence: -70[NEWLINE][ICON_GOLD] Gold: +200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_3', '[ICON_INFLUENCE] Influence: +10', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_1', '[ICON_TEAM_3] Immigrants from {2_target} gain a path to citizenship in the empire of {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_2', '[ICON_TEAM_3] The government of {1_player} deported immigrants from {2_target).', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_3', '[ICON_TEAM_3] The government of {1_player} denounced stereotypes about citizens of {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE', 'Currency Exchange', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_DESC', 'The value of your currency is rising, and the resulting trade imbalance risks hurting exports to {2_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_1', 'Set a fixed exchange rate to allow exports to continue unimpeded.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_2', 'Enact laws to strengthen your currency further, at the expense of the citystate.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_3', 'Let your Minister of Finance handle this matter.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_1', '[ICON_INFLUENCE] Influence: +70', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_2', '[ICON_INFLUENCE] Influence: -70[NEWLINE][ICON_GOLD] Gold: +200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_3', '[ICON_INFLUENCE] Influence: +10', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_1', '[ICON_TEAM_3] A fixed currency exchange rate improved exports from {1_player} to {2_target}, boosting [ICON_INFLUENCE] relations.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_2', '[ICON_TEAM_3] The currency of {1_player} rose dramatically in value, providing [ICON_GOLD] Gold at the expense of {2_target}''s economy.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_3', '[ICON_TEAM_3] Changes to {1_player}''s currency exchange rate improved exports to {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT', 'Diplomatic Incident', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_DESC', 'While on a visit to {2_player} you committed a serious faux pas during a diplomatic event, due to a cultural misunderstanding.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_1', 'Send gifts and make an official apology for the mistake, promising never to let it happen again.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_2', 'Explain the actions are acceptable in your society, and you will not apologize for your civilization''s roots.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_3', 'Let your diplomats handle this matter.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_1', '[ICON_INFLUENCE] Influence: +70[NEWLINE][ICON_CULTURE] Culture: -200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_2', '[ICON_INFLUENCE] Influence: -70[NEWLINE][ICON_CULTURE] Culture: +200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_3', '[ICON_INFLUENCE] Influence: +10', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_1', '[ICON_TEAM_3] An apology after a diplomatic incident improved [ICON_INFLUENCE] relations between {1_player} and {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_2', '[ICON_TEAM_3] Refusal to apologize for the quirks of {1_player}''s [ICON_CULTURE] culture led to a diplomatic incident with {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_3', '[ICON_TEAM_3] A diplomatic incident of {1_player} on a visit to {2_player} helped increase cultural understanding between the two nations.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME', 'Scholastic Fame', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_DESC', 'Applications to study at esteemed schools in your empire are soaring from foreign students of {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_1', 'Relax immigration restrictions for students.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_2', 'Restrict enrollment to domestic students.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_3', 'Allow school deans to handle this.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_1', '[ICON_INFLUENCE] Influence: +70[NEWLINE][ICON_RESEARCH] Science: -200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_2', '[ICON_INFLUENCE] Influence: -70[NEWLINE][ICON_RESEARCH] Science: +200', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_3', '[ICON_INFLUENCE] Influence: +10', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_1', '[ICON_TEAM_3] The quality of education offered to foreign students from {2_target} improved [ICON_INFLUENCE] relations with {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_2', '[ICON_TEAM_3] New [ICON_RESEARCH] education laws favor domestic students of {1_player} over immigrants from {2_target}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_3', '[ICON_TEAM_3] Foreign students from {2_target} are flocking to schools of {1_player}.', '', '');
/* UNITS */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR', 'Scout Savior', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_DESC', 'Your scout rescued the child of a nomadic chieftain from a deadly beast. The grateful hunters offer you hospitality at their camp.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_1', 'Ask a few nomads to join your exploration.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_2', 'Train to move quickly with hunting bows.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_3', 'Rest at the camp for a while.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_1', 'Duplicates and heals the Scout.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_2', 'Replaces with an Archer who moves quickly.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_3', 'The Scout heals and gains 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_1', '[ICON_TEAM_3] A {2_target} joined {1_player} from a tribe of nomads.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_2', '[ICON_TEAM_3] A {2_target} of {1_player} learned to use hunting bows.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_3', '[ICON_TEAM_3] A {2_target} of {1_player} rested after saving a nomadic child.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES', 'Scout Stories', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_DESC', 'Your scout travelled far and wide, braving numerous dangers and discovering many wondrous lands. The citizens of your capital are eager to hear the stories.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_1', 'Hire a writer to craft epic poems of their travels.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_2', 'Provide the scout with new training and new weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_3', 'Allow the scout to tell their stories, then move on.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_1', '[ICON_CULTURE] Culture: +100', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_2', 'Heals and upgrades to a Sentinel.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_3', '[ICON_CULTURE] Culture: +30', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_1', '[ICON_TEAM_3] Epic poems of a Scout''s travels increased the [ICON_CULTURE] Culture of {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_2', '[ICON_TEAM_3] A scout of {1_player} upgraded to new armor and weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_3', '[ICON_TEAM_3] Stories of a Scout''s travels increased the [ICON_CULTURE] Culture of {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR', 'Renowned Warrior', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_DESC', 'Your warriors are gaining popularity in your empire, with tales sung of their bravery.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_1', 'Let them return to civilian life.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_2', 'Send them new weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_3', 'Send them fresh supplies.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_1', 'Converts to a Worker who ignores terrain costs.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_2', 'Converts to a Swordsman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_3', 'Heals and gains 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_1', '[ICON_TEAM_3] Warriors of {1_player} returned to civilian life.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_2', '[ICON_TEAM_3] Warriors of {1_player} received new weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_3', '[ICON_TEAM_3] Warriors of {1_player} received fresh supplies.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER', 'Renowned Archer', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_DESC', 'Your archers are gaining popularity in your empire, with stories told of their marksmanship.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_1', 'Let them retire to civilian life.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_2', 'Send them new weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_3', 'Send them fresh supplies.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_1', 'Converts to a Worker who ignores terrain costs.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_2', 'Converts to a Composite Bowman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_3', 'Heals and gains 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_1', '[ICON_TEAM_3] Archers of {1_player} retired to civilian life.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_2', '[ICON_TEAM_3] Archers of {1_player} received new weapons.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_3', '[ICON_TEAM_3] Archers of {1_player} received fresh supplies.', '', '');
/* CUSTOM */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB', 'Land Grab', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_DESC', 'Citizens of {2_city} demand better land to work.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_1', 'Pay to annex more land into the empire.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_2', 'Conscript the dissidents and put them to work.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_3', 'Let the mayor handle this', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_1', '[ICON_TEAM_6] New Tiles: 3', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_2', '[ICON_TEAM_2] New Worker: 1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_3', '[ICON_TEAM_6] New Tiles: 1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_1', '[ICON_TEAM_3] Citizens of {2_city} annexed a large new territory.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_2', '[ICON_TEAM_3] Dissidents in {2_city} were conscripted to the workforce.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_3', '[ICON_TEAM_3] Citizens of {2_city} work newly-annexed land.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES', 'Barbarian Mercenaries', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_DESC', 'A group of hostile raiders on your borders might switch sides - for a price.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_1', 'Hire them for your civilian workforce.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_2', 'Hire them as military mercenaries.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_3', 'Ambush the traitors and loot their supplies.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_1', '[ICON_TEAM_2] New Workers: 1', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_2', '[ICON_TEAM_2] New Military Units: 2', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_3', '[ICON_GOLD] Gold: +25', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_1', '[ICON_TEAM_3] Barbarians joined the civilian workforce of {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_2', '[ICON_TEAM_3] Barbarian mercenaries joined the army of {1_player}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_3', '[ICON_TEAM_3] Barbarian mercenaries were ambushed by {1_player}.', '', '');







UPDATE LoadedFile SET Value=1, en_US=1 Where Type='Stories.sql';


