-- Insert SQL Rules Here 

--
-- It appears this only changes the order these show on the user interface.
--

UPDATE UnitPromotions
SET OrderPriority = 10;

UPDATE UnitPromotions
SET OrderPriority = 100
WHERE Type IN (
	'PROMOTION_SCOUTING_1',
	'PROMOTION_SCOUTING_2',
	'PROMOTION_NAVAL_RECON_1',
	'PROMOTION_NAVAL_RECON_2'
);

UPDATE UnitPromotions
SET OrderPriority = 90
WHERE Type IN (
	'PROMOTION_SHOCK_1',
	'PROMOTION_SHOCK_2',
	'PROMOTION_SHOCK_3',
	'PROMOTION_ACCURACY_1',
	'PROMOTION_ACCURACY_2',
	'PROMOTION_ACCURACY_3',
	'PROMOTION_TRENCHES_1',
	'PROMOTION_TRENCHES_2',
	'PROMOTION_TRENCHES_3',
	'PROMOTION_TARGETING_1',
	'PROMOTION_TARGETING_2',
	'PROMOTION_TARGETING_3',
	'PROMOTION_INTERCEPTION_1',
	'PROMOTION_INTERCEPTION_2',
	'PROMOTION_INTERCEPTION_3',
	'PROMOTION_AIR_SIEGE_1',
	'PROMOTION_AIR_SIEGE_2',
	'PROMOTION_AIR_SIEGE_3'
);

UPDATE UnitPromotions
SET OrderPriority = 80
WHERE Type IN (
	'PROMOTION_DRILL_1',
	'PROMOTION_DRILL_2',
	'PROMOTION_DRILL_3',
	'PROMOTION_BARRAGE_1',
	'PROMOTION_BARRAGE_2',
	'PROMOTION_BARRAGE_3',
	'PROMOTION_GUERRILLA_1',
	'PROMOTION_GUERRILLA_2',
	'PROMOTION_GUERRILLA_3',
	'PROMOTION_BOMBARDMENT_1',
	'PROMOTION_BOMBARDMENT_2',
	'PROMOTION_BOMBARDMENT_3',
	'PROMOTION_DOGFIGHTING_1',
	'PROMOTION_DOGFIGHTING_2',
	'PROMOTION_DOGFIGHTING_3',
	'PROMOTION_AIR_TARGETING_1',
	'PROMOTION_AIR_TARGETING_2'
);

UPDATE UnitPromotions
SET OrderPriority = 70
WHERE Type IN (
	'PROMOTION_SIEGE',
	'PROMOTION_NAVAL_SIEGE',
	'PROMOTION_MEDIC',
	'PROMOTION_REPAIR',
	'PROMOTION_AIR_REPAIR',
	'PROMOTION_HELI_REPAIR',
	'PROMOTION_VOLLEY'
);

UPDATE UnitPromotions
SET OrderPriority = 60
WHERE Type IN (
	'PROMOTION_MARCH',
	'PROMOTION_MARCH_RANGED',
	'PROMOTION_MARCH_IV',
	'PROMOTION_AIR_RANGE',
	'PROMOTION_SORTIE'
);

UPDATE UnitPromotions
SET OrderPriority = 50
WHERE Type IN (
	'PROMOTION_BLITZ',
	'PROMOTION_LOGISTICS',
	'PROMOTION_AIR_LOGISTICS',
	'PROMOTION_NAVAL_LOGISTICS',
	'PROMOTION_COVER_VANGUARD_1',
	'PROMOTION_COVER_VANGUARD_2',
	'PROMOTION_AIR_AMBUSH_1',
	'PROMOTION_AIR_AMBUSH_2'
);

UPDATE UnitPromotions
SET OrderPriority = 40
WHERE Type IN (
	'PROMOTION_CHARGE',
	'PROMOTION_INDIRECT_FIRE',
	'PROMOTION_RANGE'
);

UPDATE UnitPromotions
SET OrderPriority = 30
WHERE Type IN (
	'PROMOTION_COVER_1',
	'PROMOTION_COVER_2',
	'PROMOTION_SKIRMISH',
	'PROMOTION_AMBUSH_1',
	'PROMOTION_AMBUSH_2'
);


UPDATE LoadedFile SET Value=1 WHERE Type='Cat_PromotionOrder.sql';
