/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Traits  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Sie erhalten eine zusätzliche Spy. Große Generäle weiter sehen und geben mehr Kraft. [NEWLINE] Startet mit einem Krieger und Groß Allgemein.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Zuteilung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Ihre Gewinne eine kostenlose Kopie von jedem starken neuen Einheit Linie, die Sie zu erforschen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Einheiten bewegen sich schneller an den Flüssen, und beginnen mit der Wasserförderung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' +10% [ICON_GREAT_PEOPLE] Great People Rate von jeder Allianz und 20% [ICON_STRENGTH] Kampf gegen Zivilisationen mit mehr Städten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Nahkampf und Avantgarde Einheiten kosten 50% weniger Wartung. Alle Geräte benötigen 25% weniger Erfahrung, um ihre nächste Beförderung zu verdienen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Produktions auf Gebäude, die bereits in der [ICON_CAPITAL] Kapital existieren. Beginnt mit [ICON_RES_IRON] Eisen in den ersten fünf Städten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', '25% höhere Erträge aus befreundeter und verbündeter Stadtstaaten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Hellenisierung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' 2 [ICON_CULTURE] Kultur in jeder Stadt. Stadtstaat [ICON_INFLUENCE] Einfluss bei der Hälfte abbaut und wieder auf das Doppelte der normalen Rate.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Interne Handelswege bieten 10 [ICON_GOLD] Gold-zum Ziel.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Gewinne [ICON_CULTURE] Kultur Töten von feindlichen Einheiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' 50% [ICON_CULTURE] Kultur und ein [ICON_MOVES] Bewegung bei der [ICON_GOLDEN_AGE] Goldene Zeitalter. [NEWLINE] Beginnt mit einer einzigartigen Spearman.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' 1 [ICON_PEACE] Glaube von unbebauten Wald und Dschungel, und 150% Ausbeute aus Naturwunder. [NEWLINE] Startet mit einem Spearman.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Beschädigte Einheiten kämpfen in voller Stärke. Fischerboote und Inseln geben [ICON_CULTURE] Kultur.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Gao Miliz', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Vanguard Einheiten siehe weiter und bewegen sich schneller.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Einheiten bewegen sich schneller auf Hills. Straßen und Eisenbahnen kosten keine Wartung auf Hügeln, die Hälfte kosten anderswo.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Zivilisten bewegen sich schneller in der Wüste. Ihre ausgehenden Handelsrouten mit unterschiedlichen Kulturen mehr verdienen [ICON_GOLD] Gold-und [ICON_CULTURE] Kultur und eingehende Handelswege mehr verdienen [ICON_GOLD] für den Besitzer der Route.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Schnellere Bewegung in Wald und Dschungel, die als Straßen in freundlichen Gebiet nach der Untersuchung The Wheel zählen. [NEWLINE] Startet mit einem einzigartigen Schwertkämpfer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Große Wissenschaftler erscheinen 25% schneller, und Sie ein Schreiben an erhalten. [NEWLINE] Startet mit einem Bowman.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Wüste Wohnwagen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Einheiten bewegen sich schneller in der Wüste, Wohnwagen zu erreichen weiter und Handelswege zu verbreiten Religion schneller von euren Städten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'Nach der Erforschung Theologie, erhalten einen Bonus Großartige Person am Ende eines jeden Maya Long Count Kalender Zyklus (alle 394 Jahre). [NEWLINE] Startet mit einem einzigartigen Archer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Jedes Luxus-Ressource erhöht [ICON_GOLD] Gold-Einkommen um 5%.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' +20% [ICON_PRODUCTION] Produktions Richtung Wonder Konstruktion.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' +30 [ICON_WAR] Erfahrung für Schiffe.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Wählen Sie eines mehr Glaube als normal, wenn Sie eine Religion gefunden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Ports erhalten Sie eine kostenlose Harbor, und Einheiten können Berge überqueren. Beginnt mit Segeln, einem Bireme, und ein Krieger.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Planwirtschaft', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Einheiten siehe weiter, Zivilisten bewegen sich schneller, und Sie gewinnen ein weniger [ICON_HAPPINESS_4] Nationale Unglück pro Stadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Essen Gebäude hinzufügen 1 [ICON_CITIZEN] Bevölkerung, wenn gebaut. [NEWLINE] Startet mit einem Arbeiter.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Barbarenlager abzugeben, wenn für Doppel [ICON_GOLD] Gold-besiegt. [NEWLINE] Startet mit einem Pferd Archer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'American Dream', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Migranten bewegen sich hier von Kulturen mit geringer Glück und hohen amerikanischen kulturellen Einfluss. Ihre Bürger wandern entlang der inneren [ICON_FOOD] Essen Handelswege.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Joseon-Dynastie', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' 2 [ICON_RESEARCH] Wissenschaft von Farms. [NEWLINE] Startet mit einem Arbeiter.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Doppel Ausbeuten aus Naturwunder, plus 100 [ICON_GOLD], wenn entdeckt. [NEWLINE] Startet mit einem Scout, und erhält eine Karavelle bei Compass.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Hanse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Doppel Menge von Strategic Resources, und 3 zusätzliche Stimmen in der Weltkongress.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Schneller und stärker Einschiffung über Wasser und Nahkampfeinheiten plündern schneller.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terror', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'Stadtstaaten ergeben können Bully in Angst, als Marionetten. Montiert und Scharmützel Einheiten schneller bewegen. Beginnt mit einem Scout.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Tribut', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Interne Handelswege zwischen Städten bieten 10 [ICON_GOLD] Gold-zum Ziel.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Reconquista', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Die Eroberung Städten erhöht [ICON_PEACE] Glaubens.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Geißel Gottes', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Barbarenlager abzugeben, wenn geschlagen, und Landeinheiten weniger kosten [ICON_GOLD] Wartung. [NEWLINE] Startet mit einem Pferd Archer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Geißel Gottes', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Barbarenlager abzugeben, wenn geschlagen, und Landeinheiten weniger kosten [ICON_GOLD] Wartung. [NEWLINE] Startet mit einem einzigartigen Chariot.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' +5% [ICON_GOLD] Nationaleinkommen von jeder Art von Luxus Ressourcen Sie steuern, oder importieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] Ein Bürger wanderten aus um {1} {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] Ein Immigrant aus der {1} kam in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] Ein Bürger ausgewandert von {1} in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Sie gewann {1} {2} {3} von {4} erfassen!', '', '');


/*  Einheiten  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Kk Gebirgstruppen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Neuzeit Einheit, die nur die Österreicher können zu bauen. Es ist leistungsfähiger und hat Aktionen, die die reguläre Einheit nicht aufgenommen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Dieses Gerät verfügt über leistungsstarke Vorteile in allen kalten Wetter Gelände. Kampf in Tundra, Schnee, Hügel und sogar Berge.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'Die kk Gebirgstruppen (deutsch: Kaiserlich-königlich Gebirgstruppe) im Jahr 1906 als Teil der österreichischen Landwehr, der territorialen Armee der westlichen Reichshälfte der Hälfte der österreichisch-ungarischen Monarchie gegründet wurden [NEWLINE] in einem Memorandum von Conrad von Hötzendorf vorgeschlagen. im Februar 1906 wurde die Kriegsministerium in Wien berief eine Sitzung auf Alpine Grenzsicherheit. Feldmarschall Tunk, stimmte ihm zu und legte ein Konzept, die Grundlagen, von denen wurden dann durchgeführt. [NEWLINE] Die bestehenden Zustand Schützenregimenter waren als Gebirgsjäger ausgebildet und, zusammen mit den Landsturm-Grenzschutz-Unternehmen und Gendarmerie Abteilungen waren das Rückgrat einer territorialen Verteidigungsarmee mit lokalem Wissen an der Grenze von Tirol bilden [NEWLINE] [NEWLINE] Bataillone und Unternehmen wurden Rudeltiere und wurden mit zusätzlicher Ausstattung auf die Anforderungen der Gebirgskrieg angepasst ausgestellt;. einschließlich Ski, Seile, Steigeisen und Eispickel. Regimenter wurden von einem Berg Maschinengewehr Abschnitt von vier Maschinengewehre, die die Mobilität verbessern, könnte durch Lasttiere oder in manportable Packs auf den höchsten Erhebungen durchgeführt werden verstärkt. Das gleiche mit den zerlegbaren Bergpistolen aufgetragen. Tragbares Feld Öfen (Schwarmöfen) und beheizte Zelte unterstützt Truppen in unwirtlichen Bedingungen. [NEWLINE] Beim Skifahren die Zwei-Stick-Ansatz hatte die Einzelhaft-Verfahren ersetzt. Die Bilgeri-Bindung war eine Tourenbindung, dass mit dem normalen Wanderschuh verwendet werden könnten. Die Waffe wurde von der (kürzeren) 8mm Mannlicher M 95 Karabiner ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Einzigartige Songhai Einheit montiert. Mandekalu Kavallerie beginnt mit der Belagerung Förderung, anders als die Ritter es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Leistungsstarke Mittelalterliche Soldat einzigartig für die Japaner. Samurai kann zweimal pro Zug angreifen und sind stärker als die Longswordsmen sie ersetzen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Einzigartige babylonischen Bogenschützen-Einheit. Die Bowman ist stärker als die Archer es ersetzt, und bewegen sich schneller in Wüsten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldat der mittelalterlichen Ära einzigartig in Dänemark. Der Berserker beginnt mit dem Lade Förderung, im Gegensatz zu den Langschwertkämpfer es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Die mobile Einheit einzigartig in Deutschland. Der Panzer hat eine höhere Kraft, Schnelligkeit, und die Sichtbarkeit als Tank es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Früh-Spiel Soldat einzigartig für die Azteken. Der Jaguar Schaden heilt, wenn es einen Gegner tötet, und bekämpft effektiv in Jungle als der Krieger sie ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard Einheit einzigartig für die Amerikaner. Es ist stärker als die Skirmisher es ersetzt, sieht weiter und bewegt sich schneller in unwegsamem Gelände.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'Eine der ersten Schießpulver-Einheiten des Spiels, einzigartig in der Französisch. Musketiere haben einen Kampfbonus außerhalb von freundlichen Gebiet, anders als der Musketier es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldat einzigartig in der Irokesen. Der Mohawk-Krieger kämpft in Wald-und Dschungel stärker als der Schwertkämpfer es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldat einzigartige an die Osmanen. Die Janitscharen ist viel stärker auf den Angriff und heilt nach Kills, im Gegensatz zu den Musketier es ersetzt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Einheiten innerhalb von 1 tile [COLOR_POSITIVE_TEXT] Heilen 4 Zusätzliche HP [ENDCOLOR] pro Umdrehung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'Die einzigartige mongolische Ersatz für die Ritter bewegt sich schneller, wird reichten, und teilt nicht das Ritterschwachstellen, um Städte oder Pikeniere. Die Keshik verdient auch Erfahrung schneller.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Leistungsstarke römischen Soldaten der Klassik mit einem Bonus gegen Städte. Die Legion hat eine höhere Festigkeit als der Schwertkämpfer die es ersetzt, extra Verteidigung gegen Fernkampfangriffe und können Straßen mit der doppelten Geschwindigkeit der Arbeiter zu bauen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'Ein Liburna war eine Art von kleinen Kombüse für den Schlachtzug und Rundgänge, insbesondere durch die römische Marine eingesetzt. [NEWLINE] [NEWLINE] In seiner ursprünglichen Form hatte die Liburna eine Bank mit 25 Rudern auf jeder Seite, während in der späten römischen Republik, es wurde mit zwei Reihen Ruder (a bireme), Rest schneller, leichter und agiler als Trieren ausgestattet. Die liburnische Design wurde von den Römern übernommen und wurde ein wichtiger Teil der Marine antiken Roms durch die 2. Hälfte des 1. Jahrhunderts v. Chr.. Liburnen spielte eine Schlüsselrolle in der Schlacht von Actium in Griechenland, das die Einrichtung von Augustus als unangefochtener Herrscher des römischen Welt sah. [NEWLINE] Liburnen unterschieden sich von den Schlacht Trieren, quadriremes Quinqueremen und nicht, weil der Ruder sondern wegen seine besonderen Konstruktionsmerkmale. [NEWLINE] [NEWLINE] Nachdem die Römer hatten die liburnische angenommen, ging sie ein paar Anpassungen machen, um den Einsatz der Schiffe in der Flotte zu verbessern. Die Vorteile gewonnen aus der Addition von Widdern und Schutz vor Raketen mehr als konfektionierte für den leichten Geschwindigkeitsverlust. Neben dem Bau, die Schiffe erforderlich, dass die reguläre römische Militäreinheit, um mehr reibungslos funktionieren vereinfacht werden. Jedes Schiff betrieben als individuelle Einheit, so dass die mehr komplizierte Organisation normalerweise verwendet, war nicht notwendig. Innerhalb der Marine, gab es wohl liburnische von mehreren unterschiedlichen Größen, die alle auf spezifische Aufgaben wie Scouting und patrouillieren Roman Gewässer vor Piraterie setzen. Die Römer nutzten die liburnische insbesondere in den Provinzen des Reiches, wo die Schiffe bildeten den Großteil der Flotten. [NEWLINE] Nach und nach Liburnen wurde eine allgemeine Bezeichnung für die verschiedenen Arten von römischen Schiffen, in der Spät auch auf Frachtschiffen befestigt Antike. Tacitus und Sueton wurden sie als Synonym für das Schlachtschiff. In Inschriften wurde es als die zuletzt genannten in der Klasse der Schlachtschiffe: hexeres, penteres, quadrieres, trieres, Liburna.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'Die Liburna ist Roms erste Marineeinheit. Es ist eine Nahkampfeinheit ohne Fernkampfstärke. Die Liburna ist nützlich für das Clearing von barbarischen Schiffe aus heimischen Gewässern und für begrenzte Exploration.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Rom verwendet diese Schiffe, die Gewässer zu kontrollieren und zu schützen, ihre Handelsrouten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Leistungsstarke mobile Einheit einzigartige nach Indien. Anders als der Reiter es ersetzt, wird die Kriegselefant reichten, erfordert keine Pferde, und hat keine Anfälligkeit für Speerträger.', '', '');
/*  Sonstiges  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Handelsbüro', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Osmanischen Tribute', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Kultur. [NEWLINE] 1 [ICON_CULTURE] Kultur pro angrenzenden Moai. [NEWLINE] [ICON_LOCKED] Muss neben Küste.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' 3 [ICON_CULTURE] Kultur. [NEWLINE] 1 [ICON_CULTURE] Kultur pro angrenzenden Moai. [NEWLINE] [ICON_LOCKED] Muss neben Küste.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Kultur. [NEWLINE] 1 [ICON_CULTURE] Kultur pro angrenzenden Moai. [NEWLINE] [ICON_LOCKED] Muss neben Küste.', '', '');
/*  Amsterdam Bourse  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'Die Börse in Amsterdam gilt als die älteste der Welt. Es wurde 1602 von der niederländischen Ostindien-Kompanie für den Umgang in der gedruckten Aktien und Anleihen etabliert. Es wurde später umbenannt in Amsterdam Börse und war der erste, offiziell beginnen den Handel mit Wertpapieren.', '', '');
/*  Jelling-Steine ​​ */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Jelling-Steine', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'Die Jelling-Steine ​​sind massiv geschnitzten Runensteine ​​aus dem 10. Jahrhundert, in der Stadt Jelling in Dänemark gefunden. Der ältere der beiden Jelling Steine ​​wurde von König Gorm in Erinnerung an seine Frau Thyra angehoben. Die größere der beiden Steine ​​wurde von Harald Bluetooth, König Gorm Sohn angehoben. Harald konstruiert den zweiten Stein in Erinnerung an seine Eltern, Feier der Eroberung von Dänemark und Norwegen, und seine Bekehrung der Dänen zum Christentum. Die Runeninschriften auf dieser Steine ​​gelten als die am besten in Dänemark bekannt.', '', '');
/*  Jade Halle  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Halle', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'König Sejong wachte die Entwicklung der Chiphyonjon, der Jade Hall of Scholars, die professionellen Wissenschaftlern, die Forschung sozialen und politischen Fragen für den König und die Regierung geholfen. Die Jade-Halle würde als ein "Think Tank" von Regierungen heute werden.', '', '');
/*  Indus Sanitär  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus Sanitation', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'Die Harappa-Zivilisation des Indus River Valley entwickelt, der weltweit erste bekannte städtische Abwassersysteme um 2600 v. Chr.. Einzelne Häuser oder Gruppen von Häusern erhalten Wasser aus Brunnen. Abwasser wurde geleitet von Zimmern beiseite zum Baden abgedeckt Kanalisation entlang der Hauptstraßen. Die massiven Wände der Harappa-Städte wurden spekuliert, vor Hochwasser zu schützen. Diese Harappan Wasserbau Systeme waren noch effizienter als die von vielen Bereichen des heutigen Pakistan und Indien, die Erreichung großen städtischen Städte mit relativ wenig Entwicklung der Landwirtschaft.', '', '');
/*  Pioneer  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pionier', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Gründet neue Städte, um Ihr Imperium zu erweitern. [NEWLINE] [NEWLINE] [ICON_FOOD] Das Wachstum der Stadt angehalten, während diese Einheit gebaut wird. [NEWLINE]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'Der Pioneer ist eine amerikanische Spezialeinheit. Es bewegt sich schneller als die Siedler es ersetzt. [NEWLINE] [NEWLINE] Mit dieser Einheit, neue Städte zu bauen. Es kann sich nicht verteidigen, so begleiten sie mit einer Kampfeinheit.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Amerikanischen Pioniere sind eine der Personen in der Geschichte der USA, der Westen von der Atlantikküste wanderten zu begleichen und neue Bereiche. Der Begriff bezieht sich vor allem für diejenigen, die wollten Gebiet neu in europäischen oder amerikanischen Gesellschaft zu regeln, obwohl das Gebiet durch bewohnt oder von einheimischen Völkern genutzt haben. [NEWLINE] [NEWLINE] Der Pionier Konzept und Ethos der Migration stark zurückdatieren, Teile der Vereinigten Staaten jetzt "westlichen" Staaten, so viele Plätze wie jetzt Ostens betrachtet wurden auch von Pionieren von der Küste niedergelassen. Zum Beispiel, Daniel Boone, eine Schlüsselfigur in der amerikanischen Pioniergeschichte, angesiedelt in Kentucky, wenn das ''Dark und blutigen Boden "war immer noch unterentwickelt. [NEWLINE] [NEWLINE] Eine wichtige Entwicklung in der westlichen Siedlung war der Homestead Act, die zur Verfügung gestellt formelle Regelung, die den Abwicklungsprozess geregelt.', '', '');
/*  Dampfmühle  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Dampfmühle', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Ein Übergang begann gegen maschinelle Fabriken in Großbritannien die Wirtschaft in den 1700er Jahren, die zuvor auf Handarbeit angewiesen und Zugtiere. Diese Vorläufer der industriellen Revolution begann mit der Mechanisierung der Textilindustrie. Handels Expansion wurde durch die Einführung von Kanälen, verbesserte Straßen und Eisenbahnen aktiviert. Breitere Nutzung von Wasserrädern und der Einführung der Dampfkraft geschoben dramatischen Anstieg der Produktionskapazität. Die Entwicklung von Ganzmetall-Werkzeugmaschinen in den frühen 1800er Jahren erleichtert den Bau von immer mehr verfeinert Produktionsmaschinen für die Herstellung in einer Vielzahl von Branchen.', '', '');
/*  Dojo  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Ein japanischer Dojo ("Ort des Weges '') ist ein Treffpunkt der Ausbildung, Prüfungen und andere verwandte Begegnungen für die'' do ''Kunst zu führen. Dojos waren anfangs Ergänzung zu Tempeln. In Japan jede körperliche Ausbildungsstätte, einschließlich Wrestling Schulen, Dojo kann wegen seiner engen Kampfkunst Wurzeln bezeichnet werden.', '', '');
/*  Schrein  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Shinto-Schrein', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'In Japan existieren Shinto-Schreine Seite an Seite mit buddhistischen Tempeln, und sind die zahlreichen, berühmt, und wichtige religiöse Stätten in Japan. Ein Shinto-Schrein ist eine Struktur oder ein Objekt, dessen Hauptzweck ist zu Haus eine oder mehrere Shinto kami (Spirituosen, Naturgewalten oder Essenz). Kami kann in fast alles, was Natur-oder von Menschen gemacht, von Mt. befinden. Fuji zu einem kleinen Juwel. Als solche sind diese Schreine häufig und sehr unterschiedlich in Umfang. Der Schrein selbst ist ein großes Gebäude oder kleine Objekt, an einem Straßenrand zu sein, oder vielleicht auch von Menschen durchgeführt werden. [NEWLINE] [NEWLINE] Wie buddhistische Tempel, Shinto-Schreine sind nicht in erster Linie ein Ort der Anbetung. Wichtigsten Gebäude des Schreins sind für die Verwahrung der heiligen Gegenstände verwendet. Es gibt spezielle Gebäude für bestimmte Riten, aber diese sind in der Regel nur auf eine begrenzte Anzahl von Teilnehmern auf. Religiöse Massenveranstaltungen im Stil der christlichen Kirchen nicht mit Regelmäßigkeit stattfinden und werden nicht in den Schrein statt. Wenn viele Menschen in einer Zeremonie beteiligt, wird es einen festlichen Charakter annehmen und werden im Freien gehalten werden.', '', '');
/*  Folkskola  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'Im Jahr 1842 führte das schwedische Parlament eine vierjährige Grundschule für Kinder in Schweden, "Folkskola" (Schule der Menschen). Dies war einer der ersten öffentlichen Schulsysteme in der Welt. [NEWLINE] [NEWLINE] Schwedisch Kinder sind erforderlich, um grundskola zu besuchen, Pflichtschule, ab dem Alter von 7 bis 16, wo grundskola ist eine Kombination von Primär-und Sekundärschule. Nach grundskola, viele Schweden besuchen die Wahl gymnasieskolan, Oberschule, die Wahl entweder ein Universitätsvorbereitungsprogramm oder ein Berufsbildungsprogramm. Schüler, die eine Berufs Programm wählen in der Regel ihre Ausbildung nach gymnasieskolan zu beenden, während Studenten, die ein Hochschulvorbereitungsprogramm abzuschließen normalerweise höherer Bildung in an einer Universität oder Fachhochschule. Schüler, die eine Berufs absolvieren kann in der Hochschulbildung anzumelden, müssen aber möglicherweise zusätzliche Kurse, bevor sie sich bewerben zu nehmen.', '', '');
/*  Basilika  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Basilika', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'Das lateinische Wort Basilika (aus der griechischen Stoa, dem Tribunal Kammer eines Königs abgeleitet) wurde ursprünglich verwendet, um einen Roman öffentlichen Gebäude in dem Forum einer römischen Stadt zu beschreiben. Durch die Erweiterung, wurde es an Christian Gebäude der gleichen Form aufgebracht. [NEWLINE] [NEWLINE] Im 4. Jahrhundert, das einst die kaiserlichen Behörden hatten das Christentum mit dem Edikt von Mailand 313 entkriminalisiert, waren Christen bereit sind, größer und schöner zu bauen Gebäude für Gottesdienst als die heimliche Treffpunkte sie benutzt hatte. Traditionelle architektonische Formeln für die Tempel waren wegen der Assoziationen mit nicht-christlichen Überzeugungen ungeeignet. Alte Tempelzeremonien aufgetreten draußen unter freiem Himmel in den Augen der Götter, mit dem Tempel als Kulisse. Das Modell Konstantin wollte für seine kaiserlichen Frömmigkeit memorialize war die Architektur des (bisher weltlichen) Basiliken, hält Zeremonien im Innenbereich.', '', '');
/*  Cothon  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'Ein cothon (griechisch: "Trinkgefäß") ist eine künstliche, geschützte Innenhafen häufig in Karthago während der Punischen Kriege c.200 BCE [NEWLINE] Cothons wurden in der Regel in der phönizischen Welt gefunden.. Beispiele sind Motya (Sizilien) aus dem 6. Jahrhundert v. Chr., die eine ungewisse Zweck (Mess 35 Meter x 51 Meter) durchgeführt, obwohl es wurde vorgeschlagen, diese cothon vielleicht sogar verschließbar und entleerbar, ein Trockendock zu bilden haben. Mahdia (Tunesien) aus dem 7. Jahrhundert v. Chr. (die 72 Meter x 56 Meter gemessen) und einer aus Kition auf Zypern.', '', '');
/*  Vedi  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi ist die Bezeichnung für "alter" in der vedischen Religion, noch praktiziert die älteste Religion in der Neuzeit. Solche Altäre sind ein erhöhter Gehäuse, in der Regel mit Kusha Gras bestreut und mit Aufnahmen für das Opferfeuer.', '', '');
/*  NASA-Center  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA-Center', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'Die NASA Center ist Neuzeit Forschungszentrums, die Erweiterungen der Technologie gewährt. Es bietet auch eine kostenlose Ressource Raumschiff-Fabrik.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Seit seiner Gründung im Jahr 1958 hat die NASA viele große wissenschaftliche und technologische Meisterleistungen in der Luft-und Raumfahrt durchgeführt. NASA-Technologie hat auch für viele Anwendungen nonaerospace von der Privatwirtschaft angepasst. NASA bleibt eine führende Kraft in der wissenschaftlichen Forschung und bei der Förderung der öffentlichen Interesses an der Luft-und Raumfahrt Exploration, sowie Wissenschaft und Technologie im Allgemeinen. Vielleicht noch wichtiger ist, unsere Erforschung des Weltraums hat uns gelehrt, auf die Erde, uns selbst und das Universum auf eine neue Weise zu sehen. Während die enormen technischen und wissenschaftlichen Errungenschaften der NASA zeigen anschaulich, dass Menschen früher undenkbar Kunststücke zu erreichen, wir werden auch von der Erkenntnis, dass die Erde nur ein winziger "blue marble" im Kosmos gedemütigt.', '', '');
/*  Abbey  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Abtei', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'Die Abtei hat an seinem Herzen die Praxis der Anbetung, mit der Idee, nicht jeder einen Dienst zu bekommen, aber die Chancen für den Gottesdienst, die Anhänger regelmäßig teilnehmen, wenn nicht wöchentlich bieten Abtei. Durch seine Leistungen, blühte die Kunst als Ausdruck von Lob an den "Schöpfer". Zusätzlich Abteien selbsttragende, engagiert in der Pflege Felder, Viehzucht, dem Betrieb öffentlicher Märkte und Beschäftigungsmöglichkeiten geben für die Gemeinschaft. Die keltischen Klöster zu Zentren des Lernens, die Erhaltung der heiligen und literarischen Manuskripte und Schulen der Unterricht.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'Die Abtei ist das keltische geistige und kulturelle Zentrum jeder Gemeinschaft. Es produziert ein [ICON_FOOD] Food, [ICON_RESEARCH] Wissenschaft, [ICON_CULTURE] Kultur, [ICON_GOLD] Gold-und [ICON_PRODUCTION] Production.', '', '');
/*  Odeon  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon, aus dem Altgriechischen ᾨδεῖον, Ōideion, wörtlich "singen Ort" oder "Bauen für Musikwettbewerbe". [NEWLINE] Der pracht odeon war das Odeon des Herodes Atticus am Südwest Felsen der Akropolis in Athen etwa 160 gebaut n. Chr. von den wohlhabenden Sophist und Rhetor Herodes Atticus in Erinnerung an seine Frau. Es hatte Platz für 8000 Personen, und die Decke war wunderschön geschnitzten Balken aus Zedernholz gebaut, wahrscheinlich mit einem offenen Raum in der Mitte, um das Licht einzulassen. Es wurde auch reichlich mit Bildern und anderen Kunstwerken dekoriert.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'Das Odeon ist eine Quelle von Instant [ICON_CULTURE] Kultur. Aufbauend hilft diese Grenzen Ihres Reiches zu verbreiten.', '', '');
/*  Barbary Hafen  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbary Hafen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'Die Barbary Piraten, manchmal auch als Korsaren oder osmanischen Korsaren waren Piraten und Freibeuter, die aus Nordafrika betrieben wird, vor allem in den Häfen von Tunis, Tripolis und Algier basiert. [NEWLINE] [NEWLINE] Dieser Bereich wurde in Europa als Barbary Coast bekannt , ein Begriff aus dem Namen seines Berber Einwohner abgeleitet. [NEWLINE] Neben der Beschlagnahme von Schiffen in Razzien engagiert sie Überfälle auf europäische Küstenstädte und Dörfer, vor allem in Italien, Frankreich, Spanien und Portugal, aber auch in der britischen Inseln, die Niederlande und so weit weg wie Island. Das Hauptziel ihrer Angriffe war es, christliche Sklaven für den muslimischen Markt in Nordafrika und dem Nahen Osten zu erfassen.', '', '');
/*  Basin Bewässerung  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Basin Bewässerung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Die alten Ägypter praktizierten Basin Bewässerung mit dem Hochwasser des Nils, um die Grundstücke, die von Deichen umgeben waren überschwemmen. Das Hochwasser wurde gehalten, bis die fruchtbaren Sediment niedergelassen hatten, bevor der Überschuss wurde dem Wasserlauf zurückgeführt. [NEWLINE] Es gibt Hinweise auf der alten ägyptischen Pharao Amenemhet III in der zwölften Dynastie (ca. 1800 v. Chr.) mit dem natürlichen See des Fayoum Oasis als Reservoir für Überschüsse an Wasser für den Einsatz während der Trockenzeit zu speichern, schwoll der See jährlich von der Überschwemmung des Nils.', '', '');





UPDATE Loaded File SET Value=1, DE_DE=1 Where Type='Leaders.sql';




