/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Einberufung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' +10 [COLOR_POSITIVE_TEXT] Heilungsrate [ENDCOLOR].', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Berufsarmee', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Schaltet erweiterte Aktionen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Merkantilismus', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' 2 [ICON_MOVES]-Bewegung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Freiheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' +25% [ICON_STRENGTH] Strength in freundlichen Territorium.', '', '');
/*  Freiheit  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultur: ein in allen Städten [NEWLINE] [ICON_PRODUCTION] Produktion: ein in allen Städten [NEWLINE] [ICON_WORKER] Freischaltungen: Terracotta Armee [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Große Persönlichkeit: +1 der Wahl', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Siedler: 1 [NEWLINE] [ICON_PRODUCTION] Produktion: 25% für die Siedler', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Gold: 200 x Era [NEWLINE] [ICON_CULTURE] Neue Städte erhöhen Politik Kosten 33% weniger.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Arbeiter: 1 [NEWLINE] [ICON_WORKER] Worker Verbesserung Rate: 25%', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 National Happiness -5 pro [ICON_CONNECTED] angeschlossen Stadt. [NEWLINE] [ICON_HAPPINESS_4]% Unzufriedenheit durch [ICON_CITIZEN] Bevölkerung in Städten, die nicht [ICON_OCCUPIED] besetzt sind.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] Freie Stadt Defense Gebäude in allen Städten (aktuelle, neue, und siegte). Mit entsprechenden Tech erforscht. [NEWLINE] [ICON_PRODUCTION] +1 Produktion pro Stadt Defense Building.', '', '');
/*  Tradition  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultur: in 3 Kapital [NEWLINE] [ICON_WORKER] Freischaltungen: Banaue Reis-Terrassen [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Große Persönlichkeit Rate:. +50% [NEWLINE] [ICON_CULTURE] Verdoppelt kulturellen schreitende Expansion Fliesen weit von Städten [NEWLINE] [ICON_PEACE] Kann Große Ingenieure erwerben mit dem Glauben ab dem Industriezeitalters.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Storytellers', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Kultur: 2 pro Village und Palace', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'Oral Tradition kulturellen Materials und Tradition von einer Generation zur anderen oral übertragen. Die Nachrichten, die Zeugnis verbal in der Rede oder der Song übertragen und kann die Form zu nehmen, zum Beispiel von Volksmärchen, Sprüche, Balladen, Lieder oder Gesänge. Auf diese Weise ist es möglich, für eine Gesellschaft, mündliche Geschichte, mündliche Literatur, Recht und andere verbale Wissen über die Generationen hinweg ohne ein Schriftsystem zu übertragen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Feierliche Riten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Kultur: +1 Kultur pro Gebäude [NEWLINE] [ICON_CULTURE] 1 freie Kulturgebäude in Ihre älteste 4 Städten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Eine Zeremonie ist eine Veranstaltung der rituelle Bedeutung zu einem besonderen Anlass durchgeführt. Zeremonien kann einen physischen Display-oder Theater Komponente: Tanz, eine Prozession, die Handauflegung. Ein Feststellungs verbale Äußerung kann mit dem Anlass verbunden werden. [NEWLINE] [NEWLINE] Eine Zeremonie kann eine Übergangsritus in einem menschlichen Leben markieren, Kennzeichnung der Bedeutung der Geburt, Erwachsenenalter, die Einweihung in einer Gruppe oder Tod. Manchmal ist eine Zeremonie darf nur von einer Person mit bestimmten Stelle durchgeführt werden. Society-weiten jährlichen Zeremonien kann oder saisonale oder wiederkehrende Ereignisse, wie der Frühlingspunkt, der Wintersonnenwende und andere astronomische Jahres Positionen zu markieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Surplus Essen: +25% pro Stadt [NEWLINE] [ICON_FOOD] Nahrung: 2 pro Stadt', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Stadt-Angriff: +50% von Garnisonen [NEWLINE] [ICON_GOLD] Keine Wartung für KVP-Einheiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Produktion: +15% für Wonders [NEWLINE] [ICON_HAPPINESS_1] Happiness: 1 pro 10 [ICON_CITIZEN] Bürgerinnen und Bürger', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Bürgerinnen und Bürger in der Hauptstadt schaffen +0,5 [ICON_GOLD] Gold-und 0,5 [ICON_HAPPINESS_1] Glück.', '', '');
/*  Honor  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] enthüllt Barbarenlager [NEWLINE] [ICON_STRENGTH] +10% Kraft gegen Barbaren [NEWLINE] [ICON_CULTURE] Töten Barbaren gibt 2 Kultur pro.. . Stärke der besiegten Feinde [NEWLINE] [ICON_WORKER] Freischaltungen: Tempel der Artemis [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Stadt Glück: ein pro-Kaserne', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] Verteidigungseinheiten in der Hauptstadt. [NEWLINE] +20% [ICON_PRODUCTION] Produktion für militärische Einheiten und Gebäude.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Kriegsbeute', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Gold-Bergung aus der Ausrüstung der besiegten Feinde. [NEWLINE] [ICON_CITY_STATE] +25% Belohnungen von der Erfassung Stadtstaaten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Raub durch eine siegreiche Armee während des Krieges war gängige Praxis, in der aufgezeichneten Geschichte. Für Fußsoldaten, wurde es als eine Möglichkeit, ihre oft mageren Einkommen aufzubessern angesehen und war ein Teil der Feier des Sieges. Auf höheren Ebenen, die stolze Ausstellung der Beute war ein integraler Bestandteil der typischen römischen Triumph, und Dschingis Khan war nicht ungewöhnlich in der Verkündigung, dass das größte Glück war ", um Ihre Feinde zu besiegen ... zu berauben sie ihrer Fülle ..." [NEWLINE] [NEWLINE] Im Krieg in der Antike, die Kriegsbeute enthalten die besiegten Bevölkerung, die oft versklavt wurden, und die Frauen und Kinder, die oft in der Bevölkerung der siegreichen Landes aufgenommen wurden. In anderen vormodernen Gesellschaften waren Gegenstände aus Edelmetallen das bevorzugte Ziel des Krieges Plünderungen, vor allem wegen ihrer einfachen Transport. In vielen Fällen war Plünderungen eine Gelegenheit, Schätze, die sonst nicht erhältlich sind erhalten. Seit dem 18. Jahrhundert haben die Kunstwerke immer mehr zu einem beliebten Ziel geworden. In den 1930er Jahren und noch mehr im Zweiten Weltkrieg, engagierte Nazi-Deutschland im großen Maßstab und organisierte Plünderung von Kunst und Eigentum.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiators', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Stadt Glück: +1 pro Arena [NEWLINE] 2 [ICON_TEAM_2] Verteidigungseinheiten in der Hauptstadt..', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'War Epics', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' 1 [ICON_HAPPINESS_1] Stadt Glück von Kultur Gebäuden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Ein episches (vom altgriechischen Adjektiv ἐπικός (epikos), ab ἔπος (Epos) "Wort, Geschichte, ein Gedicht") ist ein erzählendes Gedicht langen, gewöhnlich über ein ernstes Thema mit Details zu Heldentaten und Ereignisse signifikant zu einer Kultur oder Nation . [NEWLINE] [NEWLINE] War Epen sind epische Gedichte oder eine literarische Werke von epischen Ausmaßen, die suchen oder geglaubt werden, um zu erfassen und auszudrücken, das Wesen oder der Geist einer bestimmten Nation oder einer ethnischen oder sprachlichen Gruppe mit Bestrebungen zur Unabhängigkeit oder Autonomie. Nationalen Epen erzählen oft die Herkunft einer Nation, einen Teil seiner Geschichte oder einem entscheidenden Ereignis wie entscheidende Siege oder ende Überwindung der bitteren Feinden, in der Entwicklung der nationalen Identität', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Stadt Glück: +1 pro Garrison [NEWLINE] [ICON_CULTURE] Kultur: 2 pro Garrison', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Groß Allgemein: 1 [NEWLINE] [ICON_MOVES] Bewegung:. Ein für Große Generäle [NEWLINE] [ICON_STRENGTH] +15% Kraft für alle Einheiten neben anderen befreundeten Militäreinheiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15%, wenn [COLOR_POSITIVE_TEXT] neben [ENDCOLOR], freundliche Militäreinheiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] Upgrade-Kosten: -50% für Anteile [NEWLINE] [ICON_PRODUCTION] Produktion: 15% für alle Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Krieger-Code [ENDCOLOR] [NEWLINE]', '', '');
/*  Frömmigkeit  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Fähigkeiten:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultur ein [NEWLINE] [ICON_PEACE] Glaube ein [NEWLINE] [ICON_PRODUCTION] Doppel Produktion für Schreine [ICON_WORKER] Freischaltungen: Stonehenge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] Wählen Sie eine neue fromme Glaube.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Nächstenliebe', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Gold: +25% vom Tempel [NEWLINE] [ICON_GOLD] Gold: 2 von Tempel [NEWLINE] [ICON_GOLD] Gold: drei Heiligen Stätten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'Das Wort "Liebe" kommt aus dem Alten Französisch Wort "Charité", die wiederum aus dem lateinischen "caritas" abgeleitet. [NEWLINE] [NEWLINE] Die Praxis der Nächstenliebe bedeutet die freiwillige Abgabe der Hilfe für Menschen in Not, die sind nicht auf den Geber verwandt, obwohl die ursprüngliche Bedeutung ist mehr mit den Konzepten der Kostbarkeit, Teuerung, hoher Preis. Wohltätige Zwecke direkt oder mit Hilfe einer gemeinnützigen Stiftung oder andere gute Sache getan. Diese Institutionen entwickelt, um die Durchführung der Arbeit der Unterstützung der Armen, und kam zu nennen, als "Wohltätigkeitsorganisationen". In "Wohltätigkeitsorganisationen" modernen Zeiten stellen den Großteil der wohltätigen Spenden, in Form von Geldwert. Die Typen von Wohltätigkeitsorganisationen sind Waisenhäuser, Lebensmittelbanken, religiöse Institute widmet sich der armen, Krankenhäuser, Organisationen, die ans Haus gefesselt und eingesperrt zu besuchen pflegen, und viele andere.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Inspiration', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Freie Großen Propheten: +1', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'Das Wort "Inspiration" kommt aus dem lateinischen Substantiv inspiratio und von dem Verb inspirare. Inspirare ist ein zusammengesetzter Begriff aus dem lateinischen Präfix (innen, in) und dem Verb spirare (atmen) resultieren. [NEWLINE] [NEWLINE] In der klassischen römischen Zeiten inspirare schon zu bedeuten, kommen ", tief zu atmen" und übernahm auch die übertragenen Sinne von "zu vermitteln [etwas] im Herzen oder im Kopf von jemandem". [NEWLINE] [NEWLINE] Daher "Inspiration" bezieht sich auf eine unbewusste Ausbruch von Kreativität in einem literarischen, musikalischen oder anderen künstlerischen Bemühungen. Das Konzept hat Ursprung im Judentum und Hellenismus beide. Die Griechen glaubten, dass Inspiration kam von den Musen sowie die Götter Apollo und Dionysos. Auch in den alten nordischen Religionen leitet sich Inspiration von den Göttern wie Odin. Inspiration ist auch eine göttliche Angelegenheit in hebräischer Poesie. Im Buch Amosthe Prophet spricht, von Gottes Stimme überwältigt und gezwungen, zu sprechen. Im Christentum ist die Inspiration ein Geschenk des Heiligen Geistes.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Toleranz', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Stadt Glück: +1 pro Religiöse Gebäude [NEWLINE] [ICON_PEACE] Städte mit mehreren Religionen erhalten auch den Bonus von Pantheon zweitbeliebteste Religion der Stadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Toleranz oder Duldung ist "die Praxis der absichtlich ermöglicht oder erlaubt eine Sache, von der man missbilligt. Kann man sinnvoll sprechen zu tolerieren, dh Erlauben oder zulässt, nur, wenn man in der Lage ist zu verbieten." Es wurde auch definiert als " zu tragen oder zu ertragen "oder" zu nähren, zu erhalten oder zu wahren. "Toleranz kann bedeuten," nicht mehr als Nachsicht und die Erlaubnis von den Anhängern einer beherrschenden Religion für andere Religionen zu bestehen, auch wenn die letzteren auf Missbilligung als gegeben angesehen minderwertig, falsch oder schädlich "[NEWLINE] [NEWLINE] Toleranz ist eine Geisteshaltung, die nicht-wertende Akzeptanz der unterschiedlichen Lebensweisen und Überzeugungen impliziert, während Duldung bedeutet, setzen sich mit etwas, das man missbilligt. [NEWLINE] [NEWLINE] Historische Beispiele von "Toleranz" gibt es zuhauf. Zum Beispiel in einem Akt der Toleranz, wurde der persische König Kyros der Große glaubte, die Juden aus der Gefangenschaft in 539 bis 530 v. Chr. freigegeben haben, und erlaubte die Rückkehr in ihre Heimat.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Einheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Golden Age Umdrehungen: 10 [NEWLINE] [ICON_GOLDEN_AGE] Goldene Zeitalter benötigen 50% weniger [ICON_HAPPINESS_1] National Happiness', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Einheit bezieht sich auf die Beziehungen in einer Gesellschaft, die Menschen aneinander binden. Der Begriff wird in der Regel in der Soziologie und den anderen Sozialwissenschaften beschäftigt. [NEWLINE] [NEWLINE] In einfachen Gesellschaften kann es vor allem um Verwandtschaft und gemeinsamen Werten basieren. In komplexeren Gesellschaften gibt es verschiedene Theorien darüber, was zu einem Gefühl der sozialen Solidarität trägt [NEWLINE] [NEWLINE] Das bringt in der zugehörige Begriff "Solidarität", von denen es heißt:. [NEWLINE] "Solidarität geht nicht davon aus, dass unsere Kämpfe sind die gleichen Kämpfe, oder, dass unser Schmerz ist der gleiche Schmerz, oder dass unsere Hoffnung ist, für die gleiche Zukunft. Solidarität beinhaltet Engagement und Arbeit, sowie die Erkenntnis, dass auch wenn wir nicht die gleichen Gefühle oder Leben die gleichen, oder die gleichen Stellen, leben wir auf gemeinsamem Boden. " - Sara Ahmed', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Meditation', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Glaube: +1 Schreine, Tempel [NEWLINE] [ICON_PEACE] Glaube Kosten: -33%', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Hingabe', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'Hingabe kann definiert werden als: feurig, oft selbstlose Zuneigung und Hingabe, als an eine Person oder Prinzip. Anbetung, von der Old English worthscipe, was bedeutet, Würdigkeit oder wert-Schiff ist ein Akt der Frömmigkeit in der Regel zu einer Gottheit gerichtet. Eng mit dem Begriff der Liebe verbündet, ist Hingabe oft gehofft, mit irgendeiner Form von Segen oder Segen hin und her bewegt werden. [NEWLINE] [NEWLINE] Die Anhänger, wie diejenigen, die Hingabe sind aufgerufen zu wollen, um diese Segnungen zu praktizieren, sind oft zielstrebig zu der Punkt des Fanatismus. Während also der Begriff der "Hingabe" ist gutartig sind viele historische Beispiele der religiösen Hingabe oft extremen und blutig, als Anhänger wetteifern um die Zuneigung des gewidmet mit mehr empörend angezeigt.', '', '');
/*  Reichtum  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Reichtum', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'WEALTH', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'Reichtum ist die Fülle von wertvollen Ressourcen oder materiellen Besitz. Das Konzept der Reichtum ist in allen Bereichen der Wirtschaft signifikant, doch die Bedeutung von Reichtum ist kontextabhängig, und es gibt keine allgemein auf Definition geeinigt. Auf der allgemeinsten Ebene Reichtum ist "etwas von Wert", die sowohl die subjektive Natur des Wortes, und die Idee, dass es nicht eine feste oder statische Konzept erfasst.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'Was ist der Reichtum der Sozialpolitik Zweig zu?', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'Der Zweig der Reichtum konzentriert sich auf die Entwicklung von breiten Gebiet mit einer Versorgung des Landes [ICON_GOLD] Gold-erstellt von Kernstädten, um neue Einheiten und Gebäude in unbebauten Grenzstädte zu kaufen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'Der Zweig der Reichtum konzentriert sich auf die Entwicklung von breiten Gebiet mit einer Versorgung des Landes [ICON_GOLD] Gold-erstellt von Kernstädten, um neue Einheiten und Gebäude in unbebauten Grenzstädte zu kaufen. Siehe die Regeln für die Sozialpolitik für Details.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'Die Wealth Filial', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_GOLD] Gold: +10% {TXT} [NEWLINE] [ICON_PRODUCTION] Produktion: 10% {TXT} [NEWLINE] [ICON_WORKER] Freischaltungen : Panama-Kanal [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Glück: +1 pro Markt, Schmiede [NEWLINE] [ICON_PEACE] können große Merchants beim Betreten des Industriezeitalters zu kaufen mit dem Glauben.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' 2 [ICON_MOVES] Bewegung für Nicht-Kampfeinheiten. [NEWLINE] +25% [ICON_GOLD] Erträge [ICON_CONNECTED] Binnenhandel. [NEWLINE] -25% [ICON_GOLD] Kosten für Straßen und Eisenbahnen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Gold: 1 pro Dorf [NEWLINE] [ICON_PRODUCTION] Produktion: +1 pro Mine, Sägewerk', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Kann erwerben Landsknechts. [NEWLINE] [ICON_TEAM_2] 2 Landsknechte erscheinen in der Hauptstadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Freie Großen Händler: 1 [NEWLINE] [ICON_GREAT_PEOPLE] Großen Händler Rate: 25% [NEWLINE] [ICON_GREAT_MERCHANT] Double Gold Händler aus Großhandelsmissionen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Wohnwagen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Gold: 3 pro Handelsroute', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Produktion: 4 pro Coastal City [NEWLINE] [ICON_GOLD] Gold: 4 pro Leuchtturm, Hafen, Seehafen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Gilden', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' 1 [ICON_TEAM_7] Großen Händler in der Hauptstadt. [NEWLINE] +100% [ICON_GOLD] Gold-Händler aus Großhandelsmissionen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Eine Gilde ist ein Zusammenschluss von Handwerkern in einem bestimmten Handel. Bruderschaften wie der Arbeiter waren die ersten Arten der Gilde gegründet. Sie wurden in einer Art und Weise etwas zwischen einer Gewerkschaft, eines Kartells und einer Geheimgesellschaft organisiert. Sie haben oft über Zuschüsse von Briefen Patent von einem Monarchen oder andere Behörde, die Handelsströme, um ihre Selbstständige Mitglieder durchzusetzen, und den Besitz von Werkzeugen und die Lieferung von Materialien behalten abhing.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] Einkaufskosten für Einheiten und Gebäude.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Patentrecht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' 1 [ICON_GOLD] Gold-Dörfer aus. [NEWLINE] 2 [ICON_GOLD] Gold von Häfen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Ein Patent ist ein Satz von ausschließlichen Rechten aus einem Zustand (Landesregierung) zu einem Erfinder oder ihre Rechtsnachfolger für einen begrenzten Zeitraum im Austausch für die Offenlegung einer Erfindung gewährt. [NEWLINE] [NEWLINE] Patenten im heutigen Sinne entstand im Jahr 1474, als die Republik von Venedig erließ ein Dekret, das neue und erfinderische Geräte, einmal in die Praxis umzusetzen, musste die Republik mitgeteilt das Recht, andere von der Nutzung verhindern zu erhalten. [NEWLINE] [NEWLINE] England folgte mit der Satzung des Monopol im Jahre 1623 unter König James I, die erklärt, dass Patente nur für selbstverständlich werden "Vorhaben von neuen Erfindung." Während der Regierungszeit von Queen Anne (1702-1714), die Anwälte des englischen Hofes entwickelt die Forderung, dass eine schriftliche Beschreibung der Erfindung einzureichen. Das Patentsystem in vielen anderen Ländern auf britisches Recht und kann auf die Satzung des Monopolzurückverfolgt werden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] Moves und ein Anblick für militärische Schiffe. [NEWLINE] 2 [ICON_RESEARCH] Wissenschaft für Küstenstädte. [NEWLINE] 2 [ICON_RESEARCH] Wissenschaft für Marine Gebäude.', '', '');
/*  Schirmherrschaft  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Fähigkeiten:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_GOLD] 2 Gold pro Stadtstaat Handelsroute [NEWLINE] [ICON_VIEW_CITY] zeigt alle Stadtstaaten [NEWLINE] [ICON_WORKER] Freischaltungen : Angkor Wat [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_PLUS] +100% strategische Ressource Menge und 50% [ICON_HAPPINESS_1] Nationale Happiness von Luxus-Ressourcen, die von Stadtstaat Verbündeten begabt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] +20 Instant Einfluss mit Stadt-Staaten. [NEWLINE] [ICON_INFLUENCE] 33% Einfluss von [ICON_GOLD] Gold-Geschenke an Stadt-Staaten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Special Relationship', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Einfluss bei Stadtstaaten verschlechtert 33% langsamer als normal. [NEWLINE] [ICON_INFLUENCE] Andere Spieler Einfluss mit Stadtstaaten sinkt 10% schneller.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] 20 ruht Einfluss bei Stadtstaaten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] 2 Wissenschaft pro Ära für jeden Stadtstaat Freund, und drei für jeden Verbündeten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] Stadtstaat Verbündeten Großes Geschenk der Menschen. [ICON_GREAT_PEOPLE] 10% Groß Menschen bewerten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Handelspakt', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' 2 [ICON_PRODUCTION] Produktion pro Ära für jeden Stadtstaat Freund, und drei für jeden Verbündeten (Split unter Ihren Städten).', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Freihandel ist ein System der Handelspolitik, die Händler über nationale Grenzen hinweg ohne Störung von den jeweiligen Regierungen handeln können. Aufgrund der wirtschaftlichen Prinzip des komparativen Vorteils, bietet diese Handelspartner mit gegenseitigen Gewinne. Im Rahmen dieser Politik Preise sind die einzige Determinante der Ressourcenallokation und eine unmittelbare Reflexion von Angebot und Nachfrage.', '', '');
/*  Ästhetik  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] +50% Produktion für kulturelle Gebäude [NEWLINE] [ICON_WORKER] Freischaltungen:. Uffizien [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] verborgene Antike Stätten. [NEWLINE] [ICON_TEAM_7] Ermöglicht den Erwerb von Kultur Große Menschen mit [ICON_PEACE] Glaube beim Betreten des Industriezeitalters.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Kultur: 1 pro 2 Schuss Glück.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Kultur: zwei pro-National Wonder [NEWLINE] [ICON_CULTURE] Kultur: +33% in Städten mit ein Weltwunder', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Great Artist: 1 [NEWLINE] [ICON_TEAM_7] Kultur Große Persönlichkeit Rate: 25%', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Archäologen sind doppelt so schnell produziert', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Doppel-Gebäude Thema Tourismus. [NEWLINE] [ICON_TOURISM] +25% Tourismus aus gemeinsamen Religion, offene Grenzen und Handelswege.', '', '');
/*  Exploration  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_MOVES] Moves: 2 begann für Einheiten [NEWLINE] [ICON_MOVES] Moves: 2 für Groß Admirals [NEWLINE] [ICON_SIGHT_SEA] Sight: + 1 für die Militär-Schiffe [NEWLINE] [ICON_WORKER] Freischaltungen: Red Fort [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] 2-National Happiness pro Luxury Ressource. [NEWLINE] [ICON_TEAM_7] Ermöglicht den Kauf von Groß Admirals mit Glauben beim Betreten des Industriezeitalters.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Stadt Glück: +1 pro Leuchtturm, Hafen, Seehafen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Einkaufs Kosten: -25% für Gebäude [NEWLINE] [ICON_GOLD] Wartung: -25% für Gebäude', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Kolonisation', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Städte beginnen mit 3 Bevölkerung. [NEWLINE] [ICON_TEAM_2] 2 Siedler, zwei Arbeiter und zwei Verteidigungseinheiten erscheinen in der Hauptstadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Pioniergeist', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 Bewegung für Zivilisten. [NEWLINE] [ICON_GOLD] -50% Kosten für die Straßen. [NEWLINE] [ICON_PRODUCTION] +100% Produktion für den Aufbau von Häfen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Homestead Act', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Städte haben freien Tier-1-Gebäuden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(Todo)', '', '');
/*  Wissen  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Wissen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'WISSEN', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'Wissen ist eine Vertrautheit mit jemand oder etwas, das Fakten, Informationen, Beschreibungen oder Fähigkeiten, die durch Erfahrung oder Ausbildung erworben umfassen kann. Es kann auf die theoretische oder praktische Verständnis eines Subjekts beziehen. Es kann praktische Fähigkeiten oder Know-how oder die theoretische Verständnis eines Themas sein.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Frömmigkeit erhöht das Glück, Kultur, Glaube und der Annahme Zivilisation. Frömmigkeit wird verfügbar, sobald der Klassik erreicht ist. Dies ist ein idealer Ort, um Richtlinien für Spieler, die Religionen zu erstellen oder erweitern zu erwerben.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'Was ist die Wissenszweig der Sozialpolitik zu?', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'Der Zweig der Wissen verbessert die Zivilisation Fähigkeit zur Nutzung und Erzeugung Wissenschaft, immer beim Betreten der Renaissance-Ära zur Verfügung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'Die Wissenszweig der Sozialpolitik ist voll von Politik, die Ihre Forschung erhöhen können. Dieser Zweig wird in der Zeit der Renaissance zur Verfügung. Siehe die Regeln für die Sozialpolitik für Details.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'Die Knowledge-Filiale', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Fähigkeiten: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Große Wissenschaftler: 1 [NEWLINE] [ICON_WORKER] Freischaltungen: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [ COLOR_GREY] (erledige alle Maßnahmen in diesem Baum) [ENDCOLOR] [NEWLINE] ein Instant [ICON_TEAM_5] Technologies. [NEWLINE] [ICON_PEACE] Kann Große Wissenschaftler zu kaufen mit [ICON_PEACE] Glaube, sobald Sie die Industrie-Ära geben.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[ICON_RESEARCH] +50% Forschung Abkommen Belohnungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Spionageabwehr', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] +25% Chance, um feindliche Spione zu fangen. [NEWLINE] [ICON_SPY] -25% feindlichen Spion Wirksamkeit.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(Todo)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Wissenschaft: 10%, während die Nation ist [ICON_HAPPINESS_1] glücklich', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Wissenschaft: +1 pro Dorf [NEWLINE] [ICON_RESEARCH] Wissenschaft: 2 pro Leuchtturm', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Wissenschaft: 2 pro Fach', '', '');







UPDATE LoadedFile SET Value=1, DE_DE=1 Where Type='Policies.sql';



