/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/*  ANGEBOTE  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Rüstung [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', 'Artic Netz', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Schnee und Tundra [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', 'Ich Bombardierung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Sea [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', 'Bombardierung II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Sea [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', 'Bombardierung III', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Sea [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] 6 Bereich', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] 6 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] Kann Sweep Luft zum Abfangen Einheiten zu löschen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', 'Zuteilung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] +10% Kraft [NEWLINE] [ICON_GOLD] -100% [COLOR_POSITIVE_TEXT] Upgrade-Kosten [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] Full Schaden Angriff über das Meer oder Flüsse [NEWLINE] [ICON_STRENGTH] +100%, wenn [COLOR_POSITIVE_TEXT] Begann [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[ICON_STRENGTH] +25% Kraft vs [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Rüstung [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[ICON_STRENGTH] +25% Kraft vs [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Rüstung [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', 'Bonus vs Air (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Air [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] +150% vs [COLOR_POSITIVE_TEXT] Bomber und Hubschrauber [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', 'Bonus vs Dragoner (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Dragoner [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus vs Fighters (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Hubschrauber (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Hubschrauber [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', 'Bonus vs (10) montiert', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] +10% vs Nahkampf [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', 'Bonus vs montiert (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] +50% vs Nahkampf [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', 'Angriff gegen U-Boote (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Angriff [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Submarines [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Tanks (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Tanks [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', 'Astronomie', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] Kann queren [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', 'Bonus auf Angriff (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Angriff [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', 'Bonus auf Angriff (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Angriff [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_RANGE_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR] Kann zweimal angreifen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', 'Kameradschaft', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] +15%, wenn [COLOR_POSITIVE_TEXT] Angrenzend [ENDCOLOR], um eine freundliche Einheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] Angriffe verwenden [COLOR_POSITIVE_TEXT] 1. Bewegung [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] Kann durch bewegen [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', 'Bonus gegen Großkampfschiffe (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Battleships [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Missile Cruisers [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Carriers [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] Kann Carry [COLOR_POSITIVE_TEXT] 1 [ENDCOLOR] Fracht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] Kann Carry [COLOR_POSITIVE_TEXT] 2 [ENDCOLOR] Fracht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] Kann Carry [COLOR_POSITIVE_TEXT] 3 [ENDCOLOR] Fracht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] Kann Carry [COLOR_POSITIVE_TEXT] 4 [ENDCOLOR] Fracht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] 1-Bewegung [NEWLINE] [ICON_STRENGTH] +20% vs [COLOR_POSITIVE_TEXT] Wounded [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Befestigte [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', 'Angriff gegen Städte (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Angriff [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', 'Bonus gegen Städte (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', 'Bonus gegen Städte (200)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] +200% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', 'Bonus gegen Städte (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', 'Händler Raider I', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Hafen Städte [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal Gold in Höhe von 33% des Schadens zu Häfen behandelt', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', 'Händler Raider II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Hafen Städte [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal Gold in Höhe von 33% des Schadens zu Häfen behandelt', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', 'Händler Raider III', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Hafen Städte [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal Gold gleich 34% der Schäden an Häfen behandelt', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Fernkampf-Angriffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Fernkampf-Angriffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', 'Penalty vs Fernkampf (10)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] -10% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR] gegen alle [COLOR_NEGATIVE_TEXT] Fernkampf-Angriffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '-10% Vs [COLOR_NEGATIVE_TEXT] Fernkampf [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH] +30% in die [COLOR_POSITIVE_TEXT] Kapital [ENDCOLOR]; Bonus fällt da das Gerät bekommt weiter weg', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalty für Verteidigung (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] Kann auf [COLOR_POSITIVE_TEXT] Wasser Fliesen begeben [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +100%, während [COLOR_POSITIVE_TEXT] Begann [ENDCOLOR].', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', 'Bonus auf Verteidigung (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', 'Bonus auf Verteidigung (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', 'Penalty für Verteidigung (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', 'Desert Power', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Wüsten [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15%, wenn [COLOR_POSITIVE_TEXT] neben [ENDCOLOR], um eine freundliche Einheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] Luft Sweeps [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] Luft Sweeps [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] 34% [COLOR_POSITIVE_TEXT] Luft Sweeps [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS_HELP', '[ICON_WORKER] Builds Verbesserungen +100% schneller', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS', 'Doppelarbeitsgeschwindigkeit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Gelände (Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] Kann auf [COLOR_POSITIVE_TEXT] Wasser Fliesen [ENDCOLOR] begeben', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Begann Defense (100)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] +100%, wenn [COLOR_POSITIVE_TEXT] begann [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] ein Sichtbereichs wenn [COLOR_POSITIVE_TEXT] Begann [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50% Chance, [COLOR_POSITIVE_TEXT] Ausweichen [ENDCOLOR] Abfangen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100%, [COLOR_POSITIVE_TEXT] Ausweichen [ENDCOLOR] Abfangen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Bewegung [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Bewegung [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH] -10% für [COLOR_POSITIVE_TEXT] benachbarte feindliche Einheiten [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', 'Erstschlag', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT] freie Attacke [ENDCOLOR] vor dem Kampf', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] 50%, wenn [COLOR_POSITIVE_TEXT] Flankierende [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] Alle Bewegungen verwendet [COLOR_PLAYER_ORANGE_TEXT] 1. Bewegung [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Foreign Lands Bonus (20)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', 'Bildung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Armored [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', 'Kostenlose Upgrades', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', 'Kostenlose Upgrades', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] erwirbt Erfahrung 50% schneller', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] 15% mit [COLOR_POSITIVE_TEXT] Großen General [ENDCOLOR] in derselben Kachel', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', 'Golden', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '[ICON_GOLDEN_AGE] Golden Age Punkte aus dem Kampf', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] Verbessert die Kampfkraft der Nähe [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] Verbessert die Kampfkraft der Nähe [COLOR_POSITIVE_TEXT] Landeinheiten [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1', 'Guerrilla ich', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] auf Gelände [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2', 'Guerrilla II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] auf Gelände', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3', 'Guerrilla III', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] auf Gelände', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'AI Handicap I', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] ein Visibility [NEWLINE] [ICON_WAR] +10% Erfahrung [NEWLINE] [ICON_STRENGTH] +10% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] 2 Visibility [NEWLINE] [ICON_WAR] +25% Erfahrung [NEWLINE] [ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] 2 Visibility [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] Heilt 50 Damage [ENDCOLOR], wenn tötet einen Nichtbarbareneinheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] Heile dieses Einheit [ENDCOLOR] 50 PS, sonst wird [COLOR_POSITIVE_TEXT] Verbrauchen Sie diese Gelegenheit [ENDCOLOR], um eine Promotion zu wählen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', 'Hill-Kämpfer', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Hills [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] +15% in Freundlich Territory [COLOR_POSITIVE_TEXT] [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', 'All Terrain', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] Kann queren [COLOR_POSITIVE_TEXT] Berge [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] Ignoriert Terrain Kosten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] Kann über Hindernisse anzugreifen [COLOR_POSITIVE_TEXT] [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] +33% stärker [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] +33% stärker [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] +34% stärker [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[ICON_AIR] 20% Chance, [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] Flugzeug', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[ICON_AIR] 40% Chance, [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] Flugzeug', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[ICON_AIR] 50% Chance, [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] Flugzeug', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[ICON_AIR] 100%, [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] Flugzeug', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', 'Abfangen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] 100%, abfangen [COLOR_POSITIVE_TEXT] Air Units [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] Ignoriert kulturelle Grenzen [NEWLINE] [ICON_DETECT] Kann nur durch Einheiten mit Sonar oder ein Ziegel entfernt gesehen werden', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] 33% in [COLOR_POSITIVE_TEXT] Wald / Dschungel [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', 'Bonus gegen Land (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', 'Bonus gegen Land (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', 'Penalty gegen Land (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH] -50% vs [COLOR_NEGATIVE_TEXT] Land [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MARCH_HELP', '[ICON_HEAL] Offensiv-und Umzugs nicht verhindern, dass die Heilung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +10 Healing [ENDCOLOR] für Geräte innerhalb von 1 Fliese', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] 5 Healing [ENDCOLOR] pro Runde für Geräte in benachbarte Fliesen [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] 5 Healing [ENDCOLOR] pro Runde für diese Einheit, wenn [COLOR_POSITIVE_TEXT] Außerhalb von Friendly Territory [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', 'Söldner', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50% [COLOR_POSITIVE_TEXT] Upgrade-Kosten [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Bewegung [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] 33% in [COLOR_POSITIVE_TEXT] Wald / Dschungel [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] +20% Kraft', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', 'Bergsteiger', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] Kann über Berge passieren [COLOR_POSITIVE_TEXT] [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Penalty vs montiert (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] Große Generäle [ENDCOLOR] bei Rate dieser Einheit zu bewegen, wenn sie die wiederum [COLOR_POSITIVE_TEXT] gestapelt [ENDCOLOR] starten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] Muss, um Distanzangriffs Set Up', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Angriff [ENDCOLOR] in freundliche Gebiet', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', 'Nationale Schutz', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty Offensiv-Schiffe (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', 'Naval Recon I', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_HEAL] Kann [COLOR_POSITIVE_TEXT] heilen [ENDCOLOR] außerhalb freundlich Gebiet', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', 'Naval Recon II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] 1-Bewegung [NEWLINE] [ICON_MOVES] Versuche, [COLOR_POSITIVE_TEXT] zurückziehen [ENDCOLOR] aus Nahkampf', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', 'Naval Siege', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Befestigte Units [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Bewegung [ENDCOLOR] [NEWLINE] [ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', 'Neue Einheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'Neue Einheit', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] Kann Städte erfassen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', 'Keine Defensive Terrain Boni', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] No Defensive Terrain Boni', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] kann nicht eingegeben tiefen Ozean bis Astronomie', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] kann nicht eingegeben tiefen Ozean', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] +33% in Freundlich Territory [COLOR_POSITIVE_TEXT] [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] Einheit kann [COLOR_NEGATIVE_TEXT]-Einheiten [ENDCOLOR], nur Städte nicht angreifen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] kann nicht im Nahkampf', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', 'Panamakanal', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Bewegung für Schiffe', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', 'Parthenon', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] +10% Kraft aus Groß Generäle und Admiräle', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] Kann [COLOR_POSITIVE_TEXT] Paradrop [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '[ICON_HEAL] Heilt 25 Damage Wenn eine Einheit tötet', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', 'Phalanx', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] und [COLOR_POSITIVE_TEXT] Soldat [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] Erfasst [ENDCOLOR] besiegten Feind [COLOR_POSITIVE_TEXT] Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] 1 [COLOR_POSITIVE_TEXT] Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] Kann [COLOR_POSITIVE_TEXT] Angriff zweimal [ENDCOLOR] bei 90% [ICON_RANGE_STRENGTH] reichten Kraft', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', 'Verteidigung gegen Fernkampf (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Fernkampf Schaden [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] Kann geben Rival Territory [COLOR_POSITIVE_TEXT] [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', 'Recon I', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] 2 Sight', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', 'Recon II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] 1-Bewegung [NEWLINE] [ICON_MOVES] Kann Feind Straßen benutzen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', 'Recon III', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] Kann 10 Fliesen Paradrop.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', 'Bonus vs Meer (25)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Sea [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', 'Bonus vs Meer (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Sea [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', 'Sonar', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] Kann siehe [COLOR_POSITIVE_TEXT] Submarines [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] AUF [ENDCOLOR] Terrain (keine Hügel, Wald oder Dschungel)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Befestigte Units [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', 'Gefecht', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] Versuche, aus Nahkampf zurücktreten oder eingeschlagen Kampf', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] ein extra [COLOR_POSITIVE_TEXT] Interception [ENDCOLOR] kann pro Zug gemacht werden', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] Kampf wahrscheinlich zu erstellen [COLOR_POSITIVE_TEXT] Große Generäle [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] Kampf sehr wahrscheinlich zu erstellen [COLOR_POSITIVE_TEXT] Große Generäle [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] +15% Angriff [COLOR_POSITIVE_TEXT] Städte [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Wounded [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_HELP', '[ICON_HEAL] Darf [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +20 Healing [ENDCOLOR] pro Runde heilen Außerhalb Freundlich Territory [COLOR_POSITIVE_TEXT]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] 5 [COLOR_POSITIVE_TEXT] Heilung [ENDCOLOR] außerhalb freundlich Gebiet [NEWLINE] [ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] Einheit wird [COLOR_POSITIVE_TEXT] Heilen Jeder Drehen Sie [ENDCOLOR], auch wenn es eine Aktion [NEWLINE] [ICON_MOVES] Einheit wird versuchen, zurücktreten, wenn sie mit einem Nahkampfangriff konfrontiert', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', 'Unterdrückung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Vanguard [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', 'Überlebenskünstler', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '[ICON_HEAL] +20 [COLOR_POSITIVE_TEXT] Heilung [ENDCOLOR] außerhalb freundlich Gebiet [NEWLINE] [ICON_MOVES] Keine Bewegungskosten zu plündern', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] 1-Bewegung [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1', 'Gräben ich', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] im Gelände [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2', 'Trenches II', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] im freien Gelände', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3', 'Die Gräben III', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] im freien Gelände', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', 'Kann Rivalen Gebiet ohne offene Grenzen geben, verliert aber 25% der ursprünglichen religiösen Stärke für jede wiederum sie auf eine solche Kachel beenden. Einheit wird eliminiert, wenn religiöse Kraft 0 ist.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Befestigte [ENDCOLOR]-Einheiten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] +100%, wenn [COLOR_POSITIVE_TEXT] Begann [ENDCOLOR] [NEWLINE] 1 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR], wenn [COLOR_POSITIVE_TEXT] begann [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', 'Grundkampf Penalty (50)', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[ICON_RANGE_STRENGTH] -50% Angriffs vs [COLOR_NEGATIVE_TEXT] Ground und Schiffe [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Wald und Dschungel [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1. Bewegung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT] 2 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT] Sight Bereich [ENDCOLOR]', '', '');





UPDATE LoadedFile SET Value=1, DE_DE=1 Where Type='Promotions.sql';

