/* The sql commands and text below were formulated in the Research tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1194171600
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING', 'Ausbildung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_PEDIA', 'Militärische Ausbildung ist ein Prozess, der die Fähigkeiten des Militärs festlegt und zu verbessern. Militärische Ausbildung kann freiwillig oder zwangsZoll erhoben werden. [NEWLINE] Recruit Training versucht, die grundlegende Informationen und Ausbildung in Techniken notwendig, um eine effektive Service-Mitglied sein zu lehren. Um dies zu erreichen, werden Service-Mitglieder körperlich gebohrt, technisch und psychologisch. [NEWLINE] Nach Abschluss der Grundausbildung, viele Service-Mitglieder Weiterbildung unterziehen mehr im Einklang mit ihrer gewählten oder zugewiesenen Spezialitäten. In Weiterbildung ist der Militärtechnik und Ausrüstung oft gelehrt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_QUOTE', '[NEWLINE] [TAB] [TAB] "Die Wehrpflicht wenn notwendig, aber nicht unbedingt die Wehrpflicht." [NEWLINE] [TAB] [TAB] - William Lyon Mackenzie King [NEWLINE]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE', 'Politologie', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_PEDIA', 'Während der italienischen Renaissance, gegründet Niccolò Machiavelli den Schwerpunkt der modernen Politikwissenschaft auf die direkte empirische Beobachtung der politischen Institutionen und Akteure. [NEWLINE] [NEWLINE] Später europäischen Philosophen wie Voltaire, Rousseau, Thomas Hobbes und John Locke angewandten Prinzipien aus den Materialwissenschaften die Gesellschaft als Ganzes, die Schaffung der Sozialwissenschaften. Dies ebnete den Weg für die Politik, die einen Gesellschaftsvertrag zwischen Regierenden und Regierten, eine Notwendigkeit für eine Trennung von Kirche und Staat, und die schrittweise Verkleinerung der göttlichen Recht der Könige betont.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_QUOTE', '[NEWLINE] [TAB] [TAB] "Die Politik haben keine Beziehung zur Moral." [NEWLINE] [TAB] [TAB] - Niccolo Machiavelli [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_TITLE', 'Handel', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_DESC', 'Handel entstand mit dem Beginn der Kommunikation in prähistorischen Zeiten. Es spornte gemeinsame Neugier, Einfallsreichtum und das Erlernen von Sprachen. Als solche, Handel und Spezialisierung, dass es hervorgebracht hat, mit der Beschleunigung des Wachstums des menschlichen Bewusstseins und Menschen ''Triumph über die Neandertaler-Spezies gutgeschrieben worden. [NEWLINE] [NEWLINE] Es gibt Hinweise auf den Austausch von Obsidian und Feuerstein in der Steinzeit. Ägypten gehandelt nach Materialien für die Erstellung von Schmuck seit 3000 v. Chr. verwendet. Weiträumige Handelswege erschien zuerst bei den Sumerern in Mesopotamien gehandelt mit der Harappa-Zivilisation des Indus-Tal. Die Phönizier - festgestellt Meer Händler - reiste über das Mittelmeer und im Norden bis nach Großbritannien für Quellen von Zinn zu Bronze herzustellen. Sie gründeten Kolonien Handel die Griechen nannten emporia. [NEWLINE] [NEWLINE] Der Handel noch lange nach dem Untergang der antiken Mittelmeer maritime Imperien um die menschliche Tendenz fahren zu erkunden. Fernhandel Verbreitung noch weiter mit der Zheng He riesige Flotte, die Indien, Arabien und Ostafrika erreicht vor Kolumbus den Ozean überquert.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE] [TAB] [TAB] ". Kein Grund gibt es heute entweder das Vorhandensein oder die möglichen Auswirkungen der Wirtschaft in der prähistorischen Anbruch der Menschheit Rabatt" [NEWLINE] [TAB] [TAB] - Jason Shogren [NEWLINE] [ TAB]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE] [NEWLINE] Weder Spieler noch hat die Technologie, um diesen Artikel (Handel) zu handeln.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS', 'Carvel Rümpfe', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'Carvel Schiffsdesign war einer der kritischen Entwicklungen, die die Dominanz der westlichen europäischen Seemächte von 1400 der vorliegenden aktiviert. Die Holzbohlen in carvel Rümpfe Line-Up gegeneinander, Kante an Kante, statt der überlappenden Dielendesign Klinker Rümpfe. Diese stärkere Rumpf-Design unterstützt die viel größere Schiffe und Segel.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE] [TAB] [TAB] "Ein Schiff ist im Hafen sicher, aber das ist nicht das, was für Schiffe sind." [NEWLINE] [TAB] [TAB] - William Shedd [NEWLINE]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Massenmedien', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_DESC', 'Der Begriff "Massenmedien" wurde in den 1920er Jahren mit dem Aufkommen der Funk geprägt, aber die Idee von Medien für großes Publikum Verbrauch ist seit den Dramen und Theaterstücke der antiken Welt gewesen. Massenmedien wurde direkt von der Technologie getrieben, mit größerer Fortschritte in der Publishing-und Kommunikationstechniken, die zu noch größeren Publikum möglich erreicht wird. [NEWLINE] [NEWLINE] Ursprünglich nur Kommunikationsgeräte wie Radio, Zeitungen und Zeitschriften, Massenmedien umfasst nun angewendet Fernsehen, Filme, Musik, Paperback Bücher, Videospiele und das Internet. Mit dem Aufkommen dieser weltumspannenden Medientypen entstanden auch die Fähigkeit, die Massen wie nie zuvor, und nicht immer in einem guten Weg zu erreichen. Der Versuch, Bias oder Steuer große Mengen von Informationen, sei es durch schändlich Gesinnten Propaganda oder mehr unschuldige persönliche Meinung ist in Tatsachen eingespritzt wird, wird zu einem großen Problem für einige Regierungen und Organisationen, zu beschäftigen. Invasive Werbetechniken sind auch ein Nebenprodukt der Massenmedien, sehr zum Ärger der Verbraucher überall. Während die Nachricht kann sich lohnen, und es ist immer einfacher für die gemeinsame Person, ihre Ideen und Werke zu veröffentlichen, immer in der sintflutartigen Ausgabe von Informationen gehört, kann jetzt wirklich, wie der Suche nach dem sprichwörtlichen Nadel im Heuhaufen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE] [TAB] [TAB] ".. Die Geschwindigkeit der Kommunikation ist wunderbar anzuschauen ist es auch wahr, dass Geschwindigkeit kann die Verteilung der Informationen, die wir wissen, unwahr vermehren" [NEWLINE] [TAB] [TAB] - Edward R. Murrow [NEWLINE] [TAB] [TAB] [TAB]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Massenproduktion', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'Moderne Massenproduktion ist der Bau von großen Mengen standardisierter Produkte auf Montagelinien. Wichtige Zutaten für die Massenproduktion sind industrielle Werkzeugmaschinen, austauschbare Teile, wissenschaftliche Leitung, und Stromleistung. [NEWLINE] [NEWLINE] Die Massenproduktion wurde in den 1910er und 1920er Jahren von Henry Ford die Ford Motor Company, die Elektromotoren der gut eingeführt popularisiert bekannte Technik der Kette oder sequentielle Produktion. Ford gekauft oder entwickelt und gebaut Zweck Werkzeuge und Vorrichtungen Maschine. Alle diese Werkzeugmaschinen wurden systematisch in den Produktionsablauf angeordnet. Ford-Management im Zeitstudien und Experimente auf die Werksprozesse zu mechanisieren, die sich auf Arbeiter Bewegungen zu minimieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE] [TAB] [TAB] "Es gibt eine Regel für den Industriellen und das ist:. Machen Sie die beste Qualität der Waren möglich bei möglichst geringen Kosten, zahlt die höchsten Löhne möglich" [NEWLINE] [TAB] [TAB] - Henry Ford [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Ion Propulsion', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_DESC', 'Der Antrieb der Wahl für die Science-Fiction-Autoren hat sich der Antrieb der Wahl für Wissenschaftler und Ingenieure bei der NASA. Effizienten Einsatz von Brennstoff und elektrischer Energie der Ionenantriebssystem ermöglichen moderne Raumfahrzeuge, weiter zu reisen, schneller und billiger als jede andere Antriebstechnologie verfügbar. Ionentriebwerke sind derzeit für Stationkeeping auf Kommunikationssatelliten und für den Hauptantrieb für Raumsonden verwendet. Ionentriebwerke Ionen zu vertreiben, um Schub zu erzeugen und können höhere Raumschiff Spitzengeschwindigkeiten als alle anderen derzeit verfügbaren Rakete liefern. [NEWLINE] Ein Ion ist einfach ein Atom oder Molekül, das elektrisch geladen ist. In einem Ionentriebwerk, werden Ionen durch elektrostatische Kräfte beschleunigt. Die elektrischen Felder für die Beschleunigung verwendet werden, um Elektroden an dem stromabwärtigen Ende des Triebwerks angeordnet generiert. [NEWLINE] Moderne Ionentrieb Inertgase für Treibmittel. Die Mehrheit der Triebwerke verwenden Xenon, die chemisch inert, farblos, geruchlos, geschmacklos und ist. Das Treibmittel wird von dem stromabwärtigen Ende des Triebwerks eingespritzt und fließt in Richtung der stromaufwärts gelegenen Ende.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE] [TAB] [TAB] "Alle Zivilisationen werden entweder raumfahr oder ausgestorben sind." [NEWLINE] [TAB] [TAB] - Carl Sagan [NEWLINE] [TAB]', '', '');




UPDATE LoadedFile SET Value=1, DE_DE=1 Where Type='Research.sql';





