/* The sql commands and text below were formulated in the Stories tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1563932649
If you make any changes be sure to update the spreadsheet also.*/

/*  Terrain  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING', 'Fluss-Hochwasser', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_DESC', 'Häufige saisonalen Überschwemmungen des Flusses bieten ungewöhnlich fruchtbaren Mutterboden für die Landwirtschaft.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_1', 'Bezahlen Sie für neue Bewässerungskanäle entlang des Flusses.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_2', 'Erforschen Sie bessere Möglichkeiten, um Häuser vor Hochwasser zu schützen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_3', 'Lassen Sie die Einheimischen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_1', '[ICON_TEAM_3] Neue Fluss Bewässerung verbessert [ICON_FOOD] Nahrung für {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_2', '[ICON_TEAM_3] Neue [ICON_RESEARCH] Die Forschung ist im Gange, um die Bürger von {1} vor Hochwasser zu schützen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_3', '[ICON_TEAM_3] Neue Fluss Bewässerung verbessert [ICON_GOLD] Wirtschafts Einkommen für {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE', 'Wüste Adobe', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_DESC', 'Ein ungewöhnlich robuste und schöne Form der Ton adobe Bau wurde außerhalb entwickelt {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_1', 'Verwenden Sie den unverwechselbaren Stil, um unsere Kulturdenkmäler zu verbessern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_2', 'Verwenden Sie die Ziegel für die praktische Konstruktion.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_3', 'Lassen Sie die Einheimischen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_1', '[ICON_TEAM_3] Ein neuer Stil von Lehmziegeln verbessert die [ICON_CULTURE] Kultur von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_2', '[ICON_TEAM_3] Neuerungen in Adobe Bau verbessert [ICON_PRODUCTION] Produktion in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_3', '[ICON_TEAM_3] Eine neue Form der adobe Konstruktion verbessert die [ICON_GOLD] Economy in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS', 'Schnee-Schlitten', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_DESC', 'Innovationen im alpinen Gelände in der Nähe von Reise gemacht {2} mehr zugänglich.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_1', 'Mit den Schlitten für Freizeitrennen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_2', 'Mit den Schlitten, um neue Ressourcen zu nutzen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_3', 'Lassen Sie die Einheimischen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_1', '[ICON_TEAM_3] Innovationen im Schnee Schlitten aufgefordert, neue Rassen in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_2', '[ICON_TEAM_3] Innovationen im Schnee Schlitten eröffnet neue Ressourcen in der Nähe von {2}, um Ausbeutung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_3', '[ICON_TEAM_3] Innovationen im Schnee Schlitten verbessert die [ICON_GOLD] Economy in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE', 'Berghütte', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_DESC', 'Eine landschaftlich reizvolle Berggipfel in der Nähe von {2} ist ungewöhnlich für die menschliche Besiedlung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_1', 'Bauen Sie ein spiritueller Zufluchtsort für Ruhe und Meditation.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_2', 'Erstellen Sie eine wissenschaftliche Rückzug auf die Sterne und Jahreszeiten zu studieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_3', 'Lassen Sie die Einheimischen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_1', '[ICON_TEAM_3] Ein Berg spirituelle Zuflucht erhöht [ICON_CULTURE] Kultur in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_2', '[ICON_TEAM_3] Ein Berg wissenschaftlichen Rückzug erhöht [ICON_RESEARCH] Wissenschaft in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_3', '[ICON_TEAM_3] Händler verkaufen Waren an Besucher einer Bergspitze in der Nähe von {2}.', '', '');
/*  Erweiterungen  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING', 'Gewerbe-Landwirtschaft', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_DESC', 'Vermögende Privatpersonen planen, zu kaufen und zu vermarkten kleinen Farmen in der Nähe von {2}, es sei denn, die Bauern können ihre Einnahmen zu erhöhen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_1', 'Investieren Sie in eine Kultur der traditionellen Landwirtschaft.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_2', 'Stützen Sie die Zusammenschlüsse mit eigenen Anreizen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_3', 'Lassen Sie die Einkäufe ohne Störungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_1', '[ICON_TEAM_3] Traditionelle Bauern sind ein starker Teil der [ICON_CULTURE] Kultur in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_2', '[ICON_TEAM_3] Kommerzialisierung verbessert farm [ICON_FOOD] Essen in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_3', '[ICON_TEAM_3] Buyouts verbessert farm [ICON_GOLD] in der Nähe von Gold-{2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION', 'Minenerweiterungs', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_DESC', 'Minenbetreiber in der Nähe von {2} entdeckt wertvolle Erz, aber die Arbeiter protestieren gegen gefährliche Bedingungen in den neuen Zweig Wellen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_1', 'Geben nationale Unterstützung zu mir Sicherheit zu verbessern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_2', 'Verwendung eigener Mittel, um Streikbrecher zu mieten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_3', 'Lassen Sie die Minenbetreiber umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_1', '[ICON_TEAM_3] Bergleute in der Nähe von {2} sind [ICON_HAPPINESS_1] über die sicherere Arbeitsbedingungen Happy.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_2', '[ICON_TEAM_3] Rasch endet ein Streik von {2} ''s Mine erweitert [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_3', '[ICON_TEAM_3] Ein Bergwerk in der Nähe von {2} entdeckte eine [ICON_GOLD] Profitable neue Erzadern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS', 'Dorf Proteste', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_DESC', 'Bürgerinnen und Bürger in einem Dorf in der Nähe von {2} werden unter hohem Armut und Kriminalität zu kämpfen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_1', 'Verbesserung der Bildung für die Armen, für bessere Arbeit zu qualifizieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_2', 'Verbessern Sie die Polizei zu niedrigeren Kriminalitätsraten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_3', 'Lassen Sie das Dorf Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_1', '[ICON_TEAM_3] Ein Dorf in der Nähe von {2} verbessert [ICON_RESEARCH] Bildung für die Armen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_2', '[ICON_TEAM_3] Dorfbewohner in der Nähe von {2} sind [ICON_HAPPINESS_1] über geringere Kriminalitätsraten Happy.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_3', '[ICON_TEAM_3] Eine stärkere Präsenz der Polizei verbessert die [ICON_GOLD] Wirtschaft eines Dorfes in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND', 'Plantation-Demand', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_DESC', 'Die Nachfrage steigt für die Kulturen von einer Plantage in der Nähe von {2}, in denen die Arbeitnehmer Ernte der Felder für niedrige Löhne.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_1', 'Gesetze zu erlassen, um Löhne und Arbeitsbedingungen für die Arbeitnehmer zu verbessern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_2', 'Niederhandelsbarrieren, um die Exportwirtschaft zu stärken.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_3', 'Lassen Sie die Plantagenbesitzer umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_1', '[ICON_TEAM_3]-Plantage in der Nähe von Pflücker {2} sind [ICON_HAPPINESS_1] über bessere Arbeitsbedingungen Happy.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_2', '[ICON_TEAM_3] Untere Handelsschranken verbessert plantation [ICON_FOOD] Essen in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_3', '[ICON_TEAM_3] Steigende Nachfrage verbesserte Plantage [ICON_GOLD] Erträge in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS', 'Exotische Tiere Camp', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_DESC', 'Exotische Tiere wurden außerhalb des Lagers in der Nähe von {2} entdeckt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_1', 'Erstelle ein Tier zu erhalten, um den Tourismus zu verbessern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_2', 'Bauen Sie sich ein extravagantes Jagdschloss.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_3', 'Lassen Sie die Einheimischen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_1', '[ICON_TEAM_3] Ein exotischer Natur zu bewahren verbesserte Tourismus [ICON_CULTURE] Kultur in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_2', '[ICON_TEAM_3] Ein Jagdschloss erhöht [ICON_FOOD] Essen von exotischen Tieren in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_3', '[ICON_TEAM_3] Exotische Tiere in der Nähe von {2} entdeckt verbessert Jagd [ICON_GOLD] Gold.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY', 'Qualität Steinbruch', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_DESC', '{2} Ein ungewöhnlich hoher Qualität Rock Vene wurde im Steinbruch außerhalb entdeckt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_1', 'Vermietung Handwerker bis hin zu Skulpturen aus dem Fels Handwerk.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_2', 'Fonds zusätzliche Maschinen zu beschleunigen Bergbau.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_3', 'Lassen Sie den Steinbruch-Manager umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_1', '[ICON_TEAM_3] Magnificent Skulpturen verbessert [ICON_CULTURE] Kultur in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_2', '[ICON_TEAM_3] Ein Steinbruch in der Nähe von {2} erweitert [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_3', '[ICON_TEAM_3] Ein Steinbruch in der Nähe von {2} entdeckte eine [ICON_GOLD] Profitable Rock Vene.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER', 'Exotische Lumber', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_DESC', '{2} Exotische Bäume wurden in der Nähe der lumbermill außerhalb entdeckt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_1', 'Erstellen Sie einen Nationalpark für den Tourismus zu verbessern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_2', 'Erstellen Sie neue Infrastruktur für Holzexporte.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_3', 'Lassen Sie das Holzgeschäft umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_1', '[ICON_TEAM_3] Eine exotische Nationalpark verbessert Tourismus [ICON_CULTURE] Kultur in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_2', '[ICON_TEAM_3] Umfangreiche [ICON_PRODUCTION] Produktionsinfrastruktur in der Nähe von {2} exportiert wertvollen Bäumen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_3', '[ICON_TEAM_3] Exotische Bäume in der Nähe {2} verbessert Holz [ICON_PRODUCTION] Gewinne entdeckt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING', 'Weidezaun', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_DESC', 'Die Landwirte in der Nähe von {2} will Zäune zu bauen, um Vieh draußen zu halten, aber Viehzüchter besorgt über den Verlust von Weideland sind.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_1', 'Unterstützen Sie die Bemühungen der Landwirte, Zaun das Land.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_2', 'Unterstützen Sie die Bemühungen der Viehzüchter, einen offenen Bereich zu halten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_3', 'Lassen Sie die lokalen Bürger umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_1', '[ICON_TEAM_3] Fechten eine Weide in der Nähe von {2} verbessert [ICON_FOOD] Lebensmittel aus umliegenden Felder.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_2', '[ICON_TEAM_3] Ranchers in der Nähe von {2} erhöht [ICON_PRODUCTION] Herstellung von einem offenen Bereich.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_3', '[ICON_TEAM_3] Ein Kompromiss zwischen Viehzüchtern und Bauern in der Nähe von {2} verbessert die lokale [ICON_PRODUCTION] Economy.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND', 'Angeln Nachfrage', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_DESC', 'Die Nachfrage steigt für das marine Leben in den Meeren in der Nähe von {2} gefunden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_1', 'Baue eine Stadt Aquarium für Bürger, um die exotischen Meeresbewohner zu sehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_2', 'Bauen Infrastruktur, um die lokalen Fischindustrie zu erweitern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_3', 'Lassen Sie die lokale Fischerei umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_1', '[ICON_TEAM_3] Ein Aquarium von seltenen Meereslebewesen erhöht Kultur in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_2', '[ICON_TEAM_3] Fischer in der Nähe von {2} erweitert [ICON_FOOD] Essen ausgegeben.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_3', '[ICON_TEAM_3] Seltene Meeresleben in der Nähe von {2} verbessert [ICON_GOLD] Gold-vom Fischfang.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION', 'Nun Expansion', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_DESC', 'Ein Öl-Unternehmen will in der Nähe erweitern {2}, aber die Tourismusbranche besorgt über Auswirkungen auf die Landschaft ist.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_1', 'Unterstützen Sie das Tourismus-Geschäft mit einer neuen nationalen Denkmal.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_2', 'Unterstützen Öl-Entwicklung mit neuen Straßen und Infrastruktur.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_3', 'Lassen Sie die Unternehmen damit umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_1', '[ICON_TEAM_3] Ein Denkmal für schöne Land in der Nähe von {2} Verbesserungen im Tourismus [ICON_CULTURE] Kultur.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_2', '[ICON_TEAM_3] Neue Infrastruktur ausgebaut Öl [ICON_PRODUCTION] Produktion in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_3', '[ICON_TEAM_3] Öl [ICON_GOLD] Gewinne erhöht in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING', 'Plattform für Entsorgung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_DESC', 'Mehrere Offshore-Plattformen im Ölfeld in der Nähe von {2} erschöpft ihre Ölversorgung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_1', 'Unterstützen Sie die kommerzielle Fischerei durch die Umwandlung der Rigs in künstliche Riffe.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_2', 'Die Demontage und Wiederverwendung von Komponenten für die Anlagen an anderer Stelle im Ölfeld.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_3', 'Lassen Sie das Unternehmen damit umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_1', '[ICON_TEAM_3] Ölplattformen, um künstliche Riffe verbessert Angeln [ICON_FOOD] Essen in der Nähe von {2} umgewandelt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_2', '[ICON_TEAM_3] Weiternutzung erschöpft Bohrinsel Komponenten verbessert [ICON_PRODUCTION] Produktion in der Nähe von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_3', '[ICON_TEAM_3] Verkauf stillgelegten Ölplattformen angehoben [ICON_GOLD] in der Nähe von Gold-{2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION', 'Fort Expansion', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_DESC', 'Die allgemeine, die für die Festung in der Nähe von {2} will Neubau Bemühungen starten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_1', 'Erforschen Sie neue militärische Technologien auf der Festung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_2', 'Aktualisieren Sie die defensiven Fähigkeiten des Forts in eine Zitadelle.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_3', 'Lassen Sie die allgemeinen umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_1', '[ICON_GOLD] Gold: 6', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_2', 'Die Festung wird zum Citadel.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_1', '[ICON_TEAM_3] Ein Fort in der Nähe von {2} erweitert Personal-und Forschungseinrichtungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_2', '[ICON_TEAM_3] Ein Fort in der Nähe von {2} zu einer Zitadelle ausgebaut.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_3', '[ICON_TEAM_3] Ein Hersteller in der Nähe einer Festung außerhalb von {2} verkauft neue Waffentechnologien.', '', '');
/*  GEBÄUDE  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM', 'Getreidespeicher Bevölkerung Boom', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_DESC', 'Verbesserungen an der Getreidespeicher in {2} ziehen die Bürger der Stadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_1', 'Bereitstellung von Mitteln für die Bürger, um einen neuen Platz zum Leben zu finden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_2', 'Vermietung Bürger für ein Programm öffentlicher Arbeiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_1', '[ICON_TEAM_2] Siedler: +1', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_2', '[ICON_TEAM_2] Arbeiter: 2', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_1', '[ICON_TEAM_3] Die Regierung von {2} finanziert eine neue Siedlung Programm.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_2', '[ICON_TEAM_3] Die Regierung von {2} finanziert ein neues Programm für öffentliche Arbeiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_3', '[ICON_TEAM_3] Bevölkerung boomt in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT', 'Smithy Entwicklung', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_DESC', 'Eine neue, von der Schmiede in {2} entwickelten Schmelzprozess ist potenziell gefährlich für die Arbeitnehmer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_1', 'Fund Research der Prozess sicherer zu machen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_2', 'Rohstoffe senden, sofort legte das Verfahren in die Produktion.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_1', '[ICON_TEAM_3] Umfangreiche [ICON_RESEARCH] Forschung ist im Gange, um eine sicherere Schmelzprozess in {2} erstellen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_2', '[ICON_TEAM_3] Ein neuer Schmelzprozess wurde schnell in [ICON_PRODUCTION] Produktion in {2} setzen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_3', '[ICON_TEAM_3] Ein neuer Schmelzprozess verbessert [ICON_GOLD] Gewinne in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY', 'Markt Monopoly', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_DESC', 'Ein Business bietet großen Spenden an den örtlichen Schulen ist ein Monopol auf dem Markt in {2} bilden, treibt die Preise.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_1', 'Brechen Sie das Monopol, um die Preise zu senken.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_2', 'Unterstützung der Bildungs-Spenden mit eigenen Anreizen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_3', 'Sammeln Sie Steuern auf die höhere Gewinne.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_1', '[ICON_TEAM_3] Die Bürger in {2} sind [ICON_HAPPINESS_1] Glücklich, da die Preise sinken.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_2', '[ICON_TEAM_3] Ein neues Monopol in {2} spendet stark auf [ICON_RESEARCH] Bildung.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_3', '[ICON_TEAM_3] Ein Monopol auf {2} ''s Markt erhöht [ICON_GOLD] Gold-Gewinne.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY', 'Bibliothek Kontroverse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_DESC', 'Ein umstrittenes Buch über Rassismus in der Geschichte der {2} ist Funkenbildung Unruhen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_1', 'Fonds tieferen Erforschung turbulente Vergangenheit der Stadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_2', 'Verbot des Buches, bis die Unruhen verblassen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_3', 'Dies sollte Buchverkäufe zu erhöhen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] Ein umstrittenes Buch beginnt weitere [ICON_RESEARCH] Forschung in die Geschichte der {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Aufstände in {2} verblassen als Buch verursacht [ICON_HAPPINESS_4] Wut verboten wurde.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] Ein umstrittenes Buch ist [ICON_GOLD] Verkauf gut in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY', 'Monument Kontroverse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_DESC', 'Die Bürger in {2} protestieren gegen eine alte Denkmal für die imperialistische Expansion.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_1', 'Geben Sie Reden für eine friedliche Kultur.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_2', 'Verteilen Propaganda unterstützt militaristische Expansion.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] Ruhige [ICON_CULTURE] Kultur Demonstrationen fegen durch {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Propaganda in {2} reduziert [ICON_HAPPINESS_4] Wut über den Imperialismus.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] Ein umstrittenes Denkmal ist die Verbesserung des Tourismus [ICON_GOLD] Wirtschaft in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS', 'Walled Slums', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_DESC', 'Entwicklung von {2} jenseits der alten Stadtmauer erweitert, wobei die inneren Bezirke Verschlechterung zu Slums.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_1', 'Beleben Sie die alte Stadt mit kulturellen Programmen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_2', 'Reißt die Slums, um Platz für produzierende Unternehmen zu machen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_1', '[ICON_TEAM_3] Die Innenstadt von {2} belebt seine [ICON_CULTURE] Kultur.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_2', '[ICON_TEAM_3] Slums in {2} gelöscht Raum für [ICON_PRODUCTION] Produktive Unternehmen abgerissen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_3', '[ICON_TEAM_3] Neue Unternehmen erhöht [ICON_GOLD] Gold-Umsätze in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT', 'Kaserne Recruitment', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_DESC', 'Die Bürger von {2} sind wütend über die Wehrpflicht gezwungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_1', 'Nieder Wehrpflicht Raten in der Stadt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_2', 'Investieren Sie in bundesweiten Propaganda Militäreinberufung zu erhöhen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_TIP_2', '[ICON_WAR] Neue Militäreinheiten: 2', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_1', '[ICON_TEAM_3] Die Reduzierung der Wehrpflicht Raten gesenkt [ICON_HAPPINESS_4] Anger in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_2', '[ICON_TEAM_3] Eine Kaserne in {2} worben neue Militärpersonal.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_3', '[ICON_TEAM_3] War Propaganda Bindung verbessert [ICON_GOLD] Umsatz in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE', 'Colosseum Teilnahme', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_DESC', 'Das Kolosseum in {2} zieht Rekord-Massen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_1', 'Zeigen aufwendigen Auswahlverfahren, um die Öffentlichkeit zu unterhalten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_2', 'Moderator massiven zeigt der patriotischen Propaganda.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_1', '[ICON_TEAM_3] Wettbewerbe zu gewinnen [ICON_HAPPINESS_1] Glückliche Menschenmassen in der {2} Kolosseum.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_2', '[ICON_TEAM_3] Das Kolosseum von {2} Gastgeber massiven Shows [ICON_CULTURE] Kultur Propaganda.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_3', '[ICON_TEAM_3] Verbesserungen an der {2} Kolosseum erhöht [ICON_GOLD] Gold-Einnahmen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED', 'Stabile Rasse', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_DESC', 'Die Ställe in {2} hob eine ungewöhnlich agil, stark und zuversichtlich Pferderasse.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_1', 'Trainieren Sie für Pferderennen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_2', 'Trainieren sie als Kriegspferde.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_3', 'Lassen Sie die stabilen Eigentümer zu entscheiden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_TIP_2', '[ICON_WAR] Neue Reiteinheiten: 2', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_1', '[ICON_TEAM_3] Eine neue Generation von Rennpferd verbessert [ICON_HAPPINESS_1] Glück in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_2', '[ICON_TEAM_3] Das Militär von {2} hob eine neue Art von Krieg Pferde.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_3', '[ICON_TEAM_3] Eine neue Pferderasse verbessert [ICON_GOLD] Umsatz in {2}.', '', '');
/*  CITYSTATES  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION', 'Stadtstaat Immigration', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_DESC', 'Einige Arbeiter fühlen letzten Einwanderer aus dem Stadtstaat {2} sind die Jobs weg von den Bürgern Ihrer Zivilisation.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_1', 'Pay-Programme, die den Immigranten die Staatsbürgerschaft zu geben, einen Weg.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_2', 'Verbannen Sie die Einwanderer und ihre Häuser zu beschlagnahmen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_3', 'Denunzieren ethnischen Stereotypen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_1', '[ICON_INFLUENCE] Einfluss: 70', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_2', '[ICON_INFLUENCE] Einfluss: -70 [NEWLINE] [ICON_GOLD] Gold: 200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_3', '[ICON_INFLUENCE] Einfluss: 10', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_1', '[ICON_TEAM_3] Einwanderer aus {2} gewinnen Sie einen Weg zur Staatsbürgerschaft im Reich von {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_2', '[ICON_TEAM_3] Die Regierung von {1} {deportiert Einwanderer aus 2_target).', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_3', '[ICON_TEAM_3] Die Regierung von {1} denunziert Stereotypen über die Bürger von {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE', 'Geldwechsel', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_DESC', 'Der Wert Ihrer Währung steigt, und die daraus resultierende Ungleichgewicht im Handel Risiken verletzen Exporte nach {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_1', 'Stellen Sie einen festen Wechselkurs zu ermöglichen Exporte weiterhin ungehindert.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_2', 'Gesetze zu erlassen, um Ihre Währung weiter zu stärken, auf Kosten des Citystate.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_3', 'Lassen Sie Ihren Finanzminister behandeln dieses Thema.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_1', '[ICON_INFLUENCE] Einfluss: 70', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_2', '[ICON_INFLUENCE] Einfluss: -70 [NEWLINE] [ICON_GOLD] Gold: 200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_3', '[ICON_INFLUENCE] Einfluss: 10', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_1', '[ICON_TEAM_3] Ein fester Wechselkurs verbessert die Exporte aus um {1} {2}, die Förderung [ICON_INFLUENCE] Beziehungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_2', '[ICON_TEAM_3] Die Währung von {1} stieg dramatisch an Wert, wodurch [ICON_GOLD] Gold bei Kosten von {2} ''s Wirtschaft.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_3', '[ICON_TEAM_3] Änderungen in {1} ''s Wechselkurs verbessert die Ausfuhren in {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT', 'Diplomatischen Zwischenfall', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_DESC', 'Während eines Besuchs in {2} Sie eine schwere Fauxpas während einer diplomatischen Ereignis begangen, aufgrund eines kulturellen Missverständnis.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_1', 'Senden Sie Geschenke und eine offizielle Entschuldigung für den Fehler und verspricht es nie wieder geschehen zu lassen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_2', 'Erklären Sie die Aktionen in eurer Gesellschaft akzeptabel ist, und Sie werden nicht für die Wurzeln Ihrer Zivilisation zu entschuldigen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_3', 'Lassen Sie Ihre Diplomaten behandeln dieses Thema.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_1', '[ICON_INFLUENCE] Einfluss: +70 [NEWLINE] [ICON_CULTURE] Kultur: -200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_2', '[ICON_INFLUENCE] Einfluss: -70 [NEWLINE] [ICON_CULTURE] Kultur: 200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_3', '[ICON_INFLUENCE] Einfluss: 10', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_1', '[ICON_TEAM_3] Eine Entschuldigung nach einem diplomatischen Zwischenfall verbessert [ICON_INFLUENCE] Beziehungen zwischen {1} und {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_2', '[ICON_TEAM_3] Weigerung, für den Eigenheiten von {1} ''s [ICON_CULTURE] Kultur entschuldigen führte zu einem diplomatischen Zwischenfall mit {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_3', '[ICON_TEAM_3] Ein diplomatischen Zwischenfall von {1} bei einem Besuch in {2} dazu beigetragen, das kulturelle Verständnis zwischen den beiden Nationen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME', 'Scholastic Ruhm', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_DESC', 'Die Anmeldung zu angesehenen Schulen in Ihr Reich studieren in die Höhe von ausländischen Studenten der {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_1', 'Entspannen Einwanderungsbeschränkungen für Studenten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_2', 'Beschränken Sie die Registrierung auf der eigenen Studierenden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_3', 'Lassen Schule Dekane, dies zu umgehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_1', '[ICON_INFLUENCE] Einfluss: +70 [NEWLINE] [ICON_RESEARCH] Wissenschaft: -200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_2', '[ICON_INFLUENCE] Einfluss: -70 [NEWLINE] [ICON_RESEARCH] Wissenschaft: 200', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_3', '[ICON_INFLUENCE] Einfluss: 10', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_1', '[ICON_TEAM_3] Die Qualität der Ausbildung, ausländische Studenten aus {2} verbessert [ICON_INFLUENCE] Beziehungen zu {1} angeboten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_2', '[ICON_TEAM_3] Neue [ICON_RESEARCH] Schulgesetze begünstigen inländische Studierende von {1} über Einwanderer aus {2}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_3', '[ICON_TEAM_3] Ausländische Studenten aus {2} strömen in Schulen von {1}.', '', '');
/*  Einheiten  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR', 'Scout Retter', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_DESC', 'Ihr Scout rettete das Kind einer Nomadenhäuptling von einer tödlichen Bestie. Die dankbaren Jäger bieten Ihnen Gastfreundschaft in ihrem Lager.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_1', 'Stellen Sie ein paar Nomaden zur Erkundung beizutreten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_2', 'Zug zu schnell mit Jagdbögen zu bewegen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_3', 'Seien Sie auf dem Camp für eine Weile.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_1', 'Duplikate und heilt der Scout.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_2', 'Ersetzt mit einem Bogenschützen, die schnell bewegt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_3', 'Die Scout heilt und Gewinne 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_1', '[ICON_TEAM_3] A {2} {1} trat von einem Stamm der Nomaden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_2', '[ICON_TEAM_3] A {2} von {1} gelernt, Jagdbögen zu verwenden.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_3', '[ICON_TEAM_3] A {2} von {1} ausgeruht nach dem Speichern ein Nomaden Kind.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES', 'Scout Stories', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_DESC', 'Ihr Scout reiste weit und breit, trotzten zahlreiche Gefahren und entdecken viele wunderbare Länder. Die Bürger der Ihr Kapital sind gespannt auf die Geschichten zu hören.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_1', 'Mieten Sie sich ein Schriftsteller zu epischen Gedichte von ihren Reisen Handwerk.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_2', 'Geben Sie den Scout mit neuen Trainings-und neue Waffen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_3', 'Lassen Sie den Scout, um ihre Geschichten zu erzählen, dann weiterziehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_1', '[ICON_CULTURE] Kultur: 100', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_2', 'Heilt und Upgrades zu einem Sentinel.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_3', '[ICON_CULTURE] Kultur: +30', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_1', '[ICON_TEAM_3] epische Gedichte von einem Scout Reisen erhöht die [ICON_CULTURE] Kultur von {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_2', '[ICON_TEAM_3] Ein Scout von {1}, neue Rüstungen und Waffen aufgerüstet.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_3', '[ICON_TEAM_3] Geschichten von einem Scout Reisen erhöht die [ICON_CULTURE] Kultur von {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR', 'Renommierte Krieger', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_DESC', 'Ihre Krieger sind an Popularität gewinnt in Ihr Reich, mit Geschichten über ihre Tapferkeit gesungen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_1', 'Lassen Sie sie in das zivile Leben zurückzukehren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_2', 'Schicken Sie ihnen neue Waffen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_3', 'Schicken Sie sie Nachschub.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_1', 'Konvertiert in ein Arbeitnehmer, der Gelände Kosten ignoriert.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_2', 'Wird in ein Schwertkämpfer.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_3', 'Heilt und Gewinne 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_1', '[ICON_TEAM_3] Krieger von {1} wieder in das zivile Leben.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_2', '[ICON_TEAM_3] Krieger von {1} erhalten neue Waffen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_3', '[ICON_TEAM_3] Krieger von {1} erhalten Nachschub.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER', 'Renommierte Archer', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_DESC', 'Ihre Bogenschützen sind an Popularität gewinnt in Ihr Reich, mit Geschichten über ihre Treffsicherheit erzählt.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_1', 'Lassen Sie sie ins Zivilleben zurückziehen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_2', 'Schicken Sie ihnen neue Waffen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_3', 'Schicken Sie sie Nachschub.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_1', 'Konvertiert in ein Arbeitnehmer, der Gelände Kosten ignoriert.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_2', 'Wird in ein Composite-Bowman.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_3', 'Heilt und Gewinne 5 [ICON_WAR] Experience.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_1', '[ICON_TEAM_3] Bogenschützen von {1} in das zivile Leben zurück.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_2', '[ICON_TEAM_3] Bogenschützen von {1} erhalten neue Waffen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_3', '[ICON_TEAM_3] Bogenschützen von {1} erhalten Nachschub.', '', '');
/*  CUSTOM  */
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB', 'Land Grab', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_DESC', 'Die Bürger von {2} fordern besseres Land zu arbeiten.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_1', 'Bezahlen Sie auf mehr Land in das Reich zu annektieren.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_2', 'Wehrpflichtige die Dissidenten und legte sie an die Arbeit.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_3', 'Lassen Sie die Bürgermeister umgehen', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_1', '[ICON_TEAM_6] Neue Fliesen: 3', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_2', '[ICON_TEAM_2] Neuer Mitarbeiter: 1', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_3', '[ICON_TEAM_6] Neue Fliesen: 1', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_1', '[ICON_TEAM_3] Bürger von {2} im Anhang eine große Neuland.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_2', '[ICON_TEAM_3] Dissidenten in {2} wurden der Belegschaft einberufen.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_3', '[ICON_TEAM_3] Bürger von {2} arbeiten neu beigefügt Land.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES', 'Barbarian Mercenaries', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_DESC', 'Eine Gruppe von feindlichen Angreifer auf Ihrem Grenzen könnten die Seiten zu wechseln - für einen Preis.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_1', 'Mieten Sie für Ihre zivile Mitarbeiter.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_2', 'Mieten sie als militärische Söldner.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_3', 'Ambush die Verräter und ihre Vorräte zu plündern.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_1', '[ICON_TEAM_2] Neue Arbeiter: 1', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_2', '[ICON_TEAM_2] Neue Militäreinheiten: 2', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_3', '[ICON_GOLD] Gold: 25', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_1', '[ICON_TEAM_3] Barbaren trat der zivilen Mitarbeiter von {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_2', '[ICON_TEAM_3] Barbarian Söldner trat in die Armee von {1}.', '', '');
REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_3', '[ICON_TEAM_3] Barbarian Söldner wurden von {1} in einen Hinterhalt.', '', '');







UPDATE Loaded File SET Value=1, DE_DE=1 Where Type='Stories.sql';


