/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Cechy  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Otrzymasz dodatkowe Spy. Wielcy generałowie patrz dalej i dać więcej siły. [NEWLINE] Uruchamia z Warrior i Wielkiej Generalnego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Przydział', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Twój kapitał zyskuje bezpłatną silną kopię każdej nowej linii jednostkowej Ci badawczych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Jednostki poruszają się szybciej wzdłuż rzek i rozpocząć promocję Amphibious.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' +10% [ICON_GREAT_PEOPLE] Wielka Stopa z każdego ludzie Sojuszu i +20% [ICON_STRENGTH] Walka vs cywilizacji z kilku miast.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Wojownicy i awangardy kosztują 50% mniej konserwacji. Wszystkie urządzenia wymagają 25% mniej doświadczenia, aby zarobić na kolejny awans.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Produkcja w kierunku budynków, które już istnieją w [ICON_CAPITAL] Capital. Rozpoczyna się [ICON_RES_IRON] Żelazo w pierwszych 5 miastach.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', '25% wyższe zyski z zaprzyjaźnionych i sprzymierzonych Miasta-Państwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Hellenizacja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' +2 [ICON_CULTURE] Kultura w każdym mieście. Miasto-państwo [ICON_INFLUENCE] Wpływ degraduje w połowie i odzyskuje na dwukrotność normalnej stawki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Wewnętrzne szlaki handlowe zapewniają 10 [ICON_GOLD] złota do miejsca przeznaczenia.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Zyski [ICON_CULTURE] Kultura od zabijania wrogich jednostek.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' +50% [ICON_CULTURE] Kultura i +1 [ICON_MOVES] Ruch w czasie [ICON_GOLDEN_AGE] złotych wieków. [NEWLINE] rozpoczyna się od unikalnej Spearmana.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' +1 [ICON_PEACE] Wiara z nieutwardzonych lasów i dżungli, a 150% z naturalnych cudów rentowności. [NEWLINE] Rozpoczyna się Spearmana.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Uszkodzone jednostki walczyć w pełni sił. Łodzie rybackie i Isles dać [ICON_CULTURE] Kultura.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Gao Milicji', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Jednostki Vanguard patrz dalej i szybciej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Jednostki poruszają się szybciej na Hills. Drogi i koleje koszt konserwacji na wzgórzach; pół kosztować gdzie indziej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Cywile szybciej w pustyni. Wychodzące szlaki handlowe z różnymi cywilizacjami zarobić więcej [ICON_GOLD] Gold i [ICON_CULTURE] kultura, i przychodzących szlaki handlowe zarabiają więcej [ICON_GOLD] przez właściciela drogi.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Szybszy ruch w lasach i dżungli, które liczą się jako drogi w terenie dziećmi po badaniu koła. [NEWLINE] Uruchamia z unikalnym Swordsman.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Wielcy naukowcy wydają 25% szybciej, a otrzymasz jeden w Piśmie. [NEWLINE] Rozpoczyna się Bowman.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert Przyczepa', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Jednostki poruszają się szybciej na pustyni, karawany dotrzeć dalej, i religia szlaki handlowe rozprzestrzeniać szybciej od swoich miastach.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'Po zbadaniu teologii, otrzymasz bonus wspaniały człowiek na końcu każdego cyklu kalendarza Majów: Long Count (co 394 lat). [NEWLINE] Uruchamia z unikalnym Archer.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Każdy wzrost luksus zasobów [ICON_GOLD] dochód złota o 5%.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' +20% [ICON_PRODUCTION] Produkcja w kierunku budowy Wonder.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' +30 [ICON_WAR] Doświadczenie dla statków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Wybierz jedną Wieży niż normalnie, gdy znaleźli religię.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Porty uzyskać bezpłatną Harbor, a jednostki mogą przekroczyć góry. Rozpoczyna się z żeglarstwem, a Bireme i wojownika.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Gospodarki planowej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Jednostki patrz dalej, cywile szybciej i zyskujesz 1 mniej [ICON_HAPPINESS_4] Narodowy nieszczęście na miasto.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Budynki żywności dodać 1 [ICON_CITIZEN] Ludność gdy zbudowane. [NEWLINE] Uruchamia z pracownikiem.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Obozy barbarzyńców poddać, gdy pokonał dwuosobowego [ICON_GOLD] Gold. [NEWLINE] Uruchamia z koniem Archer.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'American Dream', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Imigranci przenieść tutaj z cywilizacjami z niskim szczęścia i wysokiej amerykańskich wpływów kultury. Twoje obywatele migrują wzdłuż wewnętrznych [ICON_FOOD] szlaków handlowych Żywności.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Dynastii', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' +2 [ICON_RESEARCH] Nauka z gospodarstw. [NEWLINE] Uruchamia z pracownikiem.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Podwójne plony z naturalnych cudów, plus 100 [ICON_GOLD], gdy odkrył. [NEWLINE] Rozpoczyna się Scout, i otrzymuje Caravel w kompas.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Hanzy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Podwójna ilość od strategiczne zasoby i 3 dodatkowych głosów w Światowym Kongresie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Szybsze i silniejsze wsiadania całej wody, a wręcz jednostki plądrować szybciej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terror', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'Miasta-państwa można tyranem poddać w obawie jak marionetki. Zamontowane i jednostek potyczki szybciej. Rozpoczyna się Scout.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Hołd', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Wewnętrzne szlaki handlowe między miastami zapewniają 10 [ICON_GOLD] złota do miejsca przeznaczenia.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Rekonkwista', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Podbój miasta zwiększa [ICON_PEACE] Faith.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Plaga Boga', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Obozy barbarzyńców poddać, gdy pokonany, a jednostki lądowe kosztować mniej [ICON_GOLD] konserwacji. [NEWLINE] Uruchamia z koniem Archer.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Plaga Boga', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Obozy barbarzyńców poddać, gdy pokonany, a jednostki lądowe kosztować mniej [ICON_GOLD] konserwacji. [NEWLINE] Uruchamia z unikalnym Chariot.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Amsterdam giełda', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' +5% [ICON_GOLD] Dochód Narodowy z każdego typu Luxury zasobu można sterować lub importu.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] obywatel migracji od {1} do {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] imigrant z {1} przybył do {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] obywatel wyemigrował z {1} z {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Ty zdobyte {1} {2} {3} od przechwycenia {4}!', '', '');


/*  Jednostki  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Wojska cesarskie-Royal Mountain', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Nowoczesne urządzenie Era że tylko Austriacy mogą budować. Jest mocniejszy i dodał, że regularne promocje Urządzenie nie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Urządzenie to ma potężne zalety w każdym terenie zimnej pogody. Walka w Tundra, śnieg, wzgórza, a nawet Góry.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'The Troops Imperial-Royal Mountain (niem. Kaiserlich-Königlich Gebirgstruppe). Został założony w 1906 roku jako część austriacki Landwehr, armii terytorialnej Cisleithanian połowie Austro-Węgier [NEWLINE] Propozycja w memorandum przez Konrada von Hötzendorf , w lutym 1906 roku Ministerstwo Wojny w Wiedniu zwołał sesję na Alpine bezpieczeństwa granic. Feldmarszałek Tunk, zgodził się z nim i przedstawił koncepcję, której podstawy zostały następnie zrealizowane. [NEWLINE] Istniejące pułki strzeleckie państwowe miały być przeszkoleni, jak oddziały górskie, a wraz z przygranicznych firm i służb patrolowych landszturmu żandarmerii były do stanowią trzon sił obrony terytorialnej z lokalnej wiedzy na granicy Tyrolu [NEWLINE] [NEWLINE] Bataliony i firmy miały juczne zwierzęta i zostały wydane z dodatkowego sprzętu dostosowanego do wymogów walki górskich;. tym narty, liny, raki i czekany. Pułki zostały wzmocnione przez część pistoletu maszynowego góra czterech karabinów maszynowych, które w celu poprawy mobilności, mogą być przenoszone przez zwierzęta juczne lub manportable opakowaniach na najwyższych wysokościach. To samo stosuje się do startu, poza pistoletami górskich. Przenośne piece polowe (Schwarmöfen) i ogrzewane namioty wspiera żołnierzy do pracy w niesprzyjających warunkach. [NEWLINE] Po nartach dwa podejścia kij zastąpił metodę pojedynczego kija. Wiążące Bilgeri było wiązanie skitourowe, które mogą być używane z normalnego buta turystycznego. Karabin został zastąpiony (krótszym) 8mm Mannlicher M 95 karabinek.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unikalne Songhai zamontowane urządzenia. Mandekalu Kawalerii rozpoczyna z promocją Siege, w przeciwieństwie do rycerza, który zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Potężny średniowieczny żołnierz unikalny do Japończyków. Samuraj może atakować dwa razy na turę, i są silniejsze niż Longswordsmen ich zastąpić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unikalne urządzenie babiloński łucznik. Bowman jest silniejsza niż Archera, który zastępuje, a szybciej w pustynie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Żołnierz średniowiecznej epoki wyjątkowej Danii. Berserker rozpoczyna z promocją opłat, w przeciwieństwie do Longswordsman zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Ruchoma unikalny do Niemiec. Panzer ma większą wytrzymałość, szybkość i przejrzystość niż zbiornik, który zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Wczesnego gry żołnierza unikalny Azteków. Jaguar leczy obrażenia, gdy zabija wroga i walczy w dżungli bardziej skutecznie niż wojownika, który zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard Jednostka unikalna Amerykanom. Jest silniejszy niż Skirmisher zastępuje, widzi dalej, i porusza się szybciej w trudnym terenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'Jedną z pierwszych jednostek prochu gry, unikalnych dla Francuzów. Muszkieterowie mają premię bojową poza terytorium dziećmi, w przeciwieństwie do Musketman zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Żołnierz unikalne dla Irokezów. Mohawk Wojownik walczy silniejszy w lesie i dżungli niż szermierz, który zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Żołnierz unikalne dla Turków. Janissary jest znacznie silniejszy w ataku i leczy po zabitych, w przeciwieństwie do Musketman zastępuje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Jednostki odległości 1 płytki [COLOR_POSITIVE_TEXT] Heal 4 Dodatkowe HP [ENDCOLOR] na turę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'Unikalny Mongolski zamiennik rycerz porusza się szybciej, jest w przedziale, a nie dzielić luki Kawalerskim do miast lub pikinierów. Keshik zarabia również doświadczenie szybciej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Potężny rzymski żołnierz Classical Era z bonusem przeciwko Miasta. Legia ma większą wytrzymałość niż szermierz, który zastępuje, dodatkowa ochrona przed ataków dystansowych i mogą budować drogi z podwójną prędkością Pracowników.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'Liburna był rodzaj małego pomieszczenia kuchennego stosowany do najazdów i patrole, szczególnie przez rzymskiego marynarki. [NEWLINE] [NEWLINE] W swojej pierwotnej formie, Liburna miał jedną ławkę z 25 wioseł z każdej strony, podczas gdy pod koniec Republiki Rzymskiej, został wyposażony w dwa banki wioseł (bireme), pozostałych szybsze, lżejsze i bardziej zwinny niż triremy. Liburnian projekt został przyjęty przez Rzymian i stał się kluczową częścią starożytnego Rzymu w marynarce przez 2 połowie 1 wieku pne. Liburnians odegrał kluczową rolę w bitwie pod Akcjum w Grecji, który widział ustanowienie Augusta jako niekwestionowanego władcy świata rzymskiego. [NEWLINE] Liburnians różniły się od triremy bojowych, quadriremes i nie quinqueremes powodu wiosłowania, ale raczej ze względu na jego szczególne cechy konstrukcyjne. [NEWLINE] [NEWLINE] Kiedy Rzymianie przyjęli Liburnian, że przystąpił do kilku dostosowań w celu poprawy wykorzystania okrętów "w marynarce. Korzyści uzyskane z dodatkiem baranów i ochrony przed pociskami ponad wyrobów gotowych na lekkim utraty prędkości. Oprócz budowy, statki, które wymaga regularnych Roman jednostka wojskowa zostać uproszczone, aby mogła funkcjonować sprawniej. Każdy statek działa jako samodzielna osoba, więc bardziej skomplikowana organizacja zwykle używane nie było konieczne. W marynarce wojennej, nie było prawdopodobnie Liburnian z kilku różnych rozmiarach, wszystko umieścić na konkretne zadania, takie jak harcerstwo i patrolowanie wód rzymskie z piractwem. Rzymianie wykorzystało Liburnian zwłaszcza w prowincjach imperium, gdzie zwykle stanowiły większość flot. [NEWLINE] Stopniowo Liburnians się ogólna nazwa dla różnych typów statków rzymskich, dołączone również do statków towarowych w Późnym antyku. Tacyt i Swetoniusz używali go jako synonim statku bitwy. W inskrypcji wspomniano jako ostatnia w klasie okrętów bojowych: hexeres, penteres, quadrieres, trieres, Marko Polo.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'Marko Polo jest pierwsza jednostka marynarki Rzymu. Jest to urządzenie wręcz bez walce na dystans Siła. Marko Polo jest przydatna do usuwania statków barbarzyńców z domu i na wodach ograniczonych poszukiwań.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Rzym stosować te naczynia do kontroli wód i ochrony ich szlaków handlowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Potężne urządzenie mobilne unikalny do Indii. W przeciwieństwie do Jeździec, który zastępuje, Wojna Słoń jest wahał, nie wymaga konie, i nie ma podatność na włóczników.', '', '');
/*  Inne  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Biuro Handlowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Ottoman Tribute', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' +3 [ICON_CULTURE] Kultura. [NEWLINE] +1 [ICON_CULTURE] Kultura na sąsiedniej Moai. [NEWLINE] [ICON_LOCKED] Musi być obok wybrzeża.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' +3 [ICON_CULTURE] Kultura. [NEWLINE] +1 [ICON_CULTURE] Kultura na sąsiedniej Moai. [NEWLINE] [ICON_LOCKED] Musi być obok wybrzeża.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' +3 [ICON_CULTURE] Kultura. [NEWLINE] +1 [ICON_CULTURE] Kultura na sąsiedniej Moai. [NEWLINE] [ICON_LOCKED] Musi być obok wybrzeża.', '', '');
/*  Amsterdam giełda  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Amsterdam giełda', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'Amsterdam Stock Exchange jest uważany za najstarszy na świecie. Została założona w 1602 roku przez holenderskiego East India Company w zakresie obrotu swoich drukowanych akcje i obligacje. Został przemianowany następnie Amsterdam giełda i był pierwszym, który formalnie rozpocząć handel papierami wartościowymi.', '', '');
/*  Jelling Stones  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Jelling Stones', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'W Jelling rzeźbione masywne kamienie Kamienie runiczne z 10. wieku, znaleziono w miejscowości Jelling w Danii. Starszy z dwóch kamieni Jelling został podniesiony przez króla Gorm w pamięci jego żony Thyra. Większy z dwóch kamieni został podniesiony przez Harald Bluetooth, syna króla Gorm jest. Harald zbudowany drugi kamień w pamięci jego rodziców, obchody jego podbój Danii i Norwegii, a jego konwersji Duńczyków na chrześcijaństwo. Te inskrypcje runiczne na te kamienie są uważane za najbardziej znany w Danii.', '', '');
/*  Jade Hall  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Hall', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'Król Sejong nadzorował rozwój Chiphyonjon, Jade Sali Uczonych, profesjonalnych naukowców, którzy pomogli badawczych pytania społeczne i polityczne dla króla i rządu. Jade Hall, będą uważane za "think tank" przez rządy dzisiaj.', '', '');
/*  Indus sanitarne  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus sanitarne', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'Harappan cywilizacja doliny rzeki Indus pierwsze znane systemy zaprojektowane miejskich sanitarnych na świecie około 2600 roku pne. Poszczególne domy lub grupy domów uzyskuje wodę ze studni. Ścieki kierowane z pokoi odstawić do kąpieli do objętych kanalizacji podszewka główne ulice. Masywne mury zostały spekulowali Harappan miastach ochrona przed zalaniem. Te systemy hydrotechniczne Harappan były jeszcze bardziej wydajne niż wielu obszarach Pakistanu i Indii dzisiaj, osiągnięcie dużych miast miejskich stosunkowo niewielkim rozwoju rolnictwa.', '', '');
/*  Pioneer  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pionier', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Zakłada nowe miasta, aby rozwinąć swoje imperium. [NEWLINE] [NEWLINE] [ICON_FOOD] rozwój miasta zostaje zatrzymany, gdy urządzenie jest w trakcie budowy. [NEWLINE]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'Pioneer amerykański Unique Unit. Porusza się szybciej niż osadnika, który zastępuje. [NEWLINE] [NEWLINE] Użyj tego urządzenia do budowy nowych miast. To nie może się bronić, więc towarzyszyć jej jednostki bojowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Amerykańscy pionierzy mają żadnej z osób w historii Stanów Zjednoczonych, którzy wyemigrowali na zachód od wybrzeża Atlantyku do osiedlania się i rozwijać nowe obszary. Szczególnie odnosi się określenie tych, którzy zamierzali osiedlić terytorium nowego społeczeństwa europejskiego i amerykańskiego, chociaż może być terytorium zamieszkane przez lub wykorzystywane przez rdzennych mieszkańców. [NEWLINE] [NEWLINE] koncepcja pionierem i etos znacznie wyprzedzają migrację do części Stanów Zjednoczonych zwanego teraz państwa "zachodnie", jak wiele miejsc, teraz uważane za Wschodzie były również rozstrzygane przez pionierów z wybrzeża. Na przykład, Daniel Boone, kluczowa postać w amerykańskiej historii pioniera, osiedlił się w Kentucky, kiedy to "Mroczne i Krwawe ziemia" była jeszcze niezabudowana. [NEWLINE] [NEWLINE] Jednym ważnym wydarzeniem w zachodniej osady była ustawa Homestead, który dostarczył formalne przepisy, które reguluje proces rozliczeniowy.', '', '');
/*  Młyn parowy  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Młyn parowy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Przejście w kierunku fabryk maszynowych zaczęła oparte w gospodarce Wielkiej Brytanii w 1700 roku, wcześniej wymagającym pracy ręcznej i zwierzęta. Te prekursorami rewolucji przemysłowej rozpoczął mechanizacji przemysłu włókienniczego. Rozwój handlu był włączony przez wprowadzenie kanałów, ulepszonych dróg i linii kolejowych. Szersze wykorzystanie kół wodnych i wprowadzenia siły pary pchnął dramatyczny wzrost zdolności produkcyjnych. Rozwój wszystkich obrabiarek metali na początku 1800 roku ułatwiło budowę coraz bardziej wyrafinowanych maszyn produkcyjnych do produkcji w wielu różnych branżach.', '', '');
/*  Dojo  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Japońskie dojo ("miejsce drogi") jest miejscem spotkań do prowadzenia szkoleń, egzaminów i innych związanych z nimi spotkania dla "zrobić" sztuki. Dojo początkowo dodatkiem do świątyń. W Japonii każdy fizyczny obiekt szkoleniowy, w tym szkół zawodowych zapasach, może być nazywany ze względu na jego dojo sztuk walki bliskich korzeni.', '', '');
/*  Sanktuarium  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Shinto Shrine', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'W Japonii istnieją sanktuaria Shinto obok siebie z buddyjskich świątyń i są najliczniejsze, znanych i ważnych miejsc religijnych w Japonii. Przybytek Shinto jest budowa lub obiekt, którego głównym celem jest, aby pomieścić jedną lub więcej Shinto kami (duchy, siły przyrody, lub istotę). Kami mogą znajdować się w niemal wszystko naturalnym lub sztucznym, z Mt. Fuji do małego klejnotu. Jako takie, te kapliczki są powszechne i bardzo zróżnicowany zakres. Sama świątynia może być duży lub mały budynek, obiekt, wzdłuż drogowych, lub może nawet być wykonywane przez ludzi. [NEWLINE] [NEWLINE] Jak buddyjskich świątyń, sanktuariów Shinto nie są przede wszystkim miejscem kultu. Najważniejsze budynki sanktuarium są używane do przechowywania świętych przedmiotów. Istnieją wyspecjalizowane budynki dla niektórych obrzędów, ale te są zwykle dostępne tylko dla ograniczonej liczby uczestników. Religijne zgromadzenia masowe w stylu kościołów chrześcijańskich nie odbywają się regularnie i nie odbywają się wewnątrz świątyni. Jeśli wiele osób jest zaangażowanych w ceremonii, to zakładamy, świąteczny charakter i odbędzie się na zewnątrz.', '', '');
/*  Folkskola  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'W 1842 r. parlament szwedzki wprowadził szkołę podstawową cztery lata dla dzieci w Szwecji, "Folkskola" (szkoła ludowa). Był to jeden z pierwszych systemów szkół publicznych na świecie. [NEWLINE] [NEWLINE] Szwedzkie dzieci są zobowiązani do uczęszczania grundskola, obowiązku szkolnego, w wieku od 7 do 16, gdzie grundskola jest połączenie szkoły podstawowej i średniej. Po grundskola, wielu Szwedów udział w planowej gymnasieskolan, liceum, wybierając opcję program uniwersytecki-przygotowawcze lub programu zawodowego. Studenci, którzy zdecydują program zawodowe normalnie zakończyć edukację po gymnasieskolan a studenci, którzy ukończą program uniwersytecki-przygotowawcze normalnie studiów wyższych na uniwersytecie lub college''u. Studenci, którzy ukończą program zawodowe mogą zapisać się na szkolnictwie wyższym, ale może trzeba podjąć dodatkowe kursy, zanim będą mogły być stosowane.', '', '');
/*  Bazylika  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Bazylika', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'Łacińska bazylika słowo (pochodzi od greckiego Stoa, komory trybunałem króla) było pierwotnie używane do opisania Roman budynek publiczny znajdujący się w forum rzymskiego miasta. Za tym idzie, to było stosowane do chrześcijańskich budynków tej samej formie. [NEWLINE] [NEWLINE] W 4 wieku, gdy władze cesarskie nie zalegalizował chrześcijaństwo z 313 edykt w Mediolanie, chrześcijanie byli gotowi do budowy większych i bardziej przystojny gmachy za kult niż ukradkowych miejsca spotkań zostali korzystających. Tradycyjne wzory architektoniczne świątyń były nieprzydatne z powodu związków z nie-chrześcijańskich wierzeń. Stare obrzędy świątynne wystąpił na zewnątrz pod gołym niebem w oczach bogów, ze świątyni w tle. Model Konstantyn chciał memorialise jego cesarskiej pobożności był wcześniej architektury (świecki) bazylik, trzymając uroczystości w pomieszczeniu.', '', '');
/*  Cothon  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'Cothon (greckie: "naczynie do picia") jest sztuczny, chronione przystani wewnętrznej powszechne w Kartaginie w czasie wojen punickich c.200 pne [NEWLINE] Cothons były zazwyczaj w fenickiego świata.. Przykłady obejmują Motya (Sycylia) z 6 wieku pne, który dokonał niepewny cel, (o wymiarach 35 metrów x 51 metrów), choć sugeruje to cothon może nawet być zamykany i opróżniane, tworząc suchy dok. Mahdia (Tunezja) z 7 wieku pne, (która mierzona 72 metrów x 56 metrów), a jeden z Kition na Cyprze.', '', '');
/*  Vedi  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi jest termin "zmiany" w religii wedyjskiej, najstarsza religia nadal praktykowane w czasach współczesnych. Takie ołtarze są podwyższone obudowa, ogólnie posypana Popular trawy i posiadające pojemniki do ognia ofiarnego.', '', '');
/*  NASA Centrum  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA Centrum', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'NASA Center to nowoczesne centrum badań, że Era daje wzrost technologii. Zapewnia również bezpłatny Spaceship zasobu fabryki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Od momentu swojego powstania w 1958 roku, NASA dokonał wielu wspaniałych czynów naukowych i technologicznych w powietrzu i przestrzeni. Technologia NASA również został dostosowany do wielu zastosowań nonaerospace przez sektor prywatny. NASA pozostaje wiodącą siłą w badaniach naukowych i pobudzanie zainteresowania publicznego w eksploracji lotniczym, jak również nauki i technologii w ogóle. Co ważniejsze, nasza eksploracja przestrzeni nauczyło nas, by zobaczyć Ziemię, siebie i wszechświata w nowy sposób. Podczas gdy ogromne osiągnięcia techniczne i naukowe NASA wykazać wyraźnie, że ludzie mogą osiągnąć wcześniej niepojęte wyczyny, ale również są upokorzony przez świadomość, że Ziemia jest tylko małe "Blue Marble" w kosmosie.', '', '');
/*  Abbey  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Opactwo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'Abbey ma na swoim sercu praktyki kultu, na pomysł, aby nie dostać wszystkich do jednej usługi, ale w celu zapewnienia możliwości Opactwo wyznawcy kultu, które mogą wziąć udział w regularnie, jeśli nie co tydzień. Poprzez usługi, sztuki rozkwitła jako wyraz uwielbienia dla "Stwórcy". W opactw addycyjnych były samonośne, zaangażowany w polach uprawowych, hodowli zwierząt, działających na rynkach publicznych, i daje możliwości zatrudnienia dla społeczności. Opactw Celtic stały się ośrodkami kształcenia, ochrony świętych i literackich rękopisów i szkół nauczania.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'Opactwo jest Celtic duchowe i kulturowe ośrodkiem każdej społeczności. Produkuje 1 [ICON_FOOD] Jedzenie [ICON_RESEARCH] Nauka [ICON_CULTURE] Kultura, [ICON_GOLD] Złoto i [ICON_PRODUCTION] produkcyjnych.', '', '');
/*  Odeon  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon, od starożytnego greckiego ᾨδεῖον, Ōideion, dosłownie "śpiewa się" lub "budowanie na konkursach muzycznych". [NEWLINE] najwspanialszy Odeon był Odeon Heroda Attyka na klifie na południowy zachód od Akropolu w Atenach zbudowany w około 160 AD przez zamożnego sofista i retor Heroda Attyka w pamięci jego żony. Miał zakwaterowanie dla 8000 osób, i sufit wykonane z pięknie rzeźbionych belek z drewna cedrowego, prawdopodobnie z otwartej przestrzeni w centrum dopuszczenia światło. Został również obficie ozdobione zdjęć i innych dzieł sztuki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'Odeon jest źródłem natychmiastowej [ICON_CULTURE] Kultury. Budowanie to pomaga szerzyć granice swojego imperium.', '', '');
/*  Barbary port  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbary port', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'Piraci Barbary, nazywane Barbary korsarze i korsarze osmańscy byli piraci i prywaciarzy, którzy sterowane z Afryki Północnej, w oparciu przede wszystkim w portach Tunis, Trypolisu i Algieru. [NEWLINE] [NEWLINE] Obszar ten był znany w Europie jako Barbary Coast , termin pochodzi od nazwiska jej mieszkańców berberyjskich. [NEWLINE] Oprócz zajmowania statków, są zaangażowane w Razzias, naloty na europejskich nadmorskich miast i wsi, głównie we Włoszech, Francji, Hiszpanii i Portugalii, ale także w brytyjskim Isles, Holandia i tak daleko, jak Islandia. Głównym celem ich ataków było uchwycić chrześcijańskich niewolników na rynek muzułmańskich w Afryce Północnej i na Bliskim Wschodzie.', '', '');
/*  Umywalka nawadniania  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Dorzecze nawadniania', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Starożytni Egipcjanie praktykowali nawadniania Basin pomocą powodzi Nilu do zalewają działek, które zostały otoczone wałami. Wody powodzi odbył aż płodne osad osiadł przed nadwyżka wróciła do cieku wodnego. [NEWLINE] Istnieją dowody starożytnego faraona egipskiego Amenemheta III z XII dynastii (ok. 1800 pne), stosując naturalne jezioro w Fajum Oasis jako zbiornik do przechowywania nadwyżek wody do użytku podczas pory suchej, jezioro rosło rocznie od powodzi Nilu.', '', '');





UPDATE Loaded File SET Value=1, PL_PL=1 Where Type='Leaders.sql';




