/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Pobór do wojska', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' +10 [COLOR_POSITIVE_TEXT] Heal Oceń [ENDCOLOR].', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Wojsko zawodowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Odblokowuje zaawansowane promocje.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Merkantylizm', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' +2 [ICON_MOVES] Ruch.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Wolność', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' +25% [ICON_STRENGTH] Siła w obszarze dziećmi.', '', '');
/*  Wolność  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultura: +1 we wszystkich miastach [NEWLINE] [ICON_PRODUCTION] Produkcja: +1 we wszystkich miastach [NEWLINE] [ICON_WORKER] Odblokowuje: Terakota armia [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Wielka Osoba: +1 z wyboru', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Osadnik: +1 [NEWLINE] [ICON_PRODUCTION] Produkcja: +25% do Settlers', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Złoto: +200 x Era [NEWLINE] [ICON_CULTURE] Nowe miasta zwiększają koszty polityczne 33% mniej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Pracownicy: +1 [NEWLINE] [ICON_WORKER] Pracownik Poprawa Oceń: +25%', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 Narodowe Szczęście Nieszczęście za [ICON_CONNECTED] podłączonego miasta. [NEWLINE] [ICON_HAPPINESS_4] -5% od [ICON_CITIZEN] ludności w miastach, które nie są [ICON_OCCUPIED] okupowanych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] bezpłatny budynek Obrona City we wszystkich miastach (prąd, nowy, i podbił). Z odpowiednia technika badań. [NEWLINE] [ICON_PRODUCTION] +1 Produkcja na Obrona City Building.', '', '');
/*  Tradycja  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultura: +3 w Capital [NEWLINE] [ICON_WORKER] Odblokowuje: Banaue Rice Tarasy [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR ] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Wielka Osoba Cena:. +50% [NEWLINE] [ICON_CULTURE] Podwaja granic ekspansji kulturowej do płytek daleko od miast [NEWLINE] [ICON_PEACE] mogą zakupić Wielkie inżynierów Wiara począwszy od ery przemysłowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Gawędziarzy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Kultura: +2 na wioskę i Pałac', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'Materiał jest ustna tradycja kulturowa i tradycja przekazywana ustnie z pokolenia na pokolenie. Wiadomości lub zeznania są ustnie przekazywane w mowie lub utworu i może mieć formę, na przykład, z Bajki, powiedzeń, ballady, pieśni i przyśpiewki. W ten sposób możliwe jest społeczeństwo do przekazywania historii mówionej, literatury, prawa werbalne werbalne i inne wiedzę następnym pokoleniom bez systemu pisania.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Uroczyste obrzędy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Kultura: +1 za Culture Building [NEWLINE] [ICON_CULTURE] 1 wolne Budynek Kultury w swoich najstarszych 4 miastach.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Ceremonia jest wydarzeniem o znaczeniu rytualnym wykonywane na specjalne okazje. Ceremonie fizyczny może mieć wyświetlacz lub składnik teatralny: dance, procesji, nałożenie rąk. Deklaratoryjny wypowiedź słowna może być związane z tej okazji. [NEWLINE] [NEWLINE] ceremonia może oznaczyć rytuał przejścia w życiu człowieka, znakowanie znaczenie urodzenia, dorosłości, inicjacji w grupie, lub śmierci. Czasami ceremonia może być wykonywane wyłącznie przez osoby z określonym organem. Całej uroczystości społeczeństwa może oznaczać roczne lub sezonowych lub powtarzające się wydarzenia, takie jak równonocy wiosennej, Przesilenie zimowe i inne roczne pozycje astronomiczne.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Nadwyżka Jedzenie: +25% w mieście [NEWLINE] [ICON_FOOD] Jedzenie: +2 za miastem', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Miasto ataku: +50% z garnizonów [NEWLINE] [ICON_GOLD] Brak konserwacji jednostkom stacjonującym.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Produkcja: +15% do cudów [NEWLINE] [ICON_HAPPINESS_1] Szczęście: +1 na 10 [ICON_CITIZEN] Obywatele', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Obywatele Stolicy stworzyć 0,5 [ICON_GOLD] Gold i 0,5 [ICON_HAPPINESS_1] Happiness.', '', '');
/*  Honor  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Zdolności:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] Ujawnia obozów barbarzyńców [NEWLINE] [ICON_STRENGTH] +10% Siła przeciw barbarzyńcom [NEWLINE] [ICON_CULTURE] barbarzyńcy Zabijanie daje 2 kultury na . siłę pokonanych wrogów [NEWLINE] [ICON_WORKER] Odblokowuje: Świątynia Artemidy [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Miasto Szczęście: +1 za Koszary', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] Jednostki obronne w stolicy. [NEWLINE] +20% [ICON_PRODUCTION] produkcyjne dla jednostek wojskowych i budynków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Łupów wojennych', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Uszkodzone złoto od urządzeń z pokonanych wrogów. [NEWLINE] [ICON_CITY_STATE] +25% korzyści z robienia miast-państw.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Grabieży przez zwycięską armię podczas wojny była powszechna praktyka w całej historii. Dla piechoty, było postrzegane jako sposób na uzupełnienie ich często skromne dochody i było częścią obchodów zwycięstwa. Na wyższych poziomach, dumny wystawa łupów był integralną częścią typowej rzymskiej triumfu i Genghis Khan nie był niczym niezwykłym w głoszeniu, że największe szczęście było "pokonać swoich wrogów ... obrabować ich z bogactwa ..." [NEWLINE] [NEWLINE] W działaniach wojennych w czasach starożytnych, łupy wojenne obejmowały pokonani populacji, które były często w niewoli, a kobiety i dzieci, które często były absorbowane do zwycięskiej populacji kraju. W innych społeczeństwach przed-nowoczesnych, przedmioty z metali szlachetnych były preferowanym celem wojennej grabieży, głównie z powodu ich łatwego przenoszenia. W wielu przypadkach grabieży była okazją do uzyskania dóbr, które inaczej nie byłyby dostępne. Od 18 wieku, dzieła sztuki stają się coraz bardziej popularnym celem. W 1930 roku, a nawet bardziej, w czasie II wojny światowej Niemcy hitlerowskie zaangażowany w dużej skali i zorganizowana grabież dzieł sztuki i nieruchomości.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiatorów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Szczęście Miasto: +1 za Arena [NEWLINE] 2 [ICON_TEAM_2] Urządzenia obronne w stolicy..', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'Wojna Epics', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' +1 [ICON_HAPPINESS_1] Szczęście z budynków miasta kultura.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Epos (z greckiego przymiotnika ἐπικός (epikos), z ἔπος (epopeja) "słowo, opowieść, poemat") jest długi poemat narracyjny, zwykle dotyczące poważnego tematu, zawierające szczegóły bohaterskich czynów i wydarzeń istotnych dla kultury i narodu . [NEWLINE] [NEWLINE] eposów wojny są poematów lub literackie dzieła epickiego zakresie poszukiwania lub które są uważa się uchwycić i wyrazić istotę lub ducha danego narodu lub grupy etnicznej lub językowej z aspiracji do niezależności i autonomii. Eposów narodowych często opowiadają pochodzenie narodu, część jej historii, lub zdarzenia, takie jak kluczowe decydujących zwycięstwach lub Vanquish gorzkich wrogów, w rozwoju tożsamości narodowej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Miasto Szczęście: +1 za Garrison [NEWLINE] [ICON_CULTURE] Kultura: +2 za Garrison', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Wielki Generał: +1 [NEWLINE] [ICON_MOVES] Ruch:. +1 Dla wielkich generałów [NEWLINE] [ICON_STRENGTH] +15% Siła dla wszystkich bloków sąsiadujących z innych zaprzyjaźnionych jednostek wojskowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15%, gdy [COLOR_POSITIVE_TEXT] w sąsiedztwie [ENDCOLOR] do zaprzyjaźnionych jednostek wojskowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] koszt rozbudowy: -50% dla jednostek [NEWLINE] [ICON_PRODUCTION] Produkcja: +15% dla wszystkich jednostek', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Kod Warrior [ENDCOLOR] [NEWLINE]', '', '');
/*  Pobożność  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Zdolności:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Kultura +1 [NEWLINE] [ICON_PEACE] Wiara +1 [NEWLINE] [ICON_PRODUCTION] podwoić produkcję do sanktuariów [ICON_WORKER] Odblokowuje: Stonehenge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] Wybierz jedną nową Pobożnego wiarę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Dobroczynność', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Złoto: +25% od Świątyń [NEWLINE] [ICON_GOLD] Złoto: +2 od Świątyń [NEWLINE] [ICON_GOLD] Złoto: 3 Miejsca Święte.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'Słowo "miłość" pochodzi od francuskiego słowa Starego "Charite", które z kolei wywodzi się z łacińskiego "Caritas". [NEWLINE] [NEWLINE] praktyka miłości oznacza dobrowolne dawanie pomocy dla tych, którzy są w potrzebie nie związane z dawcą, choć pierwotne znaczenie jest bardziej zaangażowany w koncepcji cenne, drożyzna, wysokie ceny. Charytatywnej odbywa się bezpośrednio lub za pomocą charytatywną lub innego godnego zaufania przyczyny. Instytucje te ewoluowały do ​​przeprowadzenia z pracy pomoc ubogim, a zaczęto nazywać, zwane "organizacje charytatywne". W "charytatywnych" Modern Times dostarczają wielu charytatywnej, w kategoriach wartości pieniężnej. Rodzaje organizacji charytatywnych m.in. domy dziecka, banki żywności, instytuty religijne poświęcone opieką ubogich, szpitale, organizacje, które odwiedzają HOMEBOUND i uwięziony, i wiele innych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Inspiracja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Wielka Bezpłatne Prorok: +1', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'Słowo "inspiracja" pochodzi od łacińskiego rzecz Inspiratio iz inspirare czasownika. Inspirare jest określenie związek wynikający z łacińskiego przedrostka w (w środku, w) i na spirare czasownika (do oddychania). [NEWLINE] [NEWLINE] W klasycznych czasów rzymskich, inspirare już zaczęło oznaczać "głęboko oddychać" i zakłada również Graficzny poczucie "zaszczepić [coś] w sercu lub w umyśle kogoś". [NEWLINE] [NEWLINE] Stąd "inspiracja" odnosi się do nieprzytomnej przypływie kreatywności w literackich, muzycznych, artystycznych i innych przedsięwzięć. Koncepcja ma korzenie w obu hellenizm i hebraizm. Grecy wierzyli, że inspiracja pochodzi od muz, a także bogów Apolla i Dionizosa. Podobnie w starożytnym nordyckiej religii, inspiracja pochodzi od bogów, takich jak Odyna. Inspiracja jest boska sprawa w poetyce hebrajskich. W Księdze Amosthe prorok mówi o jest przytłoczony przez głos Boga i zmuszać do mówienia. W chrześcijaństwie, inspiracją jest darem Ducha Świętego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Tolerancja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Szczęście Miasto: +1 za obiekt sakralny [NEWLINE] [ICON_PEACE] Miasta z wielu religii także otrzymać bonus panteonie religii drugiego najpopularniejszego miasta.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Tolerancja i tolerancja to "praktyka pozwoli świadomie pozwalając lub coś z których jeden nie pochwala. Można sensownie mówić o tolerowanie, tj. umożliwienie lub zezwoleń, tylko jeśli ktoś jest w stanie zabronić". Zostało również określone jako " pokrywa lub znosić "lub" karmić, utrzymania lub zachowania ". tolerancji może oznaczać" nie więcej niż cierpliwości i zgody udzielonej przez wyznawców religii dominującej na innych religii istnieć, nawet jeśli są one patrzył z dezaprobatą, jak gorsze, błędne lub szkodliwe "[NEWLINE] [NEWLINE] Tolerancja jest postawą umysłu, która zakłada, bez dokonywania oceny akceptację różnych stylów życia i wierzeń, a tolerancja oznacza oddanie się z czymś, co jeden sprzeciwia. [NEWLINE] [NEWLINE] przykłady historyczne o "tolerancji" jest mnóstwo. Na przykład w akcie tolerancji, król perski Cyrus Wielki Uważa się, że został zwolniony z niewoli Żydów w 539-530 pne, i dozwolone ich powrót do ojczyzny.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Jedność', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Złoty Wiek Turns: 10 [NEWLINE] [ICON_GOLDEN_AGE] Złote Wieki wymagają 50% mniej [ICON_HAPPINESS_1] Narodowe Szczęście', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Jedności odnosi się do związków w społeczeństwie ludzie, które wiążą się ze sobą. Termin ten jest powszechnie stosowany w socjologii i innych nauk społecznych. [NEWLINE] [NEWLINE] W prostych społeczeństwach może ona być oparta głównie wokół pokrewieństwa i wspólnych wartości. W bardziej złożonych społeczeństw istnieją różne teorie co do tego, co przyczynia się do poczucia solidarności społecznej [NEWLINE] [NEWLINE] To prowadzi do związanej okresie "Solidarności", których jest powiedziane:. [NEWLINE] "Solidarność nie zakładać, że nasze zmagania są te same walki, albo że nasz ból jest taki sam ból, lub, że nasza nadzieja jest w tym samym przyszłość. Solidarność wymaga zaangażowania i pracy, a także uznanie, że nawet jeśli nie mamy te same uczucia, lub te same życie, lub te same organy, żyjemy na wspólnej ziemi. " - Sara Ahmed', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Medytacja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Wiara: +1 Sanktuaria, Świątynie [NEWLINE] [ICON_PEACE] Koszty Wiara: -33%', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Nabożeństwo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'Nabożeństwo można zdefiniować jako: żarliwą, często bezinteresownej miłości i poświęcenia, co do osoby lub co do zasady. Cześć, od worthscipe staroangielskiego, co oznacza godność lub warto-statek jest aktem pobożności religijnej zazwyczaj skierowany w kierunku bóstwa. Ściśle powiązane z pojęciem miłości, poświęcenie często nadzieję być odwzajemniona z jakąś formą dobrodziejstwem lub błogosławieństwa. [NEWLINE] [NEWLINE] Wielbiciele, jako tych, którzy praktykują pobożność nazywa chcąc otrzymać te błogosławieństwa, często są na jeden cel punkt fanatyzmu. Tak więc, podczas gdy pojęcie "pobożności" jest łagodny, wiele historycznych przykładów pobożności religijnej są często skrajne i krwawe, jak wielbiciele vie miłością oddani z wyświetlaczami bardziej skandaliczne.', '', '');
/*  Bogactwo  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Bogactwo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'BOGACTWO', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'Bogactwo jest mnóstwo cennych zasobów i dóbr materialnych. Pojęcie bogactwa jest istotna we wszystkich dziedzinach ekonomii, ale znaczenie bogactwa jest zależne od kontekstu i nie ma powszechnie uzgodnionej definicji. Na poziomie najbardziej ogólnym bogactwa jest "coś z wartości", który przechwytuje zarówno subiektywny charakter słowa, a pomysł, że to nie jest stałe lub statyczne pojęcie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'Co to jest polityka społeczna oddział Bogactwo o?', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'Oddział Wealth koncentruje się na rozwoju terytorium szeroki, z krajowej podaży [ICON_GOLD] złota utworzonej przez głównych miastach na zakup nowych jednostek i budynków w miastach przygranicznych niezabudowane.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'Oddział Wealth koncentruje się na rozwoju terytorium szeroki, z krajowej podaży [ICON_GOLD] złota utworzonej przez głównych miastach na zakup nowych jednostek i budynków w miastach przygranicznych niezabudowane. Zobacz zasady dotyczące polityki społecznej na szczegóły.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'Bogactwo Oddział', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_GOLD] Złoto: +10% {TEKST} [NEWLINE] [ICON_PRODUCTION] Produkcja: +10% {TEKST} [NEWLINE] [ICON_WORKER] Odblokowuje : Kanał Panamski [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Szczęście: +1 na Rynku, Kuźnia [NEWLINE] [ICON_PEACE] mogą zakupić Wielkie Merchants z Wiary po wejściu do epoki przemysłowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' +2 [ICON_MOVES] Ruch na rzecz jednostek spoza bojowych. [NEWLINE] +25% [ICON_GOLD] Przychody z [ICON_CONNECTED] Handel krajowy. [NEWLINE] -25% [ICON_GOLD] Koszty dla dróg i linii kolejowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Złoto: +1 na wioskę [NEWLINE] [ICON_PRODUCTION] Produkcja: +1 za Mine, Tartak', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Czy zakup Landsknechts. [NEWLINE] [ICON_TEAM_2] 2 Landsknechts pojawić w stolicy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Bezpłatne Wielki Sklep: +1 [NEWLINE] [ICON_GREAT_PEOPLE] Wielki Sklep Oceń: +25% [NEWLINE] [ICON_GREAT_MERCHANT] Podwójne złoto od Wielkich misji handlowych Sklep.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Przyczepa', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Złoto: +3 za szlak handlowy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Produkcja: +4 za nadmorskim mieście [NEWLINE] [ICON_GOLD] Złoto: +4 za Lighthouse, Port, Port morski', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Gildii', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' +1 [ICON_TEAM_7] Wielki Sklep w stolicy. [NEWLINE] +100% [ICON_GOLD] Złoto z wielkich misji handlowych Sklep.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Gildia jest stowarzyszeniem rzemieślników w danej branży. Najstarsze typy gildii powstało jako bractw pracowników. Zostały one zorganizowane w sposób coś między związkiem zawodowym, kartelu, i tajnego stowarzyszenia. Często zależało im na dotacje listów patentu przez monarchę lub innego organu egzekwowania wymiany handlowej do swoich członków na własny rachunek, a także do zachowania własności narzędzi i dostaw materiałów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] Koszt zakupu dla jednostek i budynków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Prawo patentowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' +1 [ICON_GOLD] Złoto ze wsi. [NEWLINE] +2 [ICON_GOLD] Złoto z portów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Patent jest zestaw wyłącznych praw przyznanych przez państwo (rząd krajowy) do twórcy lub jego cesjonariusza przez ograniczony okres czasu w zamian za publiczne ujawnienie wynalazku. [NEWLINE] [NEWLINE] Patenty w nowoczesnym sensie pochodzi w 1474 roku, kiedy Republika Wenecji uchwalił dekret, że nowe i pomysłowe urządzenia, raz wprowadzone do praktyki, miał być przekazane Republice uzyskać prawo uniemożliwić innym korzystanie z nich. [NEWLINE] [NEWLINE] Anglia, a następnie z Statut monopoli w 1623 roku pod wodzą króla Jakuba I, który uznał, że patenty mogą być przyznawane jedynie dla "projektów nowego wynalazku." W okresie panowania królowej Anny (1702/14), prawnicy angielski Trybunału opracowany wymóg, że pisemny opis wynalazku musi być złożone. System patentowy w wielu innych krajach jest na podstawie prawa brytyjskiego i sięgają do Statutu monopoli.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] Ruchy i +1 Sight dla statków wojskowych. [NEWLINE] +2 [ICON_RESEARCH] Nauka dla nadbrzeżnych miast. [NEWLINE] +2 [ICON_RESEARCH] Nauka dla Naval Buildings.', '', '');
/*  Patronat  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Zdolności:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_GOLD] +2 Złoto za miasto-państwo Trade Route [NEWLINE] [ICON_VIEW_CITY] ujawnia wszystkie miasta-państwa [NEWLINE] [ICON_WORKER] Odblokowuje : Angkor Wat [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_PLUS] +100% ilość zasobów strategicznych i +50% [ICON_HAPPINESS_1] Narodowy Szczęście z luksusowych środków obdarowany przez aliantów miasto-państwo.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] +20 natychmiastowy Wpływy z Miasta-Państwa. [NEWLINE] [ICON_INFLUENCE] +33% Wpływy z [ICON_GOLD] Złote prezenty dla Miasta-Państwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Specjalne związku', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Wpływ z Miasta-Państwa degraduje 33% wolniej niż normalnie. [NEWLINE] [ICON_INFLUENCE] Wpływ innych graczy z Miasta-Państwa zmniejsza się o 10% szybciej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] +20 odpoczynku wpływy z Miasta-Państwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] +2 Nauka za ery dla każdego przyjaciela, miasta-państwa i +3 dla każdego sojusznika.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] Miasto-państwo sojusznicy prezent Great People. [ICON_GREAT_PEOPLE] +10% Wielka Ludzie nocleg.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Pakt Trade', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' +2 [ICON_PRODUCTION] Produkcja na ery dla każdego przyjaciela, miasta-państwa i +3 dla każdego sojusznika (podziału między swoich miastach).', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Wolny handel jest system polityki handlowej, która pozwala przedsiębiorcom na handel ponad granicami państwowymi, bez ingerencji z rządami obu krajów. Ze względu na zasady ekonomicznej przewagi komparatywnej, zapewnia partnerom handlowym z wzajemnych korzyści. W ramach tej polityki ceny są jedynym czynnikiem decydującym o przydziale zasobów i blisko odbicie popytu i podaży.', '', '');
/*  Estetyka  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] +50% do produkcji budynków Kulturalnych [NEWLINE] [ICON_WORKER] Odblokowuje:. Uffizi [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR ] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] Wywołanie ukrytych miejsc starożytności. [NEWLINE] [ICON_TEAM_7] Umożliwia zakup wielkich ludzi kultury z [ICON_PEACE] Wiary po wejściu do epoki przemysłowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Kultura: +1 za 2 nadmiaru szczęścia.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Kultura: +2 za Narodowy Wonder [NEWLINE] [ICON_CULTURE] Kultura: +33% w miastach z Wonder World', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Wielki Artysta: 1 [NEWLINE] [ICON_TEAM_7] Kultury stopa wielkiego człowieka: +25%', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Archeolodzy są produkowane dwa razy szybciej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Doubles budynek-theme turystyka. [NEWLINE] [ICON_TOURISM] +25% turystyka od wspólnego wyznania, otwartych granic i szlaków handlowych.', '', '');
/*  Eksploracja  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_MOVES] Odeszli: 2 dla jednostek rozpoczęła [NEWLINE] [ICON_MOVES] Odeszli: 2 dla wielkich admirałów [NEWLINE] [ICON_SIGHT_SEA] Sight: + 1 dla wojskowych statków [NEWLINE] [ICON_WORKER] Odblokowuje: Czerwony Fort [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] +2 Narodowych Szczęście na Luxury Resource. [NEWLINE] [ICON_TEAM_7] Umożliwia zakup wielkich admirałów z wiary Po wejściu do epoki przemysłowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Miasto Szczęście: +1 za Latarnia Morska, Port, Port morski', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Zakup Koszt: -25% dla budynków [NEWLINE] [ICON_GOLD] Konserwacja: -25% dla budynków', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Kolonizacja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] rozpocząć Miasta z 3 populacji. [NEWLINE] [ICON_TEAM_2] 2 Settlers, 2 pracowników oraz 2 Jednostki obronne pojawiają się w stolicy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Pioneer Duch', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 ruch dla ludności cywilnej. [NEWLINE] [ICON_GOLD] koszt -50% na drogi. [NEWLINE] [ICON_PRODUCTION] produkcja +100% do budowy portów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Ustawa Homestead', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Miasta zdobyć darmowy Poziom 1 budynków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(Todo)', '', '');
/*  Wiedza  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Wiedza', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'WIEDZA', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'Wiedza to znajomość z kimś lub czymś, co może obejmować fakty, informacje, opisy, lub umiejętności nabytych przez doświadczenie czy wykształcenie. Może odnosić się do teoretycznego i praktycznego zrozumienia tematu. To może być praktyczne umiejętności lub wiedzy fachowej, lub teoretyczne zrozumienie tematu.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Pobożność zwiększa szczęście, kultura i wiara CIV przyjmująca. Pobożność staje się dostępny po osiągnięciu Classical Era. Jest to idealne miejsce do nabywania polityki dla graczy chcących stworzyć lub poszerzyć religie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'Co to jest polityka społeczna gałęzi wiedzy o?', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'Gałąź wiedzy poprawia zdolność cywilizacji do używania i generowania nauki, stają się dostępne po wejściu do renesansowej epoki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'Oddział Znajomość polityki społecznej jest pełne polityki, które mogą zwiększyć swoje badania. Oddział ten będzie dostępny w epoce renesansu. Zobacz zasady dotyczące polityki społecznej na szczegóły.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'Wiedza Oddział', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Zdolności: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Otwieracz [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Wielki Naukowiec: +1 [NEWLINE] [ICON_WORKER] Odblokowuje: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] finiszer [ENDCOLOR] [ COLOR_GREY] (zakończyć wszystkie polityki w tym drzewa) [ENDCOLOR] [NEWLINE] +1 natychmiastowy [ICON_TEAM_5] Technologie. [NEWLINE] [ICON_PEACE] Czy zakup wielkich naukowców z [ICON_PEACE] Wiary po wpisaniu ery industrialnej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[ICON_RESEARCH] nagrody porozumienia o badaniach +50%.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Kontrwywiadu', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] +25% szans złapać szpiegów wroga. [NEWLINE] [ICON_SPY] -25% wrogiem skuteczność szpiegiem.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(Todo)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Nauka: +10%, podczas gdy naród jest [ICON_HAPPINESS_1] szczęśliwy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Nauka: +1 na wioskę [NEWLINE] [ICON_RESEARCH] Nauka: +2 za Lighthouse', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Nauka: +2 za Specjalista', '', '');







UPDATE Loaded File SET Value=1, PL_PL=1 Where Type='Policies.sql';



