/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/*  PROMOCJE  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Armor [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', 'Artic mocy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] Szybciej w [COLOR_POSITIVE_TEXT] śniegu i Tundra [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', 'Bombardowanie I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] i [COLOR_POSITIVE_TEXT] morze [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', 'Bombardowanie II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] i [COLOR_POSITIVE_TEXT] morze [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', 'Bombardowanie III', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] i [COLOR_POSITIVE_TEXT] morze [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] +6 Zakres', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] +6 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] Czy Sweep, aby usunąć powietrze przechwytujących Jednostek.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', 'Przydział', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] +10% Siła [NEWLINE] [ICON_GOLD] -100% [COLOR_POSITIVE_TEXT] Upgrade Koszt [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] Pełna obrażenia atakując całej morza lub rzeki [NEWLINE] [ICON_STRENGTH] +100%, gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[ICON_STRENGTH] +25% Siła vs [COLOR_POSITIVE_TEXT] jednostek Mounted [ENDCOLOR] i [COLOR_POSITIVE_TEXT] Armor [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[ICON_STRENGTH] +25% Siła vs [COLOR_POSITIVE_TEXT] jednostek Mounted [ENDCOLOR] i [COLOR_POSITIVE_TEXT] Armor [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', 'Bonus vs Air (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] powietrza [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] +150% vs [COLOR_POSITIVE_TEXT] bombowców i helikopterów [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', 'Bonus vs dragonów (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] dragonów [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus kontra Fighters (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Helicopters (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Śmigłowce [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', 'Bonus vs Mounted (10)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] +10% vs melee [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', 'Bonus vs Mounted (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] +50% vs melee [COLOR_POSITIVE_TEXT] Mounted [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', 'Atak vs okrętów podwodnych (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] atak [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Submarines [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Tanks (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Czołgi [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', 'Astronomia', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] można przechodzić [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', 'Bonus na atak (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] atak [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', 'Bonus na atak (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] atak [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_RANGE_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR] może atakować dwa razy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', 'Koleżeństwo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] +15%, gdy [COLOR_POSITIVE_TEXT] Obok [ENDCOLOR] do przyjaznej jednostki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] Ataki użyć [COLOR_POSITIVE_TEXT] 1 Przesuń [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] można poruszać się [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', 'Bonus vs okrętów (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Pancerniki [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Krążowniki rakietowe [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Przewoźnicy [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] Czy Carry [COLOR_POSITIVE_TEXT] 1 [ENDCOLOR] cargo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] Czy Carry [COLOR_POSITIVE_TEXT] 2 [ENDCOLOR] cargo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] Czy Carry [COLOR_POSITIVE_TEXT] 3 [ENDCOLOR] cargo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] Czy Carry [COLOR_POSITIVE_TEXT] 4 [ENDCOLOR] cargo', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] +1 Ruch [NEWLINE] [ICON_STRENGTH] +20% vs [COLOR_POSITIVE_TEXT] Ranni [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] mocne [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', 'Atak kontra Miast (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] atak [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', 'Bonus vs Miast (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', 'Bonus vs Miast (200)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] +200% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', 'Bonus vs Miast (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', 'Sklep Raider I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Miasta [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal złota równą 33% obrażenia zadawane na porty', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', 'Sklep Raider II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Miasta [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal złota równą 33% obrażenia zadawane na porty', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', 'Sklep Raider III', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Miasta [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal złota równą 34% obrażenia zadawane na porty', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] ataków dystansowych [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] ataków dystansowych [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', 'Kara vs kilkudniowe (10)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] -10% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR] wobec wszystkich [COLOR_NEGATIVE_TEXT] ataków dystansowych [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '-10% Vs [COLOR_NEGATIVE_TEXT] kilkudniowe [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH] +30% w [COLOR_POSITIVE_TEXT] Capital [ENDCOLOR], premia spada jako jednostka dostaje dalej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Kara na Defense (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] można wybrać się na [COLOR_POSITIVE_TEXT] Płytki wodne [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +100%, podczas gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR].', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', 'Bonus obrony (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', 'Bonus obrony (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', 'Kara na Defense (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25% [COLOR_NEGATIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', 'Pustynia zasilania', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] Szybciej w [COLOR_POSITIVE_TEXT] Pustynie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15%, gdy [COLOR_POSITIVE_TEXT] w sąsiedztwie [ENDCOLOR] do przyjaznej jednostki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] +33% [COLOR_POSITIVE_TEXT] Sweeps powietrza [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] +33% [COLOR_POSITIVE_TEXT] Sweeps powietrza [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] +34% [COLOR_POSITIVE_TEXT] Sweeps powietrza [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOUBLE_WORK_SPEED_HELP', '[ICON_WORKER] Buduje ulepszenia +100% szybciej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOUBLE_WORK_SPEED', 'Podwójna prędkość pracy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] terenowe [ENDCOLOR] Ukształtowanie terenu (wzgórza, las lub dżungli)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] można wybrać się na [COLOR_POSITIVE_TEXT] Woda Płytki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Rozpoczęła obrony (100)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] +100%, gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] +1 Zasięg widzenia, gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50% szans na [COLOR_POSITIVE_TEXT] Omijać [ENDCOLOR] przechwytywanie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100% na [COLOR_POSITIVE_TEXT] Omijać [ENDCOLOR] przechwytywanie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT] Ruch [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT] Ruch [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH] -10% do [COLOR_POSITIVE_TEXT] sąsiednich jednostek wroga [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', 'First Strike', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT] wolny atak [ENDCOLOR] przed walką', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] +50%, gdy [COLOR_POSITIVE_TEXT] towarzyszące [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] Wszystko ruch używa [COLOR_PLAYER_ORANGE_TEXT] 1 Ruchu [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Obczyźnie Bonus (20)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', 'Formacja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Zamontowany [ENDCOLOR] i [COLOR_POSITIVE_TEXT] Armored [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] szt. Zamontowane [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', 'Darmowe aktualizacje', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', 'Darmowe aktualizacje', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] Zdobywa doświadczenie 50% szybciej', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] +15% z [COLOR_POSITIVE_TEXT] Wielki Generał [ENDCOLOR] w samej płytki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', 'Złoty', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '[ICON_GOLDEN_AGE] punktów Złoty Wiek z walki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] Poprawia skuteczność walki z okolicznych [COLOR_POSITIVE_TEXT] statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] Poprawia skuteczność walki z okolicznych [COLOR_POSITIVE_TEXT] jednostek lądowych [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1', 'Guerrilla I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na trudnym terenie [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2', 'Partyzant II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na trudnym terenie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3', 'Partyzant III', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na trudnym terenie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'Handicap I AI', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] +1 Widoczność [NEWLINE] [ICON_WAR] +10% Doświadczenie [NEWLINE] [ICON_STRENGTH] +10% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] +2 Widoczność [NEWLINE] [ICON_WAR] +25% Doświadczenie [NEWLINE] [ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] +2 Widoczność [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] Leczy 50 Obrażenia [ENDCOLOR], gdy zabija jednostkę dla barbarzyńska', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] Heal tego urządzenia [ENDCOLOR] 50 KM Spowoduje to [COLOR_POSITIVE_TEXT] Spożywać tej okazji [ENDCOLOR], aby wybrać Promocja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', 'Hill Fighter', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] Szybciej w [COLOR_POSITIVE_TEXT] Hills [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] Friendly Terytorium [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', 'Terenowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] można przechodzić [COLOR_POSITIVE_TEXT] Góry [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] Ignoruje koszty terenowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] Może zaatakować [COLOR_POSITIVE_TEXT] przez przeszkody [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] +33% silniejsze [COLOR_POSITIVE_TEXT] Przechwytywanie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] +33% silniejsze [COLOR_POSITIVE_TEXT] Przechwytywanie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] +34% silniejsze [COLOR_POSITIVE_TEXT] Przechwytywanie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[ICON_AIR] 20% szans na [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] samolotów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[ICON_AIR] 40% szans na [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] samolotów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[ICON_AIR] 50% szans na [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] samolotów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[ICON_AIR] 100% na [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] samolotów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', 'Przechwycenie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] 100% szansa na przechwycenie [COLOR_POSITIVE_TEXT] Air Units [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] Ignoruje granice kulturowe [NEWLINE] [ICON_DETECT] można zobaczyć tylko przez jednostki z sonaru lub 1 płytki z dala', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] +33% w [COLOR_POSITIVE_TEXT] Las / Dżungla [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', 'Bonus kontra Land (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', 'Bonus kontra Land (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', 'Kara kontra Land (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH] -50% vs [COLOR_NEGATIVE_TEXT] grunty [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MARCH_HELP', '[ICON_HEAL] Atakowanie i ruchu nie uniemożliwiają uzdrowienie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +10 Healing [ENDCOLOR] dla jednostek w 1 płytki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +5 Healing [ENDCOLOR] na kolei dla jednostek sąsiednich płytek [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +5 Healing [ENDCOLOR] na przełomie tego urządzenia, gdy [COLOR_POSITIVE_TEXT] Poza Friendly Terytorium [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', 'Najemnik', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50% [COLOR_POSITIVE_TEXT] Upgrade Koszt [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT] Ruch [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] +33% w [COLOR_POSITIVE_TEXT] Las / Dżungla [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] +20% Siła', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', 'Góral', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] można przejść nad [COLOR_POSITIVE_TEXT] Góry [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Kara vs Mounted (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] Wielcy generałowie [ENDCOLOR] przenieść na szybkości tego urządzenia, jeśli zaczną kolej [COLOR_POSITIVE_TEXT] ułożone [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] musi skonfigurować do ataku dystansowego', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] atak [ENDCOLOR] na terytorium dziećmi', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', 'Ochrona Narodowy', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty Atakowanie Statki (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', 'Naval Recon I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_HEAL] Czy [COLOR_POSITIVE_TEXT] leczyć [ENDCOLOR] terytorium poza przyjazny', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', 'Naval Recon II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] +1 Ruch [NEWLINE] [ICON_MOVES] Próby [COLOR_POSITIVE_TEXT] wycofać [ENDCOLOR] w walce wręcz', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', 'Oblężenie marynarki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] ufortyfikowanych jednostek [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT] Ruch [ENDCOLOR] [NEWLINE] [ICON_DETECT] +1 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', 'Nowa jednostka', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'Nowa jednostka', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] Nie Capture Miasta', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', 'Brak Obronne Bonusy terenowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] Brak Obronne Bonusy terenowe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] Nie można wprowadzić głęboki ocean aż Astronomii', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] Nie można wprowadzić głęboki ocean', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] +33% w [COLOR_POSITIVE_TEXT] Friendly Terytorium [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] Jednostka może zaatakować [COLOR_NEGATIVE_TEXT] jednostki [ENDCOLOR], tylko miasta', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] może nie Melee atak', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', 'Kanał Panamski', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Ruch statków', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', 'Partenon', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] +10% Siła z wielkich generałów, admirałów', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] Czy [COLOR_POSITIVE_TEXT] Paradrop [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '[ICON_HEAL] Leczy 25 Obrażenia Jeśli Zabójstwa jednostkę', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', 'Falanga', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Zamontowany [ENDCOLOR] i [COLOR_POSITIVE_TEXT] [ENDCOLOR] Żołnierz jednostki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] Screeny [ENDCOLOR] pokonał wroga [COLOR_POSITIVE_TEXT] Statki [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] +1 [COLOR_POSITIVE_TEXT] Zasięg [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] Czy [COLOR_POSITIVE_TEXT] atak dwukrotnie [ENDCOLOR] na poziomie 90% [ICON_RANGE_STRENGTH] wahał siłę', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', 'Obrona vs kilkudniowe (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Obrażenia [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] można wprowadzić [COLOR_POSITIVE_TEXT] Rival Territory [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', 'Recon I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] +2 Sight', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', 'Recon II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] +1 Ruch [NEWLINE] [ICON_MOVES] może korzystać z dróg wroga', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', 'Recon III', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] Czy paradrop 10 płytek.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', 'Bonus vs Morze (25)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] morze [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', 'Bonus vs Morze (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] morze [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', 'Sonar', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] widzę [COLOR_POSITIVE_TEXT] Okręty podwodne [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] +1 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH] +15% w [COLOR_POSITIVE_TEXT] OTWARTY [ENDCOLOR] Terrain (NO Hills, Las lub Jungle)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] ufortyfikowanych jednostek [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', 'Potyczka', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] Próby wycofania się z walki wręcz i rozpoczęła', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] +1 dostawka [COLOR_POSITIVE_TEXT] Przechwytywanie [ENDCOLOR] może być wykonana na przełomie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] Walka może tworzyć [COLOR_POSITIVE_TEXT] Wielcy generałowie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] Walka najprawdopodobniej Tworzenie [COLOR_POSITIVE_TEXT] Wielcy generałowie [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] atakowanie +15% [COLOR_POSITIVE_TEXT] Miasta [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Ranni [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_HELP', '[ICON_HEAL] Może leczyć [COLOR_POSITIVE_TEXT] Poza Friendly Territory [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +20 Healing [ENDCOLOR] na kolei', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] +5 [COLOR_POSITIVE_TEXT] uzdrowienie [ENDCOLOR] terytorium poza przyjazną [NEWLINE] [ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] Jednostka zostanie [COLOR_POSITIVE_TEXT] Heal każdym kroku [ENDCOLOR], nawet jeśli wykona akcję [NEWLINE] [ICON_MOVES] Jednostka będzie próbował się wycofać w obliczu ataku wręcz', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', 'Tłumienie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Vanguard [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', 'Survivalist', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '[ICON_HEAL] +20 [COLOR_POSITIVE_TEXT] uzdrowienie [ENDCOLOR] terytorium poza przyjazną [NEWLINE] [ICON_MOVES] Nie Koszt ruchu na plądrowanie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR] jednostki +1 Sight', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] +1 Ruch [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Naval [ENDCOLOR] jednostki +1 Sight', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1', 'Okopy I', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na otwartym terenie [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2', 'Okopy II', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na otwartym terenie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3', 'Rowy III', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Defense [ENDCOLOR] na otwartym terenie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', 'Może wjechać na terytorium rywala bez otwartych granic, ale traci 25% pierwotnej wytrzymałości religijnej dla każdego kolei oni kończą na takiej płytki. Jednostka zostanie wyeliminowany, gdy siła religijna jest 0.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] mocne [ENDCOLOR] szt.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] +100%, gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR] [NEWLINE] +1 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR], gdy [COLOR_POSITIVE_TEXT] rozpoczęła [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', 'Atak ziemia Karny (50)', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[ICON_RANGE_STRENGTH] -50% Atak kontra [COLOR_NEGATIVE_TEXT] Masa i okręty [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] Szybciej w [COLOR_POSITIVE_TEXT] Lasy i Jungle [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1. Ruch', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT] 2 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT] Sight Zakres [ENDCOLOR]', '', '');





UPDATE LoadedFile SET Value=1, PL_PL=1 Where Type='Promotions.sql';

