/* The sql commands and text below were formulated in the Stories tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1563932649
If you make any changes be sure to update the spreadsheet also.*/

/*  Terrain  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING', 'Rzeka Powodzie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_DESC', 'Częste sezonowe powodzie tej rzeki zapewniają niezwykle podatny wierzchniej warstwy gleby dla rolnictwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_1', 'Płacić za nowych kanałów irygacyjnych wzdłuż rzeki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_2', 'Badania lepsze sposoby ochrony domów przed powodzią.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_3', 'Niech miejscowi sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_1', '[ICON_TEAM_3] poprawiła Nowy nawadniania rzeki [ICON_FOOD] Jedzenie dla {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_2', '[ICON_TEAM_3] Nowy [ICON_RESEARCH] Badanie trwa do ochrony obywateli {1} od powodzi.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_3', '[ICON_TEAM_3] poprawiła Nowy nawadniania rzeki [ICON_GOLD] dochód Gospodarczy dla {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE', 'Pustynia Adobe', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_DESC', 'Niezwykle wytrzymały i piękny postać gliny adobe budowy został opracowany poza {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_1', 'Użyj charakterystyczny styl do zwiększenia naszych zabytków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_2', 'Użyj cegłę praktycznej konstrukcji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_3', 'Niech miejscowi sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_1', '[ICON_TEAM_3] nowy styl cegieł adobe zwiększyło [ICON_CULTURE] Kultura {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_2', '[ICON_TEAM_3] Innowacje w budownictwie adobe poprawiła [ICON_PRODUCTION] Produkcja blisko {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_3', '[ICON_TEAM_3] nowa forma konstrukcji adobe poprawiło [ICON_GOLD] Gospodarka w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS', 'Śnieg Sanie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_DESC', 'Innowacje w podróży wykonane teren w pobliżu alpejskiego {2} bardziej dostępne.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_1', 'Użyj sanki dla ras rekreacyjnych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_2', 'Użyj sanki do wykorzystania nowych zasobów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_3', 'Niech miejscowi sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_1', '[ICON_TEAM_3] Innowacje w sanki monit nowe rasy w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_2', '[ICON_TEAM_3] Innowacje w sanki otwiera nowe zasoby w pobliżu {2} do eksploatacji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_3', '[ICON_TEAM_3] Innowacje w sanki poprawiło [ICON_GOLD] Gospodarka w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE', 'Mountain Refuge', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_DESC', 'Szczyt górski w pobliżu malowniczych {2} jest niezwykle nadaje się do zamieszkania.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_1', 'Budować duchową świątynię dla odpoczynku i medytacji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_2', 'Zbudować naukową rekolekcje studiować gwiazdy i pory roku.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_3', 'Niech miejscowi sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_1', '[ICON_TEAM_3] wzrosła Mountaintop duchowe schronienie [ICON_CULTURE] Kultura w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_2', '[ICON_TEAM_3] wzrosła Mountaintop rekolekcje naukowe [ICON_RESEARCH] Nauka w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_3', '[ICON_TEAM_3] Handlarze sprzedają towary wśród użytkowników szczycie góry w pobliżu {2}.', '', '');
/*  POPRAWKI  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING', 'Rolnictwo handlowa', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_DESC', 'Osoby zamożne zamiar kupić i komercjalizacji małych gospodarstw w pobliżu {2}, chyba że miejscowi rolnicy mogą zwiększyć swoje dochody.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_1', 'Zainwestuj w kulturze tradycyjnej hodowli.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_2', 'Wspieranie łączenia zachęt skarbowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_3', 'Umożliwiają zakupy bez zakłóceń.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_1', '[ICON_TEAM_3] Tradycyjne rolnicy są silne część [ICON_CULTURE] Kultury pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_2', '[ICON_TEAM_3] Komercjalizacja poprawiła rolnicze [ICON_FOOD] Jedzenie w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_3', '[ICON_TEAM_3] Wykupy poprawiła rolnicze [ICON_GOLD] Złoto w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION', 'Rozbudowa kopalni', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_DESC', 'Operatorzy kopalni w pobliżu {2} odkryto cenną rudę, ale pracownicy protestują niebezpieczne warunki w nowych wałów branżowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_1', 'Udzielić wsparcia krajowego w celu poprawy bezpieczeństwa kopalni.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_2', 'Korzystać ze środków własnych zatrudnić wyłączniki strajk.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_3', 'Niech operator kopalni tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_1', '[ICON_TEAM_3] Górnicy w pobliżu {2} są [ICON_HAPPINESS_1] Wszystkiego o bezpieczniejszych warunków pracy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_2', '[ICON_TEAM_3] Szybko kończące strajk {2} ''s kopalni rozszerzony [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_3', '[ICON_TEAM_3] kopalni w pobliżu {2} odkrył [ICON_GOLD] zyskiem nową żyłę rudy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS', 'Protesty wieś', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_DESC', 'Obywatele w pobliżu miejscowości {2} walczą pod wysokim biedy i przestępczości.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_1', 'Poprawy edukacji dla ubogich do zakwalifikowania się do lepszej pracy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_2', 'Poprawy policji do niższych wskaźników przestępczości.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_3', 'Niech Wójt się tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_1', '[ICON_TEAM_3] wioska w pobliżu {2} poprawy [ICON_RESEARCH] Edukacja dla biednych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_2', '[ICON_TEAM_3] Mieszkańcy wsi w pobliżu {2} są [ICON_HAPPINESS_1] Wszystkiego o niższe wskaźniki przestępczości.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_3', '[ICON_TEAM_3] silniejsza obecność policji poprawiło [ICON_GOLD] gospodarka wsi niedaleko {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND', 'Popyt plantacji', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_DESC', 'Popyt rośnie na uprawach plantacji w pobliżu {2}, gdzie pracownicy zbierają pola za niskie wynagrodzenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_1', 'Ustanowienie przepisów w celu poprawy płac i warunków pracy dla pracowników.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_2', 'Niższe bariery handlowe na rzecz rozwoju gospodarki eksportowej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_3', 'Niech właściciele plantacji tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_1', '[ICON_TEAM_3] zbieracze Plantation w pobliżu {2} są [ICON_HAPPINESS_1] Wszystkiego o lepsze warunki pracy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_2', '[ICON_TEAM_3] Niższe bariery handlowe poprawiły plantacji [ICON_FOOD] jedzenie w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_3', '[ICON_TEAM_3] Rosnące zapotrzebowanie na ulepszone plantacji [ICON_GOLD] Przychody w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS', 'Obóz Zwierzęta egzotyczne', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_DESC', 'Egzotyczne zwierzęta zostały odkryte poza obozem w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_1', 'Załóż zwierzę zachowanie poprawić turystykę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_2', 'Budowanie ekstrawagancki myśliwski.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_3', 'Niech miejscowi sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_1', '[ICON_TEAM_3] egzotyczne przyrody poprawę turystyki [ICON_CULTURE] kultura pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_2', '[ICON_TEAM_3] wzrosła myśliwski [ICON_FOOD] jedzenie z egzotycznych zwierząt w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_3', '[ICON_TEAM_3] Egzotyczne zwierzęta odkryte w pobliżu {2} poprawiła polowania [ICON_GOLD] złota.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY', 'Jakość Quarry', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_DESC', 'Niezwykle wysoka jakość skały żyły odkryto w kamieniołomie na zewnątrz {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_1', 'Zatrudnić rzemieślników do jednostek rzeźby ze skały.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_2', 'Sfinansowanie dodatkowych maszyn do górnictwa prędkość.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_3', 'Niech kierownik kamieniołomu tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_1', '[ICON_TEAM_3] Wspaniałe rzeźby poprawiła [ICON_CULTURE] kultura pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_2', '[ICON_TEAM_3] kamieniołom w pobliżu {2} rozszerzonej [ICON_PRODUCTION] Production.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_3', '[ICON_TEAM_3] kamieniołom w pobliżu {2} odkrył [ICON_GOLD] zyskiem rocka żyły.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER', 'Drewno egzotyczne', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_DESC', 'Egzotyczne drzewa zostały odkryte w pobliżu Tartak poza {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_1', 'Utworzyć park narodowy w celu poprawy turystyki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_2', 'Budowanie nowej infrastruktury dla eksportu drewna.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_3', 'Niech firma graty tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_1', '[ICON_TEAM_3] poprawiła egzotyczny park narodowy turystyka [ICON_CULTURE] kultura pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_2', '[ICON_TEAM_3] Obszerne [ICON_PRODUCTION] infrastruktura produkcyjna w pobliżu {2} wywozi cenne drzewa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_3', '[ICON_TEAM_3] drzewa egzotyczne odkryte w pobliżu {2} ulepszonych tarcicy [ICON_PRODUCTION] zyski.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING', 'Pastwiska Szermierka', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_DESC', 'Rolnicy w pobliżu {2} chcą budować ogrodzenia, aby utrzymać się zwierząt gospodarskich, ale farmerzy obawiają się utraty pastwisk.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_1', 'Wspieranie wysiłków rolników do ogrodzenia terenu.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_2', 'Wspieranie wysiłków hodowców zachować otwarty zakres.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_3', 'Niech miejscowi obywatele się tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_1', '[ICON_TEAM_3] Ogrodzenie pastwiska w pobliżu {2} poprawy [ICON_FOOD] jedzenie z okolicznych pól uprawnych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_2', '[ICON_TEAM_3] Ranchers pobliżu {2} wzrosła [ICON_PRODUCTION] Produkcja z otwartym przedziale.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_3', '[ICON_TEAM_3] kompromis pomiędzy hodowców i rolników w pobliżu {2} poprawie lokalnego [ICON_PRODUCTION] Gospodarka.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND', 'Popyt wędkowanie', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_DESC', 'Popyt rośnie w życiu morskich w morzu w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_1', 'Budowanie akwarium dla obywateli miasta, aby zobaczyć egzotyczne stworzenia morskie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_2', 'Budować infrastrukturę, aby rozwinąć w lokalnym sektorze rybołówstwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_3', 'Niech lokalne rybołówstwo tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_1', '[ICON_TEAM_3] acquarium rzadkich życia morskiego wzrosła kultury w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_2', '[ICON_TEAM_3] Rybacy w pobliżu {2} rozszerzonej [ICON_FOOD] produkcji żywności.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_3', '[ICON_TEAM_3] Rzadko życie morskie w pobliżu {2} poprawy [ICON_GOLD] złota z połowów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION', 'Oraz rozszerzeń', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_DESC', 'Firma chce rozszerzyć olej pobliżu {2}, ale przemysł turystyczny jest zaniepokojony wpływem na krajobraz.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_1', 'Wspieranie turystyki biznesowej z nowym pomnikiem narodowym.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_2', 'Wspieranie rozwoju oleju z nowych dróg i infrastruktury.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_3', 'Niech firmy się tym zajmę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_1', '[ICON_TEAM_3] pomnik pięknej ziemi w pobliżu {2} poprawić turystyki [ICON_CULTURE] Kultury.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_2', '[ICON_TEAM_3] w pobliżu Nowa infrastruktura rozszerzony oleju [ICON_PRODUCTION] Produkcja {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_3', '[ICON_TEAM_3] naftowej [ICON_GOLD] Zyski wzrosły blisko {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING', 'Likwidacja platforma', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_DESC', 'Kilka platformach wiertniczych w dziedzinie ropy naftowej w pobliżu {2} wyczerpały zapas oleju.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_1', 'Wsparcie rybołówstwa komercyjnego, konwertując wiertnice do sztucznych raf.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_2', 'Demontażu i ponownego użycia komponentów dla platform innych miejscach na polu naftowym.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_3', 'Niech firma sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_1', '[ICON_TEAM_3] Wiertniczych konwertowane do sztucznych raf ulepszonych połowowy [ICON_FOOD] jedzenie w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_2', '[ICON_TEAM_3] Ponowne użycie wyczerpane elementy wieży wiertniczej poprawiła [ICON_PRODUCTION] Produkcja blisko {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_3', '[ICON_TEAM_3] sprzedaży wycofane z eksploatacji platformy wiertnicze poruszonych [ICON_GOLD] Złoto w pobliżu {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION', 'Fort Rozbudowa', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_DESC', 'Generałem fortu w pobliżu {2} pragnie rozpocząć nowe starania budowlanych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_1', 'Badania nowych technologii wojskowych w forcie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_2', 'Upgrade zdolności obronnych fortu do Cytadeli.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_3', 'Niech ogóle sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_1', '[ICON_GOLD] Złoto: +6', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_2', 'Fort staje Cytadela.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_1', '[ICON_TEAM_3] fort w pobliżu {2} spienione personel i wyposażenie badawcze.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_2', '[ICON_TEAM_3] fort w pobliżu {2} rozszerzony do Cytadeli.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_3', '[ICON_TEAM_3] producent pobliżu zewnątrz fortu {2} sprzedaje nowe technologie broni.', '', '');
/*  BUDYNKI  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM', 'Boom spichlerz mieszkańców', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_DESC', 'Poprawki do spichlerza w {2} przyciągają obywateli miasta.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_1', 'Zapewnienie środków na obywateli, aby znaleźć nowe miejsce do życia.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_2', 'Zatrudnić obywateli na program robót publicznych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_1', '[ICON_TEAM_2] Osadnik: +1', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_2', '[ICON_TEAM_2] Pracownicy: +2', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_1', '[ICON_TEAM_3] rząd {2} finansowane nowego programu rozliczeniowego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_2', '[ICON_TEAM_3] rząd {2} finansowane nowy program robót publicznych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_3', '[ICON_TEAM_3] Ludność jest dynamicznie rozwijającym się w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT', 'Rozwój Kuźnia', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_DESC', 'Nowy proces wytapiania opracowany przez kuźni w {2} jest potencjalnie niebezpieczne dla pracowników.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_1', 'Finansowania badań, aby proces bezpieczniejsze.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_2', 'Wyślij zasoby do natychmiastowego procesu do produkcji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_1', '[ICON_TEAM_3] Obszerne [ICON_RESEARCH] Prowadzone są badania zmierzające do stworzenia bezpieczniejszego procesu wytapiania w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_2', '[ICON_TEAM_3] nowy proces wytapiania szybko został oddany do [ICON_PRODUCTION] Produkcja w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_3', '[ICON_TEAM_3] poprawiła nowy proces wytapiania [ICON_GOLD] zyski w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY', 'Rynek Monopoly', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_DESC', 'Biznesu świadczących duże dotacje do lokalnych szkół jest formowanie monopol na rynku w {2}, jazdy w górę ceny.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_1', 'Rozbić monopol na niższe ceny.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_2', 'Wsparcie darowizny edukacyjne z zachęt skarbowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_3', 'Zbierać podatki od wyższych zysków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_1', '[ICON_TEAM_3] Obywatele {2} są [ICON_HAPPINESS_1] Szczęśliwy jak ceny spadają.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_2', '[ICON_TEAM_3] nowy monopol w {2} przekazuje ciężko [ICON_RESEARCH] Edukacji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_3', '[ICON_TEAM_3] monopol na {2} ''s rynku wzrosła [ICON_GOLD] Złote zyski.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY', 'Kontrowersje biblioteki', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_DESC', 'Kontrowersyjna książka o rasizmie w historii {2} jest iskrzenie zamieszki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_1', 'Finansowanie głębsze badania w burzliwej przeszłości miasta.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_2', 'Ban książkę, aż zamieszki zanikać.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_3', 'Powinno to zwiększyć sprzedaż książek.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] zaczyna kontrowersyjna książka dalej [ICON_RESEARCH] Badania nad historią {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Zamieszki w {2} znikną jako książka powodując [ICON_HAPPINESS_4] Gniew została zakazana.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] kontrowersyjna książka [ICON_GOLD] sprzedają się dobrze w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY', 'Pomnik Kontrowersje', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_DESC', 'Obywatele {2} protestują stary pomnik imperialistycznej ekspansji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_1', 'Daj przemówienia promujące pokojowego kultury.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_2', 'Rozpowszechniać propagandę wspieranie militarystyczny ekspansję.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] Ciche [ICON_CULTURE] pokazy kulturalne zamiatać przez {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Propaganda w {2} zmniejszonym [ICON_HAPPINESS_4] Anger o imperializm.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] kontrowersyjny pomnik jest poprawa turystyki [ICON_GOLD] gospodarki w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS', 'Ściankach Slums', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_DESC', 'Rozwój {2} rozszerzony poza murów miejskich, z pogarszającą wewnętrzne okręgi do slumsów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_1', 'Rewitalizacja starego miasta z programów kulturalnych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_2', 'Zburzyć slumsy, aby zrobić miejsce dla przedsiębiorstw produkcyjnych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_1', '[ICON_TEAM_3] śródmieścia {2} ożywiona jego [ICON_CULTURE] kultura.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_2', '[ICON_TEAM_3] Slums zburzony w {2} wyczyszczone miejsca na [ICON_PRODUCTION] Produktywnej przedsiębiorstw.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_3', '[ICON_TEAM_3] Nowe firmy wzrosła [ICON_GOLD] przychody złoto {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT', 'Koszary Rekrutacja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_DESC', 'Obywatele {2} są źli o przymusowej w walce.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_1', 'Niższe stawki poboru w mieście.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_2', 'Zainwestuj w ogólnopolskiej propagandy w celu zwiększenia zaciągu wojskowego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_TIP_2', '[ICON_WAR] Nowe jednostki wojskowe: 2', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_1', '[ICON_TEAM_3] Zmniejszenie stawki poboru obniżona [ICON_HAPPINESS_4] furia w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_2', '[ICON_TEAM_3] koszary A w {2} zamieszczenia nowych wojskowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_3', '[ICON_TEAM_3] poprawiła [ICON_GOLD] Przychody w {2} propaganda obligacji wojennych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE', 'Koloseum Widownia', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_DESC', 'Koloseum w {2} jest rysunek rekordowe tłumy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_1', 'Pokaż skomplikowane konkursy zabawić publiczność.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_2', 'Gościć ogromne pokazy patriotycznej propagandy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_1', '[ICON_TEAM_3] Zawody przyciągają [ICON_HAPPINESS_1] Wszystkiego tłumy w {2} Koloseum.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_2', '[ICON_TEAM_3] Koloseum z {2} organizuje masowe pokazy [ICON_CULTURE] propagandy kulturalnej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_3', '[ICON_TEAM_3] Ulepszenia {2} Koloseum podniesiona [ICON_GOLD] przychody złota.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED', 'Stabilny Rasa', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_DESC', 'Stajnie w {2} podniesiona niezwykle zwinny, silny i pewny siebie rasę koni.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_1', 'Szkolić je na wyścigach konnych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_2', 'Szkolenie ich jako koni bojowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_3', 'Niech stabilne właściciele decydują.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_TIP_2', '[ICON_WAR] Jednostki nowego konia: 2', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_1', '[ICON_TEAM_3] nowa rasa konia wyścigowego poprawiła [ICON_HAPPINESS_1] Szczęście w {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_2', '[ICON_TEAM_3] wojskowy {2} podniesione nowej rasy koni bojowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_3', '[ICON_TEAM_3] poprawiła [ICON_GOLD] Przychody w {2} nowa rasa konia.', '', '');
/*  CITYSTATES  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION', 'Miasto-państwo Imigracja', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_DESC', 'Niektórzy pracownicy czują się nowi imigranci z miasta-państwa {2} są przy pracy z dala od obywateli swojej cywilizacji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_1', 'Płacić za programy dać imigrantom ścieżkę do obywatelstwa.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_2', 'Deportować imigrantów i skonfiskować ich domów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_3', 'Wypowiedzieć stereotypów etnicznych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_1', '[ICON_INFLUENCE] Wpływ: +70', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_2', '[ICON_INFLUENCE] Wpływ: -70 [NEWLINE] [ICON_GOLD] Złoto: +200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_3', '[ICON_INFLUENCE] Wpływ: +10', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_1', '[ICON_TEAM_3] Imigranci z {2} zdobyć ścieżkę do obywatelstwa w imperium {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_2', '[ICON_TEAM_3] rząd {1} {deportowanych imigrantów z 2_target).', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_3', '[ICON_TEAM_3] rząd {1} wypowiedziana stereotypy o obywateli {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE', 'Kantor', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_DESC', 'Wartość waluty rośnie, i zagrożenia wynikające nierównowaga handlowa eksportu do boli {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_1', 'Ustaw stały kurs wymiany, aby umożliwić dalszy wywóz bez przeszkód.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_2', 'Ustanowienie przepisów w celu wzmocnienia waluty dalej, na koszt Citystate.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_3', 'Niech Twój Minister Finansów obsługiwać tę sprawę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_1', '[ICON_INFLUENCE] Wpływ: +70', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_2', '[ICON_INFLUENCE] Wpływ: -70 [NEWLINE] [ICON_GOLD] Złoto: +200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_3', '[ICON_INFLUENCE] Wpływ: +10', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_1', '[ICON_TEAM_3] stały kurs wymiany poprawie eksportu z {1} do {2}, zwiększenie [ICON_INFLUENCE] stosunków.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_2', '[ICON_TEAM_3] wzrosła walutą {1} znacznie na wartości, zapewniając [ICON_GOLD] złota kosztem {2} ''s gospodarki.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_3', '[ICON_TEAM_3] Zmiany w {1} ''s kursowych waluty poprawy eksportu do {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT', 'Incydent dyplomatyczny', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_DESC', 'Podczas wizyty w {2} to popełnił poważne faux pas podczas imprezy dyplomatycznej, w wyniku nieporozumienia kulturowego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_1', 'Wyślij prezenty i złożyć oficjalne przeprosiny za błąd, obiecując, nigdy do tego dopuścić ponownie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_2', 'Wyjaśnić działania są dopuszczalne w społeczeństwie, a nie będzie przepraszać za korzeni swojej cywilizacji.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_3', 'Niech twoje dyplomaci obsługiwać tę sprawę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_1', '[ICON_INFLUENCE] Wpływ: +70 [NEWLINE] [ICON_CULTURE] Kultura: -200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_2', '[ICON_INFLUENCE] Wpływ: -70 [NEWLINE] [ICON_CULTURE] Kultura: +200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_3', '[ICON_INFLUENCE] Wpływ: +10', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_1', '[ICON_TEAM_3] Przeprosiny po incydencie dyplomatycznym poprawiła [ICON_INFLUENCE] stosunki między {1} i {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_2', '[ICON_TEAM_3] Odmowa przeprosić za dziwactwach {1} ''s [ICON_CULTURE] kultury doprowadziły do ​​incydentu dyplomatycznego z {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_3', '[ICON_TEAM_3] {2} pomógł incydent dyplomatyczny z {1} z wizytą do zwiększenia zrozumienia kulturowego pomiędzy dwoma narodami.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME', 'Scholastic Sława', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_DESC', 'Aplikacje na studia w szkołach cenionych w swoim imperium są rosnące od zagranicznych studentów {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_1', 'Relax ograniczeń imigracyjnych dla studentów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_2', 'Ograniczyć rekrutację do studentów krajowych.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_3', 'Pozwalają dziekanów szkół do obsługi tego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_1', '[ICON_INFLUENCE] Wpływ: +70 [NEWLINE] [ICON_RESEARCH] Nauka: -200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_2', '[ICON_INFLUENCE] Wpływ: -70 [NEWLINE] [ICON_RESEARCH] Nauka: +200', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_3', '[ICON_INFLUENCE] Wpływ: +10', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_1', '[ICON_TEAM_3] jakość kształcenia oferowane studentom zagranicznym z {2} ulepszonych [ICON_INFLUENCE] stosunków z {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_2', '[ICON_TEAM_3] Nowe [ICON_RESEARCH] krajowe przepisy sprzyjają edukacji uczniów {1} na imigrantów z {2}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_3', '[ICON_TEAM_3] Zagraniczni studenci z {2} uciekają do szkół {1}.', '', '');
/*  Jednostki  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR', 'Scout Zbawiciel', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_DESC', 'Twój scout uratował dziecko wodza nomadów z zabójczą bestię. Wdzięczni myśliwi zaoferować gościnę w ich obozie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_1', 'Zadać kilka koczowników przyłączyć się do poszukiwań.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_2', 'Trenuj, aby szybko przenieść z łuków myśliwskich.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_3', 'Odpoczynek w obozie na chwilę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_1', 'Duplikaty i uzdrawia Scout.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_2', 'Zastępuje z Archera, który porusza się szybko.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_3', 'Zwiadowca uzdrawia i zyski 5 [ICON_WAR] Doświadczenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_1', '[ICON_TEAM_3] {2} {1} połączone z plemienia nomadów.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_2', '[ICON_TEAM_3] {2} {1} nauczył się używać łuków myśliwskich.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_3', '[ICON_TEAM_3] {2} {1} odpoczął po zapisaniu koczowniczy tryb dziecko.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES', 'Skaut Stories', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_DESC', 'Twój scout wyjazd daleko, padając ofiarą licznych niebezpieczeństw i odkrywając wiele cudownych krain. Obywatele swojej stolicy chętnie usłyszeć historie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_1', 'Wynajem pisarz do jednostek epickich poematów swoich podróżach.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_2', 'Zapewnić scout z nowego szkolenia i nowe bronie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_3', 'Pozwalają scout opowiedzieć swoją historię, a następnie przejść.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_1', '[ICON_CULTURE] Kultura: +100', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_2', 'Uzdrawia i aktualizacje do Sentinel.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_3', '[ICON_CULTURE] Kultura: +30', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_1', '[ICON_TEAM_3] eposów o podróżach Skauta zwiększyły [ICON_CULTURE] Kultura {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_2', '[ICON_TEAM_3] harcerz z {1} przeniesieni do nowej zbroi i broni.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_3', '[ICON_TEAM_3] Opowieści o podróżach Skauta zwiększyły [ICON_CULTURE] Kultura {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR', 'Znany wojownik', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_DESC', 'Twoje wojownicy zyskują popularność w swoim imperium, z opowieści śpiewane ich odwagę.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_1', 'Pozwól im powrócić do cywilnego życia.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_2', 'Wyślij im nowe bronie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_3', 'Wysłać do nich świeże dostawy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_1', 'Konwertuje do pracownika, który ignoruje koszty terenu.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_2', 'Konwertuje do szermierzem.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_3', 'Uzdrawia i zyski 5 [ICON_WAR] Doświadczenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_1', '[ICON_TEAM_3] Wojownicy {1} powrócił do życia cywilnego.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_2', '[ICON_TEAM_3] Wojownicy {1} otrzymał nowe bronie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_3', '[ICON_TEAM_3] Wojownicy {1} otrzymali świeże dostawy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER', 'Znany Archer', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_DESC', 'Twoje łucznicy zyskują popularność w swoim imperium, z opowieści o ich umiejętności strzeleckie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_1', 'Pozwól im odejść do cywila.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_2', 'Wyślij im nowe bronie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_3', 'Wysłać do nich świeże dostawy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_1', 'Konwertuje do pracownika, który ignoruje koszty terenu.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_2', 'Konwertuje do Composite Bowman.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_3', 'Uzdrawia i zyski 5 [ICON_WAR] Doświadczenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_1', '[ICON_TEAM_3] Łucznicy {1} na emeryturze do cywila.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_2', '[ICON_TEAM_3] Łucznicy {1} otrzymał nowe bronie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_3', '[ICON_TEAM_3] Łucznicy {1} otrzymali świeże dostawy.', '', '');
/*  CUSTOM  */
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB', 'Teren Grab', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_DESC', 'Obywatele {2} żądać lepszej ziemi do pracy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_1', 'Zapłacić załączyć więcej ziemi w imperium.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_2', 'Poborowy dysydentów i umieścić je do pracy.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_3', 'Niech burmistrz sobie z tym poradzić', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_1', '[ICON_TEAM_6] Nowe Płytki: 3', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_2', '[ICON_TEAM_2] Nowy pracownik: 1', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_3', '[ICON_TEAM_6] Nowe Płytki: 1', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_1', '[ICON_TEAM_3] Obywatele {2} załączonego dużą nowe terytorium.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_2', '[ICON_TEAM_3] Dysydenci w {2} zostali wcieleni do siły roboczej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_3', '[ICON_TEAM_3] Obywatele {2} pracować ziemię nowo załączony.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES', 'Mercenaries barbarzyńskich', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_DESC', 'Grupa wrogich najeźdźców na swoich granicach może zmienić strony - w cenie.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_1', 'Zatrudnić je do cywilnej siły roboczej.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_2', 'Wynająć im najemników jako wojskowe.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_3', 'Zasadzkę zdrajców i loot ich dostaw.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_1', '[ICON_TEAM_2] Nowe Pracownicy: 1', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_2', '[ICON_TEAM_2] Nowe jednostki wojskowe: 2', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_3', '[ICON_GOLD] Złoto: +25', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_1', '[ICON_TEAM_3] Barbarzyńcy dołączył do cywilnej zatrudnia {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_2', '[ICON_TEAM_3] najemnicy barbarzyńców wstąpił do armii {1}.', '', '');
REPLACE INTO Language_PL_PL (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_3', '[ICON_TEAM_3] najemnicy barbarzyńców w zasadzkę przez {1}.', '', '');







UPDATE Loaded File SET Value=1, PL_PL=1 Where Type='Stories.sql';


