/* The sql commands and text below were formulated in the Core tab of the Google Spreadsheet 'CAT_Language'.
https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGtjX2JldHBzdXhRbGNxVFgxT1E2OHc&usp=drive_web#gid=4
If you make any changes be sure to update the spreadsheet also.*/
/* 사막 캐러밴 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS', '사막 캐러밴', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_HELP', '[ICON_GOLD] 골드 : 5퍼센트 모든 도시에있는 각 고급 자원.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_STRATEGY', '사막의 캐러밴은 사치에서 제국의 금을 증가시킨다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_PEDIA', '아라비아을 통해 무역로 거의 3 천년 고대 중국, 고대 인도, 고대 티베트, 페르시아 제국과 지중해 국가에서 상인, 상인, 순례자, 선교사, 군인, 유목민과 도시 거주자 사이, 문화, 상업, 기술 교환을위한 중요한 경로했다 .', '', '');
/* Citystates */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED', '! 당신은 [: textkey] [1_CivName] 근처 바바리안 그룹을 죽인 그들은 감사하고, 그들과 함께 당신의 [ICON_INFLUENCE]에 미치는 영향은 15 증가했다!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_BARB_QUEST_LONG', '[ICON_CITY_STATE] {1_CivName : textkey]이 야만인 패배 싶다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_IMPROVE_RESOURCES', '자원 향상', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_IMPROVE_RESOURCES_TT', '즉시 않았 음 또는 약탈 내보낼 자원 도시 국가의 통제를 개선하기 위해 도시 국가의 동맹에 {1_num] [ICON_GOLD] 골드를 지불해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_YIELDS', '수율 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_YIELDS_TT', '플레이어가 될 경우는 [COLOR_POSITIVE_TEXT] 앨리 [ENDCOLOR]이 도시 국가의 이러한 플레이어가받을 수익률이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_QUESTS', '퀘스트 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_ALLIED_WITH', '앨리 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MINORCIV_PROTECTED_BY', '프로텍터 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_RESOURCES', '수출 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_TRAIT', '특성 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_PERSONALITY', '개성 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MINORCIV_PROTECTED_DESC', '다른 문명 도시 국가를 보호하기 위해 선택할 수 있습니다. 이 도시 국가에 전쟁을 선언하는 것은 그 보호 보답으로 당신에 전쟁을 선포하게됩니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_CULTURE_BONUS', '당신은 당신의 도시에서 그 (것)들에서 [COLOR_POSITIVE_TEXT] [ICON_CULTURE] 문화 [ENDCOLOR] 받고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_FOOD_BONUS', '당신은 당신의 도시에서 그 (것)들에서 [COLOR_POSITIVE_TEXT] [ICON_FOOD] 식품 [ENDCOLOR] 받고 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_MILITARY_BONUS', '그들은 당신에게 [COLOR_POSITIVE_TEXT] 새로운 군사 유닛은 [ENDCOLOR] 매일 몇 차례를 보낼 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_BASE', '[ICON_INFLUENCE]에 미치는 영향은 {1_CivName : textkey] 당신이 지금 포인트 증가했다 [COLOR_POSITIVE_TEXT] 친구 ENDCOLOR] [NEWLINE] [NEWLINE] {2_DetailsS​​tring] 그들은 또한 당신을 통해 단위를 이동 할 수있는 권한을 부여했다. 자신의 영토.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_CULTURE', '[COLOR_POSITIVE_TEXT] 문화 [ENDCOLOR] 도시 국가로, 그들은 당신에게 당신의 도시 [ICON_CULTURE]을 증가 예술의 희귀 작품을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MILITARISTIC', '[COLOR_POSITIVE_TEXT] 군국주의 [ENDCOLOR] 도시 국가로, 그들은 종종 당신에게 군대를 줄 것이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MARITIME', '[COLOR_POSITIVE_TEXT] 해양 [ENDCOLOR] 도시 국가로, 그들은 당신의 도시로 [ICON_FOOD] 음식을 내 보냅니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MERCANTILE', '[COLOR_POSITIVE_TEXT] 상업 [ENDCOLOR] 도시 국가로, 그들의 시장은 사람들에게 이국적인 [ICON_HAPPINESS_1] 행복의 제품을 제공하고 있습니다!)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_RELIGIOUS', '[COLOR_POSITIVE_TEXT] 종교 [ENDCOLOR] 도시 국가로, 그들은 당신과 함께 [ICON_PEACE] 신앙 의식의 지식을 공유!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_FRIENDS_LOST_BASE', '[ICON_INFLUENCE]에 미치는 영향은 {1_CivName : textkey}는 [COLOR_POSITIVE_TEXT] 친구 [ENDCOLOR ... [NEWLINE] [NEWLINE] {2_DetailsS​​tring] 또한, 당신의 단위가 더 이상 없다 더 이상 지점으로 감소 자신의 영역을 통해 이동 할 수있는 권한.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_CULTURE', '(분실 [ICON_CULTURE] 당신의 도시 문화)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_FRIENDS_MILITARISTIC', '그들은 더 이상 당신에게 군대를 줄 것이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_MARITIME', '(분실 [ICON_FOOD] 당신의 도시에있는 음식)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_MERCANTILE', '(분실 [ICON_HAPPINESS_1] 행복)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_RELIGIOUS', '(분실 [ICON_PEACE] 믿음)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_BASE', '[ICON_INFLUENCE]에 미치는 영향은 {2_MinorCivName : textkey.} 당신은 지금 자신의 [COLOR_POSITIVE_TEXT] ALLY [ENDCOLOR] [NEWLINE] [NEWLINE] {3_DetailsS​​tring] [NEWLINE] [NEWLINE] {1_ResourceDetailsS​​tring있는 점에 증가 ]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_BASE_PASSED', '[ICON_INFLUENCE]에 미치는 영향은 {3_MinorCivName : textkey.} : 그들의 ALLY [ENDCOLOR] [NEWLINE] [NEWLINE] {4_DetailsS​​tring] [당신이 [COLOR_POSITIVE_TEXT] 대신하게 [textkey] [1_CivName]이 포인트 증가했다 NL] [NEWLINE] {2_ResourceDetailsS​​tring]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_CULTURE', '[COLOR_POSITIVE_TEXT] 문화 [ENDCOLOR] 도시 국가로, 그들은 당신에게 당신의 도시 [ICON_CULTURE]을 증가 예술의 희귀 작품을 제공합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MILITARISTIC', '[COLOR_POSITIVE_TEXT] 군국주의 [ENDCOLOR] 도시 국가로, 그들은 정기적으로 당신에게 군대를 줄 것이다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MARITIME', '[COLOR_POSITIVE_TEXT] 해양 [ENDCOLOR] 도시 국가로, 그들은 이제 도시에 대형 [ICON_FOOD] 식품 수출을합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MERCANTILE', '[COLOR_POSITIVE_TEXT] 상업 [ENDCOLOR] 도시 국가로, 그들의 시장은 제국에 걸쳐 이국적인 [ICON_HAPPINESS_1] 행복 제품의 무역을 확산!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_RELIGIOUS', '[COLOR_POSITIVE_TEXT] 종교 [ENDCOLOR] 도시 국가로, 그들은 당신에게 그들의 가장 소중하게 [ICON_PEACE] 믿음의 유물을 줘!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_ALLIES_LOST', '[ICON_INFLUENCE]에 미치는 영향은 {1_CivName : textkey.} 다음과 같은 자신의 [COLOR_POSITIVE_TEXT] ALLY [ENDCOLOR] [NEWLINE] [NEWLINE] {2_DetailsS​​tring] [NEWLINE] [NEWLINE] 더 이상 지점으로 감소 그들은 더 이상 그들의 전략과 럭셔리 자원을 부여하지 않습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_ALLIES_PASSED', '[COLOR_NEGATIVE_TEXT] {1_CivName : textkey!] : [COLOR_NEGATIVE_TEXT] 새로운 동맹 [ENDCOLOR] 도시 국가의 [NL에게 그들을 만들기, 당신보다 [ENDCOLOR] 이제 [textkey] [2_MinorCivName]에 [ICON_INFLUENCE] 더 많은 영향을 ] [NEWLINE] {3_DetailsS​​tring] [NEWLINE] [NEWLINE] 이와 같이, 그들은 더 이상 그들의 전략과 럭셔리 자원을 부여하지 않습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_ALLIES_MILITARISTIC', '그들은 당신의 군대에 적은 단위 기여할 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_MARITIME_TT', '친구가 [COLOR_POSITIVE_TEXT] 해양 [ENDCOLOR] 도시 국가는 도시로 [ICON_FOOD] 음식을 제공 할 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_TT', '[ICON_INFLUENCE] 현재 {1_statusType} {2_statusText} {3_rate]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_INFLUENCE_TT', '[ICON_INFLUENCE]에 미치는 영향 : {1_statusType} {2_statusText} {3_rate]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_INFLUENCE_RIVAL_TT', '[ICON_STAR] 라이벌 ({1_civName}) {2_statusText] [ICON_INFLUENCE]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_MILITARISTIC_REWARD_TT', '[ICON_STRENGTH] 군 단위 : {1_remaining] 회전 ({2_current} / {3_threshold} {4_rate})', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_GREAT_PERSON_REWARD_TT', '[ICON_GREAT_PEOPLE] 좋은 사람 : {1_remaining] 회전 ({2_current} / {3_threshold} {4_rate})', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_TRIBUTE_TT', '[ICON_RESISTANCE] 공물 : {1_possible]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POSSIBLE', '가능한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOT_POSSIBLE', '불가능', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_GIFT_FIRST', '당신 같은 강력한 제국을 만날 것을 기쁘게 생각합니다, 그들은 당신이 [COLOR_POSITIVE_TEXT] {1_NumGold] [ICON_GOLD] 골드 [ENDCOLOR]의 선물을 제공한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_GIFT_OTHER', '당신 같은 강력한 제국을 만날 것을 기쁘게 생각합니다, 그들은 당신이 [COLOR_POSITIVE_TEXT] {1_NumGold] [ICON_GOLD] 골드 [ENDCOLOR]의 선물을 제공한다.', '', '');
/* 전문가요 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RIFLING_TITLE', '무연 분말', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RIFLING_DESC', '무연 화약의 발명은 군사 무기와 전술을 혁명. 화약 (흑색 화약이라고 함)의 이전 형태는 고체 그을음의 대량 생산. 이 연기는 배럴 반칙 정확한 촬영을 방지하고, 어려운 지휘관이 전장의 안개를 통해 주문을 주도록했다. 무연 분말은 말 그대로 많은 이동 부품으로 정확성, 볼기로드 총기 및 자동 로딩 총기에 초점을 맞춘 전략에 대한 방법을 취소.', '', '');
/* 단위 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_WARRIOR', '고대 시대의 기본 군인.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SIAMESE_WARELEPHANT', '장 SUEK', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SIAMESE_WARELEPHANT', 'Pikemen에 취약 고유 샴 단위. 코끼리가 더 자원을 필요로하지 않습니다, 마운트 유닛에 대한 보너스를 받게하고, 그들이 대체 기사보다 [ICON_STRENGTH] 더 힘이있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MEDIEVAL_SIAMESEWARELEPHANT_TEXT', '동남 아시아에서 코끼리까지 중세 시대에 전쟁에 이용되는 것을 계속했다. 시암에서, 특히, 장 SUEK, 또는 전쟁 코끼리는 매우 소중히했다. 세 사람은 목에 한 승마 코끼리를 제어 할 뒷면의 처음 한 사람에게 같은 halberds, 스피어스와 투창 등의 무기를 전달하는 중간에 전투를 수행하는 각 전쟁 코끼리에 주둔 할 것입니다. 심지어 샴 지도자는, 참으로, 전쟁 코끼리에 킹 람 캄행 왕 나레 수안 왕 마하 Chakkraphat, 스리랑카 Suriyothai의 배우자가 모두 장 SUEK 위에 싸운를 전투에서 싸울 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SIAMESE_WARELEPHANT_STRATEGY', '이 기사를 교체, 샴 유일한 단위이다. 장 SUEK 유닛은 기사보다 느리지 만 더 강력하다. 기사처럼 장 SUEK은 공격 후 이동할 수 있습니다. 다른 마운트 유닛을 공격 할 때 창을 장착, 장 SUEK은 중요한 전투 보너스를 가져옵니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CAMEL_ARCHER', '빠른 중세 아라비아 단위. 그것은 원거리되고 Pikemen에 취약점이없는, 나이트 달리 대체합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_CAVALRY', '기병', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CAVALRY', '산업 시대의 강력한 장착 장치.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CATAPULT', '게임의 첫 번째 공격 유닛. 도시에 큰 피해를하지만, 단위에 취약하고, 발사에 앞서 설정해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_TREBUCHET', '강력한 중세 공성 유닛. 도시에 큰 피해를하지만, 단위에 취약하고, 발사에 앞서 설정해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CANNON', '강력한 르네상스 시대의 공성 유닛. 도시에 큰 피해를하지만, 단위에 취약하고, 발사에 앞서 설정해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ARTILLERY', '멀리 3 타일을 발사 할 수있는 게임의 첫 번째 공성 유닛. 도시에 큰 피해를하지만, 단위에 취약하고, 발사에 앞서 설정해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROCKET_ARTILLERY', '이동 한 후 공격 할 수있는 빠른 공성 유닛. 도시에 큰 피해를하지만, 단위에 취약합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER', 'Arquebusier', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_HELP', '게임의 최초의 화약 장치. 상당히 저렴하고 강력한.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_STRATEGY', 'Arquebusier 게임에서 제 화약 유닛이다. 그것은 저렴하고 Longswordsman 이전 군인 유닛과 달리 철을 필요로하지 않습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_PEDIA', '화승총은 17 세기에 15에서 사용되는 초기 총구로드 총기입니다. 그것은 그것의 전임자 손 대포는 달리, 화승총 있습니다. 그것은 그 후속 소총과 소총과 다른 longarm 총기의 전신 같은 활강 총기입니다. [NEWLINE] [NEWLINE] 저속 총기으로, 화승총은 종종 부분적으로 또는 완전히 강철에 의해 보호 된 적을 상대로 사용 플레이트 아머. 몸통에 닳은 판금 갑옷은 17 세기 중반까지 약 1400에서 유럽 전투에서 표준이었다. 판의 좋은 정장은 일반적으로 장거리 화승총의 공을 멈출 것입니다. 그러나 가까운 거리에서, 심지어는 무거운 기갑 부대의 갑옷을 관통 할 수 있었다. 이는 일곱 판으로 갑옷 사용량의 변화 및 ​​보병의 대부분의 유형에서 플레이트 아머의 마지막으로 은퇴했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_WWI_BOMBER', '복엽 비행기', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETMAN', '초기 산업 시대의 다양한 화약 장치.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_MUSKETMAN_STRATEGY', 'Musketman는 초기 산업 시대의 화약 유닛이며 이전 보병 타입의 모든 대체 - Longswordsmen, Pikemen 및 등. 그것은 효과적으로 모든 대상을 공격 할 수있는, 저렴하고 다양한입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_LANCER', '단위는보다 빠르고 강력한 나이트보다 장착.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SIPAHI', '오스만 제국에 고유 장착 장치, 더 빠르고 강력한 나이트보다. Sipahi는 대체 창기병보다 더 높은 속도와 시야의 범위가 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_NUCLEAR_SUBMARINE', '미사일 하위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_NUCLEAR_SUBMARINE', '일반 잠수함을 격파 전문. 3 미사일을 운반 할 수 있습니다. 미사일 잠수정 구축함, 잠수함, 1 타일 범위 내에서 단위 만 볼 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_AIRBASES_HEADING2_BODY', '공중 유닛은 지상과 해상 유닛 등지도 주위를 이동하지 않습니다. 그들은 플레이어 소유 친화적 인 도시의 "기반"해야합니다. 전투기와 일부 폭격기뿐만 아니라 항공 모함을 기반으로 할 수 있습니다. 미사일 유닛은 도시, 미사일 잠수함, 미사일 순양함에 기초 할 수있다. 에어 유닛은 착수 할 수 없습니다. 확장 된 바다 항해에, 그들은 해당 선박에 의해 운반해야하는 경우 -. 캐리어, 순양함, 핵 서브 [NEWLINE] [NEWLINE] 대공 유닛과 헬기를 기반으로 할 필요가 없습니다. 그들은 다른 단위와 같은지도의 주위에 이동 착수 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_ALLMISSILES_HEADING4_BODY', '미사일은 미사일 순양함에서 미사일 잠수함에 플레이어 소유 도시를 기반으로 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCMISSILES_HEADING2_BODY', '원자 폭탄 피해의 공정한 금액을 수행하는 동안, 핵 미사일은 정말 엄청난 수 있습니다. 폭발 반경에서 잡은 모든 객실은 파괴와 도시의 공격력도 큰됩니다. 원자 폭탄과는 달리, 핵 미사일 (플레이어의 원래 자본이 방법으로 파괴되지 않을 수 있습니다) 완전히지도상에서 도시를 닦는도 할 수있다. 자신의 이름에서 알 수 있듯이 [NEWLINE] [NEWLINE], 핵 미사일, 미사일 유닛되는 그들은 미사일 순양함 또는 미사일 잠수함에 주둔하고 있지만 항공 모함 수 있습니다 의미합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_ADV_QUEST', '어떤 공중 유닛 미사일 서브베이스는 할 수 있는가?', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_HEADING4_BODY', '미사일 서브는 어떤 유형의 두 미사일까지 수행 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_HEADING4_TITLE', '미사일 하위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_MISSLECRUISER_TEXT', '미사일 순양함은 항공 모함과 미사일 서브, 현대의 무기고에있는 가장 강력한 해군 무기를 제외하고있다. 운반 엄청나게 강력한 정확하고 긴 원거리 순항 미사일을 배치하기 위하여, 미사일 순양함들은 적의도 미사일 순양함 범위에 알고 있었다 오래 전에 대상 토지 또는 바다에서 적을 파괴 할 수있다. 타이 콘데로가 급 클래스 미국의 미사일 순양함은 틀림없이 지대지, 지대공, 심지어 대잠 미사일의 거대한 다양성을 수행 할 수 있습니다 122 발사 튜브로 무장 한 해상 가장 강력한 혈관이다. 또한 짧은 순서로 들어오는 적의 미사일과 항공기를 파괴 할 수있는 대공 기관총 스타일의 총, 다양한 장착되어 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_NUCLEARSUBMARINE_HEADING', '미사일 하위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_NUCLEARSUBMARINE_TEXT', '미사일 잠수함은 은밀하게 확장 된 항해를위한 바다에서 핵 미사일의 큰 숫자를 수행하도록 설계 냉전 시대의 선박이다. 이 거대한 선박은 그들에게 거의 무제한 순항 범위 (또는 한 음식이 보유으로)을 제공, 자체 전원 핵이다. 미사일 잠수함은 전략 무기 플랫폼이다. 일반적으로 적 도시 - 그들은 자신의 목표를 타격하기 전에 중간 세계 비행 할 수있는 대륙간 미사일을 수행한다. 그들은 자신의 방어를 위해 어뢰 및 지대공 미사일을 운반 할 수 있지만, 자신의 기본 임무는 숨어 적의와 직접 충돌을 방지하는 것입니다. 그들은 모든 비용에서 살아남 아야한다 [NEWLINE] [NEWLINE] 미사일 잠수함은 미국의 일부를 형성 ''와 소련의''상호 확증 파괴 "교리 :. 어느 한쪽이 몰래 핵 공격, 아무리 성공적으로 다른 충돌한다면 공격도 한 적 서브 그것은뿐만 아니라 그들을 파괴, 승리자에 죽음의 끔찍한 양의 비가 내려 수있는 살아있는 경우. 하나 완전히 그들이 절대적으로 질문하지 않고 적의 핵 잠수함, 비행기와 대륙간 탄도 미사일 모두를 파괴 할 수 있음을 확신 할 수 없다면 따라서, 교리 상태는, 핵 전쟁은 이길 수있다. 하나는 M.A.D.에게 믿고 여부 교리 미친 아닌지하는,이 구현 된 이후이 지구상에는 핵 전쟁이 없었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GOLD_HEADING1_BODY', '아, 골드! 금은 훌륭한 물건입니다. 당신은 건물과 불가사의를 구입하는 도시 국가의 우정을 구입하고 적의 문명을 뇌물, 도로 네트워크를 지불하기 위해 군대를 구축하는 데 사용할 수 있습니다. [NEWLINE] 그것은 "그 돈 수 ''에 해당 할 수 있습니다 당신이, 사랑 해요 "하지만 핵 미사일로 무장 미사일 서브를 구입할 수 있습니다, 그리고 그것은 나쁘지 않다 t 구입.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMPUTERS_HELP', '빌드 할 수 있습니다 [COLOR_POSITIVE_TEXT] 미사일 서브 [ENDCOLOR], 구축함도 미사일을 운반 할 수있는 다른 잠수정을 제외한 모든 단위에 보이지 않는 배. 또한 구축 할 수 있도록 [COLOR_POSITIVE_TEXT] 모바일 SAM [ENDCOLOR], 적의 항공기를 무마 전문 빠른 유닛.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_GUIDED_MISSILE_STRATEGY', '유도 미사일은 적 목표를 공격 할 때 파괴 원샷 유닛이다. 유도 미사일은 플레이어 소유 친화적 인 도시 또는 미사일 서브 미사일 순양함을 타고 기초 할 수있다. 그들은 "8"의 그들의 범위와 적 유닛이나 도시를 기반으로하거나 공격하는 기지에서 이동할 수 있습니다. 자세한 내용은 미사일에 대한 규칙을 참조하십시오.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_NUCLEAR_SUBMARINE_STRATEGY', '미사일 서브는 산업 시대의 모델보다 더 거칠고 강하다. 너무 대부분의 단위에 보이지 않는 다른 잠수함을 볼 수 있습니다. 가장 중요한 것은, 미사일 잠수정은 유도 미사일과 핵 미사일을 운반 할 수 있습니다. 잠수함과 마찬가지로 핵 잠수정 적 구축함과 잠수함에 취약하다, 그래서 해안 분명히 확인하기 위해 미리 밖으로 자신의 유닛을 보낼 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_NUCLEAR_MISSILE', '적들에 핵 파괴를 발휘. 도시에 엄청난 손상을 수행하고 폭발 반경에서 잡은 모든 유닛을 파괴합니다. 미사일 순양함과 미사일 잠수정에 주둔 할 수있다. [NEWLINE] [NEWLINE] 맨해튼 프로젝트와 두 개의 우라늄 자원이 필요합니다.', '', '');
/* 건물 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_DESC', 'Chinampa', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOATING_GARDENS_STRATEGY', 'Chinampa는 워터를 교체, 아즈텍 독특한 건물입니다. 그것은 도시의 음식 출력을 증가하고, 도시는 호수 나 강 근처에있는 경우 작성해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_PEDIA', 'Chinampa 농업에 사용할 수있는 땅을 높이기 위해 민물 호수에 건설 작은 인공 섬입니다. 호수는 섬을 관개와 매우 비옥 한 성장 환경의 결과로, 신선한 유기농 재료로 제공합니다. 아즈텍은 농업이 양식의 주인이었고, ''소 치밀 코의 공중 정원''오늘 유명한 남아있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE', '고로', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE_STRATEGY', '단위를 훈련 할 때 고로는 도시의 생산을 증가시킨다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE_PEDIA', '고로 철 일반적으로, 금속을 제련하는 데 사용됩니다. 공기는 챔버의 바닥 취입하므로 재료 하향 이동하면서 화학 반응이 퍼니스에 걸쳐 일어나는 동안 연료와 광석 연속적 노의 상단을 통해 공급된다. [NEWLINE] [NEWLINE] 용광로가에서 발명했다 중국 400 BCE에 의해 일반화 1500 CE에 의해 유럽으로 확산. 진나라의 상태가 221 BCE에서 중국을 통일했고,이 시대 중국 철 제련소는 2 백 남성의 평균 인력을 고용 할 때 철 군의 성공에 필수적이었다. 1000 CE에 의해 송나라 철 산업은 벌채 숲의 에이커의 수천을 살려주는, 철강 주조에 유연탄에 숯에서 자원의 놀라운 스위치를했다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH', '스미스', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH_STRATEGY', '스미스는 도시의 생산을 증가시킨다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH_PEDIA', '스미스는 대장장이가 난방과 망치, 보통 철강에 의해 금속을 작동하는 장소입니다. 히타이트는 먼저 1500 BCE의 주위에 철 광석의 제련을 개발했다. 그들은 수백 년 동안 철 생산의 지식을 거의 독점을 유지 한 것으로 보이지만, 그들의 제국 1200 BCE, 모든 방향으로 지식의 확산 주변의 동부 지중해 격변하는 동안 붕괴 때.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY', '주조', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY_STRATEGY', '파운드리 국립 원더는 크게 도시의 생산을 증가시킨다. 이 주조를 구성하기 전에 문명은 도시의 75 %에 용광로가 있어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY_PEDIA', '주조 금속 주물의 대규모 생산을위한 장소이다. 금속은 액체로 그들을 녹는 금형에 금속을 주입, 금형 재료를 제거하거나 냉각으로 금속이 응고 된 후 주조에 의해 모양으로 캐스팅됩니다. 처리의 가장 일반적인 금속은 알루미늄과 주철입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COFFEE_HOUSE_STRATEGY', '커피 하우스는 워크샵을 교체, 오스트리아에 고유 한 르네상스 시대의 건물입니다. 그것은 증가 [ICON_GREAT_PEOPLE] 위대한 사람이 25 %에 의해 생성 된 [ICON_PRODUCTION] 생산 속도하는 도시.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PETRA_HELP', '사막 타일 +1 [ICON_FOOD] [ICON_PRODUCTION] [ICON_GOLD] 음식, 생산, 및 금 (그러나 평야 홍수하지​​ 않음).', '', '');
/* 출처 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_NATIONAL', '국립 행복', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_NATIONAL_HELP', '국가에 대한 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_CITY', '시의 행복', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_CITY_HELP', '이 도시의 인구에 의해 제한 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_IMPORTED', '{1_num] 수입', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_CITYSTATES', '{1_num]에서 [ICON_CITY_STATE]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_EXPORTED', '{1_num] 수출', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_USED', '{1_num] 중고]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_SURPLUS', '{1_num] 잉여', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_MOVES', '{1_num] [ICON_MOVES]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_EXPERIENCE', '{1_num} / {2_num] [ICON_WAR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_HEALTH', '[COLOR_NEGATIVE_TEXT] {1_num} {TXT_KEY_UPANEL_HEALTH] [ENDCOLOR]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_HEALTH_CITY', '{1_num} / {2_num} {TXT_KEY_UPANEL_HEALTH]', '', '');
/* 손상 텍스트 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_ENEMY_UNIT_WITHDRAW', '적 {@ 1_EnUName} ([COLOR_POSITIVE_TEXT] {2_Num] [ENDCOLOR] 피해가) 당신의 {@ 3_UnitName} ([COLOR_NEGATIVE_TEXT] {4_Num] [ENDCOLOR] 손상을) 공격!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_ENEMY_UNIT_WITHDRAW_CITY', '적 {@ 1_EnUName} ([COLOR_POSITIVE_TEXT] {2_Num] [ENDCOLOR] 손상) {@ 3_CityName} ([COLOR_NEGATIVE_TEXT] {4_Num] [ENDCOLOR] 손상)의 도시를 공격!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_AIR_UNIT_HURT', '귀하의 {@ 1_UnitName] [COLOR_NEGATIVE_TEXT] 적으로 [ENDCOLOR] 도청 {@ 2_EnUName]였다! ({3} % 데미지)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_AIR', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {3_Num] [ENDCOLOR] 손상) 적으로 포격했다 {@ 2_EnUName!]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_AIR_AND_DEATH', '귀하의 {@ 1_UnitName] 한 [COLOR_NEGATIVE_TEXT] 적 {@ 2_EnUName] 포격 후 [ENDCOLOR] 파괴!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_CITY', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {3_Num] [ENDCOLOR] 손상)의 적 도시로 포격 한 {@ 2_CityName!]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ATTACK_BY_AIR', '귀하의 {@ 1_UnitName] 적을 포격 {@ 2_EnUName!] ([COLOR_POSITIVE_TEXT] {3_Damage] [ENDCOLOR] 손상)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ATTACK_BY_AIR_AND_DEATH', '귀하의 {@ 1_UnitName] 적을 포격 {@ 2_EnUName}와 [COLOR_POSITIVE_TEXT]은 [ENDCOLOR] 패배!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_CITY_WAS_CAPTURED', '방어하는 동안, {@ 1_CityName] 한 [COLOR_NEGATIVE_TEXT]에서 [ENDCOLOR] 캡처 {TXT_KEY_GRAMMAR_A_AN << {@ 3_owner_adjective}} {@ 2_EnUName} ([COLOR_POSITIVE_TEXT] {4_Num] [당신의 도시 ENDCOLOR] 손상)!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_DEFENSES_REDUCED_TO', '의 방어 {이 @ 1_CityName]으로 [COLOR_NEGATIVE_TEXT] {2_Num] % [ENDCOLOR]로 감소 된 {TXT_KEY_GRAMMAR_A_AN << {3_UnitName}}!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_HURT_ENEMY_AIR', '귀하의 {@ 1_UnitName] 도청 {TXT_KEY_GRAMMAR_A_AN << {4_owner_adjective}} {@ 2_EnUName!] ([COLOR_POSITIVE_TEXT] {3} % [ENDCOLOR] 피해)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_KILLED_ENEMY_UNIT', '방어하는 동안, {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) [COLOR_POSITIVE_TEXT] [ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {@ 5_owner_adjective}} {@ 4_EnUName] 사망 !', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_KILLED_ENEMY_UNIT_CITY', ', 당신의 도시를 방어하는 동안 {@ 1_CityName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) [COLOR_POSITIVE_TEXT] 사망 [ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {@ 4_owner_adjective}} {3_EnUName] !', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_REDUCE_CITY_DEFENSES', '귀하의 {@ 1_UnitName]의 방어를 감소 {@ 2_CityName] [COLOR_POSITIVE_TEXT] {3_NewVal] % [ENDCOLOR]에!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_SHOT_DOWN_ENEMY', '귀하의 {@ 1_UnitName] [COLOR_POSITIVE_TEXT] [ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {3_owner_civ}} {@ 2_EnUName] 격추!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_CAPTURED_ENEMY_CITY', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) [COLOR_POSITIVE_TEXT] [ENDCOLOR] 촬영의 적 도시 {@ 3_CityName!]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DESTROYED_ENEMY', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) [COLOR_POSITIVE_TEXT] [ENDCOLOR] 적 {@ 3_UnitName] 패배!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DIED_ATTACKING', '귀하의 {@ 1_UnitName] [COLOR_NEGATIVE_TEXT] 적 {@ 2_EnUName} ([COLOR_POSITIVE_TEXT] {3_Num] [ENDCOLOR] 손상을) 공격 [ENDCOLOR] 사망!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DIED_ATTACKING_CITY', '귀하의 {@ 1_UnitName] [COLOR_NEGATIVE_TEXT] {@ 2_EnUName} ([COLOR_POSITIVE_TEXT] {3_Num] [ENDCOLOR] 손상)의 적의 도시를 공격 [ENDCOLOR] 사망!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_RANSOM_KILL_BY_BARBARIANS', '야만인은이 [COLOR_NEGATIVE_TEXT] 사망 [ENDCOLOR]를 {@ 1_UnitName] 당신은 자신의 몸값을 지불하는 것을 거부하기 때문에!에게', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_SHOT_DOWN', '귀하의 {@ 1_UnitName] [COLOR_NEGATIVE_TEXT] 적으로 [ENDCOLOR] 격추 {@ 2_EnUName!]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_SURRENDER', '귀하의 {@ 1_EnUName] [COLOR_NEGATIVE_TEXT] {TXT_KEY_GRAMMAR_A_AN << {@ 2_Adjective}} {@ 3_UnitName]에 [ENDCOLOR] 항복!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED', '방어하는 동안, {@ 1_UnitName] 한 [COLOR_NEGATIVE_TEXT] {TXT_KEY_GRAMMAR_A_AN << {@ 3_owner_adjective}}에서 [ENDCOLOR] 파괴 {@ 2_EnUName} ([COLOR_POSITIVE_TEXT] {4_Num] [ENDCOLOR] 손상)!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED_UNKNOWN', '방어하는 동안, {@ 1_UnitName] 한 [COLOR_NEGATIVE_TEXT] 위장 {@ 2_EnUName} ([COLOR_POSITIVE_TEXT] {3_Num] [ENDCOLOR] 손상)에 의해 [ENDCOLOR] 파괴!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED_ATTRITION', '귀하의 {@ 1_UnitName] [COLOR_NEGATIVE_TEXT] 마찰에 의해 [ENDCOLOR] 파괴되었다!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WITHDRAW', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) 적 {@ 3_EnUName} ([COLOR_POSITIVE_TEXT] {4_Num] [ENDCOLOR] 손상을) 공격!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WITHDRAW_CITY', '귀하의 {@ 1_UnitName} ([COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR] 손상) {@ 3_CityName} ([COLOR_POSITIVE_TEXT] {4_Num] [ENDCOLOR] 손상)의 적의 도시를 공격!', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOUR_CITY_ATTACKED_BY_AIR', '귀하의 도시 [가 [@ 1_CityName} ([COLOR_NEGATIVE_TEXT] {3_Num] [ENDCOLOR] 손상) 적으로 포격했다 {@ 2_EnUName!]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOUR_CITY_RANGE_ATTACK', '{@ 1_Name} {@ 2_EnUName] 적을 폭격! ([COLOR_POSITIVE_TEXT] {3_Damage] [ENDCOLOR] 손상)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
/* 기타 */
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_SEA', '바다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_SEA_TEXT', '바다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_LAND', '평지', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_LAND_TEXT', '평지', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UPANEL_UNIT_PROMOTED', '승진을 선택한다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NEXT_GOLDEN_AGE_TURN_LABEL', '{1} 회전은 다음 [ICON_GOLDEN_AGE] 황금 시대까지 남아', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOGGLE_CLOCK_FORMAT', '12 / 24 시간 시계를 전환하려면 클릭합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SAVE_DEBUG_OUTPUT', 'lua.log 디버그 정보를 저장', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_BORDER', '국경 특가', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_RESEARCH', '연구 특가', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_DEFENSE', '방위 협정', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_ALLIANCE', '제휴', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SPECIALIST_GENERAL', '일반', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_OPSCREEN_TOOLTIP_1_TIMER_LENGTH', '지형 툴팁 지연 : {1_Num] 초', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_PROMOTION_DOMAIN', '{1_domain] [NEWLINE] {2_promoHelp]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_DEITY_HELP', '나는 우주와 하나입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_IMMORTAL_HELP', '나는 좀비 종말에서 살아남을 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_EMPEROR_HELP', '나의 한계를 테스트합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_KING_HELP', '나에게 도전을 준다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_PRINCE_HELP', '장갑오고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_WARLORD_HELP', '나를 긴장하자.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_CHIEFTAIN_HELP', '내가 새로운 일을 시도 할 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_SETTLER_HELP', '내가 게임을 배울 수 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_POLICY_SAVING', '어떤 정책을 저장하지', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_POLICY_SAVING_HELP', '가능한 경우 플레이어는 즉시 사회 정책을 선택해야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_CULTURE_CITY_COST', '평화로운 확장 정책의 속도를 가속화하고, 전쟁은 속도가 느려집니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CANNOT_UNLOCK', '[ICON_LOCKED]이 정책은 현재 잠겨 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK', '[ICON_LOCKED]이 정책 나무는 지금 잠겨 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK_CULTURE', '[NEWLINE] [ICON_LOCKED] 당신은 보내고 {1_Num] [ICON_CULTURE] 문화가 필요합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK_ERA', '[NEWLINE] [ICON_LOCKED] 당신은에있을 필요가 {1_EraString : textkey.}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_UNLOCK_SPEND', '[COLOR_POSITIVE_TEXT]이 정책 트리 잠금을 해제 할 수 있습니다! [ENDCOLOR] [NEWLINE] {1_Num] [ICON_CULTURE] 문화 지출이 사회 정책 트리를 열려면 여기를 클릭하십시오.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_BLOCKED', '그 효과를 차단 당신이 선택한 다른 지점이 있기 때문에 [NEWLINE] [ICON_LOCKED] 비활성. [NEWLINE] 전환하려면 여기를 클릭하십시오.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_GAINING_HEADING2_BODY', '당신은 당신이 충분한 문화 점수를 얻었다 일단 사회 정책을 채택하고 잠금을 해제하도록 선택할 수 있습니다 : 당신이 조금 더 비용이 이후의 사람과, 100 문화 점수를 획득하면 처음 사용할 수있게됩니다. 각 정책의 비용은 더 많이 채택 증가한다. 당신은 얼마나 많은 문화를 볼 때 다음 정책을 사용할 수있게됩니다, 상태 표시 줄의 문화 아이콘 위로 마우스를 가져. 당신은 문화 섹션에서 문화이 발생에 대한 자세한 내용을보실 수 있습니다. [NEWLINE] [NEWLINE] 당신은 충분한 문화가 있으면 알림이 네 차례에 당신을 알려줍니다. 사회 정책의 창을 불러옵니다 (옆 고문에 위치) 오른쪽 상단 모서리에있는 사회 정책의 아이콘을 클릭합니다. 당신이 설정 정책을 선택하지 않으려면, 당신은 그것을 해제하기 위해 알림을 마우스 오른쪽 버튼으로 클릭 할 수 있습니다. (이 게임은하지만 다시 당신을 생각 나게하지 않을 것이다, 그래서 이것은 위험 할 수 있습니다.) 다음은 새로운 지점을 채택하거나 잠금이 해제 된 지점에서 새 정책의 잠금을 해제 할 수 있습니다. 사용할 수있는 모든 정책 (그리고 당신이 잠금을 해제 한 단지 것)를 보려면 창 아래쪽의 고급보기 전환을 클릭합니다. 당신은 문화의 필요한 양을 획득 한 경우 [NEWLINE] [NEWLINE]을 클릭합니다 탐사의 선택 분기를 열어 버튼 "정책을 채택"- 먼저 개별 정책의 잠금을 해제하기 전에 지점을 채택 포인트를 지출해야합니다. 각 분기 채용 [NEWLINE] [NEWLINE] 일부 가지가 동시에 잠금을 해제하고 활성화 할 수 없습니다. 같은 자연의 더 많은 보너스를 제공하는 각 내의 개별 정책을 즉시 당신에게 약간의 혜택을주고, 많은 지점은 한 번만 사용할 수있게 이후의 시대에 도달했습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION_HELP', '버그를 해결 작품 (자세한 내용은 마우스 오른쪽 단추로 클릭).', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION', '철도 연결', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION_STRATEGY', '일반 게임에서, 자본의 사람들은 수도에있는 사람들과 함께 정책과 철도에 오류가 발생하는 버그를 교환 할 수 없습니다. 이 무료 건물은 버그의 철도 부분을 수정합니다. [NEWLINE] [NEWLINE] {TXT_KEY_PRODUCTION_BUILDING_ALLOWS_WATER_ROUTES_EXTRA]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_NEW_YEAR', '굳게 결심 한', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_APRIL_FOOLS', '좀비', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_UFO', '외국인', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_HALLOWEEN', '흡혈귀', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PER_TURN', '턴에', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_DEFENSE', '[COLOR_POSITIVE_TEXT] 디펜스 모드는 [ENDCOLOR] : {1} %', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_ACTUAL', '[COLOR_POSITIVE_TEXT] 수익률 [ENDCOLOR] : {1}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_WITHOUTFEATURE', '[COLOR_YELLOW] 없음 {1} [ENDCOLOR] : {2}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_WITHIMPROVEMENT', '[COLOR_YELLOW]와 {1} [ENDCOLOR] : {2}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_VIEW', '전망', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_GOLD', 'AI 골드 핸디캡', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_PRODUCTION', 'AI 생산 핸디캡', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_SCIENCE', 'AI 과학 핸디캡', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_CULTURE', 'AI 문화 핸디캡', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_GOLD_TILE_MAINT', '{1_Num] 도로 및 철도의 유지 보수에 소요.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISSION_HURRY_PRODUCTION_HELP', '도시의 현재 노력 (300 + 30 * [ICON_CITIZEN] 인구) [ICON_PRODUCTION] 생산을 제공합니다. 그것은 위대한 사람을 소모합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_CITIZEN_ALLOCATION', '시 초점', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_SPECIAL_TEXT', '전문가', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_PERTURN_TEXT', '{1_perTurn : 숫자 "#"}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_PERTURN_TEXT_NEGATIVE', '{1_perTurn : 숫자 "#"}', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCED', '생산', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSUMED', '소비', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_DISABLE_START_BIAS', '아니 시작 바이어스 없습니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_REQUIRES', '필요', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MONUMENT', '기념물', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MONASTERY', '수도원', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOPIC_EXPERIENCE', '경험', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_SUBMARINE', '잠수함 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_MOUNTED_ARCHER', '장착 궁수', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_CIVILIAN', '민간 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_COMMAND', '지원 장치', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_MELEE', '군인 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_RECON', '뱅가드 단위', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SUPPLY_REACHED_TOOLTIP', '당신의 제국 {1_Num] 토지 군대를 지원할 수 있습니다. 당신은 [COLOR_NEGATIVE_TEXT] {3_Num] % [ENDCOLOR]하여 도시 토지 군대의 [ICON_PRODUCTION] 생산 감소 [COLOR_NEGATIVE_TEXT] {2_Num] [ENDCOLOR]에 의해 그 한계, 이상입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRADITION_TITLE', '소버린 {1_PlayerName : textkey}의 {2_CivName : textkey]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_DEAL_EXPIRED_GPT_FROM_US', '종료 : 우리는 [ICON_GOLD] 골드에게 [textkey] [1_CivName]에 대한 모든 회전을 제공하는 거래.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_DEAL_EXPIRED_GPT_TO_US', '제공 [ICON_GOLD] 금은 우리에게 모든 회전이 종료 : [textkey] [1_CivName] 거래.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPAIN_CONQUISTADOR_HELP', '스페인 특유의 중세 시대 유닛. 정복자는 대체 기사와 달리, +2 시야 범위와 도시에 대한 어떤 처벌이 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', '+1 [ICON_CULTURE] 문화. [NEWLINE] +1 [ICON_CULTURE 인접한 모아 당 문화. [NEWLINE] [ICON_LOCKED] 해안 옆이어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', '+1 [ICON_CULTURE] 문화. [NEWLINE] +1 [ICON_CULTURE 인접한 모아 당 문화. [NEWLINE] [ICON_LOCKED] 해안 옆이어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', '+1 [ICON_CULTURE] 문화. [NEWLINE] +1 [ICON_CULTURE 인접한 모아 당 문화. [NEWLINE] [ICON_LOCKED] 해안 옆이어야합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VICEROY', '총독', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VICEROY_HELP', '꼭두각시 상태 및 점유 도시를 감독한다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PUPPET_MODIFIER', '타운 시계', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PUPPET_MODIFIER_HELP', '괴뢰 국가를 보호합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FREEDOM_FINISHER', '자유 마무리', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAN_BUILD_COURTHOUSE', '법원을 가질 수있다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAN_BUILD_COURTHOUSE_HELP', '법원과 바닐라 버그를 해결 작동합니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAPITAL_TRADE', '자본 거래', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_BONUS', '과학 보너스', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_BONUS_HELP', '각 그물 전국 1 [ICON_HAPPINESS_1] 개종 [ICON_CAPITAL] 자본금 [ICON_RESEARCH] 1 %.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_PENALTY', '과학 보너스', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_PENALTY_HELP', '각 그물 전국 1 [ICON_HAPPINESS_4] 회심 -1 % [ICON_RESEARCH] [ICON_CAPITAL] 수도있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_UNITEDSTATES_TEXT_19', '미국은 더 이상 세계에서 유일한 초강대국이다. 그것은 적어도 중국과 그 모호한 제목을 공유합니다. 내부적으로는 20 세기 후반의 경제적 과잉에서 회복하기 위해 고군분투뿐만 아니라 마지막으로 아직도 괴롭 히고 노예와 인종 차별주의의 유령을 추방하려고. 미국은 다소 폭행 꺾이 결코입니다. 아직 자원, 드라이브 및 인적 자본이 다가오는 세기에 중요하고 중요한 문명으로 보유하고있다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_LEADERS_HARUN_TEXT_3', '하룬의 통치의 시작에, 칼리프의 수도 바그다드, 이전 칼리프에 의해 설립 된 새로운 도시에 있었다. 이 도시는 많은 아름다운 건물과 예술, 과학, 종교의 중심이었다. 하룬은이 설립 된 ''지혜의 집''수집 페르시아, 인도, 그리스, 로마 텍스트에서 과학 저술을 번역 도서관, 연구 시설. 하룬 바그다드에서 아마도 세계에서 가장 크고 가장 부유 한 도시가되고, 꽃을 피울 것입니다. 나중에 하룬은 AR-Raqqah의 전략적으로 중요한 도시로 자신의 정부를 움직일 것입니다 만, 바그다드 (도시는 1258 정복하고 몽골에 의해 해임 될 것이다) 올 세기에 예술, 과학, 상업의 위대한 도시 남아있는 것입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_TERRACE_FARM_TEXT', '테라스 농업 발리, 필리핀, 중국, 페루를 포함하여 전 세계적으로 동시에 산악 지역에서 개발. 이 스키니, 계단 필드 관개 용수의 오프 실행을 방지하고 경작지를위한 공간을 제공하고, 언덕과 산의 측면으로 절단, 보통 아무도 이전에 가능했던없는 곳. 잉카 특히 테라스 농업의 주인이었고, 장소에 자신의 테라스를 보유하는 대형 drystone 벽을 세웠다. 테라스의 모양을 구축 한 후, 잉카는 토지의 비옥도를 증가, 운하와 일정한 물에 테라스를 제공하는 수로의 시스템을 구축. 고대 잉카의 계단식 기술은 현대 페루 농민들이 오늘날 자신의 농장에서 그들을 사용하는 것이 매우 성공적이었다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_BALANCED_TEXT', '[ICON_CITIZEN]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_FOOD_TEXT', '[ICON_FOOD]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_PROD_TEXT', '[ICON_PRODUCTION]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_GOLD_TEXT', '[ICON_GOLD]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_RESEARCH_TEXT', '[ICON_RESEARCH]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_CULTURE_TEXT', '[ICON_CULTURE]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_GREAT_PERSON_TEXT', '[ICON_GREAT_PEOPLE]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_FAITH_TEXT', '[ICON_PEACE]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_AVOID_GROWTH_TEXT', '[ICON_LOCKED]', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_YIELD_FROM_CONSTRUCTION', '{1_city} {4_building] 건물에서 [COLOR_POSITIVE_TEXT] + {2_yield} {3_yieldstring] [ENDCOLOR]되었습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_TOTAL_HAPPINESS', '국가의 총 [ICON_HAPPINESS_1] 행복의 수준은 {1_Num}입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_TOTAL_UNHAPPINESS', '국가의 총 {1_Icon] 불행 레벨 {2_Num}입니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_FROM_RESOURCES', '적어도 하나의 소스를 가지고에서 {1_Num] 국립 행복 :', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_TERRAIN', '지형에서 {1_Num] 도시의 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_CITIES', '건물에서 {1_Num] 도시의 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_MISC_GLOBAL', '알 수없는 {1_Num] 국립 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_POLICIES', '사회 정책에서 {1_Num] 국립 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_BUILDINGS', '건물에서 {1_Num] 국립 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_NATURAL_WONDERS', '자연의 경이의 발견에서 {1_Num] 국립 행복.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CLICK_TO_SELL', '건물을 철거 클릭', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SELL_BUILDING_INFO', '당신은 당신이이 건물을 철거 하시겠습니까? (: 당신은 회전 당 하나의 건물을 철거 할 수 있습니다 주). 그것은 당신이 {2_Num] [ICON_GOLD] 유지 보수 턴에 금이 [NEWLINE] [NEWLINE] 저장합니다', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SAVING', '절약', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYSTATE_CAPTURE_BONUS', '시티 스테이트 캡처 동맹의 40 회전에 해당 즉각적인 보상에게 있습니다.', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_OPSCREEN_MINUTES_FOR_AUTOSAVES', '자동 저장 간격 (분)', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GENERIC', '', '', '');
REPLACE INTO Language_KO_KR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');





UPDATE Loaded File SET Value=1, KO_KR=1 Where Type='Core.sql';