/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Rasgos  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Usted obtiene un Spy extra. Grandes generales ver más lejos y dan más fuerza. [NEWLINE] comienza con un guerrero y el Gran General.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Asignación', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Su plusvalías una copia sólida libre de cada nueva línea de unidad que la investigación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Las unidades se mueven más rápido a lo largo de los ríos, y comienzan con la promoción Anfibio.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' 10% [ICON_GREAT_PEOPLE] Great People tasa de cada Alianza, y 20% [ICON_STRENGTH] Combat vs civilizaciones con más ciudades.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Unidades de cuerpo a cuerpo y de vanguardia cuestan 50% menos mantenimiento. Todas las unidades requieren un 25% menos experiencia para ganar su próxima promoción.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Producción hacia los edificios que ya existen en el [ICON_CAPITAL] capital. Empieza por [ICON_RES_IRON] de hierro en los primeros 5 ciudades.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', 'Recompensas 25% más de amigos y aliados de la ciudad-estado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Helenización', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' 2 [ICON_CULTURE] La cultura en cada ciudad. Ciudad-Estado [ICON_INFLUENCE] Influencia degrada a la mitad y se recupera el doble de la tarifa normal.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Rutas comerciales internas ofrecen 10 [ICON_GOLD] Oro al destino.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Las ganancias [ICON_CULTURE] Cultura de matar a las unidades enemigas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' 50% [ICON_CULTURE] Cultura y +1 [ICON_MOVES] Movimiento durante [ICON_GOLDEN_AGE] Eras Doradas. [NEWLINE] comienza con un único Spearman.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' 1 [ICON_PEACE] Fe de Bosques no mejoradas y Selva, y el 150% los rendimientos de las Maravillas Naturales. [NEWLINE] comienza con un Spearman.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Unidades dañadas luchar con toda su fuerza. Barcos de pesca y las islas dan [ICON_CULTURE] Cultura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Gao Milicia', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Unidades Vanguard ver más lejos y se mueven más rápido.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Las unidades se mueven más rápido en las colinas. Carreteras y ferrocarriles no tengan coste de mantenimiento en las colinas, la mitad costó en otro lugar.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Los civiles se mueven más rápido en el desierto. Sus rutas comerciales salientes con diferentes civilizaciones ganan más [ICON_GOLD] Oro y [ICON_CULTURE] Cultura y las rutas comerciales entrantes ganan más [ICON_GOLD] para el dueño de la ruta.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Más rápido movimiento en bosques y selva, que cuenta como carreteras en territorio amigo después de investigar la rueda. [NEWLINE] comienza con un espadachín único.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Grandes científicos parecen 25% más rápido y recibe una en la escritura. [NEWLINE] Inicia con una Bowman.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desierto Caravanas', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Las unidades se mueven más rápido en el desierto, caravanas llegan más lejos, y las rutas comerciales repartidos religión más rápido de sus ciudades.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'Después de investigar la Teología, recibirá un bono de Gran personaje al final de cada ciclo de calendario de la Cuenta Larga Maya (cada 394 años). [NEWLINE] comienza con un Archer único.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Cada incremento de recursos de lujo [ICON_GOLD] ingreso de Oro en un 5%.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' 20% [ICON_PRODUCTION] Producción hacia la construcción de la maravilla.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' 30 [ICON_WAR] La experiencia para los buques.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Elija una creencia más de lo normal cuando se enteró de una religión.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Puertos reciben un puerto libre, y las unidades pueden cruzar las montañas. Empieza por Vela, una Bireme, y un guerrero.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Economía planificada', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Unidades de ver más lejos, los civiles se mueven más rápido, y que ganan menos de 1 [ICON_HAPPINESS_4] Nacional Infelicidad por ciudad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Edificios Alimentación añadir 1 [ICON_CITIZEN] Población vez construido. [NEWLINE] comienza con un trabajador.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Campamentos bárbaros se rinden cuando derrotó por doble [ICON_GOLD] oro. [NEWLINE] comienza con un Archer Horse.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'Sueño Americano', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Los inmigrantes desplazan hasta aquí desde las civilizaciones con baja felicidad y alta influencia cultural de Estados Unidos. Sus ciudadanos migran a lo largo internas [] ICON_FOOD rutas comerciales de Alimentos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Dinastía Joseon', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' 2 [ICON_RESEARCH] Ciencia de Granjas. [NEWLINE] Comienza con un trabajador.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Rendimientos dobles de maravillas naturales, además de 100 [ICON_GOLD] cuando se descubrió. [NEWLINE] comienza con un explorador, y recibe una Caravel en Compass.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Liga Hanseática', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Doble cantidad de recursos estratégicos, y 3 votos extra en el Congreso Mundial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Más rápido y más fuerte de embarque a través del agua, y el cuerpo a cuerpo unidades saquean más rápido.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terror', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'Ciudad-estados usted puede rendirse matón en el miedo como marionetas. Montada y unidades de escaramuza se mueven más rápido. Empieza por un Scout.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Homenaje', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Rutas comerciales internas entre sus ciudades proporcionan 10 [ICON_GOLD] Oro al destino.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Reconquista', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Ciudades Conquistando incrementa su [ICON_PEACE] Faith.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Azote de Dios', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Campamentos bárbaros se rinden cuando derrotó, y las unidades de tierra cuestan menos [ICON_GOLD] mantenimiento. [NEWLINE] comienza con un Archer Horse.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Azote de Dios', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Campamentos bárbaros se rinden cuando derrotó, y las unidades de tierra cuestan menos [ICON_GOLD] mantenimiento. [NEWLINE] Empieza por un carro único.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' 5% [ICON_GOLD] la renta nacional de cada tipo de recurso de lujo que controles o de importación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] Un ciudadano emigró de {1} a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] Un inmigrante desde {1} llegó a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] Un ciudadano emigró de {1} a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Usted ganó {1} {2} {3} de {4} capturar!', '', '');


/*  Unidades  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Tropas Imperial-Royal Mountain', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Unidad era moderna que sólo los austriacos pueden construir. Es más potente y ha añadido promociones que la unidad regular no.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Esta unidad cuenta con poderosas ventajas en todos los terrenos clima frío. Los combates en la tundra, nieve, colinas e incluso montañas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'Las tropas imperiales-Royal Mountain (alemán: Kaiserlich-königlich Gebirgstruppe). Fueron fundadas en 1906 como parte de la Landwehr austriaco, el ejército territorial del medio Cisleithanian del Imperio Austro-Húngaro [NEWLINE] Propuesta de un memorando de Conrad von Hötzendorf , en febrero de 1906, el Ministerio de la Guerra en Viena convocó una reunión sobre seguridad en la frontera de los Alpes. El mariscal de campo Tunk, de acuerdo con él y proponer un concepto, los fundamentos de los cuales se llevaron a cabo a continuación. [NEWLINE] Los regimientos de fusileros estatales existentes debían ser entrenados como tropas de montaña y, junto con las empresas de la patrulla fronteriza y departamentos Landsturm gendarmería fueron para formar la columna vertebral de una fuerza de defensa territorial con el conocimiento local en la frontera del Tirol [NEWLINE] [NEWLINE] batallones y compañías recibieron animales de carga y se emitieron con equipo adicional adaptada a las exigencias de la guerra de montaña,. incluidos los esquís, cuerdas, crampones y piolets. Regimientos fueron reforzados por una sección de ametralladoras de montaña de cuatro ametralladoras que, para mejorar la movilidad, podrían ser transportadas por animales de carga o en paquetes manportable en las mayores altitudes. Lo mismo se aplica a los cañones de montaña-desarmar. Estufas de campo portátiles (Schwarmöfen) y carpas climatizadas asistidos tropas para operar en condiciones inhóspitas. [NEWLINE] Al esquiar el enfoque de dos stick había reemplazado el método de un solo palo. El Bilgeri vinculante era una gira de unión que podría ser utilizado con el arranque normal senderismo. El rifle fue sustituido por el (corto) Mannlicher 8mm M 95 carabina.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unique Songhai unidad montada. Mandekalu caballería comienza con la promoción de asedio, a diferencia del caballero al que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Soldado medieval Potente única para los japoneses. Samurai puede atacar dos veces por turno, y son más fuertes que el Longswordsmen que reemplazan.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unidad arquero babilonio Unique. El Bowman es más fuerte que el arquero al que sustituye, y se mueven más rápido en los desiertos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldado de la era medieval único en Dinamarca. El Berserker comienza con la promoción de carga, a diferencia del Longswordsman que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'La unidad móvil única para Alemania. El Panzer tiene mayor fuerza, velocidad, y la visibilidad que el tanque al que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Early-juego de soldado única para los aztecas. El Jaguar se cura el daño cuando se mata a un enemigo, y combate con mayor eficacia en la selva que el guerrero al que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renacimiento Unidad única de los americanos Vanguard. Es más fuerte que el Guerrillero que sustituye, ve más lejos, y se mueve más rápido en terrenos difíciles.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'Una de las primeras unidades de pólvora del juego, únicos para los franceses. Mosqueteros tienen una bonificación de combate fuera del territorio amigo, a diferencia del Mosquete que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldado único a los iroqueses. El Mohawk Warrior lucha más fuerte en el bosque y la selva que el espadachín al que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldado única para los otomanos. El jenízaro es mucho más fuerte en el ataque y se cura después de muertes, a diferencia del Mosquete que sustituye.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Las unidades dentro de 1 tile [COLOR_POSITIVE_TEXT] Heal 4 HP adicional [ENDCOLOR] por turno.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'La sustitución de Mongolia único para el Caballo se mueve más rápido, es de largo alcance, y no comparte las vulnerabilidades del Caballero a las ciudades o los piqueros. El Keshik también gana experiencia más rápidamente.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Soldado romano de gran alcance de la Era Clásica con una bonificación contra ciudades. La Legión tiene mayor resistencia que el espadachín al que sustituye, de defensa adicional contra los ataques a distancia, y se puede construir carreteras a dos veces la velocidad de los Trabajadores.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'A Liburna era un tipo de galera pequeña utilizada para asaltar y patrullas, sobre todo por la armada romana. [NEWLINE] [NEWLINE] En su forma original, el Liburna tenía un banco con 25 remos a cada lado, mientras que en el final de la República romana, estaba equipado con dos filas de remos (BIREME), que quedan más rápido, más ligero y más ágil que trirremes. El diseño liburna fue adoptada por los romanos y se convirtió en una pieza clave de la marina de guerra de la antigua Roma por la segunda mitad del siglo 1 aC. Liburnians jugaron un papel clave en la batalla de Actium, en Grecia, que vio el establecimiento de Augusto como el gobernante indiscutido del mundo romano. [NEWLINE] Liburnians eran diferentes de los trirremes batalla, cuatrirremes y no quinquerremes debido a remo sino por sus características particulares de construcción. [NEWLINE] [NEWLINE] Una vez que los romanos habían adoptado la liburna, procedieron a hacer algunas adaptaciones para mejorar el uso de los barcos en la marina. Los beneficios obtenidos de la adición de los carneros y de la protección de los misiles más maquillada de la ligera pérdida de velocidad. Además de la construcción, los barcos requieren que la unidad militar romana regulares simplificarse para poder funcionar más suavemente. Todo buque que operaba como una entidad individual, por lo que la organización sea más complicada utilizado normalmente no era necesario. Dentro de la marina de guerra, había probablemente liburna de varios tamaños diferentes, todos ponen a tareas específicas, tales como los Scouts y el patrullaje de las aguas romanas contra la piratería. Los romanos hicieron uso de la liburna especialmente en las provincias del imperio, donde los barcos forman el grueso de la flota. [NEWLINE] liburnas Gradualmente se convirtió en un nombre general para los diferentes tipos de las naves romanas, que se adjunta también a los buques de carga en Late Antigüedad. Tácito y Suetonio estaban usando como sinónimo de la nave de batalla. En las inscripciones se mencionó como el último en la clase de los barcos de guerra: hexeres, penteres, quadrieres, trieres, Liburna.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'El Liburna es primera unidad naval de Roma. Es una unidad de cuerpo a cuerpo y sin una Fuerza de combate a distancia. El Liburna es útil para la limpieza de naves bárbaras de aguas nacionales y para la exploración limitada.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Roma utilizó estos vasos para controlar las aguas y proteger sus rutas comerciales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Unidad móvil de gran alcance único en la India. A diferencia del jinete al que sustituye, el elefante de la guerra es de largo alcance, no requiere de caballos, y no tiene la vulnerabilidad a los lanceros.', '', '');
/*  Misc  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Oficina Comercial', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Otomano Homenaje', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Debes estar cerca Coast.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Debes estar cerca Coast.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura por Moai adyacente. [NEWLINE] [ICON_LOCKED] Debes estar cerca Coast.', '', '');
/*  Amsterdam Bourse  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'La Bolsa de Valores de Amsterdam es considerada la más antigua del mundo. Fue establecido en 1602 por la Compañía Holandesa de las Indias Orientales para las operaciones con sus existencias impresos y bonos. Posteriormente se cambió el nombre del Amsterdam Bourse y fue el primero en comenzar formalmente la negociación de valores.', '', '');
/*  Jelling Stones  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Jelling Stones', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'Las piedras de Jelling son runas talladas masivas desde el siglo 10, que se encuentra en la localidad de Jelling en Dinamarca. La más antigua de las dos piedras de Jelling se recaudaron por el rey Gorm en memoria de su esposa Thyra. La mayor de las dos piedras fueron recaudados por Harald Bluetooth, el hijo del rey Gorm. Harald construyó la segunda piedra en memoria de sus padres, la celebración de la conquista de Dinamarca y Noruega, y su conversión de los daneses al cristianismo. Las inscripciones rúnicas sobre estas piedras se consideran los más conocidos en Dinamarca.', '', '');
/*  Jade * Salón /
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Salón', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'Rey Sejong supervisó el desarrollo de la Chiphyonjon, el Salón Jade de Ulemas, los estudiosos profesionales que ayudaron investigación cuestiones sociales y políticas para el rey y el gobierno. El Salón Jade sería considerado un "think tank" de los gobiernos en la actualidad.', '', '');
/*  Saneamiento Indus  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Saneamiento del Indo', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'La civilización Harappa del valle del río Indo ha diseñado sistemas de saneamiento urbano primera conocidas en el mundo alrededor de 2600 aC. Viviendas individuales o grupos de hogares obtienen agua de pozos. El agua residual se dirige desde las habitaciones reservadas para el baño de los drenajes cubiertos que recubren las calles principales. Los enormes muros de las ciudades de Harappa se especuló para proteger de las inundaciones. Estos sistemas de ingeniería hidráulica de Harappa fueron aún más eficientes que las de muchas zonas de Pakistán y la India de hoy, el logro de las grandes ciudades urbanas con relativamente poco desarrollo de la agricultura.', '', '');
/*  Pioneer  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pionero', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Funda nuevas ciudades para ampliar su imperio. [NEWLINE] [NEWLINE] [ICON_FOOD] El crecimiento de la ciudad se detiene mientras la unidad está en construcción. [NEWLINE]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'El Pioneer es una unidad exclusiva de Estados Unidos. Se mueve más rápido que el colono al que sustituye. [NEWLINE] [NEWLINE] Utilice esta unidad para la construcción de nuevas ciudades. No puede defenderse a sí mismo, por lo que acompañarlo con una unidad de combate.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Pioneros americanos son cualquiera de las personas en la historia de EE.UU. que emigraron al oeste de la costa del Atlántico para establecerse y desarrollar nuevas áreas. El término se refiere especialmente a los que iban a establecerse un territorio nuevo para la sociedad europea o estadounidense, aunque el territorio pudo haber sido habitada por o utilizados por pueblos indígenas. [NEWLINE] [NEWLINE] El concepto pionero y ethos son anteriores en gran medida la migración a las partes de los Estados Unidos que ahora se llama estados "occidentales", ya que muchos lugares ahora considerados como Oriente también fueron resueltos por los pioneros de la costa. Por ejemplo, Daniel Boone, una figura clave en la historia del pionero americano, se instaló en Kentucky, cuando ese ''Dark and Bloody Ground'' era todavía poco desarrollado. [NEWLINE] [NEWLINE] Un acontecimiento importante en el asentamiento occidental fue el acto de la granja, que proporcionó legislación formal que regula el proceso de liquidación.', '', '');
/*  Molino de vapor  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Mill Steam', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Una transición se inició a las fábricas basados ​​en máquinas en la economía de Gran Bretaña en la década de 1700, con anterioridad que dependen de los animales de trabajo y de los proyectos de manuales. Estos precursores de la Revolución Industrial comenzó con la mecanización de las industrias textiles. La expansión del comercio fue posible gracias a la introducción de canales, la mejora de carreteras y vías férreas. Más amplia utilización de ruedas de agua y la introducción de la energía de vapor empuja un aumento espectacular en la capacidad de producción. El desarrollo de máquinas-herramienta todo-metálicos a principios de 1800 facilitó la construcción de máquinas de producción cada vez más refinados para la fabricación de una amplia variedad de industrias.', '', '');
/*  Dojo  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Un dojo japonés ("lugar del camino") es un lugar de reunión para llevar a cabo la formación, exámenes, y otros encuentros relacionados a las artes "hacer". Dojos fueron inicialmente complemento de templos. En Japón cualquier centro de entrenamiento físico, incluyendo las escuelas de lucha libre profesional, puede ser llamado dojo por sus estrechos raíces de las artes marciales.', '', '');
/*  Santuario  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Santuario sintoísta', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'En Japón, existen santuarios sintoístas al lado de templos budistas, y son los más numerosos, famosos e importantes lugares religiosos en Japón. Un santuario sintoísta es una estructura u objeto cuyo propósito principal es el de albergar uno o más Shinto kami (espíritus, fuerzas de la naturaleza o esencia). Kami puede residir en casi nada natural o hecho por el hombre, desde el monte. Fuji a una pequeña joya. Como tal, estos santuarios son comunes y un alcance muy variado. El santuario en sí mismo puede ser un gran edificio o pequeño objeto, a lo largo de un borde de la carretera, o incluso podría ser llevada por la gente. [NEWLINE] [NEWLINE] Al igual que los templos budistas, santuarios sintoístas no son ante todo un lugar de culto. Edificios más importantes de la capilla se utilizan para la custodia de los objetos sagrados. Hay edificios especializados para ciertos ritos, pero éstos suelen estar abiertos únicamente a un número limitado de participantes. Concentraciones masivas religiosas en el estilo de las iglesias cristianas no tienen lugar con regularidad y no se llevan a cabo en el interior del santuario. Si muchas personas participan en una ceremonia, se asumirá un carácter festivo y se celebrará al aire libre.', '', '');
/*  Folkskola  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'En 1842, el parlamento sueco introdujo una escuela primaria de cuatro años para los niños en Suecia, "Folkskola" (la escuela del pueblo). Este fue uno de los primeros sistemas de escuelas públicas en el mundo. [NEWLINE] [NEWLINE] están obligados a asistir a los niños suecos grundskola, la enseñanza obligatoria, desde la edad de 7 a 16, donde grundskola es una combinación de la escuela primaria y secundaria. Después grundskola, muchos suecos asisten al gymnasieskolan electiva, la escuela secundaria superior, pudiendo elegir entre un programa universitario preparatorio o un programa vocacional. Los estudiantes que eligen un programa vocacional normalmente terminan su educación después gymnasieskolan mientras que los estudiantes que completan un programa universitario de preparación normalmente se matriculan en la educación superior en una universidad o colegio universitario. Los estudiantes que completen un programa de formación profesional pueden matricularse en la educación superior, pero puede tener que tomar cursos adicionales antes de ser elegible para aplicar.', '', '');
/*  Basílica  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Basílica', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'La basílica palabra latina (derivado del griego Stoa, la cámara de tribunal de un rey) fue originalmente utilizado para describir un edificio público romano situado en el foro de una ciudad romana. Por extensión, se aplica a los edificios cristianos de la misma forma. [NEWLINE] [NEWLINE] En el siglo cuarto, una vez que las autoridades imperiales habían despenalizado el cristianismo con el 313 Edicto de Milán, los cristianos estaban dispuestos a construir edificios más grandes y más hermosos para la adoración de los lugares de reunión furtivos que habían estado utilizando. Fórmulas arquitectónicas tradicionales de los templos eran inadecuados debido a asociaciones con creencias no cristianas. Ceremonias en los templos antiguos ocurrieron al aire libre bajo el cielo abierto ante los ojos de los dioses, con el templo como telón de fondo. El modelo de Constantino quería memorialise por su piedad imperial era la arquitectura de las basílicas (previamente seculares), la celebración de ceremonias en el interior.', '', '');
/*  Cothon  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'A Cothon (en griego: "buque beber") es un puerto artificial, protegido interior común en Cartago durante el c.200 aC Guerras Púnicas [NEWLINE] Cothons se encuentran generalmente en el mundo fenicio.. Los ejemplos incluyen Motya (Sicilia) desde el siglo sexto antes de Cristo, que lleva a cabo un propósito incierto, (que mide 35 metros x 51 metros), aunque se ha sugerido que este Cothon incluso podría haber sido que se puede cerrar y drenaje, hasta formar un dique seco. Mahdia (Túnez) desde el siglo séptimo antes de Cristo, (que mide 72 metros x 56 metros) y uno de Kition en Chipre.', '', '');
/*  Vedi  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi es el término para "alterar" en la religión védica, la religión más antigua todavía se practica en los tiempos modernos. Estos altares son un recinto elevado, generalmente sembrada de hierba Kusha, y tener receptáculos para el fuego del sacrificio.', '', '');
/*  Center de la NASA * ​​/
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA Centro', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'El Centro de la NASA es moderno centro de investigación era que otorga aumentos en tecnología. También proporciona un recurso libre de la nave espacial de la fábrica.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Desde su creación en 1958, la NASA ha logrado muchas grandes hazañas científicas y tecnológicas en el aire y el espacio. Tecnología de la NASA también ha sido adaptado para muchos usos nonaerospace por el sector privado. NASA sigue siendo una fuerza líder en la investigación científica y estimular el interés del público en la exploración del espacio aéreo, así como la ciencia y la tecnología en general. Tal vez lo más importante, nuestra exploración del espacio nos ha enseñado a ver la Tierra, nosotros mismos, y el universo de una manera nueva. Mientras que los grandes logros técnicos y científicos de la NASA demuestran claramente que los humanos pueden lograr hazañas previamente inconcebibles, también estamos humillados por la conciencia de que la Tierra es sólo una pequeña "canica azul" en el cosmos.', '', '');
/*  Abbey  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Abadía', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'La abadía tiene en su centro la práctica de la adoración, con la idea de no tener a todos a un servicio, sino para proporcionar oportunidades de adoración que Abbey adherentes pueden participar en forma regular, si no semanal. A través de sus servicios, las artes florecieron como una expresión de alabanza al "Creador". En adición abadías fueron autoportante, que participan en el cultivo de los campos, la cría de ganado, que operan los mercados públicos, y dar oportunidades de empleo a la comunidad. Las abadías celtas se convirtieron en los centros de enseñanza, la preservación de los manuscritos sagrados y literarios, y las escuelas de enseñanza.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'La Abadía es el centro espiritual y cultural celta de cada comunidad. Produce 1 [ICON_FOOD] Alimentos [ICON_RESEARCH] Ciencia, Cultura, [ICON_GOLD] Oro [ICON_CULTURE] y [ICON_PRODUCTION] Producción.', '', '');
/*  Odeon  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon, desde el griego antiguo ᾨδεῖον, Ōideion, literalmente "cantaba lugar", o "la construcción de competencias musicales". [NEWLINE] El más magnífico odeon era el Odeón de Herodes Atticus en el acantilado suroeste de la Acrópolis en Atenas, construida alrededor de 160 AD por el sofista ricos y retórico Herodes Atticus en memoria de su esposa. Tenía alojamiento para 8.000 personas, y el techo estaba construido con vigas bellamente tallado de madera de cedro, probablemente con un espacio abierto en el centro de admitir la luz. También fue profusamente decorado con fotografías y otras obras de arte.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'El Odeon es una fuente de instantánea [ICON_CULTURE] Cultura. La construcción de estos ayuda extendió las fronteras de su imperio.', '', '');
/*  Barbary puerto  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbary Puerto', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'Los piratas de Berbería, a veces llamados corsarios berberiscos o corsarios otomanos, eran piratas y corsarios que operaban desde el norte de África, con base principalmente en los puertos de Túnez, Trípoli y Argel. [NEWLINE] [NEWLINE] Esta zona era conocida en Europa como la Costa de Berbería , un término derivado del nombre de sus habitantes bereberes. [NEWLINE] Además de apoderarse de los buques, que se dedica a las razzias, las redadas en las ciudades costeras de Europa y los pueblos, sobre todo en Italia, Francia, España y Portugal, sino también en el British Isles, los Países Bajos y de lugares tan lejanos como Islandia. El objetivo principal de sus ataques era capturar esclavos cristianos para el mercado musulmán en el norte de África y Oriente Medio.', '', '');
/*  Cuenca de Riego  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Cuenca del Riego', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Los antiguos egipcios practicaban la irrigación cuenca utilizando la inundación del Nilo para inundar terrenos que habían sido rodeados por diques. Se celebró el agua de la inundación hasta que el sedimento fértil se había instalado antes de que el superávit fue devuelta al curso de agua. [NEWLINE] Hay evidencia del antiguo faraón egipcio Amenemhat III en la duodécima dinastía (alrededor de 1800 aC) con el lago natural del Oasis Fayum como un depósito para almacenar los excedentes de agua para su uso durante las estaciones secas, el lago creció anualmente de las inundaciones del Nilo.', '', '');





UPDATE LoadedFile SET Value=1, ES_ES=1 Where Type='Leaders.sql';




