/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Conscripción', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' 10 [COLOR_POSITIVE_TEXT] Heal Tasa [ENDCOLOR].', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Ejército Profesional', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Desbloquea promociones avanzadas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Mercantilismo', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' 2 [ICON_MOVES] Movimiento.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Libertad', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' 25% [ICON_STRENGTH] Fuerza en territorio amigo.', '', '');
/*  Libertad  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura: 1 en todas las ciudades [NEWLINE] [ICON_PRODUCTION] Producción: 1 en todas las ciudades [NEWLINE] [ICON_WORKER] Desbloquea: Terracota Ejército [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (Finalizar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Gran Persona: 1 de elección', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Colono: Producción 1 [NEWLINE] [ICON_PRODUCTION]: 25% de los colonos', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Oro: 200 x Época [NEWLINE] [ICON_CULTURE] Nuevas ciudades aumentan los costos de Política 33% menos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Trabajadores: 1 [NEWLINE] Precio [ICON_WORKER] Trabajador Mejora: 25%', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] 1 Felicidad Nacional por [ICON_CONNECTED] ciudad conectada. [NEWLINE] [ICON_HAPPINESS_4] -5% La infelicidad de [ICON_CITIZEN] Población en ciudades que no se [ICON_OCCUPIED] ocupados.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] edificio City Defense gratuito en todas las ciudades (corriente, nuevo y conquistaron). Con la tecnología apropiada investigado. [NEWLINE] [ICON_PRODUCTION] 1 Producción por City Defense Building.', '', '');
/*  Tradición  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura: 3 en El Capital [NEWLINE] [ICON_WORKER] Desbloquea: Banaue terrazas de arroz [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Gran Tarifas Por Persona:. 50% [NEWLINE] [ICON_CULTURE] Duplica expansión frontera cultural azulejos lejos de las ciudades [NEWLINE] [ICON_PEACE] Puede comprar grandes ingenieros con fe a partir de la era industrial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Narradores', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Cultura: 2 por Village y Palacio', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'La tradición oral es material cultural y la tradición transmitida oralmente de una generación a otra. Los mensajes y testimonios se transmiten verbalmente en el habla o el canto y pueden tomar la forma, por ejemplo, de los cuentos populares, refranes, romances, canciones, o cánticos. De esta manera, es posible que una sociedad para transmitir la historia oral, la literatura oral, la ley oral y otros conocimientos de generación en generación sin un sistema de escritura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Ritos ceremoniales', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Cultura: 1 por Cultura Edificio [NEWLINE] [ICON_CULTURE] 1 Edificio Cultural libre en sus 4 ciudades más antiguas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Una ceremonia es un acontecimiento de significación ritual realizado en una ocasión especial. Ceremonias pueden tener una pantalla física o componente teatral: la danza, la procesión, la imposición de manos. Un pronunciamiento declarativo verbal puede estar asociada con la ocasión. [NEWLINE] [NEWLINE] Una ceremonia puede marcar un rito de iniciación en la vida humana, que marca la importancia del nacimiento, la edad adulta, la iniciación en un grupo, o la muerte. A veces una ceremonia sólo puede ser realizada por una persona con cierta autoridad. Ceremonias en toda la sociedad puede marcar eventos anuales o estacionales o recurrentes, como el equinoccio de primavera, solsticio de invierno y otras posiciones astronómicas anuales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Alimentación Excedente: 25% por la ciudad [NEWLINE] [ICON_FOOD] Alimentación: 2 por ciudad', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Ataque Ciudad: 50% de las guarniciones [NEWLINE] [ICON_GOLD] No hay mantenimiento para las unidades guarnecidas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Producción: 15% de las Maravillas [NEWLINE] [ICON_HAPPINESS_1] Felicidad: 1 por 10 [ICON_CITIZEN] Ciudadanos', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Los ciudadanos de la capital crean 0.5 [ICON_GOLD] El oro y 0,5 [ICON_HAPPINESS_1] Felicidad.', '', '');
/*  Honor  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Habilidades:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] revela campamentos bárbaros [NEWLINE] [ICON_STRENGTH] 10% de la fuerza contra los bárbaros [NEWLINE] [ICON_CULTURE] bárbaros Killing da 2 Cultura por . fuerza de los enemigos derrotados [NEWLINE] [ICON_WORKER] Desbloquea: Templo de Artemisa [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] [ENDCOLOR] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Ciudad Finisher Felicidad: 1 por cada Cuartel', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] Unidades de Defensa en la capital. [NEWLINE] [ICON_PRODUCTION] Producción 20% de las unidades militares y edificios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Botín de guerra', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Salvage oro del equipo de los enemigos derrotados. [NEWLINE] [ICON_CITY_STATE] 25% recompensas de la captura de las ciudades-estado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'El saqueo de un ejército victorioso en la guerra ha sido una práctica común en toda la historia registrada. Para los soldados de infantería, fue visto como una forma de complementar sus ingresos a menudo pobre y fue parte de la celebración de la victoria. En niveles más altos, la exposición orgulloso de botín era una parte integral del triunfo típica romana, y Genghis Khan no era inusual en la proclamación de que la mayor felicidad era "para vencer a tus enemigos ... para robarles sus riquezas ..." [NEWLINE] [NEWLINE] En la guerra en la antigüedad, el botín de guerra incluyen las poblaciones derrotadas, que a menudo fueron esclavizadas, y las mujeres y los niños, que a menudo eran absorbidos por la población del país victorioso. En otras sociedades premodernas, los objetos de metales preciosos fueron el blanco preferido de los saqueos de guerra, en gran parte debido a su fácil traslado. En muchos casos, el saqueo era una oportunidad para obtener tesoros que de otra manera no habrían sido obtenible. Desde el siglo 18, las obras de arte se han convertido en cada vez más un objetivo popular. En la década de 1930 y más aún durante la Segunda Guerra Mundial, la Alemania nazi dedica a gran escala y organizó el saqueo de arte y propiedad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiators', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Felicidad City: 1 por Arena [NEWLINE] 2 Unidades de Defensa [ICON_TEAM_2] en la capital..', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'Epopeyas de Guerra', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' 1 [ICON_HAPPINESS_1] Felicidad Ciudad de los edificios de Cultura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Una epopeya (desde el antiguo adjetivo ἐπικός griega (epikos), desde ἔπος (EPOS) "palabra, historia, poema") es un largo poema narrativo, normalmente en relación con un tema serio que contiene detalles de los hechos y acontecimientos heroicos significativa a una cultura o nación . [NEWLINE] [NEWLINE] epopeyas de guerra son los poemas épicos o una obra literaria de alcance épico que buscan o que se cree para captar y expresar la esencia o el espíritu de una nación en particular, o un grupo étnico o lingüístico con aspiraciones a la independencia o autonomía. Epopeyas nacionales con frecuencia relatan el origen de una nación, una parte de su historia, o un acontecimiento crucial como victorias decisivas o la derrota de los enemigos acérrimos, en el desarrollo de la identidad nacional', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Felicidad City: 1 por la guarnición [NEWLINE] [ICON_CULTURE] Cultura: 2 por la guarnición', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Gran general: 1 [NEWLINE] [ICON_MOVES] Movimiento:. 1 para Grandes generales [NEWLINE] [ICON_STRENGTH] 15% de fuerza para todas las Unidades adyacentes a otras unidades militares amigas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] 15% cuando [COLOR_POSITIVE_TEXT] adyacente [ENDCOLOR] a unidades militares amigas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] costo de actualización: -50% para las unidades [NEWLINE] [ICON_PRODUCTION] Producción: 15% para todas las unidades', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Code Warrior [ENDCOLOR] [NEWLINE]', '', '');
/*  Piedad  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Habilidades:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura 1 [NEWLINE] [ICON_PEACE] Fe 1 [NEWLINE] [ICON_PRODUCTION] Producción Doble Santuarios [ICON_WORKER] Desbloquea: Stonehenge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] Elegir una nueva creencia piadosa.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Caridad', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Oro: 25% de los Templos [NEWLINE] [ICON_GOLD] Oro: 2 de Templos [NEWLINE] [ICON_GOLD] Oro: 3 Lugares Santos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'La palabra "caridad" viene de la antigua palabra francesa "Charité", que, a su vez, se deriva de las "caritas" Latina. [NEWLINE] [NEWLINE] El ejercicio de la caridad significa la entrega voluntaria de ayuda a los necesitados que están no relacionados con el donante, aunque el significado original está más involucrado con los conceptos de valor inapreciable, carestía de vida, precio alto. Las donaciones caritativas se realiza directamente o por medio de un fondo de caridad u otra causa. Estas instituciones han evolucionado para llevar a cabo la labor de asistencia a los pobres, y llegó a ser llamado, llamado ''caridades. En las caridades de ''Tiempos modernos proporcionar la mayor parte de las donaciones caritativas, en términos de valor monetario. Los tipos de organizaciones benéficas incluyen orfanatos, bancos de alimentos, institutos religiosos dedicados al cuidado de los pobres, hospitales, organizaciones que visitan los confinados y encarcelados, y muchos otros.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Inspiración', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Gratis Gran Profeta: 1', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'La palabra "inspiración" viene del sustantivo latino inspiratio y desde el inspirare verbo. Inspirare es un término compuesto resultante del prefijo latino (en el interior, en) y el spirare verbo (para respirar). [NEWLINE] [NEWLINE] En tiempos de los romanos clásicos, inspirare ya había llegado a significar "respirar profundamente" y asumió también el sentido figurado de "inculcar [algo] en el corazón o en la mente de una persona". [NEWLINE] [NEWLINE] De ahí que "inspiración" se refiere a un estallido inconsciente de la creatividad en una obra literaria, musical, u otra actividad artística. El concepto tiene su origen en tanto el helenismo y el judaísmo. Los griegos creían que la inspiración vino de las musas, así como de los dioses Apolo y Dioniso. Del mismo modo, en las religiones nórdicas antiguas, la inspiración proviene de los dioses, como Odin. La inspiración es también una cuestión divina en las poéticas hebreas. En el libro del profeta Amosthe habla de ser abrumado por la voz de Dios y obligado a hablar. En el cristianismo, la inspiración es un don del Espíritu Santo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Tolerancia', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Felicidad City: 1 por edificio religioso [NEWLINE] [ICON_PEACE] Ciudades con múltiples religiones también tienen la ventaja Panteón de segunda religión más popular de la ciudad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'La tolerancia o la tolerancia es "la práctica de permitir o permitir una cosa de la que uno desaprueba deliberadamente. Uno puede hablar con sentido de tolerar, es decir, de permitir o autorizar, sólo si uno está en una posición de no permitir". También se ha definido como " llevar o aguantar "o" para nutrir, sustentar o preservar ". Tolerancia puede significar" no es más que la paciencia y el permiso dado por los seguidores de una religión dominante de otras religiones a existir, a pesar de que estos últimos se miraban con desaprobación mientras inferior, errónea o perjudicial "[NEWLINE] [NEWLINE] La tolerancia es una actitud mental que implica la aceptación sin prejuicios de los diferentes estilos de vida y creencias, mientras que la tolerancia implica poner con algo que uno desaprueba. [NEWLINE] [NEWLINE] Ejemplos históricos de la "tolerancia" abundan. Por ejemplo, en un acto de tolerancia, se creía que el rey persa Ciro el Grande que han dado a conocer los Judios de su cautiverio en 539-530 aC, y se le permitió regresar a su patria.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Unidad', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Golden Age Turns: 10 [NEWLINE] [ICON_GOLDEN_AGE] Edades de Oro requieren un 50% menos [ICON_HAPPINESS_1] Felicidad Nacional', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Unidad refiere a los lazos en una sociedad que unen a las personas entre sí. El término se emplea generalmente en la sociología y otras ciencias sociales. [NEWLINE] [NEWLINE] En las sociedades simples que puede basarse principalmente en el parentesco y los valores compartidos. En las sociedades más complejas hay varias teorías en cuanto a lo que contribuye a un sentido de la solidaridad social [NEWLINE] [NEWLINE] Esto introduce el término asociado de la "solidaridad" de la que se dice:. [NEWLINE] "La solidaridad no asume que nuestras luchas son las mismas luchas, o que nuestro dolor es el mismo dolor, o que nuestra esperanza es que el mismo futuro. Solidaridad implica el compromiso y el trabajo, así como el reconocimiento de que, incluso si no tenemos los mismos sentimientos, o las mismas vidas, o los mismos órganos, que viven en un terreno común ". - Sara Ahmed', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Meditación', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Fe: 1 santuarios, templos [NEWLINE] [ICON_PEACE] Costos Fe: -33%', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Devoción', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'La devoción se puede definir como: ardiente, afecto a menudo desinteresado y la dedicación, como a una persona o principio. Culto, de la worthscipe Inglés Antiguo, que significa dignidad o valor-barco es un acto de devoción religiosa por lo general dirigidas a una deidad. Estrechamente vinculada al concepto del amor, la devoción es a menudo la esperanza de ser correspondido con algún tipo de bendición o bendición. [NEWLINE] [NEWLINE] Los devotos, como los que practican la devoción se llama querer recibir estas bendiciones, son a menudo de una sola mente para el punto del fanatismo. Así, mientras que el concepto de ''devoción'' es benigno, muchos ejemplos históricos de la devoción religiosa a menudo extrema y sangrienta, como devotos compiten por el afecto de los devotos con pantallas más indignantes.', '', '');
/*  Riqueza  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Riqueza', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'RIQUEZA', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'La riqueza es la abundancia de recursos valiosos o posesiones materiales. El concepto de riqueza es significativa en todos los ámbitos de la economía, sin embargo, el significado de la riqueza depende del contexto y no hay acuerdo universal sobre la definición. A la riqueza de nivel más general es "cualquier cosa de valor", que captura tanto la naturaleza subjetiva de la palabra, y la idea de que no es un concepto fijo o estático.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', '¿Cuál es la rama de la política social sobre la Riqueza?', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'La rama de la riqueza se concentra en desarrollar el territorio de ancho, con una oferta nacional de [ICON_GOLD] Oro creado por las ciudades principales para comprar nuevas unidades y edificios en ciudades fronterizas subdesarrolladas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'La rama de la riqueza se concentra en desarrollar el territorio de ancho, con una oferta nacional de [ICON_GOLD] Oro creado por las ciudades principales para comprar nuevas unidades y edificios en ciudades fronterizas subdesarrolladas. Consulte las normas de Políticas Sociales para obtener más detalles.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'El Poder Riqueza', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_GOLD] Oro: 10% {TXT} [NEWLINE] [] ICON_PRODUCTION de producción: 10% {TXT} [NEWLINE] [ICON_WORKER] Desbloquea : Canal de Panamá [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Felicidad: 1 por cada mercado, Smithy [NEWLINE] [ICON_PEACE] Puede comprar grandes comerciantes con fe al entrar en la era industrial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' 2 [ICON_MOVES] Movimiento por unidades no combatientes. [NEWLINE] 25% [ICON_GOLD] Ingresos de [ICON_CONNECTED] Comercio Interior. [NEWLINE] -25% [ICON_GOLD] Costo de carreteras y ferrocarriles.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Oro: 1 por cada Village [NEWLINE] [ICON_PRODUCTION] Producción: 1 por cada mina, Lumbermill', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Puede comprar Landsknechts. [NEWLINE] [ICON_TEAM_2] 2 Landsknechts aparecen en la Capital.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Gratis Gran mercader: 1 [NEWLINE] [ICON_GREAT_PEOPLE] Gran Cambio Merchant: 25% [NEWLINE] [ICON_GREAT_MERCHANT] Doble de Oro de Grandes misiones comerciales Merchant.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Caravanas', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Oro: 3 por Ruta Comercial', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Producción: 4 por Coastal City [NEWLINE] [ICON_GOLD] Oro: 4 por Faro, Puerto, Puerto', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Gremios', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' 1 [ICON_TEAM_7] Gran mercader en la Capital. [NEWLINE] [ICON_GOLD] Oro de Grandes misiones comerciales Merchant 100%.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Una alianza es una asociación de artesanos en un comercio particular. Los primeros tipos de gremio se formaron como cofradías de trabajadores. Estaban organizados de una manera algo entre un sindicato, un cartel y una sociedad secreta. A menudo dependían de concesiones de patentes de invención por un monarca o de otra autoridad para hacer cumplir el flujo del comercio entre sus miembros por cuenta propia, y para conservar la propiedad de las herramientas y el suministro de materiales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] El costo de compra de las unidades y edificios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Derecho de Patentes', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' 1 [ICON_GOLD] Oro de Aldeas. [NEWLINE] 2 [ICON_GOLD] Oro de Puertos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Una patente es un conjunto de derechos exclusivos concedidos por un Estado (gobierno nacional) a un inventor o su cesionario por un período limitado de tiempo a cambio de la divulgación pública de una invención. [NEWLINE] [NEWLINE] Las patentes en el sentido moderno se originó en 1474, cuando la República de Venecia promulgó un decreto que los dispositivos nuevos e innovadores, una vez puestas en práctica, tuvieron que ser comunicada a la República para obtener el derecho de impedir a otros su utilización. [NEWLINE] [NEWLINE] Inglaterra siguió con la Ley de Monopolios en 1623 bajo el reinado de James I, que declaró que las patentes sólo se podían conceder para "proyectos de nueva invención." Durante el reinado de la reina Ana (1702-1714), los abogados de El Corte Inglés ha desarrollado el requisito de que una descripción escrita de la invención debe ser presentada. El sistema de patentes en muchos otros países se basa en la ley británica y se remonta a la Ley de Monopolios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] Moves y 1 Sight para los buques militares. [NEWLINE] 2 [ICON_RESEARCH] Ciencia para las ciudades costeras. [NEWLINE] 2 Science [ICON_RESEARCH] para Edificios Navales.', '', '');
/*  Patrocinio  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Habilidades:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_GOLD] 2 Oro por la ciudad-Estado de Rutas Comerciales [NEWLINE] [ICON_VIEW_CITY] Revela todos las ciudades-estado [NEWLINE] [ICON_WORKER] Desbloquea : Angkor Wat [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [icon_plus] Cantidad de recurso estratégico 100% y 50% [ICON_HAPPINESS_1] Nacional La felicidad de los recursos de lujo dotados por aliados Ciudad-Estado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] 20 Influencia instantánea con las ciudades-estado. [NEWLINE] [ICON_INFLUENCE] 33% Influencia de [ICON_GOLD] regalos de oro a las ciudades-estado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Relación especial', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Influencia de las ciudades-estado se degrada 33% más lento de lo normal. [NEWLINE] [ICON_INFLUENCE] Influencia de otros jugadores con las ciudades-estado se reduce un 10% más rápido.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] 20 descansando influencia con las ciudades-estado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] 2 Ciencia por época por cada amigo de la ciudad-Estado, y 3 para cada aliado.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[] ICON_GREAT_PEOPLE regalo aliados Ciudad-Estado Great People. [ICON_GREAT_PEOPLE] 10% Great People Cambio.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Pacto de Comercio', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' 2 [ICON_PRODUCTION] Producción por época por cada amigo de la ciudad-Estado, y 3 para cada aliado (división entre sus ciudades).', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'El libre comercio es un sistema de la política comercial que permite a los comerciantes para comerciar a través de fronteras nacionales, sin la interferencia de los gobiernos respectivos. Debido al principio económico de la ventaja comparativa, esto proporciona a los socios comerciales con beneficios mutuos. En virtud de esta política de precios son el único determinante de la asignación de recursos, y un cierre reflejo de la oferta y la demanda.', '', '');
/*  Estética  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] 50% de producción de edificios culturales [NEWLINE] [ICON_WORKER] Desbloquea:. Uffizi [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] Revela sitios Antigüedad ocultos. [NEWLINE] [ICON_TEAM_7] Permite la compra de Culturales gran gente con [ICON_PEACE] fe al entrar en la Era Industrial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Cultura: 1 por 2 superávit felicidad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Cultura: 2 por Nacional Wonder [NEWLINE] [ICON_CULTURE] Cultura: 33% en las ciudades con una Maravilla del Mundo', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Gran Artista: 1 [NEWLINE] [ICON_TEAM_7] Cultural tasa Gran Persona: 25%', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Los arqueólogos se producen dos veces más rápido', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Dobles turismo edificio de tema. [NEWLINE] [ICON_TOURISM] 25% del turismo de la religión compartida, la apertura de fronteras y rutas comerciales.', '', '');
/*  Exploración  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_MOVES] Manejaba: 2 Unidades embarcó [NEWLINE] [ICON_MOVES] Manejaba: 2 de Grandes Almirantes [NEWLINE] [ICON_SIGHT_SEA] Sight: + 1 para los buques militares [NEWLINE] [ICON_WORKER] Desbloquea: Fuerte Rojo [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (Finalizar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] 2 Nacionales Felicidad por recurso de lujo. [NEWLINE] [ICON_TEAM_7] Permite la compra de Grandes Almirantes con fe al entrar en la Era Industrial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Felicidad City: 1 por cada faro, puerto, puerto', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Coste de compra: -25% para los edificios [NEWLINE] [ICON_GOLD] Mantenimiento: -25% para los edificios', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Colonización', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Ciudades comienzan con 3 habitantes. [NEWLINE] [ICON_TEAM_2] 2 Colonos, 2 trabajadores, y 2 unidades de defensa aparecen en la Capital.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Espíritu Pionero', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] 1 movimiento de la población civil. [NEWLINE] [ICON_GOLD] costo -50% para carreteras. [NEWLINE] [ICON_PRODUCTION] La producción de 100% para la construcción de puertos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Homestead Act', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Ciudades ganan capa gratuita 1 edificios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(TODO)', '', '');
/*  Conocimiento  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Conocimiento', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'CONOCIMIENTO', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'El conocimiento es una familiaridad con alguien o algo, que puede incluir datos, información, descripciones, o las habilidades adquiridas por la experiencia o la educación. Puede referirse a la comprensión teórica o práctica de un sujeto. Puede ser técnica o conocimiento práctico, o la comprensión teórica de un sujeto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Piedad aumenta la Felicidad, Cultura y Fe de la civ adopción. Piedad esté disponible una vez que se alcanza la Época Clásica. Este es un lugar ideal para adquirir las políticas para los jugadores que buscan crear o ampliar las religiones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', '¿Cuál es el conocimiento de la política social sobre la rama?', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'La rama del conocimiento mejora la capacidad de la civilización de usar y generar ciencia, estén disponibles al entrar en el Renacimiento.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'La rama del conocimiento de las políticas sociales está llena de las políticas que pueden aumentar su investigación. Esta rama se encuentre disponible en la época renacentista. Consulte las normas de Políticas Sociales para obtener más detalles.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'El Poder del Conocimiento', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Habilidades: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Abridor [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Gran Científico: 1 [NEWLINE] [ICON_WORKER] Desbloquea: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [ COLOR_GREY] (terminar todas las políticas en este árbol) [ENDCOLOR] [NEWLINE] 1 instantánea [ICON_TEAM_5] Tecnologías. [NEWLINE] [ICON_PEACE] Puede comprar grandes científicos con [ICON_PEACE] La fe una vez que entramos en la era industrial.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[] ICON_RESEARCH recompensas acuerdo de investigación 50%.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Contraespionaje', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] 25% de posibilidades de atrapar espías enemigos. [NEWLINE] [ICON_SPY] -25% de efectividad espía enemigo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(TODO)', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Ciencia: 10%, mientras que la nación es [ICON_HAPPINESS_1] feliz', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Ciencia: 1 por cada Village [NEWLINE] [ICON_RESEARCH] Ciencia: 2 por Faro', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Ciencia: 2 por especialista', '', '');







UPDATE Loaded File SET Value=1, ES_ES=1 Where Type='Policies.sql';



