/* The sql commands and text below were formulated in the Research tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1194171600
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING', 'Formación', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_PEDIA', 'El entrenamiento militar es un proceso que establece y mejorar las capacidades del personal militar. La educación militar puede ser deber voluntario u obligatorio. [NEWLINE] Entrenamiento de Reclutas intenta enseñar a la información básica y la formación en técnicas necesarias para ser un miembro de un servicio efectivo. Para lograr esto, los miembros del servicio se perforan física, técnica y psicológicamente. [NEWLINE] Después de terminar el entrenamiento básico, muchos miembros del servicio reciben capacitación avanzada más en línea con sus especialidades elegidas o asignados. En el entrenamiento avanzado, tecnología y equipos militares a menudo se les enseña.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_QUOTE', '[NEWLINE] [TAB] [TAB] "El servicio militar obligatorio si es necesario, pero no necesariamente el servicio militar obligatorio". [NEWLINE] [TAB] [TAB] - William Lyon Mackenzie King [NEWLINE]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE', 'Ciencias Políticas', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_PEDIA', 'Durante el Renacimiento italiano, Niccolò Machiavelli estableció el énfasis de la ciencia política moderna en la observación empírica directa de las instituciones y actores políticos. [NEWLINE] [NEWLINE] Más tarde filósofos europeos como Voltaire, Rousseau, Thomas Hobbes y John Locke aplican los principios de las ciencias de los materiales de la sociedad en su conjunto, la creación de las ciencias sociales. Éstos abrieron el camino para políticas que enfatizaba un contrato social entre gobernantes y gobernados, la necesidad de una separación de la iglesia y el estado, y la disminución gradual del derecho divino de los reyes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_QUOTE', '[NEWLINE] [TAB] [TAB] "La política no tienen relación con la moral". [NEWLINE] [TAB] [TAB] - Nicolás Maquiavelo [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_TITLE', 'Comercio', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_DESC', 'Comercio se originó con el inicio de la comunicación en los tiempos prehistóricos. Se estimuló la curiosidad común, el ingenio y el aprendizaje de idiomas. Como tal, el comercio y la especialización que engendró ha sido acreditado con la aceleración del crecimiento de la conciencia humana y el triunfo de los seres humanos sobre la especie neandertal. [NEWLINE] [NEWLINE] Hay evidencia del intercambio de obsidiana y pedernal durante la Edad de Piedra. Egipto cambiado por los materiales utilizados para la creación de joyas desde el año 3000 antes de Cristo. Rutas comerciales de largo alcance aparecieron por primera vez cuando los sumerios en Mesopotamia comerciaban con la civilización Harappa del valle del Indo. Los fenicios - señaló comerciantes marítimos - viajaron a través del Mar Mediterráneo, y tan al norte como Gran Bretaña por las fuentes de estaño para fabricar bronce. Ellos establecieron el comercio colonias que los griegos llamaban emporia. [NEWLINE] [NEWLINE] Comercio continuó impulsando la tendencia humana de explorar mucho después de la desaparición de los antiguos imperios marítimos mediterráneos. Propagación comercio a larga distancia incluso más lejos con enorme flota de la Zheng He, que llegó a la India, Arabia y África del Este antes de que Colón cruzó el océano.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE] [TAB] [TAB] "No hay razón existe hoy en día para descontar la presencia o impacto potencial de la economía en el amanecer de pre-histórico de la humanidad". [NEWLINE] [TAB] [TAB] - Jason Shogren [NEWLINE] [ TAB]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE] [NEWLINE] Ninguno de los jugadores todavía tiene la tecnología para cambiar este objeto (Comercio).', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS', 'Carvel Cascos', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'Diseño Carvel barco era uno de los acontecimientos cruciales que permitieron a la dominación de las potencias navales de Europa occidental desde 1400 hasta el presente. Los tablones de madera en cascos carvel alinean uno contra el otro, de borde a borde, en lugar del diseño del tablón superposición de los cascos de clinker. Este diseño del casco más fuerte apoya barcos y velas más grandes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE] [TAB] [TAB] "Un barco está a salvo en el puerto, pero eso no es lo que los barcos son para." [NEWLINE] [TAB] [TAB] - William Shedd [NEWLINE]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Medios de comunicación', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_DESC', 'El término "medios de comunicación" fue acuñado en la década de 1920 con la llegada de la radio, pero la idea de los medios de comunicación para gran consumo público ha estado presente desde los dramas y obras de teatro del mundo antiguo. Los medios de comunicación ha sido impulsada directamente por la tecnología, con mayores avances en las técnicas de edición y comunicaciones que llevan a aún mayores audiencias posibles de ser alcanzadas. [NEWLINE] [NEWLINE] Originalmente sólo se aplica a dispositivos de comunicación como radio, periódicos y revistas, medios de comunicación abarca ahora televisión, películas, música, libros de bolsillo, los videojuegos e Internet. Con la llegada de este tipo de medios de comunicación-que abarca el globo se ha planteado también la posibilidad de llegar a las masas como nunca antes, y no siempre en el buen sentido. El intento de sesgo o de control de grandes cantidades de información, ya sea a través de la propaganda vilmente de mente o las opiniones personales más inocentes que se inyecta en los hechos, se está convirtiendo en un gran problema para algunos gobiernos y organizaciones a tratar. Técnicas de publicidad invasoras son también un subproducto de los medios de comunicación, para gran disgusto de los consumidores en todas partes. Mientras que el mensaje puede ser útil y es cada vez más fácil para la persona común para publicar sus ideas y obras de arte, se les escuche en la salida torrencial de información ahora disponible realmente puede ser como buscar la aguja en un pajar.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE] [TAB] [TAB] "La velocidad de las comunicaciones es maravilloso para la vista también es cierto que la velocidad puede multiplicar la difusión de la información que sabemos que no es cierto.". [NEWLINE] [TAB] [TAB] - Edward R. Murrow [NEWLINE] [TAB] [TAB] [TAB]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Fabricación en serie', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'La producción en masa moderna es la construcción de grandes cantidades de productos estandarizados en líneas de montaje. Ingredientes importantes para la producción en serie de maquinaria y equipo industrial, partes intercambiables, de gestión científica, y la energía eléctrica. [NEWLINE] [NEWLINE] La producción en masa se popularizó en la década de 1910 y 1920 por parte de Ford Motor Company de Henry Ford, que introdujo los motores eléctricos para el bienestar técnica conocida de la cadena de producción o secuencial. Ford también han comprado o diseñado y construido máquinas herramientas y accesorios especiales. Todas estas máquinas-herramienta se organizaron sistemáticamente en el flujo de producción. Dirección de Ford realizó estudios de tiempo y experimentos para mecanizar sus procesos de fábrica, centrándose en reducir al mínimo los movimientos de los trabajadores.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE] [TAB] [TAB] "Hay una regla para el industrial y que es la siguiente:. Hacer la mejor calidad de los productos posibles al menor costo posible, el pago de los salarios más altos posibles" [NEWLINE] [TAB] [TAB] - Henry Ford [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Ion Propulsion', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_DESC', 'La propulsión de elección para los escritores de ciencia ficción se ha convertido en la propulsión de la opción para los científicos e ingenieros de la NASA. Uso eficiente del sistema de propulsión iónica de combustible y energía eléctrica permiten modernas naves espaciales para viajar más lejos, más rápido y más barato que cualquier otra tecnología de propulsión disponibles en la actualidad. Propulsores de iones se utilizan actualmente para stationkeeping en los satélites de comunicación y para la propulsión principal de las sondas del espacio profundo. Propulsores de iones expulsan iones para crear empuje y pueden proporcionar mayores velocidades máximas de naves espaciales que cualquier otro cohete disponibles actualmente. [NEWLINE] Un ion es simplemente un átomo o molécula que se carga eléctricamente. En un propulsor de iones, los iones son acelerados por las fuerzas electrostáticas. Los campos eléctricos utilizados para la aceleración son generados por electrodos colocados en el extremo de aguas abajo de la hélice. [NEWLINE] modernos propulsores de iones utilizan gases inertes para el propelente. La mayoría de los propulsores utilizar xenón, que es químicamente inerte, incoloro, inodoro e insípido. El propulsor se inyecta desde el extremo aguas abajo de la hélice y fluye hacia el extremo aguas arriba.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE] [TAB] [TAB] "Todas las civilizaciones se convierten ya sea spacefaring o extintas." [NEWLINE] [TAB] [TAB] - Carl Sagan [NEWLINE] [TAB]', '', '');




UPDATE Loaded File SET Value=1, ES_ES=1 Where Type='Research.sql';





