/* The sql commands and text below were formulated in the Stories tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1563932649
If you make any changes be sure to update the spreadsheet also.*/

/*  Terreno  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING', 'Río Inundaciones', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_DESC', 'Inundaciones estacionales frecuentes de este río proporcionan tierra vegetal inusualmente fértil para la agricultura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_1', 'Pagar por los nuevos canales de riego a lo largo del río.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_2', 'La investigación de mejores formas de proteger a los hogares de las inundaciones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_OUTCOME_3', 'Deje que los lugareños manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_1', '[ICON_TEAM_3] Nuevo riego río mejoró [ICON_FOOD] Alimentos para {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_2', '[ICON_TEAM_3] está en marcha nuevo [ICON_RESEARCH] La investigación para proteger a los ciudadanos de {1} de las inundaciones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RIVER_FLOODING_ALERT_3', '[ICON_TEAM_3] Nuevo riego río mejoró [ICON_GOLD] ingreso económico para {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE', 'Desierto de Adobe', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_DESC', 'Una forma inusualmente resistente y hermosa de la arcilla del adobe de la construcción se desarrolló fuera {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_1', 'Utilice el estilo distintivo para mejorar nuestros monumentos culturales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_2', 'Utilice el ladrillo para la construcción práctica.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_OUTCOME_3', 'Deje que los lugareños manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_1', '[ICON_TEAM_3] Un nuevo estilo de ladrillos de adobe mejorado la [ICON_CULTURE] Cultura de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_2', '[ICON_TEAM_3] Las innovaciones en la construcción de adobe mejorado [ICON_PRODUCTION] Producción cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DESERT_ADOBE_ALERT_3', '[ICON_TEAM_3] Una nueva forma de construcción de adobe mejorado la [ICON_GOLD] Economy cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS', 'Nieve Trineos', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_DESC', 'Las innovaciones en los viajes alpinos hechos terreno cerca {2} más accesible.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_1', 'Utilice los trineos para las carreras recreativas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_2', 'Utilice los trineos para explotar nuevos recursos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_OUTCOME_3', 'Deje que los lugareños manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_1', '[ICON_TEAM_3] Innovaciones en trineos de nieve provocaron nuevas razas cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_2', '[ICON_TEAM_3] Innovaciones en trineos de nieve abrieron nuevos recursos cerca de {2} a la explotación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SNOW_SLEDS_ALERT_3', '[ICON_TEAM_3] Innovaciones en trineos de nieve mejoraron la [ICON_GOLD] Economy cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE', 'Refugio de Montaña', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_DESC', 'Cima de una montaña escénica cerca {2} es extraordinariamente adecuado para la habitación humana.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_1', 'Construir un santuario espiritual para el descanso y la meditación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_2', 'Construir un retiro académico para estudiar las estrellas y las estaciones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_OUTCOME_3', 'Deje que los lugareños manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_1', '[ICON_TEAM_3] Un refugio espiritual cima de la montaña se incrementó [ICON_CULTURE] Cultura cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_2', '[ICON_TEAM_3] Un retiro académico montaña aumentó [ICON_RESEARCH] Ciencia cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MOUNTAIN_REFUGE_ALERT_3', '[ICON_TEAM_3] Los comerciantes están vendiendo mercancía a los visitantes de una montaña cerca de {2}.', '', '');
/*  MEJORAS  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING', 'La agricultura comercial', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_DESC', 'Los individuos ricos planean comprar y comercializar pequeñas granjas cerca {2}, a menos que los agricultores locales puedan aumentar sus ingresos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_1', 'Invertir en la cultura de la agricultura tradicional.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_2', 'Apoyar a las fusiones con incentivos de tesorería.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_OUTCOME_3', 'Permitir las compras sin interferencias.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_1', '[ICON_TEAM_3] Los agricultores tradicionales son una parte importante de la [ICON_CULTURE] Cultura cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_2', '[ICON_TEAM_3] Comercialización mejorado granja [ICON_FOOD] Alimentación cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COMMERCIAL_FARMING_ALERT_3', '[ICON_TEAM_3] Buyouts mejoraron granja [ICON_GOLD] Oro cerca de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION', 'Expansión de la mina', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_DESC', 'Los operadores de minas cerca de {2} descubrieron el mineral valioso, pero los trabajadores están protestando por las condiciones peligrosas en los nuevos ejes de la rama.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_1', 'Dar apoyo nacional para mejorar la seguridad en las minas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_2', 'Utilizar los fondos de tesorería a contratar esquiroles.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_OUTCOME_3', 'Deje que el operador de la mina manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_1', '[ICON_TEAM_3] Mineros cerca {2} son [ICON_HAPPINESS_1] feliz acerca de las condiciones de trabajo más seguras.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_2', '[ICON_TEAM_3] Rápidamente poner fin a una huelga de {2} ''s mina expandida [ICON_PRODUCTION] Producción.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MINE_EXPANSION_ALERT_3', '[ICON_TEAM_3] Una mina cerca de {2} descubrió un [ICON_GOLD] Rentable nueva veta de mineral.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS', 'Protestas Village', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_DESC', 'Los ciudadanos de una aldea cerca de {2} están luchando en condiciones de alta pobreza y la delincuencia.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_1', 'Mejorar la educación para los pobres para calificar para un mejor trabajo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_2', 'Mejorar la fuerza policial para las tasas de criminalidad más bajas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_OUTCOME_3', 'Deje que el alcalde del pueblo manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_1', '[ICON_TEAM_3] Una aldea cerca de {2} mejorado [ICON_RESEARCH] La educación para los pobres.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_2', '[ICON_TEAM_3] Los aldeanos cerca de {2} son [ICON_HAPPINESS_1] feliz sobre los índices de criminalidad más bajos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_VILLAGE_PROTESTS_ALERT_3', '[ICON_TEAM_3] Una fuerte presencia policial ha mejorado la economía [ICON_GOLD] de un pueblo cerca de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND', 'Demanda Plantación', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_DESC', 'La demanda está aumentando para los cultivos de una plantación cerca de {2}, donde los trabajadores de la cosecha de los campos por un salario bajo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_1', 'Promulgar leyes para mejorar las condiciones salariales y de los trabajadores.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_2', 'Menores obstáculos al comercio para fortalecer la economía de exportación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_OUTCOME_3', 'Deje que los dueños de las plantaciones manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_1', '[ICON_TEAM_3] recolectores Plantation cerca {2} son [ICON_HAPPINESS_1] Feliz por mejores condiciones de trabajo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_2', '[ICON_TEAM_3] barreras comerciales más bajas mejoraron plantación [ICON_FOOD] Alimentación cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLANTATION_DEMAND_ALERT_3', '[ICON_TEAM_3] Aumento de la demanda de mejora de plantación [ICON_GOLD] Ingresos cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS', 'Exóticas Camp Animales', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_DESC', 'Animales exóticos fueron descubiertos fuera del campamento cerca de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_1', 'Crear un animal preservar para mejorar el turismo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_2', 'Construir un caza extravagante lodge.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_OUTCOME_3', 'Deje que los lugareños manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_1', '[ICON_TEAM_3] Una exótica naturaleza preservar la mejora del turismo [ICON_CULTURE] Cultura cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_2', '[ICON_TEAM_3] Un pabellón de caza aumentó [ICON_FOOD] Alimentación de animales exóticos cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_CAMP_ANIMALS_ALERT_3', '[ICON_TEAM_3] Animales exóticos descubiertos cerca {2} mejoraron caza [ICON_GOLD] oro.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY', 'Cantera Calidad', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_DESC', 'Una vena roca inusualmente alta calidad fue descubierto en la cantera fuera {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_1', 'Alquiler de artesanos para elaborar esculturas de la roca.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_2', 'Financiar la maquinaria adicional para las operaciones mineras velocidad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_OUTCOME_3', 'Deje que el encargado de la cantera manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_1', '[ICON_TEAM_3] esculturas magníficas mejoraron [ICON_CULTURE] Cultura cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_2', '[ICON_TEAM_3] Una cantera cerca de {2} Producción ampliado [ICON_PRODUCTION].', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_QUALITY_QUARRY_ALERT_3', '[ICON_TEAM_3] Una cantera cerca de {2} descubrió un [ICON_GOLD] vena roca rentable.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER', 'Madera exótica', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_DESC', 'Árboles exóticos fueron descubiertos cerca del aserradero fuera {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_1', 'Crear un parque nacional para mejorar el turismo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_2', 'Construir una nueva infraestructura para las exportaciones de madera.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_OUTCOME_3', 'Deje que el negocio de la madera manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_1', '[ICON_TEAM_3] Un parque nacional exótica mejoró el turismo [ICON_CULTURE] Cultura cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_2', '[ICON_TEAM_3] Extensa [ICON_PRODUCTION] la infraestructura de producción cerca de {2} exporta árboles valiosos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_EXOTIC_LUMBER_ALERT_3', '[] ICON_TEAM_3 árboles exóticos descubiertos cerca {2} mejoradas de madera [ICON_PRODUCTION] Utilidades.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING', 'Pasto Esgrima', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_DESC', 'Los agricultores cerca de {2} quieren construir cercas para impedir la entrada de ganado, pero los ganaderos están preocupados por la pérdida de tierras de pastoreo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_1', 'Apoyar los esfuerzos de los agricultores para cercar la tierra.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_2', 'Apoyar los esfuerzos de los ganaderos para mantener un campo abierto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_OUTCOME_3', 'Deje que los ciudadanos locales manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_1', '[ICON_TEAM_3] Cercar un pasto cerca {2} mejorado [ICON_FOOD] Alimentación de tierras de cultivo circundantes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_2', '[ICON_TEAM_3] Ganaderos cerca {2} incrementado [ICON_PRODUCTION] La producción de un campo abierto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PASTURE_FENCING_ALERT_3', '[ICON_TEAM_3] Un compromiso entre los ganaderos y los agricultores cercanos {2} mejoró la [ICON_PRODUCTION] Economía local.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND', 'Demanda Pesca', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_DESC', 'La demanda va en aumento para la vida marina que se encuentra en los mares cercanos a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_1', 'Construir un acuario de la ciudad para los ciudadanos de ver las criaturas marinas exóticas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_2', 'Construir infraestructura para expandir la industria pesquera local.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_OUTCOME_3', 'Deje que las pesquerías locales manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_1', '[ICON_TEAM_3] Un acuario de vida marina rara aumentó cultura en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_2', '[ICON_TEAM_3] Pescadores cerca de {2} de salida ampliado [ICON_FOOD] Alimentación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FISHING_DEMAND_ALERT_3', '[ICON_TEAM_3] la vida marina cerca de Rare {2} mejorado [ICON_GOLD] Oro de la pesca.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION', 'Bueno Expansión', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_DESC', 'Un negocio petrolero desea ampliar cerca de {2}, pero la industria del turismo está preocupado por el impacto en el paisaje.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_1', 'Apoyar el turismo de negocios con un nuevo monumento nacional.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_2', 'Apoyar el desarrollo de petróleo con nuevas carreteras y la infraestructura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_OUTCOME_3', 'Deje que las empresas manejan esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_1', '[ICON_TEAM_3] Un monumento a la tierra hermosa cerca {2} mejorado el turismo [ICON_CULTURE] Cultura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_2', '[ICON_TEAM_3] infraestructura ampliada aceite nuevo [ICON_PRODUCTION] Producción cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WELL_EXPANSION_ALERT_3', '[ICON_TEAM_3] Petróleo [ICON_GOLD] Los beneficios se incrementaron cerca de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING', 'Desmantelamiento Plataforma', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_DESC', 'Varios plataformas costa afuera en el campo de petróleo cerca de {2} agotaron su suministro de petróleo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_1', 'Apoyo a la pesca comercial mediante la conversión de los equipos en los arrecifes artificiales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_2', 'Desmontar y reutilizar los componentes de las plataformas en el campo de petróleo en otras partes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_OUTCOME_3', 'Deje que el negocio de manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_1', '[ICON_TEAM_3] Las plataformas petroleras convierten en arrecifes artificiales mejoradas de pesca [ICON_FOOD] Alimentación cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_2', '[ICON_TEAM_3] Reutilización de componentes de la plataforma petrolera agotados mejoraron [ICON_PRODUCTION] Producción cerca {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_PLATFORM_DECOMMISSIONING_ALERT_3', '[ICON_TEAM_3] La venta de las plataformas petroleras fuera de servicio planteadas [ICON_GOLD] Oro cerca de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION', 'Fort Expansión', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_DESC', 'El general a cargo de la fortaleza cerca de {2} desea iniciar esfuerzos de nueva construcción.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_1', 'La investigación de nuevas tecnologías militares en el fuerte.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_2', 'Mejora la capacidad defensiva de la fortaleza en una ciudadela.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_OUTCOME_3', 'Deje que el general de manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_1', '[ICON_GOLD] Oro: 6', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_TIP_2', 'La fortaleza se convierte en una ciudadela.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_1', '[ICON_TEAM_3] Una fortaleza cerca de {2} expandido personal y las instalaciones de investigación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_2', '[ICON_TEAM_3] Una fortaleza cerca {2} se expandió a una ciudadela.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_FORT_EXPANSION_ALERT_3', '[ICON_TEAM_3] Un fabricante de cerca de una fortaleza fuera {2} comercializa nuevas tecnologías de armas.', '', '');
/*  EDIFICIOS  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM', 'Granero Boom Población', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_DESC', 'Mejoras en el granero en {2} están atrayendo a los ciudadanos a la ciudad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_1', 'Proporcionar fondos para los ciudadanos a encontrar un nuevo lugar para vivir.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_2', 'Alquiler de ciudadanos para un programa de obras públicas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_1', '[ICON_TEAM_2] Colono: 1', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_TIP_2', '[ICON_TEAM_2] Trabajadores: 2', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_1', '[ICON_TEAM_3] El Gobierno de {2} financió un nuevo programa de liquidación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_2', '[ICON_TEAM_3] El Gobierno de {2} financió un nuevo programa de obras públicas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_GRANARY_POPULATION_BOOM_ALERT_3', '[ICON_TEAM_3] Población está en auge en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT', 'Desarrollo Smithy', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_DESC', 'Un nuevo proceso de fundición desarrollada por la herrería en {2} es potencialmente peligroso para los trabajadores.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_1', 'Financiar la investigación para hacer el proceso más seguro.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_2', 'Enviar recursos a poner inmediatamente el proceso de la producción.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_1', '[ICON_TEAM_3] Extensa [ICON_RESEARCH] La investigación está en marcha para crear un proceso de fundición más seguro en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_2', '[ICON_TEAM_3] Un nuevo proceso de fundición se puso rápidamente en [ICON_PRODUCTION] La producción de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SMITHY_DEVELOPMENT_ALERT_3', '[ICON_TEAM_3] Un nuevo proceso de fusión mejorada [ICON_GOLD] Profits in {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY', 'Mercado Monopolio', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_DESC', 'Un negocio que proporciona grandes donaciones a las escuelas locales se está formando un monopolio en el mercado en {2}, haciendo subir los precios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_1', 'Romper el monopolio de bajar los precios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_2', 'Apoyar las donaciones educativas con incentivos de tesorería.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_OUTCOME_3', 'Recaudar impuestos sobre las ganancias más altas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_1', '[ICON_TEAM_3] son ​​ciudadanos de {2} [ICON_HAPPINESS_1] Feliz como los precios bajan.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_2', '[ICON_TEAM_3] Un nuevo monopolio en {2} dona gran medida a [ICON_RESEARCH] Educación.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MARKET_MONOPOLY_ALERT_3', '[ICON_TEAM_3] Un monopolio de {2} ''s de mercado aumentó [ICON_GOLD] ganancias del oro.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY', 'Controversia Biblioteca', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_DESC', 'Un polémico libro sobre el racismo en la historia de {2} está provocando disturbios.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_1', 'Financiar la investigación más profunda en el turbulento pasado de la ciudad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_2', 'Prohibir el libro hasta que los disturbios se desvanecen.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_OUTCOME_3', 'Esto debería aumentar la venta de libros.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] Un polémico libro comienza más [ICON_RESEARCH] La investigación sobre la historia de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] Disturbios en {2} se desvanecen como un libro que causa [ICON_HAPPINESS_4] La ira fue prohibida.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LIBRARY_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] Un polémico libro es [ICON_GOLD] Vendiendo bien en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY', 'Controversia Monumento', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_DESC', 'Los ciudadanos de {2} están protestando por un monumento a la expansión imperialista.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_1', 'Dar discursos que promueven una cultura pacífica.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_2', 'Distribuir propaganda apoyando la expansión militarista.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_1', '[ICON_TEAM_3] pacíficas [ICON_CULTURE] manifestaciones culturales barren {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_2', '[ICON_TEAM_3] La propaganda en {2} reducida [ICON_HAPPINESS_4] Anger sobre el imperialismo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_MONUMENT_CONTROVERSY_ALERT_3', '[ICON_TEAM_3] Un monumento controvertido está mejorando el turismo [ICON_GOLD] economía en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS', 'Walled Slums', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_DESC', 'Desarrollo de {2} expandido más allá de la antigua muralla de la ciudad, con los distritos interiores deterioro de los barrios marginales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_1', 'Revitalizar la ciudad vieja con los programas culturales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_2', 'Derribar los barrios pobres para hacer espacio para las empresas productivas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_1', '[ICON_TEAM_3] El centro de la ciudad de {2} revitalizó su [ICON_CULTURE] Cultura.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_2', '[ICON_TEAM_3] Tugurios derribadas en {2} habitación despejado para [] ICON_PRODUCTION empresas productivas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_WALLED_SLUMS_ALERT_3', '[ICON_TEAM_3] Los nuevos negocios aumentaron [ICON_GOLD] los ingresos del oro en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT', 'Cuartel Reclutamiento', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_DESC', 'Los ciudadanos de {2} están molestos por el reclutamiento militar forzoso.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_1', 'Las menores tasas de reclutamiento en la ciudad.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_2', 'Invertir en propaganda a nivel nacional para aumentar el alistamiento militar.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_TIP_2', '[ICON_WAR] Nuevas Unidades Militares: 2', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_1', '[ICON_TEAM_3] La reducción de las tasas de reclutamiento bajaron [ICON_HAPPINESS_4] Anger en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_2', '[ICON_TEAM_3] cuarteles A en {2} alistaron nuevos efectivos militares.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARRACKS_RECRUITMENT_ALERT_3', '[ICON_TEAM_3] propaganda de bonos Guerra mejoró [ICON_GOLD] Los ingresos en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE', 'Asistencia Coliseo', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_DESC', 'El Coliseo en {2} está atrayendo multitudes récord.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_1', 'Mostrar competiciones elaborados para entretener al público.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_2', 'Anfitrión demostraciones masivas de propaganda patriótica.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_OUTCOME_3', 'Deje que el alcalde manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_1', '[ICON_TEAM_3] competiciones atraen [ICON_HAPPINESS_1] multitudes felices en el {2} Coliseo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_2', '[ICON_TEAM_3] El Coliseo de {2} se celebran espectáculos masivos de [ICON_CULTURE] propaganda cultural.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_COLOSSEUM_ATTENDANCE_ALERT_3', '[ICON_TEAM_3] Mejoras en el {2} Coliseo plantearon [ICON_GOLD] los ingresos del oro.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED', 'Raza Estable', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_DESC', 'Los establos en {2} plantearon una raza inusualmente ágil, fuerte y confiada de los caballos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_1', 'Entrenarlos para las carreras de caballos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_2', 'Entrenarlos como caballos de guerra.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_OUTCOME_3', 'Deje que los propietarios decidan estables.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_TIP_2', '[ICON_WAR] Nuevas Unidades de caballos: 2', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_1', '[ICON_TEAM_3] Una nueva raza de caballo de carrera mejoró [ICON_HAPPINESS_1] La felicidad en {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_2', '[ICON_TEAM_3] El ejército de {2} planteó una nueva raza de caballos de guerra.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_STABLE_BREED_ALERT_3', '[ICON_TEAM_3] Una nueva raza de caballos mejoró [ICON_GOLD] Los ingresos en {2}.', '', '');
/*  CITYSTATES  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION', 'Ciudad-Estado de Inmigración', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_DESC', 'Algunos trabajadores se sienten los inmigrantes recientes de la ciudad-estado de {2} están tomando empleos a los ciudadanos de su civilización.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_1', 'Pagar por programas para dar a los inmigrantes un camino a la ciudadanía.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_2', 'Deportar a los inmigrantes y confiscar sus hogares.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_OUTCOME_3', 'Denuncian los estereotipos étnicos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_1', '[ICON_INFLUENCE] Influencia: 70', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_2', '[ICON_INFLUENCE] Influencia: -70 [NEWLINE] [ICON_GOLD] Oro: 200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_TIP_3', '[ICON_INFLUENCE] Influencia: 10', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_1', '[ICON_TEAM_3] Los inmigrantes de {2} ganan un camino a la ciudadanía en el imperio de {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_2', '[ICON_TEAM_3] El Gobierno de {1} deportado inmigrantes de {2_target).', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CITYSTATE_IMMIGRATION_ALERT_3', '[ICON_TEAM_3] El Gobierno de {1} denunció los estereotipos acerca de los ciudadanos de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE', 'Cambio de divisas', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_DESC', 'El valor de su moneda va en aumento, y el desequilibrio comercial resultante arriesga dañando las exportaciones a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_1', 'Establecer un tipo de cambio fijo para permitir que las exportaciones continúen sin trabas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_2', 'Promulgar leyes para fortalecer su moneda aún más, a expensas de la Citystate.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_OUTCOME_3', 'Deje que su Ministro de Hacienda manejar este asunto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_1', '[ICON_INFLUENCE] Influencia: 70', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_2', '[ICON_INFLUENCE] Influencia: -70 [NEWLINE] [ICON_GOLD] Oro: 200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_TIP_3', '[ICON_INFLUENCE] Influencia: 10', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_1', '[ICON_TEAM_3] Un tipo de cambio fijo mejoró las exportaciones de {1} a {2}, aumentando [ICON_INFLUENCE] relaciones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_2', '[ICON_TEAM_3] La moneda de {1} aumentó dramáticamente en valor, proporcionando [ICON_GOLD] Oro a expensas de {2} ''s economía.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_CURRENCY_EXCHANGE_ALERT_3', '[ICON_TEAM_3] Modificaciones a {1} ''s de tasa de cambio de divisas mejoradas exportaciones a {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT', 'Diplomática de Incidentes', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_DESC', 'Durante una visita a {2} que cometió un grave paso en falso durante un evento diplomático, debido a un malentendido cultural.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_1', 'Enviar regalos y hacer una disculpa oficial por el error, prometiendo no volver a dejar que suceda de nuevo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_2', 'Explique las acciones son aceptables en su sociedad, y no te disculpas por las raíces de su civilización.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_OUTCOME_3', 'Deje que sus diplomáticos manejan este asunto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_1', '[ICON_INFLUENCE] Influencia: 70 [NEWLINE] [ICON_CULTURE] Cultura: -200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_2', '[ICON_INFLUENCE] Influencia: -70 [NEWLINE] [ICON_CULTURE] Cultura: 200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_TIP_3', '[ICON_INFLUENCE] Influencia: 10', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_1', '[ICON_TEAM_3] Una disculpa después de un incidente diplomático mejoró [ICON_INFLUENCE] relaciones entre {1} y {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_2', '[ICON_TEAM_3] La negativa a disculparse por las peculiaridades de {1} ''s [ICON_CULTURE] cultura dio lugar a un incidente diplomático con {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_DIPLOMATIC_INCIDENT_ALERT_3', '[ICON_TEAM_3] Un incidente diplomático de {1} en una visita a {2} ayudó a incrementar la comprensión cultural entre las dos naciones.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME', 'Fama Scholastic', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_DESC', 'Las solicitudes para estudiar en escuelas estimados en su imperio se han disparado de estudiantes extranjeros de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_1', 'Relájese restricciones a la inmigración para los estudiantes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_2', 'Restringir la inscripción a los estudiantes nacionales.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_OUTCOME_3', 'Permitir a los decanos de la escuela para manejar esto.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_1', '[ICON_INFLUENCE] Influencia: 70 [NEWLINE] [ICON_RESEARCH] Ciencia: -200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_2', '[ICON_INFLUENCE] Influencia: Ciencia -70 [NEWLINE] [ICON_RESEARCH]: 200', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_TIP_3', '[ICON_INFLUENCE] Influencia: 10', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_1', '[ICON_TEAM_3] La calidad de la educación ofrecida a los estudiantes extranjeros de {2} mejoradas [ICON_INFLUENCE] relaciones con {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_2', '[ICON_TEAM_3] nuevos [ICON_RESEARCH] las leyes de educación a favor de los estudiantes nacionales de {1} sobre los inmigrantes de {2}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCHOLASTIC_FAME_ALERT_3', '[ICON_TEAM_3] Los estudiantes extranjeros procedentes {2} están acudiendo a las escuelas de {1}.', '', '');
/*  UNIDADES  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR', 'Scouts Salvador', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_DESC', 'Tu explorador rescató al niño de un jefe nómada de una bestia mortal. Los cazadores agradecidos le ofrecen hospitalidad en su campamento.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_1', 'Pida a algunos nómadas a unirse a su exploración.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_2', 'Capacitar para moverse rápidamente con arcos de caza.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_OUTCOME_3', 'Descanse en el campo por un tiempo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_1', 'Duplicados y cura el escucha.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_2', 'Sustituye a un arquero que se mueve rápidamente.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_TIP_3', 'Los Scouts se cura y ganancias 5 [ICON_WAR] Experiencia.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_1', '[ICON_TEAM_3] A {2} {1} unido a una tribu de nómadas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_2', '[ICON_TEAM_3] A {2} de {1} aprendido a usar arcos de caza.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_SAVIOR_ALERT_3', '[ICON_TEAM_3] A {2} de {1} descansado después de salvar a un niño nómada.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES', 'Scout Stories', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_DESC', 'Tu explorador viajó a lo largo y ancho, desafiando numerosos peligros y descubrir muchas tierras maravillosas. Los ciudadanos de su capital social están dispuestos a escuchar las historias.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_1', 'Contratar a un escritor para elaborar poemas épicos de sus viajes.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_2', 'Proporcionar el explorador con la nueva formación y nuevas armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_OUTCOME_3', 'Permitir que el explorador para contar sus historias, y luego seguir adelante.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_1', '[ICON_CULTURE] Cultura: 100', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_2', 'Cura y actualizaciones a un Centinela.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_TIP_3', '[ICON_CULTURE] Cultura: 30', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_1', '[ICON_TEAM_3] poemas épicos de los viajes de un explorador aumentó el [ICON_CULTURE] Cultura de {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_2', '[ICON_TEAM_3] Un explorador de {1} actualizarse a nuevas armaduras y armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_SCOUT_STORIES_ALERT_3', '[ICON_TEAM_3] Las historias de los viajes de un explorador aumentó el [ICON_CULTURE] Cultura de {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR', 'Warrior Reconocido', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_DESC', 'Sus guerreros están ganando popularidad en su imperio, con cuentos cantados de su valentía.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_1', 'Conviértanse ellos a la vida civil.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_2', 'Envíalas nuevas armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_OUTCOME_3', 'Envíalas suministros frescos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_1', 'Se convierte en un trabajador que no tiene en cuenta los costes del terreno.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_2', 'Convierte a un espadachín.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_TIP_3', 'Cura y ganancias 5 [ICON_WAR] Experiencia.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_1', '[ICON_TEAM_3] Guerreros de {1} regresaron a la vida civil.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_2', '[ICON_TEAM_3] Guerreros de {1} recibieron nuevas armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_WARRIOR_ALERT_3', '[ICON_TEAM_3] Guerreros de {1} recibieron suministros frescos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER', 'Reconocido Archer', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_DESC', 'Sus arqueros están ganando popularidad en su imperio, con historias que se cuentan de su puntería.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_1', 'Deja que se retiran a la vida civil.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_2', 'Envíalas nuevas armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_OUTCOME_3', 'Envíalas suministros frescos.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_1', 'Se convierte en un trabajador que no tiene en cuenta los costes del terreno.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_2', 'Se convierte en un compuesto Bowman.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_TIP_3', 'Cura y ganancias 5 [ICON_WAR] Experiencia.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_1', '[ICON_TEAM_3] Archers of {1} se retiró a la vida civil.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_2', '[ICON_TEAM_3] Archers of {1} recibieron nuevas armas.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_RENOWNED_ARCHER_ALERT_3', '[ICON_TEAM_3] Archers of {1} recibieron suministros frescos.', '', '');
/*  CUSTOM  */
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB', 'Land Grab', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_DESC', 'Los ciudadanos de {2} demandan una mejor tierra para trabajar.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_1', 'Pagar para anexar más tierras al imperio.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_2', 'Recluta a los disidentes y los puso a trabajar.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_OUTCOME_3', 'Deje que el alcalde manejar este', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_1', '[ICON_TEAM_6] Nuevos Azulejos: 3', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_2', '[ICON_TEAM_2] Nuevo Trabajador: 1', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_TIP_3', '[ICON_TEAM_6] Nuevos Azulejos: 1', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_1', '[ICON_TEAM_3] Los ciudadanos de {2} se anexó un territorio nuevo y grande.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_2', '[ICON_TEAM_3] Disidentes en {2} fueron reclutados a la fuerza de trabajo.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_LAND_GRAB_ALERT_3', '[ICON_TEAM_3] Los ciudadanos de {2} funcionan tierra anexionada recientemente.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES', 'Bárbaros mercenarios', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_DESC', 'Un grupo de invasores hostiles en sus fronteras podría cambiar de lado - por un precio.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_1', 'Contratarlos para su fuerza laboral civil.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_2', 'Contratarlos mercenarios como militares.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_OUTCOME_3', 'Emboscada a los traidores y saquear sus suministros.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_1', '[ICON_TEAM_2] Nuevos Trabajadores: 1', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_2', '[ICON_TEAM_2] Nuevas Unidades Militares: 2', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_TIP_3', '[ICON_GOLD] Oro: 25', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_1', '[ICON_TEAM_3] Barbarians se unieron a la fuerza laboral civil de {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_2', '[ICON_TEAM_3] mercenarios bárbaros se unieron al ejército de {1}.', '', '');
REPLACE INTO Language_ES_ES (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRIGGER_BARBARIAN_MERCENARIES_ALERT_3', '[ICON_TEAM_3] mercenarios bárbaros fueron emboscados por {1}.', '', '');







UPDATE LoadedFile SET Value=1, ES_ES=1 Where Type='Stories.sql';


