/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Tratti  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Si ottiene una spia supplementare. Grandi Generali vedere più lontano e dare più forza. [NEWLINE] Inizia con un Guerriero e Grande Generale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Assegnazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Il tuo plusvalenze un forte copia gratuita di ogni nuova linea di unità si ricerca.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Le unità si muovono più velocemente lungo i fiumi, e iniziare con la promozione anfibio.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' +10% [ICON_GREAT_PEOPLE] Great tasso di persone di ogni Alliance, e il 20% [ICON_STRENGTH] Combattimento vs civiltà con altre città.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Le unità da mischia e all''avanguardia costano il 50% in meno manutenzione. Tutte le unità richiedono il 25% in meno esperienza per guadagnare la loro prossima promozione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Produzione verso gli edifici che già esistono nel [ICON_CAPITAL] Capital. Inizia con [ICON_RES_IRON] ferro nelle prime 5 città.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', 'Superiori del 25% ricompense da amici e alleati City-Stati.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Ellenizzazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' 2 [ICON_CULTURE] Cultura in ogni città. Città-Stato [ICON_INFLUENCE] Influenza degrada a metà e recupera al doppio della velocità normale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Rotte commerciali interni forniscono 10 [ICON_GOLD] oro per la destinazione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Gli utili [ICON_CULTURE] Cultura di uccidere le unità nemiche.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' +50% [ICON_CULTURE] Cultura e +1 [ICON_MOVES] movimento durante [ICON_GOLDEN_AGE] Età dell''Oro. [NEWLINE] Inizia con un Spearman unico.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' +1 [ICON_PEACE] La fede da foreste non migliorate e Jungle, e 150% i raccolti di meraviglie naturali. [NEWLINE] inizia con un Spearman.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Unità danneggiati combattono a piena forza. Pescherecci e Isles danno [ICON_CULTURE] Cultura.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Gao Militia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Unità Vanguard vedere più lontano e si muovono più velocemente.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Le unità si muovono più velocemente sul Hills. Strade e ferrovie costano nessuna manutenzione sulle colline, a metà costa altrove.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'I civili si muovono più velocemente nel deserto. I tuoi rotte commerciali in uscita con civiltà diverse guadagnano più oro [ICON_GOLD] e [ICON_CULTURE] Cultura e rotte commerciali in arrivo guadagnano di più [ICON_GOLD] per il proprietario del percorso.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Più veloce movimento Foreste e Jungle, che contano come strade in territorio amico dopo la ricerca La Ruota. [NEWLINE] inizia con un Spadaccino unico.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Grandi scienziati appaiono 25% più veloce, e si riceve uno alla scrittura. [NEWLINE] Inizia con una Bowman.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert Caravans', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Le unità si muovono più velocemente nel deserto, carovane raggiungono più lontano, e rotte commerciali diffondono la religione più velocemente da vostre città.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'Dopo la ricerca Teologia, ricevono un bonus grande persona alla fine di ogni ciclo del calendario Maya Lungo Count (ogni 394 anni). [NEWLINE] Inizia con un Archer unico.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Ogni aumento di risorse di lusso [ICON_GOLD] reddito oro del 5%.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' +20% [ICON_PRODUCTION] Produzione verso la costruzione Wonder.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' +30 [ICON_WAR] Experience per le navi.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Scegliere una più Belief del normale quando hai trovato una religione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Porti ottenere un porto libero, e le unità possono attraversare le montagne. Inizia con Vela, un Bireme, e un Guerriero.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Economia pianificata', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Unità di vedere più lontano, i civili si muovono più velocemente, e si guadagna di meno 1 [ICON_HAPPINESS_4] Nazionale infelicità per città.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Edifici alimentari aggiungi 1 [ICON_CITIZEN] Popolazione quando costruito. [NEWLINE] Inizia con un lavoratore.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Campi barbari si arrendono quando sconfisse per il doppio [ICON_GOLD] oro. [NEWLINE] Inizia con un cavallo Archer.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'American Dream', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Gli immigrati si spostano qui da civiltà a bassa felicità e grande influenza culturale americana. I vostri cittadini migrano lungo [ICON_FOOD] rotte commerciali alimentare interne.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Dinastia Joseon', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' 2 [ICON_RESEARCH] Scienza da Farms. [NEWLINE] Inizia con un lavoratore.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Rese doppie da meraviglie naturali, oltre 100 [ICON_GOLD] quando ha scoperto. [NEWLINE] Inizia con uno scout, e riceve un Caravel a Compass.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Lega Anseatica', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Quantità doppia di Risorse Strategiche, e 3 voti supplementari al Congresso Mondiale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Imbarco veloce e più forte attraverso l''acqua, e mischia le unità saccheggiare più velocemente.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terror', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'City-stati si può bullo arrendersi nella paura come burattini. Montato e le unità di schermaglia si muovono più velocemente. Inizia con uno Scout.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Omaggio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Rotte commerciali interne tra le vostre città offrono 10 [ICON_GOLD] oro per la destinazione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Reconquista', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Conquistare città aumenta il [ICON_PEACE] Fede.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Flagello di Dio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Campi barbari si arrendono quando sconfitti, e le unità di terra costano meno manutenzione [ICON_GOLD]. [NEWLINE] Inizia con un cavallo Archer.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Flagello di Dio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Campi barbari si arrendono quando sconfitti, e le unità di terra costano meno manutenzione [ICON_GOLD]. [NEWLINE] Inizia con un carro unico.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' +5% [ICON_GOLD] reddito nazionale da ogni tipo di risorsa di lusso che controlli o di importazione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] Un cittadino migrato da {1} a {2}.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] Un immigrato dal {1} ​​arrivato a {2}.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] Un cittadino emigrato da {1} a {2}.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Avete guadagnato {1} {2} {3} da catturare {4}!', '', '');


/*  Unità  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Truppe imperiali-Royal Mountain', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Unità Epoca Moderna che solo gli austriaci possono costruire. E ''più potente e ha aggiunto promozioni che l''unità regolare non fa.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Questa unità dispone di potenti vantaggi in tutti i terreni freddo. Combattere in Tundra, Neve, colline e persino montagne.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'Le truppe imperiali-Royal Mountain (tedesco: Kaiserlich-königlich Gebirgstruppe). Furono fondate nel 1906 come parte della Landwehr austriaca, l''esercito territoriale della metà Cisleithanian dell''Impero austro-ungarico [NEWLINE] Proposto in un memorandum da Conrad von Hötzendorf , nel febbraio 1906 il Ministero della Guerra di Vienna ha convocato una sessione sulla sicurezza dei confini alpini. Maresciallo Tunk, d''accordo con lui e ha presentato una concept, i fondamenti delle quali sono state poi effettuate. [NEWLINE] I reggimenti fucile di Stato esistenti dovevano essere addestrati come truppe di montagna e, insieme con le società di pattugliamento delle frontiere Landsturm e reparti di gendarmeria erano a formare la spina dorsale di una forza di difesa territoriale con la conoscenza locale sul confine del Tirolo [NEWLINE] [NEWLINE] Battaglioni e le società hanno avuto animali da soma e sono stati emessi con attrezzature supplementari adattati alle esigenze della guerra di montagna,. tra cui sci, corde, ramponi e piccozze. Reggimenti sono stati rafforzati da una sezione mitragliatrice montagna di quattro mitragliatrici che, per migliorare la mobilità, potrebbero essere trasportati da animali da soma o in confezioni manportable alle quote più elevate. Lo stesso vale per i cannoni da montagna take-apart. Stufe da campo portatili (Schwarmöfen) e tende riscaldate assistiti truppe di operare in condizioni inospitali. [NEWLINE] Quando lo sci l''approccio a due bastone aveva sostituito il metodo single-bastone. Il Bilgeri associazione era un legame che potrebbe essere utilizzato con il normale avvio escursioni touring. Il fucile è stato sostituito dal (breve) 8 millimetri Mannlicher M 95 carabina.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Songhai unico montato unità. Mandekalu Cavalleria inizia con la promozione Siege, a differenza del Cavaliere che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Potente soldato medievale unica per i giapponesi. Samurai può attaccare due volte per turno, e sono più forte del Longswordsmen che sostituiscono.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unità arciere babilonese unico. Il Bowman è più forte del Archer che sostituisce, e si muovono più velocemente nei deserti.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldato del periodo medievale unica di Danimarca. Il Berserker inizia con la promozione di carica, a differenza del Longswordsman che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Unità mobile unico nel suo genere in Germania. Il Panzer ha una maggiore forza, velocità, e la visibilità del carro armato che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Early-gioco soldato unica per gli Aztechi. La Jaguar guarisce danni quando si uccide un nemico, e combatte più efficacemente a Jungle rispetto al Guerriero che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard Unità unica per gli americani. E ''più forte del Skirmisher che sostituisce, vede più lontano, e si muove più velocemente in terreni accidentati.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'Una delle prime unità di polvere da sparo del gioco, uniche per i francesi. Moschettieri hanno un bonus di combattimento al di fuori del territorio amico, a differenza del Soldato con moschetto che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldato unico per gli Irochesi. Il Mohawk guerriero combatte più forte nella foresta e Jungle rispetto alla Spadaccino che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldato unica per gli ottomani. Il giannizzero è molto più forte in attacco e guarisce dopo uccide, a differenza del Soldato con moschetto che sostituisce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Unità entro 1 tessera [COLOR_POSITIVE_TEXT] Heal 4 Ulteriori HP [ENDCOLOR] per turno.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'L''unica sostituzione mongolo per il Cavaliere si muove più velocemente, è variato, e non condivide le vulnerabilità del Cavaliere a Città o Picchieri. Il Keshik guadagna anche l''esperienza più rapidamente.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Potente soldato romano di epoca classica con un bonus contro le città. La Legione ha una forza superiore alla Spadaccino che sostituisce, la difesa supplementare contro attacchi a distanza, e può costruire strade al doppio della velocità dei lavoratori.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'Un Liburna era un tipo di piccola cambusa utilizzato per le razzie e le pattuglie, in particolare da parte della marina romana. [NEWLINE] [NEWLINE] Nella sua forma originaria, il Liburna aveva una panca con 25 remi per lato, mentre nella tarda Repubblica romana, è stato dotato di due banchi di remi (un bireme), rimanendo più veloce, più leggero e più agile di triremi. Il progetto Liburni è stato adottato dai Romani e divenne un elemento chiave della marina di Roma antica dal 2 ° metà del 1 ° secolo aC. Liburni giocato un ruolo chiave nella battaglia di Azio in Grecia, che ha visto l''istituzione di Augusto come il sovrano indiscusso del mondo romano. [NEWLINE] Liburni erano diverse dalle triremi di battaglia, quadriremi e non quinqueremi a causa di canottaggio, ma piuttosto a causa di le sue specifiche caratteristiche costruttive. [NEWLINE] [NEWLINE] Una volta che i Romani avevano adottato dei Liburni, hanno proceduto a fare un paio di adattamenti per migliorare l''utilizzo delle navi all''interno della marina. I benefici ottenuti dalla somma dei montoni e la protezione da missili più che compensato-up per la leggera perdita di velocità. Oltre alla costruzione, le navi richiesto che l''unità militare romana regolare essere semplificato per un funzionamento più fluido. Ogni nave ha operato come entità individuale, così l''organizzazione più complicato normalmente utilizzato non era necessario. All''interno della marina, c''erano probabilmente liburnica di diverse dimensioni diverse, tutti messi a compiti specifici come scouting e pattugliamento nelle acque romane contro la pirateria. I Romani fecero uso dei Liburni particolare nelle province dell''impero, dove le navi hanno formato la maggior parte delle flotte. [NEWLINE] Liburni A poco a poco è diventato un nome generico per i diversi tipi di navi romane, collegata anche alle navi da carico in tarda Antichità. Tacito e Svetonio usavano come un sinonimo per la nave di battaglia. In iscrizioni è stato menzionato come l''ultimo della classe delle navi da battaglia: hexeres, penteres, quadrieres, trieres, Liburna.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'La Liburna è la prima unità navale di Roma. Si tratta di una unità di corpo a corpo senza forza di combattimento a distanza. La Liburna è utile per sgombrare le navi barbariche su acque di casa e per l''esplorazione limitata.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Roma usato queste navi per il controllo delle acque e proteggere le loro rotte commerciali.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Potente unità mobile unico nel suo genere in India. A differenza del Cavaliere che sostituisce, l''elefante da guerra è variato, non richiede cavalli, e non ha alcuna vulnerabilità di Lancieri.', '', '');
/*  Varie  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Ufficio Commercio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Ottoman Tribute', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura per adiacente Moai. [NEWLINE] [ICON_LOCKED] Deve essere accanto a Costa.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura per adiacente Moai. [NEWLINE] [ICON_LOCKED] Deve essere accanto a Costa.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Cultura. [NEWLINE] 1 [ICON_CULTURE] Cultura per adiacente Moai. [NEWLINE] [ICON_LOCKED] Deve essere accanto a Costa.', '', '');
/*  Amsterdam Bourse  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'La Borsa di Amsterdam è considerato il più antico del mondo. E ''stata fondata nel 1602 dalla East India Company olandese per i rapporti nelle sue azioni e obbligazioni stampati. Successivamente è stato ribattezzato Amsterdam Borsa e fu il primo a cominciare formalmente negoziazione di valori mobiliari.', '', '');
/*  Jelling Stones  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Jelling Stones', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'Le pietre di Jelling sono enormi pietre runiche intagliate dal 10 ° secolo, che si trova nella città di Jelling in Danimarca. Il più vecchio dei due pietre di Jelling è stata sollevata dal re Gorm in memoria di sua moglie Thyra. La più grande delle due pietre è stata sollevata da Harald Bluetooth, figlio del re Gorm. Harald costruito la seconda pietra in memoria dei suoi genitori, la celebrazione della sua conquista della Danimarca e della Norvegia, e la sua conversione dei danesi al cristianesimo. Le iscrizioni runiche su queste pietre sono considerate il più noto in Danimarca.', '', '');
/*  Jade Sala  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Sala', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'Re Sejong supervisionato lo sviluppo del Chiphyonjon, Giada Sala studiosi, gli studiosi professionisti che hanno contribuito di ricerca questioni sociali e politiche per il re e il governo. Il Jade sala sarebbe considerato un "think tank" da parte dei governi di oggi.', '', '');
/*  Indus Sanitari  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus Sanitation', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'La civiltà di Harappa della valle del fiume Indo prima progettato noti sistemi sanitari urbane del mondo intorno al 2600 aC. Case singole o gruppi di case ottenuti acqua dai pozzi. Le acque reflue è stato diretto da camere riservate alla balneazione nelle fognature coperte che costeggiano le strade principali. Le possenti mura della città di Harappa sono stati speculato per proteggere dalle inondazioni. Questi sistemi di ingegneria idraulica Harappa erano ancora più efficienti di quelli di molte zone del Pakistan e dell''India di oggi, ottenendo grandi città urbane con relativamente poco lo sviluppo dell''agricoltura.', '', '');
/*  Pioneer  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pioniere', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Fonda nuove città per espandere il tuo impero. [NEWLINE] [NEWLINE] [ICON_FOOD] La crescita della città è fermo mentre l''unità è in costruzione. [NEWLINE]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'Il Pioneer è una Unità esclusiva americano. Si muove più velocemente di quanto il colono che sostituisce. [NEWLINE] [NEWLINE] Utilizzare questa unità per costruire nuove città. Non può difendersi, in modo da accompagnare con una unità di combattimento.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Pionieri americani sono nessuna delle persone nella storia degli Stati Uniti che migrarono a ovest dalla costa atlantica di stabilirsi e sviluppare nuove aree. Il termine si riferisce in particolare a coloro che andavano a stabilirsi un territorio nuovo per la società europea o americana, anche se il territorio può essere stato abitato da o utilizzati dai popoli indigeni. [NEWLINE] [NEWLINE] Il concetto pioniere ed ethos anteriori notevolmente la migrazione a parti degli Stati Uniti ora si chiama Stati "occidentali", come molti luoghi ormai considerati Oriente erano anche risolta da pionieri dalla costa. Ad esempio, Daniel Boone, una figura chiave nella storia dei pionieri americani, si stabilì a Kentucky, quando quella ''Dark e terra sanguinante'' era ancora poco sviluppata. [NEWLINE] [NEWLINE] Un importante sviluppo nella colonia occidentale era l''Homestead Act, che ha fornito legislazione formale che regolava il processo di risoluzione.', '', '');
/*  Mill Steam  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Mill Steam', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Una transizione è iniziata verso le fabbriche a macchina in economia della Gran Bretagna nel 1700, precedentemente prive di autonomia manuali del lavoro e gli animali da tiro. Questi precursori della rivoluzione industriale iniziato con la meccanizzazione delle industrie tessili. Espansione del commercio è stata attivata con l''introduzione di canali, strade migliori, e ferrovie. Utilizzo più ampio delle ruote idrauliche e l''introduzione della forza vapore spinto drammatici aumenti della capacità produttiva. Lo sviluppo delle macchine utensili completamente in metallo nei primi anni del 1800 ha facilitato la costruzione di macchine di produzione sempre più raffinate per la produzione in una vasta gamma di industrie.', '', '');
/*  Dojo  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Un dojo giapponese (''luogo di mezzo'') è un luogo di ritrovo per condurre la formazione, gli esami, e altri incontri relativi per il ''fare'' arte. Dojo erano inizialmente aggiunta ai templi. In Giappone ogni struttura di formazione fisica, comprese le scuole di wrestling professionale, può essere chiamato dojo a causa dei suoi stretti arti marziali radici.', '', '');
/*  Culto  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Shinto Shrine', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'In Giappone, santuari shintoisti esistono fianco a fianco con templi buddisti, e sono i più numerosi, famosi e importanti siti religiosi in Giappone. Un sacrario scintoista è una struttura o un oggetto il cui scopo principale è quello di ospitare uno o più Shinto kami (spiriti, forze naturali, o essenza). Kami può risiedere in quasi tutto naturale o provocata dall''uomo, dal Monte. Fuji ad un piccolo gioiello. Come tali, questi santuari sono comuni e una diversa portata. Il Santuario si può essere un grande edificio o oggetto di piccole dimensioni, lungo una strada, o potrebbe anche essere effettuata da persone. [NEWLINE] [NEWLINE] Come templi buddisti, santuari shintoisti non sono principalmente un luogo di culto. Più importanti edifici del santuario sono utilizzati per la custodia di oggetti sacri. Ci sono edifici specializzati per determinati riti, ma questi di solito sono aperti solo a un numero limitato di partecipanti. Raduni di massa religiose in stile delle chiese cristiane non avvengono con regolarità e non si svolgono all''interno del santuario. Se molte persone sono coinvolte in una cerimonia, che assumerà un carattere festoso e si terrà all''aperto.', '', '');
/*  Folkskola  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'Nel 1842, il parlamento svedese ha introdotto una scuola elementare di quattro anni per i bambini in Svezia, "Folkskola" (scuola del popolo). Questo è stato uno dei primi sistemi scolastici pubblici in tutto il mondo. [NEWLINE] [NEWLINE] bambini svedesi sono tenuti a frequentare grundskola, scuola dell''obbligo, dai 7 ai 16 anni, dove grundskola è una combinazione di scuola primaria e secondaria. Dopo grundskola, molti svedesi frequentano la gymnasieskolan elettiva, la scuola secondaria superiore, scegliendo un programma universitario, preparazione o di un programma professionale. Gli studenti che scelgono un programma professionale, normalmente terminano la loro formazione dopo gymnasieskolan mentre gli studenti che completano un programma universitario di preparazione al solito si iscrivono nel settore dell''istruzione superiore in un collegio universitario o università. Gli studenti che completano un programma professionale, possono iscriversi nel settore dell''istruzione superiore, ma potrebbe essere necessario seguire dei corsi supplementari prima di essere ammessi ad applicare.', '', '');
/*  Basilica  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Basilica', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'La basilica parola latina (derivato dal greco Stoa, la camera giurisdizionale di un re) è stato originariamente utilizzato per descrivere un edificio pubblico romano situato nel forum di una città romana. Per estensione, è stato applicato a edifici cristiani della stessa forma. [NEWLINE] [NEWLINE] Nel 4 ° secolo, una volta che le autorità imperiali avevano depenalizzato il cristianesimo con il 313 Editto di Milano, i cristiani erano pronti a costruire edifici più grandi e più bello per culto rispetto ai furtivi ritrovi erano state utilizzando. Formule architettoniche tradizionali per i templi erano inadatti a causa di associazioni con credenze non cristiane. Vecchi cerimonie del tempio sono verificati all''aperto sotto il cielo aperto al cospetto degli dei, con il tempio come sfondo. Il modello Costantino ha voluto commemorare per la sua pietà imperiale era l''architettura (in precedenza secolari) basiliche, in possesso di cerimonie al chiuso.', '', '');
/*  Cothon  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'A cothon (in greco: "nave potabile") è un porto interno protetto comune artificiale a Cartagine durante la guerre puniche C.200 aC [NEWLINE] Cothons sono generalmente presenti nel mondo fenicio.. Gli esempi includono Mozia (Sicilia) dal 6 ° secolo aC, che ha eseguito uno scopo incerto, (misura 35 metri x 51 metri), anche se è stato suggerito questo cothon potrebbe anche essere richiudibile e drenabile per formare un bacino di carenaggio. Mahdia (Tunisia) dal 7 ° secolo aC, (che misurava 72 metri x 56 metri) e uno da Kition di Cipro.', '', '');
/*  Dell'appalto Vedi  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi è il termine per "alterare" nella religione vedica, la religione più antica ancora praticata in tempi moderni. Tali altari sono un recinto elevata, generalmente cosparsa con erba Kusha, e con recipienti per il fuoco sacrificale.', '', '');
/*  NASA Center  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA Centro', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'La NASA Center è il centro di ricerca Epoca Moderna che concede aumenti di tecnologia. Fornisce inoltre una risorsa gratuita Spaceship Factory.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Fin dalla sua istituzione nel 1958, la NASA ha compiuto molte grandi imprese scientifiche e tecnologiche in aria e lo spazio. Tecnologia della NASA è stato anche adattato per molti usi nonaerospace dal settore privato. NASA rimane una forza trainante nella ricerca scientifica e nello stimolare l''interesse del pubblico per l''esplorazione aerospaziale, così come la scienza e la tecnologia in generale. Forse ancora più importante, la nostra esplorazione dello spazio ci ha insegnato a vedere la Terra, noi stessi e l''universo in modo nuovo. Mentre le conquiste tecniche e scientifiche tremendi della NASA dimostrano vividamente che gli esseri umani possono realizzare imprese precedentemente impensabili, anche noi siamo umiliati dalla consapevolezza che la Terra è solo un piccolo "marmo verde" nel cosmo.', '', '');
/*  Abbey  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Abbazia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'L''Abbazia ha al suo centro la pratica del culto, con l''idea di non arrivare a tutti di un servizio, ma di fornire opportunità di culto che Abbey gli aderenti possono partecipare con regolarità, se non settimanale. Attraverso i suoi servizi, fiorirono le arti come espressione di lode al ''Creator''. In aggiunta sono stati abbazie autoportante, impegnati in campi che coltivano, allevamento di bestiame, che operano mercati pubblici, e dando opportunità di lavoro per la comunità. Le abbazie celtiche divennero i centri di apprendimento, conservazione dei manoscritti sacri e letterari, e le scuole di istruzione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'L''Abbazia è il centro spirituale e culturale celtica di ogni comunità. Produce +1 [ICON_FOOD] Prodotti alimentari, [ICON_RESEARCH] Scienza, [ICON_CULTURE] Cultura, Oro [ICON_GOLD] e [ICON_PRODUCTION] Produzione.', '', '');
/*  Odeon  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon, dal greco antico ᾨδεῖον, Ōideion, letteralmente "cantare posto", o "costruzione per concorsi musicali". [NEWLINE] Il più magnifico Odeon era l''Odeon di Erode Attico sulla scogliera a sud ovest di l''Acropoli di Atene costruito in circa 160 dC dal sofista ricchi e retore Erode Attico in memoria di sua moglie. Aveva sistemazione per 8000 persone, e il soffitto è stato costruito da travi splendidamente scolpito di legno di cedro, probabilmente con uno spazio aperto nel centro di ammettere la luce. E ''stato anche abbondantemente decorata con foto e altre opere d''arte.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'L''Odeon è una fonte di instant [ICON_CULTURE] Cultura. Costruire questi aiuta a diffondere i confini del tuo impero.', '', '');
/*  Barbary Port  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbary Port', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'I pirati barbareschi, a volte chiamati corsari barbareschi o corsari ottomani, erano pirati e corsari che operavano dal Nord Africa, basata principalmente nei porti di Tunisi, Tripoli e Algeri. [NEWLINE] [NEWLINE] Questa zona era conosciuta in Europa come Barbary Coast , un termine che deriva dal nome dei suoi abitanti berberi. [NEWLINE] Oltre al sequestro delle navi, hanno impegnato in razzie, raid su città e villaggi costieri europei, principalmente in Italia, Francia, Spagna e Portogallo, ma anche in inglese Isles, i Paesi Bassi e lontani come l''Islanda. Lo scopo principale dei loro attacchi era quello di catturare schiavi cristiani per il mercato musulmano del Nord Africa e del Medio Oriente.', '', '');
/*  Bacino di irrigazione  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Bacino di irrigazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Gli antichi egizi praticavano bacino di irrigazione con l''inondazione del Nilo a inondare terreni che erano stati circondati da dighe. L''acqua delle inondazioni si è svolta fino al sedimento fertile era stabilito prima che il surplus è stato restituito al corso d''acqua. [NEWLINE] Non c''è testimonianza dell''antico faraone egiziano Amenemhet III nel XII dinastia (circa 1800 aC) con il lago naturale del Faiyum Oasis come un serbatoio per immagazzinare eccedenze di acqua per uso durante le stagioni secche, il lago si gonfiava ogni anno dalle inondazioni del Nilo.', '', '');





UPDATE LoadedFile SET Value=1, IT_IT=1 Where Type='Leaders.sql';




