/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Coscrizione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' +10 [COLOR_POSITIVE_TEXT] Heal Tariffa [ENDCOLOR].', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Esercito professionale', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Sblocca promozioni avanzate.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Mercantilismo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' 2 [ICON_MOVES] Movimento.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Libertà', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' +25% [ICON_STRENGTH] Forza in territorio amico.', '', '');
/*  Liberty  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura: +1 in tutte le città [NEWLINE] [ICON_PRODUCTION] Produzione: +1 in tutte le città [NEWLINE] [ICON_WORKER] Sblocca: Terracotta Army [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Grande Personaggio: +1 di scelta', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Colono: Produzione +1 [NEWLINE] [ICON_PRODUCTION]: +25% per i coloni', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Oro: 200 x Era [NEWLINE] [ICON_CULTURE] Nuove città aumentano i costi Privacy 33% in meno.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[ICON_TEAM_2] Addetti: +1 [NEWLINE] [ICON_WORKER] Operaio Miglioramento Vota: +25%', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 Felicità Nazionale per [ICON_CONNECTED] città collegate. [NEWLINE] [ICON_HAPPINESS_4] -5% infelicità da [ICON_CITIZEN] Popolazione in città che non sono [ICON_OCCUPIED] Occupati.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] Libero edificio della città Difesa in tutte le città (attuale, nuovo, e conquistarono). Con la tecnologia appropriata ricercato. [NEWLINE] [ICON_PRODUCTION] +1 Produzione per Città Difesa Building.', '', '');
/*  Tradizione  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura: tre in capitale [NEWLINE] [ICON_WORKER] Sblocca: Banaue Rice Terraces [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Grande Personaggio Rate:. +50% [NEWLINE] [ICON_CULTURE] Raddoppia espansione confine culturale piastrelle lontano dalle città [NEWLINE] [ICON_PEACE] possono acquistare Grandi Ingegneri con fede a partire nell''era industriale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Storytellers', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Cultura: +2 al Village e Palace', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'La tradizione orale è materiale culturale e la tradizione trasmessa oralmente da una generazione all''altra. I messaggi o le testimonianze vengono trasmessi verbalmente nel discorso o di una canzone e possono assumere la forma, ad esempio, di leggende popolari, detti, ballate, canzoni o canti. In questo modo, è possibile per una società di trasmettere storia verbale, letteratura verbale, legge verbale ed altre conoscenze attraverso le generazioni senza un sistema di scrittura.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Riti cerimoniali', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Cultura: +1 per la cultura di un edificio [NEWLINE] [ICON_CULTURE] 1 libera di un edificio culturale per le 4 città più antiche.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Una cerimonia è un evento di significato rituale eseguita in un''occasione speciale. Cerimonie possono avere un display fisico o componente teatrale: la danza, una processione, l''imposizione delle mani. Un pronunciamento verbale di accertamento può essere associato con l''occasione. [NEWLINE] [NEWLINE] Una cerimonia potrebbe segnare un rito di passaggio in una vita umana, segnando il significato di nascita, l''età adulta, l''iniziazione in un gruppo, o di morte. A volte una cerimonia può essere eseguito solo da una persona con una certa autorità. Cerimonie a livello di società possono contrassegnare gli eventi annuali o stagionali o ricorrenti, come l''equinozio di primavera, solstizio d''inverno e altre posizioni astronomiche annuali.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Surplus alimentare: +25% per città [NEWLINE] [ICON_FOOD] Cucina: due per città', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Città Attacco: +50% da guarnigioni [NEWLINE] [ICON_GOLD] Nessuna manutenzione per le unità presidiata.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Produzione: +15% per Wonders [NEWLINE] [ICON_HAPPINESS_1] Felicità: uno ogni 10 [ICON_CITIZEN] Cittadini', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] I cittadini della Capitale creano +0.5 [ICON_GOLD] Oro e +0,5 [ICON_HAPPINESS_1] Happiness.', '', '');
/*  Honor  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Abilità:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] rivela campi barbari [NEWLINE] [ICON_STRENGTH] +10% Forza contro i barbari [NEWLINE] [ICON_CULTURE] barbari Uccidere dà 2 Cultura per . forza dei nemici sconfitti [NEWLINE] [ICON_WORKER] Sblocca: Tempio di Artemide [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Città Felicità: +1 per Barracks', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] unità di difesa del capitale. [NEWLINE] +20% di produzione [ICON_PRODUCTION] per le unità militari e gli edifici.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Spoils of War', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Salvage oro dalle apparecchiature di nemici sconfitti. [NEWLINE] [ICON_CITY_STATE] +25% ricompense da catturare City-Stati.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Saccheggio da un esercito vittorioso durante la guerra è stata una pratica comune nel corso della storia. Per i soldati a piedi, è stato visto come un modo per integrare il loro reddito, spesso magro e faceva parte della celebrazione della vittoria. Ai livelli più alti, la mostra fiero di bottino era parte integrante del tipico trionfo romano, e Gengis Khan non era insolito nel proclamare che la più grande felicità era "per sconfiggere i tuoi nemici ... per derubarli delle loro ricchezze ..." [NEWLINE] [NEWLINE] Nella guerra in tempi antichi, il bottino di guerra, incluse le popolazioni sconfitti, che sono stati spesso schiavizzati, e le donne ei bambini, che sono stati spesso assorbiti nella popolazione del paese vittorioso. In altre società pre-moderne, oggetti in metalli preziosi sono stati il ​​bersaglio preferito dei saccheggi della guerra, in gran parte a causa della loro facile trasportabilità. In molti casi saccheggio è stata l''occasione di ottenere i tesori che altrimenti non sarebbe stato ottenibile. Dal 18 ° secolo, le opere d''arte sono sempre più un obiettivo popolare. Nel 1930 e ancor più durante la seconda guerra mondiale, la Germania nazista impegnato in larga scala e organizzato saccheggio d''arte e immobili.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiators', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Happiness Città: +1 per Arena [NEWLINE] 2 [ICON_TEAM_2] unità di difesa del capitale..', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'Epic War', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' +1 [ICON_HAPPINESS_1] Città Felicità da edifici Cultura.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Un epico (dall''antico aggettivo ἐπικός Greco (epikos), da ἔπος (EPOS) "parola, racconto, poesia") è un poema narrativo lungo, di solito riguardante un argomento serio contenente i dettagli di atti ed eventi eroici significativo per una cultura o di una nazione . [NEWLINE] [NEWLINE] poemi di guerra sono poemi epici o un opera letteraria di portata epica che cercano o si crede di catturare ed esprimere l''essenza o spirito di una particolare nazione o un gruppo etnico o linguistico con aspirazioni di indipendenza o autonomia. Epopee nazionali spesso raccontano l''origine di una nazione, una parte della sua storia, o un evento cruciale come vittorie decisive o Vanquishing dei nemici amari, nello sviluppo dell''identità nazionale', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Città Happiness: +1 per Garrison [NEWLINE] [ICON_CULTURE] Cultura: +2 per Garrison', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Grande Generale: 1 [NEWLINE] [ICON_MOVES] Movimento:. +1 Per Grandi Generali [NEWLINE] [ICON_STRENGTH] +15% Forza per tutte le unità adiacenti ad altre unità militari amiche.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% quando [COLOR_POSITIVE_TEXT] adiacente [ENDCOLOR] per unità militari amiche.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] costo di aggiornamento: -50% per le quote [NEWLINE] [ICON_PRODUCTION] Produzione: +15% per tutte le unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Code Warrior [ENDCOLOR] [NEWLINE]', '', '');
/*  Pietà  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Abilità:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Cultura +1 [NEWLINE] [ICON_PEACE] Faith +1 [NEWLINE] [ICON_PRODUCTION] raddoppiare la produzione per Santuari [ICON_WORKER] Sblocca: Stonehenge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] Scegliere una nuova convinzione Pio.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Carità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Oro: +25% da templi [NEWLINE] [ICON_GOLD] Oro: 2 da templi [NEWLINE] [ICON_GOLD] Oro: 3 Luoghi Santi.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'La parola "carità" deriva dalla vecchia parola francese "Charité" che, a sua volta, deriva dalle "caritas" latino. [NEWLINE] [NEWLINE] La pratica della carità significa la donazione volontaria di aiuto a chi è nel bisogno che sono non legati al donatore, anche se il significato originale è più coinvolto con i concetti di preziosità, dearness, prezzo elevato. Beneficenza viene effettuata direttamente o per mezzo di un trust di beneficenza o altra causa. Queste istituzioni si sono evoluti per effettuare il lavoro di assistenza ai poveri, ed è venuto per essere chiamato, chiamato «beneficenza». In ''beneficenza'' tempi moderni fornire la maggior parte delle donazioni, in termini di valore monetario. I tipi di beneficenza sono orfanotrofi, banchi alimentari, istituti religiosi dedicati alla cura dei poveri, ospedali, organizzazioni che visitano il homebound e imprigionato, e molti altri.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Ispirazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] gratuita di Great Prophet: +1', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'La parola "ispirazione" deriva dal sostantivo latino inspiratio e dal verbo inspirare. Inspirare è un termine composto che deriva dal prefisso latino in (all''interno, in) e il verbo spirare (respirare). [NEWLINE] [NEWLINE] In epoca classica romana, inspirare era già venuto a significare "a respirare profondamente" e ha assunto anche senso figurato di "instillare [qualcosa], nel cuore o nella mente di qualcuno". [NEWLINE] [NEWLINE] Quindi ''ispirazione'' si riferisce a una raffica inconscia di creatività in un''opera letteraria, musicale, o altra attività artistica. Il concetto ha origini sia ellenismo e l''ebraismo. I greci credevano che l''ispirazione venne dalle muse, così come gli dei Apollo e Dioniso. Allo stesso modo, nelle religioni nordiche antiche, l''ispirazione deriva dalle divinità, come Odino. L''ispirazione è anche una questione divina nella poetica ebraico. Nel Libro di Amosthe profeta parla di essere sopraffatti dalla voce di Dio e costretto a parlare. Nel cristianesimo, l''ispirazione è un dono dello Spirito Santo.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Tolleranza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Happiness Città: +1 per edificio religioso [NEWLINE] [ICON_PEACE] Le città con più religioni anche ottenere il bonus Pantheon della religione secondo più popolare della città.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Tolleranza o tolleranza è "la pratica di deliberatamente consentire o permettere una cosa di cui si disapprova. Si può significativamente parlare di tollerare, cioè di consentire o consentire, solo se si è in grado di impedire." E ''stato anche definito come " sopportare o resistere "o" per nutrire, sostenere o preservare ". tolleranza può significare" non più di tolleranza e il permesso dato dai seguaci di una religione dominante per le altre religioni di esistere, anche se questi ultimi sono guardato con disapprovazione, come inferiore, scambiato o nocivo "[NEWLINE] [NEWLINE] La tolleranza è un atteggiamento mentale che comporta l''accettazione non giudicante dei diversi stili di vita o credenze, considerando la tolleranza implica la messa con qualcosa che si disapprova. [NEWLINE] [NEWLINE] esempi storici di ''tolleranza'' abbondano. Ad esempio, in un atto di tolleranza, il re persiano Ciro il Grande è stato creduto di aver liberato gli ebrei dalla cattività in 539-530 aC, e permise il loro ritorno in patria.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Golden Age Attiva: 10 [NEWLINE] [ICON_GOLDEN_AGE] epoca d''oro richiedono il 50% in meno di [ICON_HAPPINESS_1] Felicità Nazionale', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'L''unità si riferisce ai legami in una società che legano le persone tra loro. Il termine viene generalmente impiegato in sociologia e altre scienze sociali. [NEWLINE] [NEWLINE] Nelle società semplici si può essere basato principalmente intorno parentela e di valori condivisi. Nelle società più complesse, ci sono varie teorie su ciò che contribuisce al senso di solidarietà sociale [NEWLINE] [NEWLINE] Questo porta a termine associato di ''solidarietà'' di cui si dice:. [NEWLINE] "La solidarietà non presuppone che le nostre lotte sono le stesse lotte, o che il nostro dolore è lo stesso dolore, o che la nostra speranza è per lo stesso futuro. Solidarietà comporta impegno e lavoro, così come il riconoscimento che, anche se non abbiamo gli stessi sentimenti, o le stesse vite, o gli stessi corpi, ci vivono su un terreno comune ". - Sara Ahmed', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Meditazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] Faith: +1 Santuari, Templi [NEWLINE] [ICON_PEACE] Costi Faith: -33%', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Devozione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'La devozione può essere definita come: ardente, affetto spesso disinteressata e dedizione, da una persona o principio. Culto, dal worthscipe antico inglese, che significa dignità o la pena nave è un atto di devozione religiosa di solito orientata verso una divinità. Strettamente affine al concetto di amore, devozione è spesso spera di essere ricambiato con qualche forma di vantaggio o benedizione. [NEWLINE] [NEWLINE] I devoti, quelli che praticano la devozione sono chiamati voler ricevere queste benedizioni, sono spesso a senso unico di il punto di fanatismo. Così, mentre il concetto di ''devozione'' è benigno, molti esempi storici di devozione religiosa sono spesso estreme e sanguinante, mentre i devoti si contendono l''affetto dei devoti con i display più scandaloso.', '', '');
/*  Ricchezza  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Ricchezza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'RICCHEZZA', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'La ricchezza è l''abbondanza di risorse preziose o beni materiali. Il concetto di ricchezza è significativa in tutti i settori dell''economia, ma il significato della ricchezza è dipendente dal contesto e non è universalmente convenuto definizione. Alla ricchezza livello più generale è "qualcosa di valore", che cattura sia la natura soggettiva della parola, e l''idea che non è un concetto fisso o statico.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'Qual è la ricchezza politica sociale ramo in merito?', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'Il ramo di ricchezza si concentra sullo sviluppo territorio ampio, con una fornitura nazionale di [ICON_GOLD] oro creato da città principali per l''acquisto di nuove unità ed edifici in città di frontiera non sviluppate.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'Il ramo di ricchezza si concentra sullo sviluppo territorio ampio, con una fornitura nazionale di [ICON_GOLD] oro creato da città principali per l''acquisto di nuove unità ed edifici in città di frontiera non sviluppate. Vedi le norme in materia di Politiche Sociali per i dettagli.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'La ricchezza Branch', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_GOLD] Oro: +10% {TXT} [NEWLINE] [ICON_PRODUCTION] Produzione: +10% {TXT} [NEWLINE] [ICON_WORKER] Sblocca : Canale di Panama [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Happiness: +1 per mercato, Fucina [NEWLINE] [ICON_PEACE] possono acquistare grandi mercanti con fede entrando nell''era industriale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' 2 [ICON_MOVES] Movimento per unità non combattenti. [NEWLINE] +25% [ICON_GOLD] Proventi da [ICON_CONNECTED] Commercio Interno. [NEWLINE] -25% Costo [ICON_GOLD] per strade e ferrovie.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Oro: +1 per Village [NEWLINE] [ICON_PRODUCTION] Produzione: +1 per Mine, Segheria', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] possono acquistare lanzichenecchi. [NEWLINE] [ICON_TEAM_2] 2 lanzichenecchi appaiono nella Capitale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Libero Grande Mercante: +1 [NEWLINE] [ICON_GREAT_PEOPLE] Merchant ottimo prezzo: +25% [NEWLINE] [ICON_GREAT_MERCHANT] Double Gold da Great missioni commerciali Merchant.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Roulotte', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Oro: +3 per rotta commerciale', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Produzione: +4 per Coastal City [NEWLINE] [ICON_GOLD] Oro: +4 per Faro, Porto, Seaport', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Gilde', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' +1 [ICON_TEAM_7] Grande Mercante nella Capitale. [NEWLINE] +100% Oro [ICON_GOLD] da Great missioni commerciali Merchant.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Una gilda è un''associazione di artigiani in un particolare commercio. I primi tipi di gilda si sono formate come confraternite dei lavoratori. Essi sono stati organizzati in maniera qualcosa tra un sindacato, un cartello, e una società segreta. Spesso dipendeva concessione di lettere di brevetto da un monarca o altra autorità per far rispettare il flusso degli scambi ai propri soci lavoratori autonomi, e di mantenere la proprietà degli strumenti e la fornitura di materiali.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] Il costo di acquisto per le unità e gli edifici.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Legge sui brevetti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' +1 [ICON_GOLD] oro da villaggi. [NEWLINE] 2 Oro [ICON_GOLD] da porti.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Un brevetto è un insieme di diritti esclusivi concessi da uno Stato (governo nazionale) per un inventore o il loro assegnatario per un periodo limitato di tempo in cambio della divulgazione di un''invenzione. [NEWLINE] [NEWLINE] I brevetti in senso moderno origine nel 1474, quando la Repubblica di Venezia ha emanato un decreto che nuovi e fantasiosi dispositivi, una volta messe in pratica, dovevano essere comunicate alla Repubblica per ottenere il diritto di impedire ad altri di servirsi di esse. [NEWLINE] [NEWLINE] Inghilterra seguito con la Statuto dei Monopoli nel 1623 sotto il re Giacomo I, che ha dichiarato che i brevetti possono essere concessi solo per i "progetti di nuova invenzione." Durante il regno della regina Anna (1702-1714), gli avvocati della Corte inglese ha sviluppato il requisito che una descrizione scritta dell''invenzione deve essere presentata. Il sistema dei brevetti in molti altri paesi si basa sul diritto inglese e può essere fatta risalire allo Statuto dei Monopoli.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] Sposta e uno spettacolo per navi militari. [NEWLINE] 2 [ICON_RESEARCH] Science for Coastal Cities. [NEWLINE] 2 Scienza [ICON_RESEARCH] per costruzioni navali.', '', '');
/*  Patrocinio  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Abilità:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_GOLD] 2 oro per Città-Stato rotta commerciale [NEWLINE] [ICON_VIEW_CITY] rivela tutta città-stato [NEWLINE] [ICON_WORKER] Sblocca : Angkor Wat [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_PLUS] +100% la quantità di risorsa strategica e +50% [ICON_HAPPINESS_1] Nazionale Felicità da risorse di lusso Donata da alleati Città-Stato.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] +20 Influenza immediata città-stato. [NEWLINE] [ICON_INFLUENCE] +33% Influenza da [ICON_GOLD] Oro doni di città-stato.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Special Relationship', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Influenza con la città-stato degrada il 33% più lento del normale. [NEWLINE] [ICON_INFLUENCE] Influenza Altri giocatori con città-stato si riduce del 10% più veloce.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] +20 riposo influenza City-Stati.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] 2 Scienza per epoca per ogni amico Città-Stato, e +3 per ogni alleato.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] alleati Città-Stato regalo grandi persone. [ICON_GREAT_PEOPLE] +10% Grande persone Rate.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Patto di Commercio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' 2 [ICON_PRODUCTION] Produzione per epoca per ogni amico Città-Stato, e +3 per ogni alleato (split tra le vostre città).', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Il libero commercio è un sistema di politica commerciale che permette agli operatori di commercio oltre i confini nazionali senza interferenze da parte dei rispettivi governi. Grazie al principio economico del vantaggio comparato, questo fornisce ai partner commerciali con vantaggi reciproci. Nell''ambito di questa politica dei prezzi sono l''unico fattore determinante di allocazione delle risorse, e una riflessione stretta della domanda e dell''offerta.', '', '');
/*  Estetica  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] +50% di produzione per gli edifici culturali [NEWLINE] [ICON_WORKER] Sblocca:. Uffizi [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] Rivela siti Antichità nascosti. [NEWLINE] [ICON_TEAM_7] consente l''acquisto di Culturali Grandi Personaggi con [ICON_PEACE] La fede entrando Industrial Era.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Cultura: +1 per 2 surplus felicità.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Cultura: due per Nazionale Wonder [NEWLINE] [ICON_CULTURE] Cultura: +33% nelle città con una Wonder World', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Grande Artista: 1 [NEWLINE] [ICON_TEAM_7] Culturale tasso Grande Personaggio: +25%', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Gli archeologi sono prodotte due volte più veloce', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Doubles Turismo edificio-tema. [NEWLINE] [ICON_TOURISM] +25% del turismo dalla religione comune, frontiere aperte e rotte commerciali.', '', '');
/*  Esplorazione  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_MOVES] Mosse: due per le unità imbarcata [NEWLINE] [ICON_MOVES] Mosse: due eccezionali Ammiragli [NEWLINE] [ICON_SIGHT_SEA] Sight: + 1 per Navi Militari [NEWLINE] [ICON_WORKER] Sblocca: Red Fort [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] 2 nazionali Felicità per ogni risorsa di lusso. [NEWLINE] [ICON_TEAM_7] Consente l''acquisto di grandi ammiragli con la fede entrando Industrial Era.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Città Happiness: +1 per Faro, Porto, Seaport', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Acquisto Costo: -25% per Edifici [NEWLINE] [ICON_GOLD] Manutenzione: -25% per Edifici', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Colonizzazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Città iniziano con 3 abitanti. [NEWLINE] [ICON_TEAM_2] 2 Settlers, 2 operai e 2 unità di difesa appaiono nella Capitale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Spirit Pioneer', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 movimento per i civili. [NEWLINE] [ICON_GOLD] costo -50% per le strade. [NEWLINE] [ICON_PRODUCTION] produzione +100% per la costruzione di porti.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Homestead Act', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Città guadagnano tier libero 1 edifici.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(Todo)', '', '');
/*  Conoscenza  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Conoscenza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'CONOSCENZA', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'La conoscenza è una familiarità con qualcuno o qualcosa, che può includere fatti, informazioni, descrizioni, o competenze acquisite attraverso l''esperienza o formazione. Si può fare riferimento alla comprensione teorica o pratica di un soggetto. Può essere giocata pratico o perizia, o la comprensione teorica di un soggetto.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Pietà aumenta la Felicità, Cultura e Fede del civ dell''adozione. Pietà diventa disponibile una volta raggiunta l''epoca classica. Questo è un luogo ideale per acquistare le politiche per i giocatori che cercano di creare o espandere le religioni.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'Qual è la conoscenza politica sociale ramo merito?', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'Il ramo della conoscenza migliora la capacità di civiltà da utilizzare e generare Scienza, divenendo disponibile entrando del Rinascimento.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'Il ramo Conoscenza delle politiche sociali è piena di politiche che possono aumentare la vostra ricerca. Questo ramo diventa disponibile in epoca rinascimentale. Vedi le norme in materia di Politiche Sociali per i dettagli.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'The Knowledge Branch', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Abilità: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Opener [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Grande Scienziato: +1 [NEWLINE] [ICON_WORKER] Sblocca: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [ COLOR_GREY] (a concretizzare tutte le politiche in questo albero) [ENDCOLOR] [NEWLINE] +1 immediata [ICON_TEAM_5] Technologies. [NEWLINE] [ICON_PEACE] possono acquistare grandi scienziati con [ICON_PEACE] La fede una volta entrati nell''era industriale.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[ICON_RESEARCH] ricompense +50% accordo di ricerca.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Controspionaggio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] +25% di possibilità di catturare spie nemiche. [NEWLINE] [ICON_SPY] -25% nemico efficacia spia.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(Todo)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Scienza: +10% mentre la nazione è [ICON_HAPPINESS_1] felice', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Scienza: +1 per Village [NEWLINE] [ICON_RESEARCH] Scienza: +2 per Faro', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Scienza: +2 al Specialist', '', '');







UPDATE Loaded File SET Value=1, IT_IT=1 Where Type='Policies.sql';



