/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/*  PROMOZIONI  */
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Armatura [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', 'Potenza Artic', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Neve e Tundra [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', 'Bombardamento I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] [COLOR_POSITIVE_TEXT] Mare [ENDCOLOR] unità e', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', 'Bombardamento II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] [COLOR_POSITIVE_TEXT] Mare [ENDCOLOR] unità e', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', 'Bombardamento III', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] [COLOR_POSITIVE_TEXT] Mare [ENDCOLOR] unità e', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] 6 Gamma', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] 6 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] può aria Sweep per cancellare Unità di intercettazione.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] navali [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', 'Assegnazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] +10% Forza [NEWLINE] [ICON_GOLD] -100% [COLOR_POSITIVE_TEXT] Costo Aggiornamento [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] danno completa di attaccare il mare o fiumi [NEWLINE] [ICON_STRENGTH] +100% quando [COLOR_POSITIVE_TEXT] imbarcato [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[ICON_STRENGTH] +25% Forza vs [COLOR_POSITIVE_TEXT] Le unità a cavallo [ENDCOLOR] e [COLOR_POSITIVE_TEXT] Armatura [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[ICON_STRENGTH] +25% Forza vs [COLOR_POSITIVE_TEXT] Le unità a cavallo [ENDCOLOR] e [COLOR_POSITIVE_TEXT] Armatura [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', 'Bonus vs Air (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Aria [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] +150% vs [COLOR_POSITIVE_TEXT] bombardieri ed elicotteri [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', 'Bonus vs Dragoni (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Dragoni [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus vs Fighters (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Elicotteri (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Helicopters [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', 'Bonus vs Montato (10)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] +10% vs melee [COLOR_POSITIVE_TEXT] [ENDCOLOR] Le unità a cavallo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', 'Bonus vs Montato (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] +50% vs melee [COLOR_POSITIVE_TEXT] [ENDCOLOR] Le unità a cavallo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', 'Attacco vs Submarines (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Attacco [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Sottomarini [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Tanks (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] [Serbatoi EndColor]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', 'Astronomia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] può attraversare [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', 'Bonus Attack (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Attacco [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', 'Bonus Attack (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Attacco [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_RANGE_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR] Può attaccare due volte', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Ships [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Ships [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Ships [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', 'Cameratismo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] +15% quando [COLOR_POSITIVE_TEXT] Adiacente [ENDCOLOR] per una unità amica', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] Attacchi usa [COLOR_POSITIVE_TEXT] 1 azione [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] Può passare attraverso [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', 'Bonus vs Capital Ships (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Battleships [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Missile da crociera [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Carriers [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] può trasportare [COLOR_POSITIVE_TEXT] 1 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] può trasportare [COLOR_POSITIVE_TEXT] 2 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] può trasportare [COLOR_POSITIVE_TEXT] 3 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] può trasportare [COLOR_POSITIVE_TEXT] 4 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] +1 Movimento [NEWLINE] [ICON_STRENGTH] +20% vs [COLOR_POSITIVE_TEXT] [ENDCOLOR] unità feriti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] unità fortificate [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', 'Attacco vs Città (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Attacco [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', 'Bonus vs Città (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', 'Bonus vs Città (200)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] +200% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', 'Bonus vs Città (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', 'Merchant Raider I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Cities [ENDCOLOR] [NEWLINE] [ICON_GOLD] Ruba oro pari al 33% del danno inflitto ai porti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', 'Merchant Raider II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Cities [ENDCOLOR] [NEWLINE] [ICON_GOLD] Ruba oro pari al 33% del danno inflitto ai porti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', 'Merchant Raider III', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] Port Cities [ENDCOLOR] [NEWLINE] [ICON_GOLD] Ruba oro pari al 34% del danno inflitto ai porti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] attacchi a distanza [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] attacchi a distanza [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', 'Penalty vs Ranged (10)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] -10% [COLOR_NEGATIVE_TEXT] Difesa [ENDCOLOR] contro tutti [COLOR_NEGATIVE_TEXT] attacchi a distanza [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '-10% Vs [COLOR_NEGATIVE_TEXT] a distanza [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH] +30% nel [COLOR_POSITIVE_TEXT] Capital [ENDCOLOR]; bonus cade come l''unità si allontana', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Punizione sulla Difesa (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50% [COLOR_NEGATIVE_TEXT] Difesa [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] può imbarcarsi su [COLOR_POSITIVE_TEXT] Campagna Acqua [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +100%, mentre [COLOR_POSITIVE_TEXT] imbarcato [ENDCOLOR].', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', 'Bonus Difesa (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', 'Bonus Difesa (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', 'Punizione sulla Difesa (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25% [COLOR_NEGATIVE_TEXT] Difesa [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', 'Desert Potenza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Deserti [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% quando [COLOR_POSITIVE_TEXT] adiacente [ENDCOLOR] per una unità amica', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] sweep Air [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] sweep Air [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] 34% [COLOR_POSITIVE_TEXT] sweep Air [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOUBLE_WORK_SPEED_HELP', '[ICON_WORKER] Costruisce miglioramenti% più veloce 100', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOUBLE_WORK_SPEED', 'Doppia velocità di lavoro', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] ROUGH [ENDCOLOR] Terrain (Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] può imbarcarsi su [COLOR_POSITIVE_TEXT] Acqua Piastrelle [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Imbarcato Difesa (100)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] +100% quando [COLOR_POSITIVE_TEXT] s''imbarcò [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] +1 Sight Campo quando [COLOR_POSITIVE_TEXT] imbarcato [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50% di probabilità di [COLOR_POSITIVE_TEXT] Evade [ENDCOLOR] intercettazioni', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100% di possibilità di [COLOR_POSITIVE_TEXT] Evade [ENDCOLOR] intercettazioni', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Movement [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Movement [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH] -10% per [COLOR_POSITIVE_TEXT] unità nemiche adiacenti [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', 'First Strike', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT] attacco gratuito [ENDCOLOR] prima del combattimento', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] +50% quando [COLOR_POSITIVE_TEXT] accompagnamento [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] Tutti i movimenti usa [COLOR_PLAYER_ORANGE_TEXT] 1 azione [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Terre Straniere Bonus (20)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', 'Formazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Portata [ENDCOLOR] [ENDCOLOR] unità e [COLOR_POSITIVE_TEXT] blindati', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT] Le unità a cavallo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', 'Aggiornamenti gratuiti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', 'Aggiornamenti gratuiti', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] Guadagna esperienza il 50% più veloce', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] +15%, con [COLOR_POSITIVE_TEXT] Grande Generale [ENDCOLOR] nella stessa piastrella', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', 'D''oro', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '[ICON_GOLDEN_AGE] punti Golden Age da combattimento', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] Migliora l''efficacia di combattimento del vicino [COLOR_POSITIVE_TEXT] Navi [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] Migliora l''efficacia di combattimento del vicino [COLOR_POSITIVE_TEXT] Unità di terra [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1', 'Guerrilla I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] sul fuoristrada [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2', 'Guerrilla II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] su fuoristrada', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3', 'Guerrilla III', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] su fuoristrada', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'AI Handicap I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] +1 Visibilità [NEWLINE] [ICON_WAR] +10% Esperienza [NEWLINE] [ICON_STRENGTH] +10% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] 2 Visibilità [NEWLINE] [ICON_WAR] +25% Esperienza [NEWLINE] [ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] 2 Visibilità [NEWLINE] [ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] guarisce 50 Damage [ENDCOLOR] quando si uccide una unità non Barbarian', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] Heal questa Unità [ENDCOLOR] 50 CV In questo modo si [COLOR_POSITIVE_TEXT] Consumare questa occasione [ENDCOLOR] per scegliere una Promozione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', 'Hill Fighter', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Hills [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] amichevole Territory [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', 'All Terrain', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] può attraversare [COLOR_POSITIVE_TEXT] Montagne [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] ignora i costi del terreno', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] Può attaccare [COLOR_POSITIVE_TEXT] oltre gli ostacoli [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] 33% più forti [COLOR_POSITIVE_TEXT] Intercettazioni [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] 33% più forti [COLOR_POSITIVE_TEXT] Intercettazioni [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] 34% più forti [COLOR_POSITIVE_TEXT] Intercettazioni [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[ICON_AIR] 20% di probabilità di [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] aeromobile', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[ICON_AIR] 40% di probabilità di [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] aeromobile', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[ICON_AIR] 50% di probabilità di [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] aeromobile', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[ICON_AIR] 100% di possibilità di [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] aeromobile', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', 'Intercettazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] 100% di possibilità di intercettare [COLOR_POSITIVE_TEXT] Aria Unità [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] ignora i confini culturali [NEWLINE] [ICON_DETECT] può essere vista solo da unità con Sonar o 1 casella di distanza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT] Foresta / Giungla [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', 'Bonus vs Terreni (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', 'Bonus vs Terreni (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', 'Penalty vs Terreni (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH]% vs -50 [COLOR_NEGATIVE_TEXT] Terreno [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MARCH_HELP', '[ICON_HEAL] Attaccare e in movimento non impediscono la guarigione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +10 Healing [ENDCOLOR] per unità entro 1 tessera', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] +5 Healing [ENDCOLOR] per turno per le unità a tessere adiacenti [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +5 Healing [ENDCOLOR] per turno per questa unità quando [COLOR_POSITIVE_TEXT] Al di fuori del territorio amico [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', 'Mercenario', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50% [COLOR_POSITIVE_TEXT] Costo Aggiornamento [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Movement [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT] Foresta / Giungla [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] +20% Forza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', 'Alpinista', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] può passare sopra [COLOR_POSITIVE_TEXT] Montagne [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Penalty vs Montato (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] Grandi Generali [ENDCOLOR] si muovono a ritmo di questa unità se iniziano il turno [COLOR_POSITIVE_TEXT] accatastati [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] deve impostare a Attacco a Distanza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Attacco [ENDCOLOR] in territorio amico', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', 'Protezione Nazionale', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Ships [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty attaccare le navi (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', 'Naval Recon I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_HEAL] può [COLOR_POSITIVE_TEXT] curare [ENDCOLOR] territorio al di fuori amichevole', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', 'Naval Recon II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] +1 Movimento [NEWLINE] [ICON_MOVES] I tentativi di [COLOR_POSITIVE_TEXT] ritirare [ENDCOLOR] dal combattimento corpo a corpo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', 'Naval Siege', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Le unità fortificate [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Movement [ENDCOLOR] [NEWLINE] [ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', 'Nuova Unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'Nuova Unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] Impossibile catturare Città', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', 'Nessun bonus terreno difensivo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] Nessun bonus terreno difensivo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] Impossibile immettere profondo oceano fino Astronomia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] Impossibile immettere profondo oceano', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT] amichevole Territory [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] Unità non può attaccare [COLOR_NEGATIVE_TEXT] unità [ENDCOLOR], solo città', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] non puoi attacco corpo a corpo', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', 'Canale di Panama', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Movimento per navi', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', 'Partenone', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] +10% Forza da Great generali e ammiragli', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] può [COLOR_POSITIVE_TEXT] Paradrop [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '[ICON_HEAL] Guarisce 25 Danni Se uccide un unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', 'Falange', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Portata [ENDCOLOR] [COLOR_POSITIVE_TEXT] Soldier [ENDCOLOR] unità e', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] Acquisisce [ENDCOLOR] nemici sconfitti [COLOR_POSITIVE_TEXT] Ships [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] 1 [COLOR_POSITIVE_TEXT] Range [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] può [COLOR_POSITIVE_TEXT] attacco due volte [ENDCOLOR] al 90% [ICON_RANGE_STRENGTH] forza a distanza', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', 'Difesa vs Ranged (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] danno a distanza [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] Può entrare [COLOR_POSITIVE_TEXT] Territorio Rival [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', 'Recon I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] 2 Sight', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', 'Recon II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] +1 Movimento [NEWLINE] [ICON_MOVES] Può utilizzare strade nemici', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', 'Recon III', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] Può paradrop 10 tessere.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', 'Bonus vs Mare (25)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT] Mare [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', 'Bonus vs Mare (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Mare [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', 'Sonar', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] Può vedere [COLOR_POSITIVE_TEXT] Sottomarini [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT] APERTO [ENDCOLOR] Terrain (NO Hills, foresta o giungla)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] Città [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] Le unità fortificate [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', 'Scaramuccia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] I tentativi di ritirarsi dalla mischia o imbarcati combattimento', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] +1 supplementare [COLOR_POSITIVE_TEXT] Dribbling [ENDCOLOR] può essere fatta per turno', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] Combattimento rischia di creare [COLOR_POSITIVE_TEXT] Grandi Generali [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] Combattimento molto probabilmente a creare [COLOR_POSITIVE_TEXT] Grandi Generali [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] +15% attacco [COLOR_POSITIVE_TEXT] Città [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT] unità di feriti [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_HELP', '[ICON_HEAL] Può guarire [COLOR_POSITIVE_TEXT] Esterni Territory [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] +20 Healing [ENDCOLOR] per turno', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] 5 [COLOR_POSITIVE_TEXT] guarigione [ENDCOLOR] territorio al di fuori amichevole [NEWLINE] [ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] Unità [COLOR_POSITIVE_TEXT] guarire ogni Ruotare [ENDCOLOR], anche se si esegue un''azione [NEWLINE] [ICON_MOVES] Unità tenterà di ritirarsi di fronte a un attacco in mischia', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', 'Repressione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT] Vanguard [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', 'Survivalist', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '[ICON_HEAL] +20 [COLOR_POSITIVE_TEXT] guarigione [ENDCOLOR] territorio al di fuori amichevole [NEWLINE] [ICON_MOVES] Nessun Costo di movimento a saccheggiare', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] navali [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] +1 Movimento [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] navali [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] +1 Sight [NEWLINE] [ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT] navali [ENDCOLOR] unità', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1', 'Trincee I', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] su Open Terrain [NEWLINE] [ICON_DETECT] +1 Sight', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2', 'Trincee II', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] su Open Terrain', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3', 'Trincee III', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3_HELP', '[ICON_STRENGTH] +20% [COLOR_POSITIVE_TEXT] Difesa [ENDCOLOR] su Open Terrain', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', 'Può entrare nel territorio rivale senza frontiere aperte, ma perde il 25% della forza religiosa originale per ogni turno finiscono su tale tessera. L''unità è eliminato quando la forza religiosa è 0.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT] unità fortificate [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] +100% quando [COLOR_POSITIVE_TEXT] imbarcato [ENDCOLOR] [NEWLINE] 1 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR] quando [COLOR_POSITIVE_TEXT] s''imbarcò [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', 'Attacco a terra Penalty (50)', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[ICON_RANGE_STRENGTH] -50% attacco vs [COLOR_NEGATIVE_TEXT] Ground e navi [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT] Foreste e Jungle [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1 Movimento', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT] 2 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT] Sight Campo [ENDCOLOR]', '', '');





UPDATE Loaded File SET Value=1, IT_IT=1 Where Type='Promotions.sql';

