/* The sql commands and text below were formulated in the Research tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1194171600
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING', 'Formazione', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_PEDIA', 'L''addestramento militare è un processo che stabilisce e migliorare le capacità del personale militare. Educazione militare può essere imposta volontaria o obbligatoria. [NEWLINE] formazione Recruit tenta di insegnare le informazioni di base e la formazione in tecniche necessarie per essere un membro effettivo servizio. Per raggiungere questo obiettivo, i membri del servizio sono forati fisicamente, tecnicamente e psicologicamente. [NEWLINE] Dopo aver terminato la formazione di base, molti membri del servizio di una formazione avanzata più in linea con le loro specialità scelti o assegnati. In formazione avanzata, tecnologia e attrezzature militari è spesso insegnato.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_QUOTE', '[NEWLINE] [TAB] [TAB] "coscrizione se necessario, ma non necessariamente coscrizione". [NEWLINE] [TAB] [TAB] - William Lyon Mackenzie King [NEWLINE]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE', 'Scienze Politiche', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_PEDIA', 'Durante il Rinascimento italiano, Niccolò Machiavelli ha stabilito l''enfasi della moderna scienza politica sull''osservazione empirica diretta di istituzioni e attori politici. [NEWLINE] [NEWLINE] filosofi tardi europei come Voltaire, Rousseau, Thomas Hobbes e John Locke applicati i principi dalle scienze dei materiali alla società nel suo insieme, creando le scienze sociali. Questi hanno aperto la strada a politiche che ha sottolineato un contratto sociale tra governo e governati, la necessità di una separazione tra chiesa e stato, e la graduale diminuzione del diritto divino dei re.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_QUOTE', '[NEWLINE] [TAB] [TAB] "La politica non hanno alcuna relazione con la morale". [NEWLINE] [TAB] [TAB] - Niccolò Machiavelli [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_TITLE', 'Commercio', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_DESC', 'Commercio avuto origine con l''inizio della comunicazione in epoca preistorica. E ''stimolato la curiosità comune, l''ingegno, e l''apprendimento delle lingue. Come tale, il commercio e la specializzazione che ha generato è stato accreditato con accelerare la crescita della coscienza umana e il trionfo degli umani sulle specie Neanderthal. [NEWLINE] [NEWLINE] Ci sono prove dello scambio di ossidiana e selce durante l''età della pietra. Egitto scambiato per i materiali utilizzati per la creazione di gioielli dal 3000 aC. Lungo raggio rotte commerciali prima apparizione, quando i Sumeri in Mesopotamia negoziati con la civiltà Harappa della Valle dell''Indo. I Fenici - ha rilevato gli operatori del mare - viaggiato attraverso il Mar Mediterraneo, e come estremo a nord come la Gran Bretagna per le fonti di stagno per la produzione di bronzo. Hanno stabilito il commercio colonie che i greci chiamavano empori. [NEWLINE] [NEWLINE] Commercio ha continuato a guidare la tendenza umana ad esplorare molto tempo dopo la scomparsa degli antichi imperi marittimi del Mediterraneo. Lunga distanza spread scambi ancora più lontano con enorme flotta di Zheng He, che ha raggiunto l''India, Arabia e Africa orientale prima che Colombo attraversò l''oceano.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE] [TAB] [TAB] "Non c''è ragione esiste oggi a scontare la presenza o potenziale impatto di economia in albori pre-storica dell''umanità". [NEWLINE] [TAB] [TAB] - Jason Shogren [NEWLINE] [ TAB]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE] [NEWLINE] Nessun giocatore ancora ha la tecnologia per il commercio questo articolo (Commercio).', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS', 'Carvel Hulls', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'Disegno Carvel nave era uno degli sviluppi critici che hanno permesso il dominio di potenze navali dell''Europa occidentale dal 1400 ad oggi. Le assi di legno di scafi Carvel allineano contro l''altro, da bordo a bordo, invece del disegno della plancia sovrapposizione di scafi clinker. Questo disegno della carena forti supporti di navi molto più grandi e vele.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE] [TAB] [TAB] "Una nave è al sicuro in porto, ma non è questo che le navi sono per." [NEWLINE] [TAB] [TAB] - William Shedd [NEWLINE]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Mass media', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_DESC', 'Il termine "mass media" è stato coniato nel 1920 con l''avvento della radio, ma l''idea di supporto per il largo consumo pubblico è stato intorno dal drammi e commedie del mondo antico. I mass media è stato direttamente guidato dalla tecnologia, con maggiori progressi nelle tecniche editoriali e di comunicazione che portano a un pubblico ancora più grandi possibili stati raggiunti. [NEWLINE] [NEWLINE] Originariamente appena applicato a dispositivi di comunicazione come radio, giornali e riviste, mass media comprende ora televisione, film, musica, libri tascabili, videogiochi e Internet. Con l''avvento di questi tipi di media globe-spanning è anche emersa la capacità di raggiungere le masse come mai prima, e non sempre in senso buono. Il tentativo di sbieco o di controllo di grandi quantità di informazioni, sia attraverso la propaganda nefariously mentalità o più innocenti opinioni personali iniettati in fatti, sta diventando un grande problema per alcuni governi e organizzazioni per affrontare. Tecniche pubblicitarie invasive sono un sottoprodotto dei mass media, tanto per il fastidio di consumatori in tutto il mondo. Mentre il messaggio può essere utile ed è sempre più facile per la persona comune a pubblicare le loro idee e opere, sempre ascoltato nella produzione torrenziale di informazioni ora disponibili può davvero essere come ricerca di quel proverbiale ago nel pagliaio.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE] [TAB] [TAB] "La velocità delle comunicazioni è meravigliosa da vedere è anche vero che la velocità può moltiplicare la diffusione di informazioni che sappiamo essere falso.". [NEWLINE] [TAB] [TAB] - Edward R. Murrow [NEWLINE] [TAB] [TAB] [TAB]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Mass Production', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'La produzione di massa moderna è la costruzione di grandi quantità di prodotti standardizzati su linee di assemblaggio. Ingredienti importanti per la produzione di massa sono macchine utensili industriali, parti intercambiabili, gestione scientifica e di energia elettrica. [NEWLINE] [NEWLINE] La produzione di massa è stato reso popolare negli anni 1910 e 1920 da parte di Henry Ford Ford Motor Company, che ha introdotto i motori elettrici per il benessere tecnica nota della catena di produzione o sequenziale. Ford ha anche acquistato o progettato e costruito impieghi speciali macchine utensili e attrezzature. Tutte queste macchine utensili sono state organizzate sistematicamente nel processo di produzione. Gestione Ford effettuato studi a tempo ed esperimenti per meccanizzare i processi di fabbrica, puntando sulla minimizzazione dei movimenti dei lavoratori.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE] [TAB] [TAB] "C''è una regola per l''industriale e cioè:. Rendere la migliore qualità dei prodotti possibili al minor costo possibile, pagando i salari più alti possibili" [NEWLINE] [TAB] [TAB] - Henry Ford [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Ion Propulsion', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_DESC', 'La propulsione di scelta per gli scrittori di fantascienza è diventata la propulsione di scelta per gli scienziati e gli ingegneri della NASA. L''uso efficiente del sistema di propulsione ioni di combustibile e di energia elettrica consentono navicella moderna di viaggiare più lontano, più veloce e più economico rispetto a qualsiasi altra tecnologia di propulsione attualmente disponibile. I propulsori ionici sono attualmente utilizzati per stationkeeping sui satelliti di comunicazione e per la propulsione principale sonde spaziali profonde. I propulsori ionici espellere ioni per creare la spinta e in grado di fornire elevate velocità di punta di veicoli spaziali di ogni altro razzo attualmente disponibile. [NEWLINE] Uno ione è semplicemente un atomo o una molecola che viene caricata elettricamente. In un propulsore ionico, gli ioni sono accelerati da forze elettrostatiche. I campi elettrici utilizzati per l''accelerazione sono generati da elettrodi posizionati alla fine a valle del propulsore. [NEWLINE] propulsori ionici moderni utilizzano gas inerti per propellente. La maggior parte dei propulsori utilizzano xeno, che è chimicamente inerte, incolore, inodore, insapore e. Il propellente viene iniettato dalla estremità a valle del propulsore e scorre verso l''estremità a monte.', '', '');
REPLACE INTO Language_IT_IT (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE] [TAB] [TAB] "Tutte le civiltà diventano sia viaggiare nello spazio o estinti". [NEWLINE] [TAB] [TAB] - Carl Sagan [NEWLINE] [TAB]', '', '');




UPDATE LoadedFile SET Value=1, IT_IT=1 Where Type='Research.sql';





