/* The sql commands and text below were formulated in the Core tab of the Google Spreadsheet 'CAT_Language'.
https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGtjX2JldHBzdXhRbGNxVFgxT1E2OHc&usp=drive_web#gid=4
If you make any changes be sure to update the spreadsheet also.*/
/*砂漠のキャラバン*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS', '砂漠キャラバン', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_HELP', '[ICON_GOLD]ゴールド：各贅沢なリソースのすべての都市で5パーセント。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_STRATEGY', '砂漠キャラバンは贅沢品から帝国の金を増やす。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DESERT_CARAVANS_PEDIA', 'アラビアを通じて貿易ルートは、ほぼ3000年の古代中国、古代インド、古代チベット、ペルシャ帝国や地中海諸国からのトレーダー、商人、巡礼者、宣教師たち、兵士、遊牧民と都市住民の間で、文化、商業、および技術交流のための重要なパスだった。', '', '');
/* Citystates */
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED', 'あなたは[：テキスト·キー] [1_CivName]近く蛮族のグループを殺した！彼らは感謝しているし、彼らとあなたの[ICON_INFLUENCE]影響15増加している！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_BARB_QUEST_LONG', '[ICON_CITY_STATE] {1_CivName：テキスト·キー}これらの野蛮人は敗北したいと考えています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_IMPROVE_RESOURCES', 'リソースを改善', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_IMPROVE_RESOURCES_TT', 'すぐに市ステートコントロールが、改良されていないか、略奪エクスポート可能な資源を改善するために市·州の味方に{1_num} [ICON_GOLD]ゴールドを支払う。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_YIELDS', '得られます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_YIELDS_TT', 'プレイヤーは[ENDCOLORこの都市国家の[COLOR_POSITIVE_TEXT]アリーなった場合、これらは、プレイヤーが受け取る利回りです。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_QUESTS', 'クエスト：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_ALLIED_WITH', 'ALLY：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MINORCIV_PROTECTED_BY', 'プロテクター：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_RESOURCES', '輸出：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_TRAIT', 'TRAIT：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POP_CSTATE_PERSONALITY', '性格：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MINORCIV_PROTECTED_DESC', '他の文明は、都市国家を保護することを選択することができる。その都市国家との戦争を宣言すると、そのプロテクタにはお返しにあなたに宣戦布告することになります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_CULTURE_BONUS', 'あなたはすべての都市で、そこから[ENDCOLOR] [COLOR_POSITIVE_TEXT] [ICON_CULTURE]文化を受けている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_FOOD_BONUS', 'あなたはすべての都市で、そこから[COLOR_POSITIVE_TEXT] [ICON_FOOD]フード[ENDCOLOR]を受けている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CSTATE_MILITARY_BONUS', '彼らはあなたに[COLOR_POSITIVE_TEXT]新しい軍事ユニット[ENDCOLOR]ごとに数ターンを送信します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_BASE', '[ICON_INFLUENCE]への影響は、{1_CivName：テキスト·キー}あなたが今の時点まで増加している[COLOR_POSITIVE_TEXT] FRIENDS [ENDCOLOR] [NEWLINE] [NEWLINE] {2_DetailsS​​tring}彼らはまた、あなたを通して単位を移動する許可を与えている。自国の領土。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_CULTURE', '[COLOR_POSITIVE_TEXT]文化[ENDCOLOR]市ステートとして、彼らはあなたの街の[ICON_CULTURE]を増加芸術の珍しい作品を、与える。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MILITARISTIC', '[COLOR_POSITIVE_TEXT]軍国[ENDCOLOR]市ステートとして、彼らは時々あなたの軍事ユニットを与える。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MARITIME', '[COLOR_POSITIVE_TEXT]海事[ENDCOLOR]市 - 状態として、彼らはあなたの都市へ[ICON_FOOD]フードをエクスポートします。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_MERCANTILE', '[COLOR_POSITIVE_TEXT]マーカンタイル[ENDCOLOR]市 - 状態として、彼らの市場はあなたの人々にエキゾチック[ICON_HAPPINESS_1]幸福の商品を提供！）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_FRIENDS_RELIGIOUS', '[COLOR_POSITIVE_TEXT]宗教[ENDCOLOR]市ステートとして、彼らはあなたと[ICON_PEACE]信仰の儀式の知識を共有！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_FRIENDS_LOST_BASE', '[ICON_INFLUENCE]への影響は、{1_CivName：テキスト·キー}に[COLOR_POSITIVE_TEXT]友人[ENDCOLOR] ... [NEWLINE] [NEWLINE] {2_DetailsS​​tring}また、あなたのユニットは、もはや持っていないされなくなった時点まで減少した自国の領土内を移動するための権限。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_CULTURE', '（ロスト[ICON_CULTURE]あなたの都市で文化）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_FRIENDS_MILITARISTIC', '彼らはもはやあなたに軍事ユニットを与えないでしょう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_MARITIME', '（ロスト[ICON_FOOD]あなたの都市での食品）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_MERCANTILE', '（ロスト[ICON_HAPPINESS_1]幸福）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_RELIGIOUS', '（ロスト[ICON_PEACE]フェイス）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_BASE', '[ICON_INFLUENCE]への影響は、{2_MinorCivName：テキスト·キー}。あなたは今では[COLOR_POSITIVE_TEXT] ALLY [ENDCOLOR] [NEWLINE] [NEWLINE] {3_DetailsS​​tring} [NEWLINE] [NEWLINE] {1_ResourceDetailsS​​tringある点まで増加している}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_BASE_PASSED', 'として彼らの味方[ENDCOLOR] [NEWLINE] [NEWLINE] {4_DetailsS​​tring} [。：あなたは[COLOR_POSITIVE_TEXT] [テキストキー] [1_CivName]取ってきた点まで増加している：[テキストキー] [3_MinorCivName]上の[ICON_INFLUENCE]影響NL] [NEWLINE] {2_ResourceDetailsS​​tring}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_CULTURE', '[COLOR_POSITIVE_TEXT]文化[ENDCOLOR]市ステートとして、彼らはあなたの街の[ICON_CULTURE]を増加芸術の珍しい作品を、与える。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MILITARISTIC', '[COLOR_POSITIVE_TEXT]軍国[ENDCOLOR]市ステートとして、彼らは定期的にあなたの軍隊を与える。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MARITIME', '[COLOR_POSITIVE_TEXT]海事[ENDCOLOR]市ステートとして、彼らは今あなたの都市への大規模[ICON_FOOD]食品の輸出を行う。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_MERCANTILE', '[COLOR_POSITIVE_TEXT]マーカンタイル[ENDCOLOR]市 - 状態として、彼らの市場はあなたの帝国全体にエキゾチック[ICON_HAPPINESS_1]幸福財の貿易を広める！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_NOW_ALLIES_RELIGIOUS', '[COLOR_POSITIVE_TEXT]宗教[ENDCOLOR]市ステートとして、彼らはあなたに彼らの最も貴重[ICON_PEACE]信仰の遺物を与える！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_ALLIES_LOST', '[ICON_INFLUENCE]への影響は、{1_CivName：テキスト·キー}。次のような彼らの[COLOR_POSITIVE_TEXT] ALLY [ENDCOLOR] [NEWLINE] [NEWLINE] {2_DetailsS​​tring} [NEWLINE] [NEWLINE]不要になった時点まで減少した、彼らはもはやあなたに彼らの戦略や高級資源を付与していない。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_ALLIES_PASSED', '[COLOR_NEGATIVE_TEXT] {1_CivName：テキスト·キー} [ENDCOLOR]今{2_MinorCivName：テキスト·キー}をより[ICON_INFLUENCE]の影響があります！あなたは、それらを[ENDCOLOR]都市国家の[COLOR_NEGATIVE_TEXT]新アリー作るよりは[NL [NEWLINE] {3_DetailsS​​tring} [NEWLINE] [NEWLINE]このように、彼らはもはやあなたに彼らの戦略や高級資源を付与していない。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_MINOR_LOST_ALLIES_MILITARISTIC', '彼らはあなたの軍事に少ない単位貢献していきます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_MARITIME_TT', '助けた[COLOR_POSITIVE_TEXT]海事[ENDCOLOR]都市国家あなたの都市へ[ICON_FOOD]フードを与えるだろう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_TT', '[ICON_INFLUENCE]現在{1_statusType}：{2_statusText} {3_rate}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_INFLUENCE_TT', '[ICON_INFLUENCE]影響：{1_statusType} {2_statusText} {3_rate}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_INFLUENCE_RIVAL_TT', '[ICON_STAR]ライバル（{1_civName}）：{2_statusText} [ICON_INFLUENCE]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_MILITARISTIC_REWARD_TT', '[ICON_STRENGTH]ミリタリー単位：{1_remaining}回転（{2_current} / {3_threshold} {4_rate}）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_GREAT_PERSON_REWARD_TT', '[ICON_GREAT_PEOPLE]グレートパーソン：{1_remaining}回転（{2_current} / {3_threshold} {4_rate}）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_STATUS_TRIBUTE_TT', '[ICON_RESISTANCE]トリビュート：{1_possible}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POSSIBLE', '可能', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOT_POSSIBLE', '不可', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_GIFT_FIRST', 'あなたのような強大な帝国を満たすために喜んで、彼らは[ENDCOLOR] [COLOR_POSITIVE_TEXT] {1_NumGold} [ICON_GOLD]ゴールドのギフトを提供します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_STATE_GIFT_OTHER', 'あなたのような強大な帝国を満たすために喜んで、彼らは[ENDCOLOR] [COLOR_POSITIVE_TEXT] {1_NumGold} [ICON_GOLD]ゴールドのギフトを提供します。', '', '');
/*テックス*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RIFLING_TITLE', '無煙火薬', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RIFLING_DESC', '無煙火薬の発明は、軍の武器と戦術に革命をもたらしました。火薬（黒色火薬と呼ばれる）の古い形態は、固体煤を大量に産生した。この煙は、樽を汚さ正確な射撃を防止し、それが困難な指揮官が戦場ヘイズを通じて受注を与えるために作ら。無煙火薬は、文字通り多くの可動部品の精度、逆子ローディング銃器、およびオートローディング銃器に焦点を当てた戦術への道をクリアしました。', '', '');
/*ユニット*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_WARRIOR', '古代時代の基本的な兵士。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SIAMESE_WARELEPHANT', 'チャンSUEK', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SIAMESE_WARELEPHANT', '槍兵に弱いユニークなシャムユニット。象がないリソースを必要としない、マウントユニットに対するボーナスを受け取り、彼らは交換して騎士団より[ICON_STRENGTH]より多くの強さを持っている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MEDIEVAL_SIAMESEWARELEPHANT_TEXT', '東南アジアでは象がはるか中世に戦争で採用され続けた。サイアムでは、特に、チャンSUEK、または戦争の象が珍重された。三人は、途中で1象を制御するために、第1と背面に1人にそのような鉾、槍や投げ槍などの武器を渡すために、1が戦闘を行うために、首に乗って、それぞれの戦争象に駐留することになる。でも、シャム指導者たちは、確かに、戦争象に王ラムカムヘン王ナレスアン王マハChakkraphat、スリランカSuriyothaiの配偶者は、すべてのチャンSUEKの上に戦ってきたの戦いをで戦うだろう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SIAMESE_WARELEPHANT_STRATEGY', 'これは騎士を置き換え、シャムユニークなユニットです。チャンSUEKユニットは騎士よりも遅いですが、それはより強力です。騎士のようなチャンSUEKは攻撃後に移動することができます。他のマウントのユニットを攻撃する際に槍を装備した、チャンSUEKはかなりの戦闘ボーナスを得る。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CAMEL_ARCHER', 'ファスト中世アラビアユニット。それがあったし、それが取って代わる騎士とは違って、槍兵に対する脆弱性を持っていません。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_CAVALRY', 'ドラグーン', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CAVALRY', '産業革命の強力なマウントユニット。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CATAPULT', 'ゲームの最初の攻城ユニット。都市への大きなダメージを与えますが、台に脆弱であり、焼成前に設定する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_TREBUCHET', '強力な中世の攻城ユニット。都市への大きなダメージを与えますが、台に脆弱であり、焼成前に設定する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CANNON', '強力なルネッサンス時代の攻城ユニット。都市への大きなダメージを与えますが、台に脆弱であり、焼成前に設定する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ARTILLERY', '3タイルを離れて発射することのできるゲームで最初の攻城ユニット。都市への大きなダメージを与えますが、台に脆弱であり、焼成前に設定する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROCKET_ARTILLERY', '移動した後に攻撃することができる高速な攻城ユニット。都市への大きなダメージを与えますが、単位に対して脆弱です。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER', 'Arquebusier', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_HELP', 'ゲームの最初の火薬ユニット。かなり安いと強力。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_STRATEGY', 'Arquebusier、ゲームの最初の火薬ユニットです。それは安価であり、Longswordsmanおよびそれ以前の兵士ユニットとは異なり、鉄を必要としない。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ARQUEBUSIER_PEDIA', '火縄銃は、17世紀に15世紀に使用される初期の銃口仕掛け銃器です。それは、その前身の手の大砲とは異なり、火縄銃を持っています。それは、その後継者のような滑銃器マスケット銃とライフル銃やその他longarm銃器の前身である。[NEWLINE] [NEWLINE]低速火器としては、火縄銃は、多くの場合、部分的または完全に鋼により保護されていた敵に対して使用されたプレートアーマー。胴体の際に着用プレートアーマーは約1400から17世紀半ばまでのヨーロッパの戦闘で標準だった。プレートの良いスーツは通常、長い距離で火縄銃ボールを停止します。しかし、至近距離で、それも重騎兵の鎧を貫通することが可能であった。これは、3四半期板として鎧の使用状況の変化、および歩兵ほとんどのタイプからプ​​レートアーマーの最後に引退につながった。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_WWI_BOMBER', '複葉機', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETMAN', '初期の産業革命の多彩な火薬ユニット。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_MUSKETMAN_STRATEGY', 'Musketmanは初期の産業革命の火薬ユニットであり、それは、古いフット兵士タイプをすべて置き換え -  Longswordsmen、槍兵、などが挙げられる。それが効果的にすべてのターゲットを攻撃することのできる、安価で汎用性があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_LANCER', 'より速く、より強力な騎士よりも単位が取り付けられている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SIPAHI', '騎士より速く、より強力なオスマン帝国に固有のユニットを、取り付けられている。 Sipahiはそれが取って代わるランサーよりも高速と視界範囲を持っている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_NUCLEAR_SUBMARINE', 'ミサイルサブ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_NUCLEAR_SUBMARINE', '定期的な潜水艦を倒しに特化。 3ミサイルを運ぶことができます。ミサイル潜水は駆逐艦、潜水艦、および1タイルの範囲内のユニットは非公開です。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_AIRBASES_HEADING2_BODY', '航空ユニットは、地上と海上ユニットのようにマップを移動しないでください。彼らは、プレイヤーが所有する優しい都市の「ベース」されなければならない。戦闘機や一部の爆撃機は、同様に航空母艦に基づくこ​​とができる。ミサイルユニットは都市、ミサイル潜水艦、ミサイル巡洋艦に基づくこ​​とができる。航空ユニットは、着手することはできません。拡張された海の航海に、彼らは適切な容器で実施しなければならない場合は - 。キャリア、巡洋艦、または核のサブ[NEWLINE] [NEWLINE]対空ユニットやヘリコプターを基にする必要はありません。彼らは、他のユニットのようなマップを移動し、着手することができます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_ALLMISSILES_HEADING4_BODY', 'ミサイルは、プレイヤーが所有する都市に、ミサイル巡洋艦で、ミサイル潜水艦に基づくこ​​とができる。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCMISSILES_HEADING2_BODY', '原爆被害のかなりの量をしながら、核ミサイルは本当に壊滅的です。爆発半径に巻き込ますべてのユニットが破壊され、都市へのダメージはさらに大きくなりますしている。原子爆弾とは違って、核ミサイルは（プレイヤーのオリジナルの資本が、この方法で破壊されない場合がありますので）完全に地図から都市を払拭しても可能である。その名前が示すように、[NEWLINE] [NEWLINE]、核ミサイルは、ミサイルの単位である彼らはミサイル巡洋艦やミサイル潜水艦に駐留することを意味しますが、いない空母。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_ADV_QUEST', 'どのような航空ユニットミサイルサブベースはできますか？', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_HEADING4_BODY', 'ミサイルのサブは、任意のタイプの2ミサイルまで運ぶことができます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AIRPOWER_NUCSUBMARINE_HEADING4_TITLE', 'ミサイルサブ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_MISSLECRUISER_TEXT', 'ミサイル巡洋艦は、空母やミサイル、サブ、近代的な武器の中で最も強力な海軍武器を除いてです。非常に強力な、正確かつ長期であった巡航ミサイルを運ぶし、展開するために設計された、ミサイル巡洋艦は、多くの場合、敵にもミサイル巡洋艦の範囲で知っていたずっと前に、土地や海の上の敵をターゲットにして破壊することができます。タイコンデロガ級のアメリカミサイル巡洋艦は、ほぼ間違いなく面対面、対空、さらに対潜ミサイルの巨大な様々を運ぶことができる122発射管で武装海上最も強力な血管です。また、短い順に入ってくる敵のミサイルや航空機を破壊することができる対空ガトリング式の銃の様々な装備されています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_NUCLEARSUBMARINE_HEADING', 'ミサイルサブ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_MODERN_NUCLEARSUBMARINE_TEXT', 'ミサイル潜水艦はこっそり拡張航海のための海の下に核ミサイルを大量に運ぶために設計された冷戦時代の船、である。これらの巨大な船は、彼らにほぼ無限の航続距離（または限り食べ物が出て保持しているような）を与えて、自分を搭載核である。ミサイル潜水艦は、戦略兵器プラットフォームです。一般的には敵の都市 - 彼らは彼らの目標に到達する前に、世界中の途中で飛ぶことができる大陸間ミサイルを運ぶ。彼らは自分自身の防衛のための魚雷や対空ミサイルを運ぶことができるが、その主な任務は、隠された滞在し、敵との直接の競合を避けるためです。彼らはすべてのコストで生存しなければならない[NEWLINE] [NEWLINE]ミサイル潜水艦が米国の一部を形成し」とソ連の​​「相互確証破壊」の教義：。いずれかの側にスニーク核攻撃、どんなに成功して、他にヒットした場合攻撃でも1敵のサブは、それが同様にそれらを破壊し、勝利すると死の恐ろしい量をダウン雨でし生き残った場合。 1は完全に彼らが絶対的に質問せずに、敵の核潜水艦、飛行機とのICBMの一つ一つを破壊することができることを保証することができない限り、このようにして、教義の状態は、核戦争は勝ち取れないです。 1はM.A.D.を信じているかどうか教義非常識かどうかであるためには、それが実施されて以来、この惑星には核戦争がなかった。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GOLD_HEADING1_BODY', 'ああ、ゴールド！ゴールドは素晴らしいものです。あなたは都市国家の友情を買うために、敵の文明を買収するために、建物や不思議を購入するには、道路網の支払いに、軍隊を構築するためにそれを使用することができます。[NEWLINE]それは "お金は「できることは事実かもしれTあなたが "愛し買うが、それは核ミサイルで武装ミサイルサブを購入することができ、それは悪くはない。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMPUTERS_HELP', 'あなたは[COLOR_POSITIVE_TEXT]ミサイルサブ[ENDCOLOR]、駆逐艦やミサイルをも運ぶことができる他の潜水を除く全てのユニットには見えない船を構築することができます。また、あなたは[COLOR_POSITIVE_TEXT]携帯SAM [ENDCOLOR]、敵機を阻止に特化した高速のユニットを構築することができます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_GUIDED_MISSILE_STRATEGY', '誘導ミサイルは、敵のターゲットを攻撃する際に破壊されたワンショットユニットです。誘導ミサイルは、プレイヤーが所有する優しい都市やミサイルSubまたはミサイル巡洋艦に乗っ基づくことができる。彼らは、「8」の彼らの範囲で敵のユニットや都市をベース又は攻撃するベースから移動することができる。詳細については、ミサイルに関する規則を参照してください。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_NUCLEAR_SUBMARINE_STRATEGY', 'ミサイルサブ産業時代のモデルよりも厳しいと強い。それはあまりにもほとんどのユニットには見えませんし、他の潜水艦を見ることができます。最も重要なのは、ミサイル潜水は誘導ミサイルや核ミサイルを運ぶことができます。潜水艦と同様、原子力潜水は敵の駆逐艦や潜水艦に対して脆弱であるため、海岸がクリアされていることを確認する前に、独自の単位を発送させていただきます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_NUCLEAR_MISSILE', 'あなたの敵の際の核破壊を解き放つ。都市への計り知れないダメージを与えると爆発半径に巻き込ま任意のユニットを破壊する。ミサイル巡洋艦とミサイル潜水に駐留することができる。[NEWLINE] [NEWLINE]マンハッタン計画と2ウラン資源が必要です。', '', '');
/*建物*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_DESC', 'Chinampa', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOATING_GARDENS_STRATEGY', 'Chinampaは水車を置き換え、アステカユニークな建物です。それは都市の食糧出力を増加させ、市は湖や川の近くにある場合に構築する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FLOATING_GARDENS_PEDIA', 'Chinampaは、農業に利用できる土地を高めるために、淡水湖の上に構築小さな人工島である。湖は島を灌漑し、信じられないほどの肥沃な生育環境で、その結果、新鮮な有機物質でそれを提供しています。アステカは、農業のこの形態の巨匠だった、と「ソチミルコの浮遊庭園「今日は有名なままです。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE', '溶鉱炉', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE_STRATEGY', 'ユニットを訓練するとき高炉は、市内の産生を増加させる。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BLAST_FURNACE_PEDIA', '高炉は、一般に、鉄金属を精錬するために使用される。燃料や鉱石を連続空気がチャンバーの底に吹き込まれている間、炉の上部から供給されていますので、材料が下方に移動する際の化学反応は、炉全体で行われている。[NEWLINE] [NEWLINE]高炉がで発明された中国、400紀元前によって当たり前、1500、CEによってヨーロッパに広がる。秦の国が221紀元前に中国を統一した時の鉄は、軍の成功に不可欠であり、この時代の中国の鉄の製錬所は、200以上の男性の平均労働力を採用。 1000年CEによる宋鉄業界は伐採から森林のエーカー数千人を温存、鉄鋼の鋳造に瀝青炭への木炭からのリソースの顕著なスイッチを作った。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH', 'スミス', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH_STRATEGY', 'スミスは、市内の産生を増加させる。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SMITH_PEDIA', 'スミスは鍛冶屋が鉄や鋼、通常、加熱とハンマーで金属を働く場所です。ヒッタイトは、まず1500 BCEのまわり鉄鉱石の精錬を開発しました。彼らは数百年のための鉄生産の知識に近い独占を維持しているように見えるが、その帝国は1200年頃、全方向での知識の広がりの周りの東地中海動乱の際に崩壊したとき。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY', 'ファウンドリ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY_STRATEGY', 'ファウンドリー国立ワンダーが大幅市の産生を増加させる。それは鋳造を構築する前に、文明はその都市の75％で高炉を持っている必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOUNDRY_PEDIA', 'ファウンドリは、金属鋳物の大規模生産のための場所である。金属は、液体にそれらを溶融金属を金型に流し込み、金型材料を除去するか、それが冷却するにつれて金属が固化した後に鋳造により形状に鋳造される。処理された最も一般的な金属は、アルミニウムおよび鋳鉄である。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COFFEE_HOUSE_STRATEGY', 'コー​​ヒーハウスは、ワークショップを置き換え、オーストリアに固有のルネッサンス時代の建物です。これは、[ICON_GREAT_PEOPLE]偉人が25％生成される時に、市の[ICON_PRODUCTION]生産と速度が向上します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_WONDER_PETRA_HELP', '砂漠のタイル1 [ICON_FOOD] [ICON_PRODUCTION] [ICON_GOLD]フード·生産·ゴールド（しかし平野の洪水はない）。', '', '');
/*リソース*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_NATIONAL', '国民幸福', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_NATIONAL_HELP', '国家のために幸せ。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_CITY', '街の幸福', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HAPPINESS_CITY_HELP', 'この都市の人口によって制限幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_IMPORTED', '{1_num}インポート', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_CITYSTATES', '{1_num}から[ICON_CITY_STATE]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_EXPORTED', '{1_num}エクスポートされた', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_USED', '{1_num}に使用され', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RES_SURPLUS', '{1_num}剰余金', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_MOVES', '{1_num} [ICON_MOVES]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_EXPERIENCE', '{1_num} / {2_num} [ICON_WAR]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_HEALTH', '[COLOR_NEGATIVE_TEXT] {1_num} {TXT_KEY_UPANEL_HEALTH} [ENDCOLOR]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOVERINFO_HEALTH_CITY', '{1_num} / {2_num} {TXT_KEY_UPANEL_HEALTH}', '', '');
/*ダメージテキスト*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_ENEMY_UNIT_WITHDRAW', '敵は{@ 1_EnUName}（[COLOR_POSITIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）あなたの{@ 3_UnitName}（[COLOR_NEGATIVE_TEXT] {4_Num} [ENDCOLOR]ダメージ）を攻撃した！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_ENEMY_UNIT_WITHDRAW_CITY', '敵は{@ 1_EnUName}（[COLOR_POSITIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）{@ 3_CityName}（[COLOR_NEGATIVE_TEXT] {4_Num} [ENDCOLOR]ダメージ）のあなたの街を攻撃！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_AIR_UNIT_HURT', 'あなたの{@ 1_UnitName} [COLOR_NEGATIVE_TEXT]敵に[ENDCOLOR]傍受{@ 2_EnUName}でした！ （{3}％ダメージ）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_AIR', 'あなたの{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {3_Num} [ENDCOLOR]ダメージ）敵に衝撃を与えた{@ 2_EnUName}！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_AIR_AND_DEATH', 'あなたの{@ 1_UnitName}は[COLOR_NEGATIVE_TEXT] {2_EnUName] @]！敵に砲撃された後、[ENDCOLOR]破壊されました', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ARE_ATTACKED_BY_CITY', 'あなたの{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {3_Num} [ENDCOLOR]ダメージ）は敵都市によって衝撃された{@ 2_CityName}！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ATTACK_BY_AIR', 'あなたの{@ 1_UnitName}敵を砲撃{@ 2_EnUName}！ （[COLOR_POSITIVE_TEXT] {3_Damage} [ENDCOLOR]ダメージ）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_ATTACK_BY_AIR_AND_DEATH', 'あなたの{@ 1_UnitName}敵を砲撃{@ 2_EnUName}と[COLOR_POSITIVE_TEXT]それは[ENDCOLOR]敗北！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_CITY_WAS_CAPTURED', '守りつつ、あなたの街の{@ 1_CityName} [COLOR_NEGATIVE_TEXT]捕獲された[ENDCOLOR]で{TXT_KEY_GRAMMAR_A_AN << {@ 3_owner_adjective}} {2_EnUName] @]（[COLOR_POSITIVE_TEXT] {4_Num} [ ENDCOLOR]ダメージ）！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_DEFENSES_REDUCED_TO', '{@ 1_CityName} [COLOR_NEGATIVE_TEXT] {2_Num}％[ENDCOLOR]で{TXT_KEY_GRAMMAR_A_AN << {3_UnitName}}！に縮小されてきた中であなたの防御', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_HURT_ENEMY_AIR', 'あなたは{@ 1_UnitName} {TXT_KEY_GRAMMAR_A_AN << {4_owner_adjective}} {2_EnUName] @]傍受！ （[COLOR_POSITIVE_TEXT] {3}％[ENDCOLOR]ダメージ）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_KILLED_ENEMY_UNIT', '守りつつ、あなたの{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）[COLOR_POSITIVE_TEXT] [ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {@ 5_owner_adjective}} {@ 4_EnUName}が死亡！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_KILLED_ENEMY_UNIT_CITY', '、のあなたの街を守りながら{@ 1_CityName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）[COLOR_POSITIVE_TEXT]殺さ[ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {@ 4_owner_adjective}} {3_EnUName] ]！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_REDUCE_CITY_DEFENSES', 'あなたの{@ 1_UnitName}の防御力を減少さ{@ 2_CityName} [COLOR_POSITIVE_TEXT] {3_NewVal}％[ENDCOLOR]へ！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_SHOT_DOWN_ENEMY', 'あなたの{@ 1_UnitName} [COLOR_POSITIVE_TEXT] [ENDCOLOR] {TXT_KEY_GRAMMAR_A_AN << {3_owner_civ}} {@ 2_EnUName}撃墜！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_CAPTURED_ENEMY_CITY', 'あなたの{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）[COLOR_POSITIVE_TEXT] [ENDCOLOR]捕獲の敵·シティ{@ 3_CityName}！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DESTROYED_ENEMY', 'あなたの{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）[COLOR_POSITIVE_TEXT] [ENDCOLOR]敵{@ 3_UnitName}敗北！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DIED_ATTACKING', 'あなたの{@ 1_UnitName} [COLOR_NEGATIVE_TEXT]敵{@ 2_EnUName}（[COLOR_POSITIVE_TEXT] {3_Num} [ENDCOLOR]ダメージを）攻撃する[ENDCOLOR]死んだ！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_DIED_ATTACKING_CITY', 'あなたの{@ 1_UnitName} [COLOR_NEGATIVE_TEXT] {@ 2_EnUName}（[COLOR_POSITIVE_TEXT] {3_Num} [ENDCOLOR]ダメージ）の敵都市を攻撃[ENDCOLOR]死んだ！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_RANSOM_KILL_BY_BARBARIANS', 'あなたが彼らの身代金を支払うことを拒否したため、蛮族は[COLOR_NEGATIVE_TEXT]あなたの{@ 1_UnitName} [ENDCOLOR]殺した！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_SHOT_DOWN', 'あなたの{@ 1_UnitName} [COLOR_NEGATIVE_TEXT]敵に[ENDCOLOR]撃墜された{@ 2_EnUName}！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_SURRENDER', 'あなたの{@ 1_EnUName} [COLOR_NEGATIVE_TEXT] {TXT_KEY_GRAMMAR_A_AN << {@ 2_Adjective}} {@ 3_UnitName}に[ENDCOLOR]投降！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED', '守りつつ、あなたの{@ 1_UnitName}は[COLOR_NEGATIVE_TEXT] {TXT_KEY_GRAMMAR_A_AN << {@ 3_owner_adjective}} {@ 2_EnUName}（[COLOR_POSITIVE_TEXT] {4_Num} [ENDCOLOR]で[ENDCOLOR]破壊されましたダメージ）！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED_UNKNOWN', '守りつつ、あなたの{@ 1_UnitName}は[COLOR_NEGATIVE_TEXT]装った{@ 2_EnUName}（[COLOR_POSITIVE_TEXT] {3_Num} [ENDCOLOR]ダメージ）で[ENDCOLOR]破壊されました！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WAS_DESTROYED_ATTRITION', 'あなたの{@ 1_UnitName} [COLOR_NEGATIVE_TEXT]のスレで[ENDCOLOR]破壊されました！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WITHDRAW', 'あなたは{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）（[COLOR_POSITIVE_TEXT] {4_Num} [ENDCOLOR]ダメージ）[3_EnUName] @ []の敵を攻撃！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOU_UNIT_WITHDRAW_CITY', 'あなたは{@ 1_UnitName}（[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]ダメージ）{@ 3_CityName}（[COLOR_POSITIVE_TEXT] {4_Num} [ENDCOLOR]ダメージ）の敵都市を攻撃！', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOUR_CITY_ATTACKED_BY_AIR', '{@ 1_CityName}（[COLOR_NEGATIVE_TEXT] {3_Num} [ENDCOLOR]ダメージ）{2_EnUName] @]敵に砲撃されました！のあなたの都市', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISC_YOUR_CITY_RANGE_ATTACK', '{@ 1_Name} {@ 2_EnUName}敵を砲撃！ （[COLOR_POSITIVE_TEXT] {3_Damage} [ENDCOLOR]ダメージ）', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
/*その他*/
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_SEA', '海', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_SEA_TEXT', '海', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_LAND', '平坦地', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPECIALTERRAIN_LAND_TEXT', '平坦地', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UPANEL_UNIT_PROMOTED', 'プロモーションをCHOOSE', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NEXT_GOLDEN_AGE_TURN_LABEL', '{1}次の[ICON_GOLDEN_AGE]ゴールデン·エイジまで左ターン', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOGGLE_CLOCK_FORMAT', '12/24時間制を切り替えるをクリックします。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SAVE_DEBUG_OUTPUT', 'lua.logするデバッグ情報を保存', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_BORDER', 'ボーダーのお得な情報', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_RESEARCH', '研究情報', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_DEFENSE', '防衛協定', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DEALS_ALLIANCE', 'アライアンス', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SPECIALIST_GENERAL', '一般', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_OPSCREEN_TOOLTIP_1_TIMER_LENGTH', '地形ツールチップ遅延：{1_Num}秒', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_PROMOTION_DOMAIN', '{1_domain} [NEWLINE] {2_promoHelp}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_DEITY_HELP', '私は宇宙と一人です。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_IMMORTAL_HELP', '私はゾンビの黙示録を生き残る。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_EMPEROR_HELP', '私の限界をテスト。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_KING_HELP', '私に挑戦を与える。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_PRINCE_HELP', '手袋はオフに来ている。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_WARLORD_HELP', '私はリラックスしてみましょう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_CHIEFTAIN_HELP', '私は新しいことを試してみましょう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HANDICAP_SETTLER_HELP', '私は、ゲームを学びましょう。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_POLICY_SAVING', '、ポリシーの保存しない', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_POLICY_SAVING_HELP', '使用可能な場合プレイヤーはすぐに社会政策を選択する必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_CULTURE_CITY_COST', '平和的な拡大は、あなたの政策金利を高速化し、戦争はそれが遅くなります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CANNOT_UNLOCK', '[ICON_LOCKED]このポリシーは、今のロックされています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK', '[ICON_LOCKED]このポリシーツリーは現在、ロックされています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK_CULTURE', '[NEWLINE] [ICON_LOCKED]あなたは{1_Num} [ICON_CULTURE]文化費やす必要。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_CANNOT_UNLOCK_ERA', '[NEWLINE] [ICON_LOCKED]あなたがしている必要{1_EraString：テキスト·キー}。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_UNLOCK_SPEND', '[COLOR_POSITIVE_TEXT]このポリシーツリーがロックを解除することができます！[ENDCOLOR] [NEWLINE] {1_Num} [ICON_CULTURE]文化を費やしてこの社会政策ツリーを開くには、ここをクリックしてください。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_BLOCKED', 'その効果をブロックし、選択した他の支店があるため、[NEWLINE] [ICON_LOCKED]非アクティブ[NEWLINE]切り替えるには、ここをクリックしてください。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_GAINING_HEADING2_BODY', 'あなたは十分なカルチャーポイントを獲得した後、社会政策を採用し、ロックを解除するかを選択することができます：あなたはもう少しコストに続くもので、100カルチャーポイントを獲得後、最初の1が利用可能になります。各ポリシーのコストはより多くのあなたが採用して増加します。あなたが現在持っているどのくらいの文化を参照したとき、次のポリシーが使用可能になります、ステータスバーの文化のアイコンの上にマウスを置く。あなたは文化セクションの文化を利息を計上についての詳細を読むことができ[NEWLINE] [NEWLINE]あなたは十分な文化を持っていたら、通知はあなたのターンに警告を表示します。社会政策のペインを表示するために（横に顧問にあります）右上に社会政策のアイコンをクリックしてください。あなたはターンポリシー]を選択したくない場合、あなたはそれを却下する通知を右クリックすることができる。 （ゲームはしかし、再びあなたを思い出されませんので、これは危険なことができます。）ここでは、新しいブランチを採用またはロック解除ブランチ内に新しいポリシーのロックを解除するかを選択できます。使用可能なすべてのポリシー（としない​​あなたがロックを解除したものだけを）表示するには、ペインの下部にある[詳細表示]トグルをクリックしてください。あなたは文化の必要量を取得しているときに[NEWLINE] [NEWLINE]をクリックしてください探査用に選択されたブランチを開くためのボタン」政策を採用する」 - は、最初に、個々のポリシーのいずれかのロックを解除する前にブランチを採用するポイントを使わなければなりません。各ブランチの採用は、各内の個々の政策が同じ性質のより多くのボーナスを提供すると、すぐにあなたにいくつかの利点が得られます。[NEWLINE] [NEWLINE]いくつかのブランチがロックを解除し、アクティブ同時に、多くの枝が一度だけ使用可能になったことがないかもしれない後の時代に到達しました。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION_HELP', 'バグを回避します（詳細は、右クリックします）。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION', '鉄道の接続', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_CONNECTION_STRATEGY', '通常のゲームでは、首都の人々は、首都の人々との政策や鉄道でのエラーの原因となるバグを取引することはできません。この無料建物は、バグの鉄道の一部を修正した。[NEWLINE] [NEWLINE] {TXT_KEY_PRODUCTION_BUILDING_ALLOWS_WATER_ROUTES_EXTRA}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_NEW_YEAR', '断固たる', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_APRIL_FOOLS', 'ゾンビ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_UFO', 'エイリアン', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_HOLIDAY_HALLOWEEN', '吸血鬼', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PER_TURN', 'ターンごと', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_DEFENSE', '[COLOR_POSITIVE_TEXT]防衛モッズ[ENDCOLOR]：{1}％', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_ACTUAL', '[COLOR_POSITIVE_TEXT]利回り[ENDCOLOR]：{1}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_WITHOUTFEATURE', '{2}：[COLOR_YELLOW] {1} [ENDCOLOR]無し', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PLOT_YIELDS_WITHIMPROVEMENT', '[COLOR_YELLOW]に{1} [ENDCOLOR]：{2}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_VIEW', 'ビュー', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_GOLD', 'AIゴールドハンディキャップ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_PRODUCTION', 'AIの生産ハンディキャップ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_SCIENCE', 'AIサイエンスハンディキャップ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AI_CULTURE', 'AIの文化ハンディキャップ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_GOLD_TILE_MAINT', '{1_Num}道路と鉄道の保守に費やさ。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MISSION_HURRY_PRODUCTION_HELP', '街の現在の努力（300 + 30 * [ICON_CITIZEN]集団）[ICON_PRODUCTION]生産を提供します。それは偉大な人を消費します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_CITIZEN_ALLOCATION', '街のフォーカス', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_SPECIAL_TEXT', '専門家', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_PERTURN_TEXT', '{1_perTurn：番号「＃ "}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_PERTURN_TEXT_NEGATIVE', '{1_perTurn：番号「＃ "}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PRODUCED', '生産', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSUMED', '消費された', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_DISABLE_START_BIAS', 'いいえスタートバイアスません', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_REQUIRES', 'が必要です', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MONUMENT', 'モニュメント', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_MONASTERY', '修道院', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TOPIC_EXPERIENCE', '経験', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_SUBMARINE', '潜水艦ユニット', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_MOUNTED_ARCHER', '取り付けられた射手', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_CIVILIAN', '民間人の単位', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_COMMAND', 'サポートユニット', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_MELEE', '兵士ユニット', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_RECON', 'ヴァンガードユニット', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SUPPLY_REACHED_TOOLTIP', 'あなたの帝国は、{1_Num}陸上軍事ユニットをサポートすることができます。あなたはその制限を超えて[COLOR_NEGATIVE_TEXT] {2_Num} [ENDCOLOR]、[COLOR_NEGATIVE_TEXT] {3_Num}％[ENDCOLOR]で、あなたの都市で土地軍事ユニットの[ICON_PRODUCTION]生産が減少した。である', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRADITION_TITLE', 'ソブリン{1_PlayerName：テキスト·キー}の{2_CivName：テキスト·キー}', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_DEAL_EXPIRED_GPT_FROM_US', '終了している：我々は[ICON_GOLD]ゴールドの[テキストキー] [1_CivName]に毎ターンを提供した取引。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_NOTIFICATION_DEAL_EXPIRED_GPT_TO_US', '買収{1_CivName：テキスト·キー}すべての私たちに向ける提供[ICON_GOLD]金は終了しました。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_SPAIN_CONQUISTADOR_HELP', 'スペインに固有の中世時代のユニット。コンキスタドールはそれが取って代わる騎士とは異なり、2視界範囲や都市に対する違約金がかかりませんしています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', '隣接するモアイあたりの1は[ICON_CULTURE]文化[NEWLINE] 1 [ICON_CULTURE]文化[NEWLINE] [ICON_LOCKED]海岸の隣にある必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', '隣接するモアイあたりの1は[ICON_CULTURE]文化[NEWLINE] 1 [ICON_CULTURE]文化[NEWLINE] [ICON_LOCKED]海岸の隣にある必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', '隣接するモアイあたりの1は[ICON_CULTURE]文化[NEWLINE] 1 [ICON_CULTURE]文化[NEWLINE] [ICON_LOCKED]海岸の隣にある必要があります。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VICEROY', '総督', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VICEROY_HELP', '人形の状態と占有都市を監督。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PUPPET_MODIFIER', 'タウン·ウォッチ', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_PUPPET_MODIFIER_HELP', 'パペット国家を守る。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FREEDOM_FINISHER', '自由フィニッシャー', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAN_BUILD_COURTHOUSE', '裁判所を持つことができます', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAN_BUILD_COURTHOUSE_HELP', 'の裁判所でバニラのバグを回避します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_CAPITAL_TRADE', '資本取引', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_BONUS', '科学ボーナス', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_BONUS_HELP', '各ネットナショナルは1 [ICON_HAPPINESS_1] [ICON_CAPITAL]キャピタルに[ICON_RESEARCH] 1パーセントに変換します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_PENALTY', '科学ボーナス', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_SCIENCE_PENALTY_HELP', '各ネットナショナルは1 [ICON_HAPPINESS_4] [ICON_CAPITAL]キャピタルに[ICON_RESEARCH]に-1％に変換します。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_UNITEDSTATES_TEXT_19', '米国はもはや世界で唯一の超大国ではありません。それは少なくとも、中国とその怪しげなタイトルを共有しています。内部的には、20世紀後半の経済の行き過ぎから回復するのに苦労だけでなく、最終的にはまだそれを見物奴隷と人種差別の幽霊を追放しようとしている。米国はやや疲弊しているが、決して破壊される。それはまだこれからの世紀に不可欠かつ重要な文明であると資源、ドライブと人的資本を持っています。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_LEADERS_HARUN_TEXT_3', 'ハルーンの治世の開始時に、カリフの首都バグダッド、以前のカリフによって設立された新しい都市にいた。市は、多くの美しい建物が芸術、科学と宗教の中心地だった。ハルーンは ''知恵の家」ペルシャ、インド、ギリシア、ローマテキストから科学的な著作を収集、翻訳図書館や研究施設が設立しました。ハルーンバグダッドの下で、おそらく世界で最大かつ最も豊かな都市になってきて、花になる。後でハルーンはラッカの戦略的に重要な都市に彼の政府を動かすだろうが、バグダッドでは（市が1258年に征服し、モンゴル人によって略奪されます）に来て何世紀にもわたって、芸術、科学、商業の偉大な都市残る。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_TERRACE_FARM_TEXT', 'テラス農業バリ、フィリピン、中国、ペルーなど、世界各地で同時に山岳地帯で開発された。これらのスキニーは、通常、どれもこれまで可能でなかった場合、フィールドは、丘や山の辺にカット灌漑水の流れ落ちるのを防止し、耕地のためのスペースを提供して辞任した。特にインカテラス農業の巨匠だったし、場所で彼らのテラスを保持するために大規模な、drystone壁を建てた。テラスの形を構築した後、インカはその後、土地の肥沃度を高め、一定の水とテラスを提供するために、運河や水路のシステムを構築した。古代インカ段丘技術は、現代のペルーの農家が今も彼らの農場でそれらを利用するように成功した。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_BALANCED_TEXT', '[ICON_CITIZEN]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_FOOD_TEXT', '[ICON_FOOD]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_PROD_TEXT', '[ICON_PRODUCTION]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_GOLD_TEXT', '[ICON_GOLD]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_RESEARCH_TEXT', '[ICON_RESEARCH]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_CULTURE_TEXT', '[ICON_CULTURE]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_GREAT_PERSON_TEXT', '[ICON_GREAT_PEOPLE]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_FAITH_TEXT', '[ICON_PEACE]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYVIEW_FOCUS_AVOID_GROWTH_TEXT', '[ICON_LOCKED]', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_YIELD_FROM_CONSTRUCTION', '{1_city} [COLOR_POSITIVE_TEXT] + {2_yield} {3_yieldstring} [ENDCOLOR] {4_building}の構築から得られた。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_TOTAL_HAPPINESS', '国の総[ICON_HAPPINESS_1]幸福レベルは{1_Num}である。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_TOTAL_UNHAPPINESS', '総{1_Icon}国家の不幸レベル{2_Num}である。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_FROM_RESOURCES', 'の少なくとも1つのソースを持っていることから{1_Num}ナショナル幸福：', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_TERRAIN', '地形から{1_Num}市幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_CITIES', '建物からの{1_Num}市幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_MISC_GLOBAL', '未知からの{1_Num}ナショナル幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_POLICIES', '社会政策からの{1_Num}ナショナル幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_BUILDINGS', '建物からの{1_Num}ナショナル幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TP_HAPPINESS_NATURAL_WONDERS', 'ナチュラルワンダーの発見から{1_Num}ナショナル幸福。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CLICK_TO_SELL', '建物を取り壊すためにクリック', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SELL_BUILDING_INFO', 'あなたはこの建物を破壊してもよろしいですか？それは、[NEWLINE] [NEWLINE]（：あなたは1ターンに1つの建物を破壊することがあります）あなたのメンテナンス中のターンに{2_Num} [ICON_GOLD]ゴールドが保存されます', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SAVING', '節約', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITYSTATE_CAPTURE_BONUS', 'シティステイトをキャプチャするアライアンスの40ターンに相当即時報酬を与えます。', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_OPSCREEN_MINUTES_FOR_AUTOSAVES', '自動保存の間隔を分', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GENERIC', '', '', '');
REPLACE INTO Language_JA_JP (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');





UPDATE Loaded File SET Value=1, JA_JP=1 Where Type='Core.sql';