/* The sql commands and text below were formulated in the Armies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=742165834
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_GUN', 'Archers à cheval', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_CIVILIAN', 'Unités civiles', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_COMMAND', 'Les unités d''appui', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_MELEE', 'unités de soldat', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_RESOURCE_COAL_HELP', 'Utilisé par les usines.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_NAVALMELEE', 'navires d''escorte', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_NAVALRANGED', 'Navires ordinaires', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_SUBMARINE', 'Navires chasseurs', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNITCOMBAT_RECON', 'Unités d''avant-garde', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTIONS_SECTION_5', 'Vanguard Promotions', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DUMMY_COAL', '_', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DUMMY_COAL_HELP', 'L''ignorer. Il fonctionne tout simplement autour d''un bug avec les ressources stratégiques dans le jeu (si aucun appareil utilise une ressource, il ne peut pas être échangé).', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_PROMOTION_SAVING', 'Pas de promotion d''économies', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GAME_OPTION_PROMOTION_SAVING_HELP', 'Les joueurs doivent prendre Promotions immédiatement lorsqu''il sera disponible.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_REFUGEES_OPTION', '[] ICON_CITIZEN réfugiés de guerre', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_MARITIME_OPTION', '[ICON_WAR] Citystate Maritime Capturé', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_CULTURAL_OPTION', '[ICON_WAR] Citystate culturel Capturé', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_MILITARISTIC_OPTION', '[ICON_WAR] Capturé militariste Citystate', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_RELIGIOUS_OPTION', '[ICON_WAR] Citystate religieuse Capturé', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_MERCANTILE_OPTION', '[ICON_WAR] Capturé Mercantile Citystate', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CNOTIFICATION_CAPTURED_OTHER_OPTION', '[ICON_WAR] Capturé Autres Citystate', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POPUP_CITY_CAPTURE_INFO', 'Comment traitons-nous la dissidence?', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_PUPPET', 'Miséricorde', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_PUPPET_HELP', 'Éviter les pertes ou destruction. Persistante dissidence réduit votre bonheur par [ICON_HAPPINESS_4] {1}.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_PILLAGE', 'Force', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_PILLAGE_HELP', 'Tuez tous les dissidents, de perdre immédiatement la moitié de la population. Votre bonheur gouttes par [ICON_HAPPINESS_4] {1}.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_RAZE', 'Colère', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CAPTURE_RAZE_HELP', 'Tuer immédiatement la moitié de la population, puis de graver la ville à la terre. Votre bonheur tombe temporairement par [ICON_HAPPINESS_4] {1}, puis récupère lentement que vous raser la ville.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_PARATROOPER', 'Aéroporté', '', '');
/*  Unités  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_CHARIOR_ARCHER', 'Un archer monté rapide qui n''est pas vulnérable à lanciers, contrairement cavaliers.', '', '');
/*  Fantassins  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_HOPLITE', 'Soldat unique pour les Grecs. Hoplites commencent par la promotion Phalanx, contrairement à la Lanciers qu''ils remplacent.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SCOUT', 'Scouts excellent à explorer, et sont utiles comme garnisons de la ville bon marché.', '', '');
/*  Mobile  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_CAVALRY', 'Dragon', '', '');
/*  Navires  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_CARAVEL', 'Carrack', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_RENAISSANCE_CARAVEL_TEXT', 'Carracks étaient le principal navire de guerre européen des années 1400-années 1500. Ils ont été développés pour une utilisation dans l''océan Atlantique, assez pour être stable dans les mers fortes grand, et assez spacieux pour transporter les provisions pour les longs voyages. Les «châteaux» de haut à chaque extrémité ont un avantage de taille pour les archers tirant vers le bas sur les navires ennemis. Ceux-ci remplacent caravelles parce carracks ont été utilisés dans la guerre et d''exploration, tandis que caravelles ont été utilisés uniquement pour l''exploration.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_GALLEY', 'Pirate', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_LIBURNA_PEDIA', 'Ce chasseur léger et rapide était un navire dominante de l''époque classique. Il avait à l''origine un banc avec 25 rames de chaque côté, tandis que des années plus tard, il a été équipé de deux rangs de rames (un BIREME), plus rapide, plus léger, et plus agile que trirèmes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SHIP_OF_THE_LINE', 'Bateau de la ligne', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_SHIP_OF_THE_LINE_PEDIA', 'Le premier changement majeur dans la guerre navale s''est produite dans les années 1600 que le travers est devenu la tactique navale primaire. Expédié formés de longues lignes à fichier unique et sapait la flotte ennemie de loin. C''est ce qu''on appelle une "ligne de bataille." L''avantage de la hauteur donnée par les châteaux de navires ont été presque éliminé, maintenant que le combat au corps-à-corps était moins essentiel. Les châteaux ont diminué, ce qui rend le vaisseau de ligne plus légère et plus maniable, et la coque ont augmenté grand et plus fort. L''expression «ligne de bataille navire" finalement raccourci à "cuirassé".', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_PRIVATEER', 'Galion', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_PRIVATEER_TEXT', 'Galions étaient grandes, voiliers multi-pontés utilisés à partir des années 1500-années 1700, qui a remplacé carracks. Haut gaillard de la caraque progressivement perdu importance à canon remplacé archers pour des attaques navales. Galions invoqué canon orienté vers l''avant pour faire sauter l''ennemi que le navire éperonné un ennemi, suivie par l''embarquement de marins.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIVILOPEDIA_UNITS_RENAISSANCE_IRONCLAD_TEXT', 'Un cuirassé était un navire de guerre à vapeur propulsé au milieu des années 1800, protégé par des plaques de fer ou armure en acier. Le cuirassé a été élaboré à la suite de la vulnérabilité des navires de guerre en bois obus explosifs ou incendiaires. Le premier cuirassé, La Gloire, a été lancé par la marine française en Novembre 1859. [NEWLINE] [NEWLINE] cuirassés ont été conçus pour plusieurs rôles, notamment comme en haute mer, les navires cuirassés de défense côtière, et les croiseurs à long terme. L''évolution rapide de la conception du navire de guerre à la fin du 19ème siècle a transformé le cuirassé d''un navire à coque en bois qui a effectué voiles pour compléter ses machines à vapeur dans l''acier construit, cuirassés et croiseurs familiers au 20ème siècle tourelles. Ce changement a été poussé vers l''avant par le développement des armes lourdes de guerre (les cuirassés des années 1880 réalisées certaines des armes les plus lourdes jamais montés à la mer), les machines à vapeur plus sophistiqués, et les progrès de la métallurgie qui ont fait de la construction navale en acier possible. [NEWLINE] [NL ] Le rythme rapide des changements dans la période à toute épreuve signifiait que de nombreux navires étaient obsolètes dès qu''ils étaient complets, et que les tactiques navales étaient dans un état de flux. Beaucoup de cuirassés ont été construits pour faire usage de la RAM ou la torpille, où un certain nombre de designers navals examiné les armes essentielles de combat naval. Il n''ya pas de fin à la période clairement à toute épreuve, mais vers la fin des années 1890, le cuirassé terme a chuté hors d''usage. Nouveaux navires ont été construits de plus en plus à un modèle standard et cuirassés désignés ou croiseurs cuirassés.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_MISSILE_DESTROYER', 'Missile Destroyer', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_MISSILE_DESTROYER_PEDIA', 'Un destroyer lance-missiles est un destroyer conçu pour lancer des missiles. Beaucoup sont également équipés pour s''acquitter de l''anti-sous-marine, anti-aérienne et des opérations anti-surface. [NEWLINE] [NEWLINE] En plus des armes à feu qui destroyers ont, un destroyer lance-missiles est généralement équipé de deux grands magazines de missiles qui magasin les missiles pour le navire. Certains destroyers lance-missiles contiennent de puissants radars du système d''arme, comme le système de combat Aegis des États-Unis, et peuvent être adoptées pour une utilisation dans un rôle anti-missile balistique ou un rôle de défense antimissile. Cela est particulièrement vrai des marines qui exploitent plus croiseurs, comme d''autres navires doivent être prises pour combler l''écart.', '', '');




UPDATE Loaded File SET Value=1, FR_FR=1 Where Type='Armies.sql';
