/* The sql commands and text below were formulated in the Leaders tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1739820272
If you make any changes be sure to update the spreadsheet also.*/

/*  Caractères  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'Vous obtenez un espion supplémentaire. Grands Généraux voir plus loin et de donner plus de force. [NEWLINE] Commence par un guerrier et la Grande-général.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT_SHORT', 'Attribution', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ALLOTMENT', 'Votre capital gagne une forte exemplaire gratuit de chaque nouvelle ligne de l''unité vous la recherche.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Les unités se déplacent plus vite le long des rivières, et commencent par la promotion amphibie.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', ' 10% [ICON_GREAT_PEOPLE] Grande taux de personnes de chaque Alliance, et 20% [ICON_STRENGTH] Combat vs civilisations avec autres villes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Mêlée et avant-garde unités coûtent 50% moins d''entretien. Toutes les unités doivent 25% moins d''expérience pour gagner leur prochaine promotion.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% de la production [ICON_PRODUCTION] vers des bâtiments qui existent déjà dans la [ICON_CAPITAL] Capital. Commence par [ICON_RES_IRON] Fer dans les 5 premières villes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', 'Récompenses 25% de plus de cités-États amis et alliés.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Hellénisation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', ' 2 Culture [ICON_CULTURE] dans chaque ville. Ville-État [ICON_INFLUENCE] Influence dégrade à moitié et récupère deux fois le taux normal.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Routes commerciales internes donnent 10 [ICON_GOLD] or à la destination.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Les gains Culture [ICON_CULTURE] de tuer les unités ennemies.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', ' 50% [ICON_CULTURE] Culture et +1 [ICON_MOVES] Mouvement cours [ICON_GOLDEN_AGE] âges d''or. [NEWLINE] Commence par un Spearman unique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', ' Une foi [ICON_PEACE] de forêts non aménagées et Jungle, et 150% des rendements de merveilles naturelles. [NEWLINE] Commence par un Spearman.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Unités endommagées battent à pleine puissance. Bateaux de pêche et îles donnent [ICON_CULTURE] Culture.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA_SHORT', 'Gao Milice', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GAO_MILITIA', 'Unités Vanguard voir plus loin et se déplacent plus rapidement.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Les unités se déplacent plus vite sur Hills. Les routes et les chemins de fer coûtent pas d''entretien sur les collines, dont la moitié a coûté ailleurs.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Les civils se déplacent plus rapidement dans le désert. Vos routes commerciales à l''étranger avec les différentes civilisations gagner plus d''or [ICON_GOLD] et [ICON_CULTURE] Culture et routes commerciales entrants gagnent plus [ICON_GOLD] pour le propriétaire de la route.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Un mouvement plus rapide dans les forêts et la jungle, qui comptent que les routes en territoire ami, après des recherches la roue. [NEWLINE] Commence par un épéiste unique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Grands scientifiques apparaissent 25% plus rapide, et vous recevez une à l''écriture. [NEWLINE] Commence par un Bowman.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert caravane', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Les unités se déplacent plus rapidement dans le désert, caravanes atteignent plus loin, et les routes commerciales réparties religion plus rapide de vos villes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'Après avoir étudié la théologie, de recevoir un bonus de Grande-personne à la fin de chaque cycle de calendrier compte Long Maya (tous les 394 ans). [NEWLINE] Commence avec un Archer unique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Chaque augmentation de ressources de luxe [ICON_GOLD] revenu d''or de 5%.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', ' 20% de la production [ICON_PRODUCTION] vers la construction de Wonder.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', ' 30 [ICON_WAR] Expérience pour les navires.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Choisissez une autre croyance que la normale quand vous avez trouvé une religion.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Ports obtenir un port libre, et les unités peuvent traverser des montagnes. Commence par voile, un Bireme, et un guerrier.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Économie planifiée', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Unités voir plus loin, les civils se déplacent plus rapidement, et vous gagnez 1 moins [ICON_HAPPINESS_4] National malheur par ville.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'bâtiments alimentaires ajouter 1 [ICON_CITIZEN] Population lorsqu''ils sont construits. [NEWLINE] Commence par un travailleur.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Camps barbares rendent en cas de défaite pour le double [ICON_GOLD] or. [NEWLINE] Commence par un cheval Archer.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'American Dream', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Les immigrants se déplacent ici des civilisations à faible bonheur et une grande influence culturelle américaine. Vos citoyens migrent le long de [] ICON_FOOD routes commerciales de l''alimentation interne.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Dynastie Joseon', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', ' 2 [ICON_RESEARCH] Sciences de fermes. [NEWLINE] Commence par un travailleur.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Doubler les rendements de merveilles naturelles, plus de 100 [ICON_GOLD] lors de sa découverte. [NEWLINE] commence par un scout, et reçoit un Caravel à Compass.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Ligue hanséatique', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Double quantité de ressources stratégiques, et 3 voix supplémentaires au Congrès mondial.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Vite et plus fort embarquement dans l''eau, et mêlée unités pillent plus rapide.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terreur', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'City-états vous pouvez despote se rendre dans la peur comme des marionnettes. Gendarmerie et les unités escarmouche se déplacer plus rapidement. Commence par un scout.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Hommage', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Routes commerciales internes entre vos villes offrent 10 [ICON_GOLD] or à la destination.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Reconquista', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Conquérir villes augmente votre [ICON_PEACE] foi.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Fléau de Dieu', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Camps barbares rendent en cas de défaite, et les unités terrestres coûtent moins [ICON_GOLD] entretien. [NEWLINE] Commence par un cheval Archer.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD_SHORT', 'Fléau de Dieu', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCOURGE_OF_GOD', 'Camps barbares rendent en cas de défaite, et les unités terrestres coûtent moins [ICON_GOLD] entretien. [NEWLINE] Commence par un char unique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Bourse d''Amsterdam', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', ' 5% [ICON_GOLD] revenu national de chaque type de ressource de luxe que vous contrôlez ou d''importation.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] Un citoyen émigré de {1} et {2}.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] Un immigrant de {1} est arrivé à {2}.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] Un citoyen émigré de {1} et {2}.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'Vous avez gagné {1} {2} {3} de capturer {4}!', '', '');


/*  Unités  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Troupes impériales-Mont-Royal', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Unité de l''ère moderne que seuls les Autrichiens peuvent construire. Il est plus puissant et a ajouté promotions que l''unité régulière ne fait pas.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'Cette unité a des avantages puissants sur tous les terrains de froid. Les combats dans la toundra, neige, collines et montagnes même.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'Les troupes impériales-Mont-Royal (allemand: Kaiserlich-königlich Gebirgstruppe). Été fondée en 1906 dans le cadre de la Landwehr autrichienne, l''armée territoriale de la moitié Cisleithanian de l''Empire austro-hongrois [NEWLINE] proposé dans un mémorandum Conrad von Hötzendorf , en Février 1906, le ministère de la Guerre à Vienne a organisé une session sur la sécurité à la frontière des Alpes. Maréchal Tunk, d''accord avec lui et a présenté un concept, les principes fondamentaux qui ont ensuite été effectués. [NEWLINE] Les régiments existants de fusil de l''Etat devaient être formés comme des troupes de montagne et, de concert avec les sociétés de patrouille frontalière landsturm et les services de gendarmerie étaient pour former l''épine dorsale d''une force de défense territoriale avec des connaissances locales sur la frontière du Tyrol [NEWLINE] [NEWLINE] bataillons et les compagnies ont eu des animaux de meute et ont été émis avec un équipement supplémentaire adapté aux exigences de la guerre de montagne,. notamment skis, des cordes, crampons et piolets. Régiments ont été renforcées par une section de mitrailleuse de montagne de quatre mitrailleuses qui, pour améliorer la mobilité, peuvent être transportées par les animaux de bât ou dans des emballages manportable aux altitudes les plus élevées. Le même s''applique aux canons de montagne démontable. Poêles portables de terrain (Schwarmöfen) et des tentes chauffées ont aidé les troupes de fonctionner dans des conditions inhospitalières. [NEWLINE] Lorsque le ski l''approche en deux bâton avait remplacé la méthode simple bâton. La liaison Bilgeri était une liaison qui peut être utilisé avec la chaussure de randonnée normale tournée. Le fusil a été remplacé par la (courte) 8mm Mannlicher M 95 carabine.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unique Songhaï monté unité. Mandekalu cavalerie commence avec la promotion de siège, contrairement au chevalier qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Puissant soldat médiéval unique pour les Japonais. Samurai peut attaquer deux fois par tour, et sont plus forts que le Longswordsmen qu''ils remplacent.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unité archer babylonien unique. L''archer est plus forte que l''Archer qu''il remplace, et se déplacer plus rapidement dans les déserts.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldat de l''ère médiévale unique au Danemark. Le Berserker commence avec la promotion de charge, contrairement à la Longswordsman qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Unité mobile unique en Allemagne. Le Panzer a une plus grande résistance, la vitesse et la visibilité de la cuve qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', '-Début de match soldat unique pour les Aztèques. La Jaguar guérit dégâts quand il tue un ennemi, et se bat plus efficacement dans la jungle que le guerrier qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard unité unique pour les Américains. Il est plus fort que le tirailleur qu''il remplace, voit plus loin, et se déplace plus rapidement en terrain accidenté.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'L''une des premières unités de la poudre à canon du jeu, unique à la française. Mousquetaires ont un bonus de combat en dehors du territoire ami, contrairement à la Musketman qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldat unique pour les Iroquois. Le guerrier Mohawk bat plus fort dans la forêt et la jungle de l''épéiste qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldat unique pour les Ottomans. Le janissaire est beaucoup plus forte sur l''attaque et guérit après tués, contrairement à la Musketman qu''il remplace.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Unités de 1 tuile [COLOR_POSITIVE_TEXT] Guérir 4 HP supplémentaires [ENDCOLOR] par tour.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'Le remplacement mongol unique pour le Chevalier se déplace plus vite, est varié, et ne partage pas les vulnérabilités du Chevalier de villes ou piquiers. Le Keshik gagne également de l''expérience plus rapidement.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Puissant soldat romain de l''époque classique avec un bonus contre les villes. La Légion a une résistance supérieure à la Swordsman qu''il remplace, défense supplémentaire contre les attaques à distance, et peut construire des routes à deux fois la vitesse de travail.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'Un Liburna était un type de petite cuisine utilisé pour mener des raids et des patrouilles, en particulier par la marine romaine. [NEWLINE] [NEWLINE] Dans sa forme originale, le Liburna avait un banc avec 25 rames de chaque côté, tandis que dans la fin de la République romaine, il a été équipé de deux rangs de rames (un BIREME), restant plus rapide, plus léger, et plus agile que trirèmes. La conception Liburnian a été adopté par les Romains et est devenu un élément clé de la marine antique Rome par la 2e moitié du 1er siècle avant JC. Liburniens joué un rôle clé dans la bataille d''Actium en Grèce, qui a vu la mise en place d''Auguste comme le maître incontesté du monde romain. [NEWLINE] Liburniens étaient différents des galères de combat, quadrirèmes et quinquérèmes pas à cause de l''aviron, mais plutôt à cause de ses caractéristiques particulières de construction. [NEWLINE] [NEWLINE] Une fois que les Romains avaient adopté la Liburnian, ils ont commencé à faire quelques adaptations pour améliorer l''utilisation des navires dans la marine. Les avantages tirés de l''ajout de béliers et de la protection contre les missiles plus confectionnés pour la légère perte de vitesse. Outre la construction, les navires doivent que l''unité militaire romain régulière être simplifiée afin de fonctionner plus en douceur. Chaque navire était exploité comme une entité individuelle, si l''organisation plus compliquée normalement utilisé n''était pas nécessaire. Dans la marine, il y avait probablement Liburnian de plusieurs tailles différentes, tous mis à des tâches spécifiques telles que le dépistage et patrouiller les eaux romains contre la piraterie. Les Romains ont fait usage de la Liburnian en particulier dans les provinces de l''empire, où les navires formaient le gros de la flotte. [NEWLINE] Liburniens Peu à peu est devenu un nom générique pour les différents types de navires romains, joint également aux navires de charge en fin de Antiquité. Tacite et Suétone utilisaient comme synonyme pour le navire de combat. Dans les inscriptions, il a été mentionné que le dernier de la classe des navires de guerre: hexeres, penteres, quadrieres, trières, Liburna.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'Le Liburna est la première unité navale de Rome. C''est une unité de mêlée sans force de combat à distance. Le Liburna est utile pour dégager les navires barbares hors des eaux de la maison et à l''exploration limitée.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Rome a utilisé ces navires pour contrôler les eaux et protéger leurs routes commerciales.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Unité mobile unique et puissant pour l''Inde. Contrairement au Cavalier qu''il remplace, l''éléphant de guerre est varié, ne nécessite pas de chevaux, et n''a pas la vulnérabilité aux Lanciers.', '', '');
/*  Divers  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Bureau de commerce', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Ottoman Hommage', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Culture. [NEWLINE] 1 [ICON_CULTURE] Culture par Moai adjacente. [NEWLINE] [ICON_LOCKED] doit être à côté de la côte.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', ' 3 [ICON_CULTURE] Culture. [NEWLINE] 1 [ICON_CULTURE] Culture par Moai adjacente. [NEWLINE] [ICON_LOCKED] doit être à côté de la côte.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', ' 3 [ICON_CULTURE] Culture. [NEWLINE] 1 [ICON_CULTURE] Culture par Moai adjacente. [NEWLINE] [ICON_LOCKED] doit être à côté de la côte.', '', '');
/*  Bourse d'Amsterdam  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Bourse d''Amsterdam', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'La Bourse d''Amsterdam est considéré comme le plus ancien dans le monde. Il a été établi en 1602 par la Compagnie hollandaise des Indes pour les transactions sur ses actions et les obligations imprimés. Il a ensuite été rebaptisé Bourse d''Amsterdam et a été le premier à commencer officiellement la négociation de titres.', '', '');
/*  Jelling Pierres  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Gélification Pierres', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'Les pierres sont des pierres runiques de Jelling massives sculptées du 10e siècle, trouvé à la ville de Jelling au Danemark. Le plus âgé des deux pierres Jelling a été soulevée par le roi Gorm dans la mémoire de sa femme Thyra. La plus grande des deux pierres ont été recueillis par Harald Bluetooth, le fils du roi Gorm. Harald construit la deuxième pierre en mémoire de ses parents, la célébration de sa conquête du Danemark et de la Norvège, et sa conversion des Danois au christianisme. Les inscriptions runiques sur ces pierres sont considérées comme la plus connue au Danemark.', '', '');
/*  Jade * Hall /
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Temple', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'Roi Sejong a supervisé le développement de la Chiphyonjon, la salle Jade de chercheurs, les chercheurs professionnels qui ont participé à la recherche des questions sociales et politiques pour le roi et le gouvernement. La salle Jade serait considéré comme un "think tank" par les gouvernements aujourd''hui.', '', '');
/*  Indus assainissement  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus assainissement', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'La civilisation de la vallée de l''Indus Indus conçu des systèmes d''assainissement urbains d''abord connu du monde vers 2600 avant notre ère. Maisons individuelles ou des groupes de maisons obtenus l''eau des puits. Les eaux usées a été réalisé à partir de pièces mises de côté pour la baignade des drains couverts qui bordent les rues principales. Les murs massifs de villes harappéens ont spéculé à protéger des inondations. Ces systèmes de génie hydraulique harappéens étaient encore plus efficaces que celles de plusieurs régions du Pakistan et de l''Inde aujourd''hui, la réalisation de grands centres urbains avec relativement peu de développement de l''agriculture.', '', '');
/*  Pioneer  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER', 'Pionnier', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_HELP', 'Fonde de nouvelles villes pour étendre votre empire. [NEWLINE] [NEWLINE] [ICON_FOOD] La croissance de la ville est à l''arrêt alors que cette unité est en cours de construction. [NEWLINE]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_STRATEGY', 'Le Pioneer est une unité unique américain. Il se déplace plus vite que le colon qu''il remplace. [NEWLINE] [NEWLINE] Utilisez cet appareil pour construire de nouvelles villes. Il ne peut pas se défendre, si l''accompagner d''une unité de combat.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AMERICAN_PIONEER_PEDIA', 'Pionniers américains sont l''une des personnes dans l''histoire des États-Unis qui ont émigré à l''ouest de la côte Atlantique pour s''installer et développer de nouveaux domaines. Le terme se réfère en particulier à ceux qui allaient s''installer un nouveau territoire à la société européenne ou américaine, bien que le territoire ait été habitée par ou utilisés par les peuples autochtones. [NEWLINE] [NEWLINE] La notion de pionnier et de l''ethos antérieurs grandement la migration vers les parties des États-Unis maintenant appelé les États «occidentaux», autant d''endroits maintenant considérés comme de l''Est ont également été installés par les pionniers de la côte. Par exemple, Daniel Boone, un personnage clé dans l''histoire de pionnier américain, s''installe dans le Kentucky, où que ''Dark et Rez sanglante »était encore peu développé. [NEWLINE] [NEWLINE] Un développement important dans la colonisation de l''Ouest était le Homestead Act, qui prévoit législation formelle qui réglemente le processus de règlement.', '', '');
/*  Moulin à vapeur  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Moulin à vapeur', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'Une transition a commencé vers les usines en machine à l''économie de la Grande-Bretagne dans les années 1700, déjà tributaires de travail et d''animaux de manuels. Ces précurseurs de la révolution industrielle a commencé avec la mécanisation de l''industrie du textile. L''expansion du commerce a été activée par l''introduction de canaux, de l''amélioration des routes et des voies ferrées. L''utilisation plus large des roues de l''eau et de l''introduction de la machine à vapeur a poussé une augmentation spectaculaire de la capacité de production. Le développement de l''ensemble des métaux machines-outils dans les années 1800 a facilité la construction de machines de production de plus en plus raffinés pour la fabrication d''une grande variété d''industries.', '', '');
/*  Dojo  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'Un dojo japonais («de la place de la voie») est un lieu de rassemblement pour assurer la formation, les examens et autres rencontres connexes pour les arts «faire». Dojos ont d''abord été adjoint aux temples. Au Japon un établissement de formation physique, y compris les écoles de lutte professionnelle, peut être appelé dojo en raison de ses proches racines d''arts martiaux.', '', '');
/*  Sanctuaire  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE', 'Shinto', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JAPANESE_SHRINE_PEDIA', 'Au Japon, les sanctuaires shinto existent côte à côte avec des temples bouddhistes, et sont les plus nombreux, célèbres et importants sites religieux au Japon. Un temple shintoïste est une structure ou d''un objet dont le but principal est d''accueillir un ou plusieurs Shinto kami (esprits, les forces naturelles, ou l''essence). Kami peut résider dans presque rien de naturel ou d''origine humaine, du mont. Fuji à un petit bijou. En tant que tel, ces sanctuaires sont fréquents et varient considérablement dans leur portée. Le sanctuaire lui-même peut être un grand bâtiment ou un petit objet, le long d''une route, ou pourrait même être effectuée par des personnes. [NEWLINE] [NEWLINE] Comme les temples bouddhistes, shintoïstes sont pas principalement un lieu de culte. Bâtiments les plus importants du sanctuaire sont utilisés pour la conservation des objets sacrés. Il ya des bâtiments spécialisés pour certains rites, mais ceux-ci sont généralement ouverts qu''à un nombre limité de participants. Rassemblements de masse religieux dans le style des églises chrétiennes n''ont pas lieu avec une régularité et ne sont pas tenus à l''intérieur du sanctuaire. Si beaucoup de gens sont impliqués dans une cérémonie, on prendra un caractère festif et se tiendra à l''extérieur.', '', '');
/*  Folkskola  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'En 1842, le parlement suédois a introduit une école primaire de quatre ans pour les enfants en Suède, "folkskola" (l''école du peuple). Ce fut l''un des premiers systèmes scolaires publics dans le monde. [NEWLINE] [NEWLINE] enfants suédois sont tenus d''assister à grundskola, l''école obligatoire, de 7 à 16 ans, où grundskola est une combinaison de l''école primaire et secondaire. Après grundskola, beaucoup de Suédois assister à la gymnasieskolan élective, l''enseignement secondaire supérieur, en choisissant soit un programme préuniversitaire ou d''un programme de formation professionnelle. Les étudiants qui choisissent un programme de formation professionnelle se terminent normalement leur scolarité après gymnasieskolan tandis que les étudiants qui suivent un programme de préparation à l''université s''inscrivent normalement dans l''enseignement supérieur dans un collège ou une université. Les étudiants qui terminent un programme de formation professionnelle peuvent s''inscrire dans l''enseignement supérieur, mais peuvent avoir besoin de prendre des cours supplémentaires avant d''être admissibles au programme.', '', '');
/*  Basilique  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Basilique', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'Le mot basilique latine (dérivé du grec Stoa, la chambre du tribunal d''un roi) était à l''origine utilisé pour décrire un bâtiment public romaine située dans le forum de la ville romaine. Par extension, il a été appliqué aux bâtiments chrétiens de la même forme. [NEWLINE] [NEWLINE] Au 4ème siècle, une fois que les autorités impériales ont dépénalisé le christianisme avec le 313 édit de Milan, les chrétiens étaient prêts à construire des édifices plus grands et plus beaux pour culte que les lieux de rencontre furtifs qu''ils utilisaient. Formules architecturales traditionnelles pour les temples n''étaient pas adaptés car des associations ayant des croyances non-chrétiennes. Vieux cérémonies du temple ont eu lieu en plein air sous le ciel ouvert, à la vue des dieux, avec le temple en toile de fond. Le modèle Constantin voulait immortaliser pour sa piété impériale était l''architecture des basiliques (auparavant laïques), la tenue de cérémonies à l''intérieur.', '', '');
/*  Cothon  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'Un cothon (en grec: «récipient à boire») est un port artificiel protégée intérieur commun à Carthage durant la guerres puniques c.200 BCE [NEWLINE] Cothons ont généralement été dans le monde phénicien.. Les exemples incluent Motya (Sicile) à partir du 6ème siècle avant JC, qui a effectué un but incertain, (mesure 35 mètres x 51 mètres), bien qu''il ait été suggéré que cette cothon pourrait même avoir été refermable et vidangeable pour former une cale sèche. Mahdia (Tunisie) à partir du 7ème siècle avant JC, (qui mesurait 72 mètres x 56 mètres) et un de Kition à Chypre.', '', '');
/*  Vedi  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi est le terme pour «modifier» dans la religion védique, la plus ancienne religion encore pratiquée dans les temps modernes. Ces autels sont une enceinte élevée, généralement parsemé de Kusha herbe, et ayant récipients pour le feu sacrificiel.', '', '');
/*  NASA Center  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA Centre', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'Le Centre de la NASA est le centre de recherche de l''ère moderne qui accorde des augmentations de la technologie. Il fournit également une connexion ressources Spaceship usine.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Depuis sa création en 1958, la NASA a accompli de grands exploits scientifiques et technologiques dans l''air et de l''espace. Technologie de la NASA a également été adapté pour de nombreuses utilisations de nonaerospace par le secteur privé. NASA reste une force de premier plan dans la recherche scientifique et à stimuler l''intérêt du public dans l''exploration de l''aérospatiale, ainsi que la science et la technologie en général. Peut-être plus important encore, notre exploration de l''espace nous a appris à voir la Terre, nous-mêmes, et l''univers d''une manière nouvelle. Alors que les réalisations techniques et scientifiques de la NASA montrent d''énormes vivement que les humains peuvent accomplir des exploits inconcevables auparavant, nous sommes aussi une leçon d''humilité par la prise de conscience que la Terre est un tout petit "marbre bleu" dans le cosmos.', '', '');
/*  Abbaye  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Abbaye', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'L''abbaye est au cœur de la pratique du culte, avec l''idée de ne pas mettre tout le monde à un service, mais à offrir des possibilités de culte abbaye adhérents peuvent participer régulièrement, sinon hebdomadaire. Grâce à ses services, les arts ont fleuri comme une expression de louange au «Créateur». En abbayes d''addition ont été auto-support, engagé dans cultiver les champs, l''élevage, l''exploitation des marchés publics, et offrir des possibilités d''emploi à la communauté. Les abbayes celtiques sont devenus les centres d''apprentissage, la préservation des manuscrits sacrés et littéraires, et les écoles d''instruction.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'L''abbaye est le centre spirituel et culturel celtique de chaque communauté. Il produit une [ICON_FOOD] Alimentation [ICON_RESEARCH] Science, [ICON_CULTURE] Culture [ICON_GOLD] or et [ICON_PRODUCTION] production.', '', '');
/*  Odeon  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon, du grec ancien ᾨδεῖον, Ōideion, littéralement «chante lieu", ou "la construction de concours de musique". [NEWLINE] Le plus magnifique odéon était l''Odéon d''Hérode Atticus, sur la falaise sud-ouest de l''Acropole d''Athènes, construite vers 160 AD par le sophiste et rhéteur riche Hérode Atticus en mémoire de son épouse. Il y avait peut accueillir 8000 personnes, et le plafond a été construit de poutres en bois sculpté en bois de cèdre, probablement avec un espace ouvert dans le centre d''admettre la lumière. Il a également été abondamment décoré avec des photos et d''autres œuvres d''art.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'L''Odéon est une source d''instantané [ICON_CULTURE] Culture. Construire les aide à répandre les frontières de votre empire.', '', '');
/*  Barbarie Port  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbarie Port', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'Les pirates barbaresques, parfois appelés corsaires barbaresques ou corsaires ottomans, des pirates et des corsaires qui opéraient à partir de l''Afrique du Nord, basé principalement dans les ports de Tunis, Tripoli et Alger. [NEWLINE] [NEWLINE] Cette région était connue en Europe que la côte de Barbarie , un terme dérivé du nom de ses habitants berbères. [NEWLINE] En plus de la saisie des navires, ils engagés dans des razzias, les raids sur les villes et villages côtiers européens, principalement en Italie, France, Espagne, et du Portugal, mais aussi dans le British Isles, les Pays-Bas et d''aussi loin que l''Islande. Le but principal de leurs attaques était de capturer des esclaves chrétiens pour le marché musulman en Afrique du Nord et le Moyen-Orient.', '', '');
/*  Bassin d'irrigation  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Bassin d''irrigation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Les anciens Egyptiens pratiquaient l''irrigation du bassin de l''aide de la crue du Nil pour inonder les terrains qui avaient été entourés par des digues. L''eau d''inondation a eu lieu jusqu''à ce que le sédiment fertile avait réglé avant l''excédent a été remis au cours d''eau. [NEWLINE] Il existe des preuves de l''ancien pharaon égyptien Amenemhat III à la XIIe dynastie (environ 1800 avant notre ère) en utilisant le lac naturel du Fayoum Oasis comme un réservoir pour stocker les excédents d''eau pour une utilisation pendant les saisons sèches, le lac gonflé chaque année des inondations du Nil.', '', '');





UPDATE Loaded File SET Value=1, FR_FR=1 Where Type='Leaders.sql';




