/* The sql commands and text below were formulated in the Policies tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION', 'Conscription', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CONSCRIPTION_HELP', ' 10 [COLOR_POSITIVE_TEXT] Tarif [ENDCOLOR] guérir.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY', 'Armée de métier', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PROFESSIONAL_ARMY_HELP', 'Débloque les promotions avancées.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM', 'Mercantilisme', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCANTILISM_HELP', ' 2 [ICON_MOVES] Mouvement.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM', 'Liberté', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREEDOM_HELP', ' 25% [ICON_STRENGTH] Force en territoire ami.', '', '');
/*  Liberté  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_LIBERTY_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Culture: +1 dans toutes les villes [NEWLINE] [ICON_PRODUCTION] Production: 1 dans toutes les villes [NEWLINE] [ICON_WORKER] Débloque: Terracotta Armée [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Grande personne: +1 de choix', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLLECTIVE_RULE_HELP', '[ICON_TEAM_2] Settler: Production 1 [NEWLINE] [ICON_PRODUCTION]: 25% pour les colons', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERITOCRACY_HELP', '[ICON_GOLD] Or: 200 x Era [NEWLINE] [ICON_CULTURE] Nouvelles villes augmentent les coûts de 33% moins de politique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CITIZENSHIP_HELP', '[] ICON_TEAM_2 travailleurs: 1 [NEWLINE] [ICON_WORKER] Taux de travailleurs Amélioration: 25%', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPRESENTATION_HELP', '[ICON_HAPPINESS_1] +1 bonheur national par [ICON_CONNECTED] ville connectée. [NEWLINE] [ICON_HAPPINESS_4] -5% malheur de [ICON_CITIZEN] population dans les villes qui ne sont pas [ICON_OCCUPIED] occupés.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_REPUBLIC_HELP', '[ICON_TEAM_9] bâtiment Ville Defense Free dans toutes les villes (en cours, nouvelle, et conquis). Avec la technologie appropriée recherches. [NEWLINE] [ICON_PRODUCTION] une production par City Building Défense.', '', '');
/*  Tradition  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_TRADITION_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Culture: trois dans la capitale [NEWLINE] [ICON_WORKER] Déverrouille: Banaue Rice Terraces [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [ICON_GREAT_PEOPLE] Grande Taux de Personne:. +50% [NEWLINE] [ICON_CULTURE] Doubles extension de frontière culturelle à carreaux loin des villes [NEWLINE] [ICON_PEACE] Possibilité d''acheter des Grands ingénieurs avec la foi à partir de l''ère industrielle.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY', 'Storytellers', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_HELP', '[ICON_CULTURE] Culture: deux par village et le Palais', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ORAL_HISTORY_TEXT', 'La tradition orale est matériel culturel et la tradition transmise oralement d''une génération à l''autre. Les messages ou des témoignages sont transmis oralement dans la parole ou de la chanson et peuvent prendre la forme, par exemple, des contes, dictons, des ballades, des chansons, ou des chants. De cette façon, il est possible pour une société de transmettre l''histoire orale, la littérature orale, le droit verbale et d''autres connaissances à travers les générations sans un système d''écriture.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES', 'Rites de cérémonie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_HELP', '[ICON_CULTURE] Culture: +1 par la culture du bâtiment [NEWLINE] [ICON_CULTURE] 1 Bâtiment culturel gratuit dans vos anciennes 4 villes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CEREMONIAL_RITES_TEXT', 'Une cérémonie est un événement d''importance rituelle exécutée sur une occasion spéciale. Cérémonies peuvent avoir un affichage physique ou composante théâtrale: danse, une procession, l''imposition des mains. Une déclaration verbale déclaratoire peut être associé à l''occasion. [NEWLINE] [NEWLINE] Une cérémonie peut marquer un rite de passage dans une vie humaine, marquant l''importance de naissance, l''âge adulte, l''initiation à un groupe, ou la mort. Parfois, une cérémonie ne peut être effectuée par une personne avec une certaine autorité. cérémonies de la société à l''échelle peuvent marquer des événements annuels ou saisonniers ou récurrents, tels que l''équinoxe de printemps, le solstice d''hiver et d''autres positions astronomiques annuelles.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_LANDED_ELITE_HELP', '[ICON_FOOD] Surplus alimentaire: 25% par la ville [NEWLINE] [ICON_FOOD] Alimentation: deux par ville', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_OLIGARCHY_HELP', '[ICON_RANGE_STRENGTH] Ville Attaque: +50% de garnisons [NEWLINE] [ICON_GOLD] Pas d''entretien pour les unités en garnison.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARISTOCRACY_HELP', '[ICON_PRODUCTION] Production: 15% pour les merveilles [NEWLINE] [ICON_HAPPINESS_1] Bonheur: +1 par 10 [] ICON_CITIZEN citoyens', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MONARCHY_HELP', '[ICON_CITIZEN] Les citoyens de la capitale créent 0,5 [ICON_GOLD] or et 0,5 [ICON_HAPPINESS_1] bonheur.', '', '');
/*  Honneur  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_HONOR_HELP', 'Capacités:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_VIEW_CITY] révèle camps barbares [NEWLINE] [ICON_STRENGTH] 10% de la résistance contre les barbares [NEWLINE] [ICON_CULTURE] barbares Tuer donne 2 Culture par . force d''ennemis vaincus [NEWLINE] [ICON_WORKER] Débloque: Temple d''Artémis [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Ville Bonheur: +1 par Barracks', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_TRADITION_HELP', ' 2 [ICON_TEAM_2] Unités de défense à la capitale. [NEWLINE] 20% de la production [ICON_PRODUCTION] pour les unités militaires et des bâtiments.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR', 'Spoils of War', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_HELP', '[ICON_GOLD] Salvage or de l''équipement des ennemis vaincus. [NEWLINE] [ICON_CITY_STATE] 25% de récompenses de capture City-Unis.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPOILS_OF_WAR_TEXT', 'Pillage par une armée victorieuse pendant la guerre a été une pratique courante dans toute l''histoire enregistrée. Pour fantassins, il a été considéré comme un moyen de compléter leurs revenus souvent maigre et faisait partie de la célébration de la victoire. Sur des niveaux plus élevés, l''exposition fier de butin était une partie intégrante de la victoire romaine typique, et Gengis Khan n''était pas rare en proclamant que le plus grand bonheur était de «vaincre vos ennemis ... à les dépouiller de leurs richesses ..." [NEWLINE] [NEWLINE] Dans la guerre dans les temps anciens, le butin de guerre inclus les populations vaincues, qui ont souvent été réduits à l''esclavage, et les femmes et les enfants, qui sont souvent absorbés dans la population du pays victorieux. Dans d''autres sociétés pré-modernes, objets en métaux précieux ont été la cible préférée de pillage de guerre, en grande partie en raison de leur portabilité facile. Dans de nombreux cas de pillage a été l''occasion d''obtenir des trésors qui, autrement, n''auraient pas été obtenues. Depuis le 18ème siècle, des œuvres d''art de plus en plus devenir une cible populaire. Dans les années 1930 et plus encore pendant la Seconde Guerre mondiale, l''Allemagne nazie engagée à grande échelle et organisé le pillage de l''art et de la propriété.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS', 'Gladiators', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_HELP', '[ICON_HAPPINESS_1] Ville Bonheur: +1 par Arena [NEWLINE] 2 [] ICON_TEAM_2 unités de défense de la capitale..', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GLADIATORS_TEXT', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS', 'Les épopées de guerre', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_HELP', ' 1 [ICON_HAPPINESS_1] Le bonheur de la ville de bâtiments Culture.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WAR_EPICS_TEXT', 'Une épopée (de l''ancien adjectif ἐπικός grec (epikos), de ἔπος (épopée) "mot, histoire, poème") est un récit long poème, habituellement pour un sujet sérieux avec des détails de faits et des événements héroïques importante à une culture ou d''une nation . [NEWLINE] [NEWLINE] épopées de guerre sont des poèmes épiques ou une œuvre littéraire d''envergure épique qui cherchent ou l''on croit saisir et exprimer l''essence ou l''esprit d''une nation particulière, ou un groupe ethnique ou linguistique avec les aspirations à l''indépendance ou l''autonomie. Épopées nationales racontent souvent l''origine d''une nation, d''une partie de son histoire, ou un événement crucial, comme des victoires décisives ou le vainquant des ennemis acharnés, dans le développement de l''identité nationale', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MILITARY_CASTE_HELP', '[ICON_HAPPINESS_1] Ville Bonheur: +1 par Garrison [NEWLINE] [ICON_CULTURE] Culture: deux par Garrison', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DISCIPLINE_HELP', '[ICON_TEAM_7] Grande général: 1 [NEWLINE] [ICON_MOVES] Mouvement:. 1 pour Grands Généraux [NEWLINE] [ICON_STRENGTH] 15% de la résistance pour toutes les unités adjacentes à d''autres unités militaires amies.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] 15% lorsque [COLOR_POSITIVE_TEXT] adjacent [ENDCOLOR] aux unités militaires amies.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROFESSIONAL_ARMY_HELP', '[ICON_GOLD] coût de mise à niveau: -50% pour les unités [NEWLINE] [ICON_PRODUCTION] Production: 15% pour toutes les unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_WARRIOR_CODE_HELP', '[COLOR_POSITIVE_TEXT] Code Warrior [ENDCOLOR] [NEWLINE]', '', '');
/*  Piété  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PIETY_HELP', 'Capacités:. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_CULTURE] Culture 1 [NEWLINE] [ICON_PEACE] Faith 1 [NEWLINE] [ICON_PRODUCTION] Double production pour Sanctuaires [ICON_WORKER] Débloque: Stonehenge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] Choisissez une nouvelle croyance Pieux.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY', 'Charité', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_HELP', '[ICON_GOLD] Or: 25% de temples [NEWLINE] [ICON_GOLD] Or: deux Temples de [NEWLINE] [ICON_GOLD] Or: 3 lieux saints.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CHARITY_PEDIA', 'Le mot «charité» vient du vieux mot français «charité», qui, à son tour, a été dérivé de la "caritas" latine. [NEWLINE] [NEWLINE] La pratique de la charité signifie la remise volontaire de l''aide à ceux dans le besoin qui sont ne sont pas liées au donateur, si la signification originelle est plus impliqué avec les concepts de préciosité, cherté, prix élevé. Les dons de charité se fait directement ou par l''intermédiaire d''une fiducie de bienfaisance ou d''une autre cause. Ces institutions ont évolué pour mener à bien le travail d''aider les pauvres, et sont venus à être appelé, appelé «organismes de bienfaisance». En charités "temps modernes fournissent l''essentiel des dons de bienfaisance, en termes de valeur monétaire. Les types d''organismes de bienfaisance comprennent les orphelinats, les banques alimentaires, les instituts religieux dédiés aux soins des pauvres, les hôpitaux, les organisations qui visitent confinées et emprisonné, et bien d''autres.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION', 'Inspiration', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_HELP', '[ICON_TEAM_7] Gratuit Grand Prophète: +1', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_INSPIRATION_PEDIA', 'Le mot «inspiration» vient du nom latin Inspiratio et de la inspirare verbe. Inspirare est un terme composé résultant du préfixe latin (à l''intérieur, en) et la spirare verbe (à respirer). [NEWLINE] [NEWLINE] A l''époque romaine classique, inspirare avait déjà venu à signifier «à respirer profondément» et assumé également le sens figuré de «inculquer [quelque chose] dans le cœur ou dans l''esprit de quelqu''un". [NEWLINE] [NEWLINE] où «inspiration» se réfère à un éclatement inconscient de la créativité dans une œuvre littéraire, musicale ou autre activité artistique. Le concept a des origines à la fois dans l''hellénisme et l''hébraïsme. Les Grecs croyaient que l''inspiration est venue des muses, ainsi que les dieux Apollon et Dionysos. De même, dans les religions antiques scandinaves, l''inspiration provient des dieux, comme Odin. L''inspiration est aussi une question divine dans la poétique hébreu. Dans le livre de Amosthe prophète parle d''être submergé par la voix de Dieu et contraint de parler. Dans le christianisme, l''inspiration est un don de l''Esprit Saint.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE', 'Tolérance', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_HELP', '[ICON_HAPPINESS_1] Ville Bonheur: +1 par Édifice religieux [NEWLINE] [ICON_PEACE] Villes avec plusieurs religions obtenir aussi le bonus Panthéon de la deuxième religion la plus populaire de la ville.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TOLERANCE_PEDIA', 'Tolérance ou la tolérance est «la pratique de délibérément permettant ou permettant une chose dont on désapprouve. On peut véritablement parler de tolérer, c''est à dire de permettre ou de permettre, que si l''on est en mesure de refuser". Elle a également été défini comme " soutenir ou supporter "ou" pour nourrir, entretenir ou préserver ". tolérance peut signifier« pas plus de patience et de l''autorisation donnée par les adeptes d''une religion dominante pour les autres religions d''exister, même si ceux-ci sont considérés avec réprobation que inférieure, à tort ou nocif »[NEWLINE] [NEWLINE] La tolérance est une attitude d''esprit qui implique l''acceptation non critique de différents modes de vie ou les croyances, alors que la tolérance implique de mettre en place quelque chose que l''on désapprouve. [NEWLINE] [NEWLINE] exemples historiques de la «tolérance» abondent. Par exemple, dans un acte de tolérance, le roi de Perse Cyrus le Grand était censé avoir libéré les Juifs de la captivité de 539 à 530 avant JC, et a permis leur retour dans leur patrie.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY', 'Unité', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_HELP', '[ICON_GOLDEN_AGE] Golden Age Active: 10 [NEWLINE] [ICON_GOLDEN_AGE] Age d''or nécessitent 50% moins [ICON_HAPPINESS_1] Bonheur National', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_UNITY_PEDIA', 'Unité se réfère à des liens dans une société qui unissent les gens les uns aux autres. Le terme est généralement utilisé en sociologie et les autres sciences sociales. [NEWLINE] [NEWLINE] Dans les sociétés simples, il peut être basée principalement autour de la parenté et des valeurs partagées. Dans les sociétés plus complexes, il existe plusieurs théories quant à ce qui contribue à un sentiment de solidarité sociale [NEWLINE] [NEWLINE] Cela porte dans le terme associé de «solidarité» dont il est dit:. [NEWLINE] «Solidarité n''assume pas nos luttes sont les mêmes luttes, ou que notre douleur est la même douleur, ou que notre espoir est le même avenir. solidarité implique un engagement et le travail, ainsi que la reconnaissance du fait que, même si nous n''avons pas les mêmes sentiments, ou les mêmes vies, ni les mêmes organes, nous ne vivons sur un terrain commun ". - Sara Ahmed', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION', 'Méditation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_HELP', '[ICON_PEACE] foi: une Sanctuaires, temples [NEWLINE] [ICON_PEACE] Coûts de la foi: -33%', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MEDITATION_PEDIA', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION', 'Dévotion', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_HELP', 'x', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_DEVOTION_PEDIA', 'Dévotion peut être définie comme: ardent, affection souvent désintéressé et le dévouement, à une personne ou un principe. Culte, de la worthscipe vieil anglais, ce qui signifie le mérite ou la valeur-navire est un acte de dévotion religieuse généralement dirigée vers une divinité. Étroitement liée à la notion de l''amour, la dévotion est souvent souhaité être réciproque avec une certaine forme de bénédiction ou une bénédiction. [NEWLINE] [NEWLINE] Les dévots, comme ceux qui pratiquent la dévotion sont appelés vouloir recevoir ces bénédictions, sont souvent simple d''esprit à le point de fanatisme. Ainsi, alors que la notion de «dévotion» est bénigne, de nombreux exemples historiques de dévotion religieuse sont souvent extrêmes et sanglant, comme les dévots se disputent l''affection de la dévouée avec des écrans plus scandaleux.', '', '');
/*  Richesse  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE', 'Richesse', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_CAP', 'RICHESSE', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_COMMERCE_HEADING', '{TXT}', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COMMERCE_TEXT', 'La richesse est l''abondance de ressources précieuses ou des biens matériels. Le concept de la richesse est importante dans tous les domaines de l''économie, mais le sens de la richesse dépend du contexte et il n''y a aucune définition universellement acceptée. À la richesse, le niveau le plus général est «quelque chose de valeur", qui reflète à la fois la nature subjective de la parole, et l''idée que ce n''est pas un concept fixe ou statique.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_ADV_QUEST', 'Quelle est la politique sociale du patrimoine branche sur?', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_COMMERCE_HEADING3_BODY', 'La branche de la richesse se concentre sur le développement de l''échelle du territoire, avec une offre nationale de [ICON_GOLD] Or créé par les villes de base pour acheter de nouvelles unités et bâtiments dans les villes frontalières sous-développés.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_BODY', 'La branche de la richesse se concentre sur le développement de l''échelle du territoire, avec une offre nationale de [ICON_GOLD] Or créé par les villes de base pour acheter de nouvelles unités et bâtiments dans les villes frontalières sous-développés. Voir les règles sur les politiques sociales pour plus de détails.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_COMMERCE_HEADING4_TITLE', 'La Direction générale de la richesse', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_COMMERCE_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_GOLD] Or: +10% {TXT} [NEWLINE] [] ICON_PRODUCTION production: +10% {TXT} [NEWLINE] [ICON_WORKER] déverrouille : Canal de Panama [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] Bonheur: +1 par marché, Smithy [NEWLINE] [ICON_PEACE] Possibilité d''acheter des Grands commerçants avec la foi en entrant dans l''ère industrielle.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP_OLD', ' 2 [ICON_MOVES] Mouvement pour les unités non-combattantes. [NEWLINE] 25% [ICON_GOLD] revenu de [ICON_CONNECTED] Commerce intérieur. [NEWLINE] -25% Coût [ICON_GOLD] pour les routes et les chemins de fer.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP', '[ICON_GOLD] Or: une par village [NEWLINE] [ICON_PRODUCTION] Production: +1 par mine, Scierie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_UNIONS_HELP', '[ICON_GOLD] Peut acheter lansquenets. [NEWLINE] [ICON_TEAM_2] 2 lansquenets apparaissent à la capitale.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ENTREPRENEURSHIP_HELP', '[ICON_TEAM_7] Gratuit Grande Merchant: 1 [NEWLINE] [ICON_GREAT_PEOPLE] Great Rate marchand: +25% [NEWLINE] [ICON_GREAT_MERCHANT] Double or de Great missions commerciales du commerçant.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS', 'Caravanes', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CARAVANS_HELP', '[ICON_GOLD] Or: 3 par route commerciale', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MARITIME_INFRASTRUCTURE_HELP', '[ICON_PRODUCTION] Production: 4 par ville côtière [NEWLINE] [ICON_GOLD] Or: 4 par Phare, Port, Port maritime', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS', 'Guildes', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_HELP', ' 1 [ICON_TEAM_7] Grande Merchant à la capitale. [NEWLINE] 100% d''or [ICON_GOLD] de Great missions commerciales marchand.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_GUILDS_TEXT', 'Une guilde est une association d''artisans dans un métier particulier. Les premiers types de guilde ont été formés comme des confréries des travailleurs. Ils ont été organisés dans quelque chose de manière entre un syndicat, une entente, et une société secrète. Ils dépendaient souvent de la délivrance de lettres patentes par un monarque ou une autre autorité pour faire appliquer le flux des échanges à leurs membres indépendants, et de conserver la propriété des outils et la fourniture des matériaux.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PROTECTIONISM_HELP_OLD', '-20% [ICON_GOLD] Le coût d''acquisition pour les unités et bâtiments.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW', 'Loi sur les brevets', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_HELP', ' 1 [ICON_GOLD] or de villages. [NEWLINE] 2 Gold [ICON_GOLD] de ports.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PATENT_LAW_TEXT', 'Un brevet est un ensemble de droits exclusifs accordés par un État (gouvernement national) à un inventeur ou leurs cessionnaires pour une période de temps limitée en échange de la divulgation publique d''une invention. [NEWLINE] [NEWLINE] brevets dans le sens moderne origine en 1474, lorsque la République de Venise a adopté un décret que les dispositifs nouveaux et inventifs, une fois mises en pratique, doivent être communiqués à la République pour obtenir le droit d''empêcher les autres de les utiliser. [NEWLINE] [NEWLINE] Angleterre a suivi avec la Statut des monopoles en 1623 sous le roi Jacques Ier, qui a déclaré que les brevets ne peuvent être accordées pour des "projets de nouvelle invention." Pendant le règne de la reine Anne (1702-1714), les avocats de la Cour d''Angleterre ont développé l''exigence d''une description écrite de l''invention doit être présentée. Le système des brevets dans de nombreux autres pays se fonde sur le droit britannique et peut être retracée à la loi sur les monopoles.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCHANT_NAVY_HELP_OLD', ' 1 [ICON_MOVES] mouvements et une vue pour les navires militaires. [NEWLINE] 2 [ICON_RESEARCH] La science pour les villes côtières. [NEWLINE] 2 Science [ICON_RESEARCH] pour les bâtiments de la Marine.', '', '');
/*  Patronage  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_PATRONAGE_HELP', 'Capacités:.. [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_GOLD] 2 or par Cité-Etat commerce Route [NEWLINE] [ICON_VIEW_CITY] Révèle tous Ville-Unis [NEWLINE] [ICON_WORKER] déverrouille : Angkor Wat [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [icon_plus] 100% la quantité de ressource stratégique et 50% [ICON_HAPPINESS_1] National Bonheur des ressources de luxe offert par les alliés Ville-Etat.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PHILANTHROPY_HELP', '[ICON_INFLUENCE] 20 Influence instantanée avec City-Unis. [NEWLINE] [ICON_INFLUENCE] 33% Influence de [] ICON_GOLD cadeaux d''or de la ville-Unis.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP', 'Special Relationship', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_HELP', '[ICON_INFLUENCE] Influence de Ville-Unis se dégrade de 33% plus lent que la normale. [NEWLINE] [ICON_INFLUENCE] L''influence des autres joueurs avec City-Unis en baisse de 10% plus rapide.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SPECIAL_RELATIONSHIP_TEXT', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CONSULATES_HELP', '[ICON_INFLUENCE] 20 influence de repos avec City-Unis.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCHOLASTICISM_HELP', '[ICON_RESEARCH] 2 Sciences par époque pour chaque ami Ville-État, et trois pour chaque allié.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP', '[ICON_GREAT_PEOPLE] ville-État alliés cadeaux des gens formidables. [ICON_GREAT_PEOPLE] 10% Great Rate gens.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT', 'Pacte de commerce', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_HELP', ' 2 [ICON_PRODUCTION] Production par période pour chaque ami Ville-État, et trois pour chaque allié (répartition entre vos villes).', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_TRADE_PACT_TEXT', 'Le libre-échange est un système de politique commerciale qui permet aux opérateurs de commerce à travers les frontières nationales sans ingérence des gouvernements respectifs. En raison du principe économique de l''avantage comparatif, cela donne partenaires commerciaux avec des gains mutuels. En vertu de cette politique des prix sont le seul déterminant de la répartition des ressources, et une réflexion à proximité de l''offre et de la demande.', '', '');
/*  Esthétique  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_AESTHETICS_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_PRODUCTION] 50% la production de bâtiments culturels [NEWLINE] [ICON_WORKER] Débloque:. Uffizi [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR ] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] Révèle sites Antiquités cachés. [NEWLINE] [ICON_TEAM_7] Permet l''achat de la culture des gens super avec [ICON_PEACE] foi en entrant dans l''ère industrielle.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FINE_ARTS_HELP', '[ICON_CULTURE] Culture: +1 par 2 le bonheur de surplus.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_CULTURAL_CENTERS_HELP', '[ICON_CULTURE] Culture: deux par National Wonder [NEWLINE] [ICON_CULTURE] Culture: 33% dans les villes avec une Wonder World', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ARTISTIC_GENIUS_HELP', '[ICON_TEAM_7] Great Artist: 1 [NEWLINE] [ICON_TEAM_7] culturel taux Grande personne: 25%', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FLOURISHING_OF_ARTS_HELP', 'Les archéologues sont produits deux fois plus vite', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_ETHICS_HELP', '[ICON_TOURISM] Doubles renforcement thème du tourisme. [NEWLINE] [ICON_TOURISM] 25% du tourisme de la religion commune, l''ouverture des frontières, et les routes commerciales.', '', '');
/*  Exploration  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_EXPLORATION_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_MOVES] Moves: 2 pour les unités Embarqués [NEWLINE] [ICON_MOVES] Moves: 2 pour Grands Amiraux [NEWLINE] [ICON_SIGHT_SEA] Vue: + 1 pour les navires militaires [NEWLINE] [ICON_WORKER] Débloque: Fort Rouge [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] [ICON_HAPPINESS_1] +2 nationales Bonheur par des ressources de luxe. [NEWLINE] [ICON_TEAM_7] Permet à l''achat de grands amiraux de la foi en entrant dans l''ère industrielle.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_NAVAL_TRADITION_HELP', '[ICON_HAPPINESS_1] Ville Bonheur: +1 par Phare, Port, Port maritime', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_MERCANTILISM_HELP', '[ICON_GOLD] Coût d''achat: -25% pour les bâtiments [NEWLINE] [ICON_GOLD] Entretien: -25% pour les bâtiments', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION', 'Colonisation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_HELP', '[ICON_CITIZEN] Villes commencent par 3 la population. [NEWLINE] [ICON_TEAM_2] 2 colons, deux travailleurs et deux unités de défense apparaissent à la capitale.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COLONIZATION_TEXT', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT', 'Pioneer Esprit', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_HELP', '[ICON_MOVES] +1 mouvement pour les civils. [NEWLINE] [ICON_GOLD] coût de -50% pour les routes. [NEWLINE] [ICON_PRODUCTION] de production 100% pour la construction de ports.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_PIONEER_SPIRIT_TEXT', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT', 'Loi de Homestead', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_HELP', '[ICON_TEAM_9] Villes gagnent niveau gratuit 1 bâtiments.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HOMESTEAD_ACT_TEXT', '(À faire)', '', '');
/*  Connaissance  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM', 'Connaissance', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_CAP', 'CONNAISSANCES', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_POLICY_RATIONALISM_HEADING', '{TXT}', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_TITLE', '{TXT}', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_RATIONALISM_TEXT', 'La connaissance est une connaissance de quelqu''un ou quelque chose, ce qui peut inclure des faits, informations, descriptions, ou des compétences acquises par l''expérience ou l''éducation. Il peut se référer à la compréhension théorique ou pratique d''un sujet. Il peut être connaissance ou une expertise pratique, ou la compréhension théorique du sujet.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_PIETY_HEADING3_BODY', 'Piété augmente le bonheur, la culture et la foi de la civilisation adoption. Piété devient disponible une fois l''ère classique est atteint. C''est un endroit idéal pour acquérir des politiques pour les joueurs qui cherchent à créer ou élargir les religions.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_ADV_QUEST', 'Quelle est la politique sociale de connaissances sur la branche?', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_SOCIALPOLICY_RATIONALISM_HEADING3_BODY', 'La branche des connaissances améliore la capacité de la civilisation à utiliser et générer des sciences, de devenir disponible à l''entrée de l''ère de la Renaissance.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_BODY', 'La branche de connaissance des politiques sociales est pleine de politiques qui peuvent augmenter votre recherche. Cette branche sera disponible à l''époque de la Renaissance. Voir les règles sur les politiques sociales pour plus de détails.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_RATIONALISM_HEADING4_TITLE', 'La Direction générale des connaissances', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_BRANCH_RATIONALISM_HELP', 'Capacités: [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] ouvreur [ENDCOLOR] [NEWLINE] [ICON_TEAM_7] Grand Scientifique: 1 [NEWLINE] [ICON_WORKER] Débloque: Bell Labs [NEWLINE] [NEWLINE] [COLOR_POSITIVE_TEXT] Finisher [ENDCOLOR] [ COLOR_GREY] (terminer toutes les politiques dans cet arbre) [ENDCOLOR] [NEWLINE] +1 instant [ICON_TEAM_5] Technologies. [NEWLINE] [ICON_PEACE] peut acheter grands scientifiques avec [ICON_PEACE] foi une fois que vous entrez dans l''ère industrielle.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SCIENTIFIC_REVOLUTION_HELP', '[] ICON_RESEARCH récompenses de contrat de recherche de 50%.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE', 'Contre-espionnage', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_HELP', '[ICON_SPY] 25% de chances d''attraper des espions ennemis. [NEWLINE] [ICON_SPY] -25% ennemi de l''efficacité de l''espion.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_COUNTERINTELLIGENCE_TEXT', '(À faire)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_HUMANISM_HELP', '[ICON_RESEARCH] Science: +10%, tandis que la nation est [ICON_HAPPINESS_1] heureux', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_FREE_THOUGHT_HELP', '[ICON_RESEARCH] Science: une par village [NEWLINE] [ICON_RESEARCH] Science: 2 par Phare', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLICY_SECULARISM_HELP', '[ICON_RESEARCH] Science: 2 par spécialiste', '', '');







UPDATE Loaded File SET Value=1, FR_FR=1 Where Type='Policies.sql';



