/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/*  PROMOTIONS  */
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] 33% vs [COLOR_POSITIVE_TEXT] Armure [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', 'Puissance Artic', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] plus rapide dans [COLOR_POSITIVE_TEXT] Neige et Tundra [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', 'Je bombardement', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [ENDCOLOR] et [] COLOR_POSITIVE_TEXT mer [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', 'Bombardement II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [ENDCOLOR] et [] COLOR_POSITIVE_TEXT mer [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', 'Bombardement III', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [ENDCOLOR] et [] COLOR_POSITIVE_TEXT mer [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] 6 Plage', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] 6 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] peuvent l''air de balayage pour effacer unités d''interception.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] 33% vs [COLOR_POSITIVE_TEXT] navales [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', 'Attribution', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] 10% de la résistance [NEWLINE] [ICON_GOLD] -100% [COLOR_POSITIVE_TEXT] Coût de mise à niveau [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] dommages pleine attaquer à la mer ou les rivières [NEWLINE] [ICON_STRENGTH] 100% lorsque [COLOR_POSITIVE_TEXT] Embarqué [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[ICON_STRENGTH] 25% Force vs [COLOR_POSITIVE_TEXT] Les unités montées [ENDCOLOR] et [COLOR_POSITIVE_TEXT] Armure [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[ICON_STRENGTH] 25% Force vs [COLOR_POSITIVE_TEXT] Les unités montées [ENDCOLOR] et [COLOR_POSITIVE_TEXT] Armure [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', 'Bonus vs Air (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Air [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] 150% vs [COLOR_POSITIVE_TEXT] Bombers et hélicoptères [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', 'Bonus vs Dragons (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Dragons [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus vs Fighters (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Hélicoptères (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Hélicoptères [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', 'Bonus vs Gendarmerie (10)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] 10% vs mêlée [COLOR_POSITIVE_TEXT] cheval [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', 'Bonus vs Gendarmerie (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] 50% vs mêlée [COLOR_POSITIVE_TEXT] cheval [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', 'Attaque vs sous-marins (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] 25% [COLOR_POSITIVE_TEXT] Attaque [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Les sous-marins [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Réservoirs (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Réservoirs [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', 'Astronomie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] Peut traverser [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', 'Bonus sur Attaque (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] 25% [COLOR_POSITIVE_TEXT] Attaque [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', 'Bonus sur Attaque (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Attaque [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_RANGE_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR] peut attaquer deux fois', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', 'Camaraderie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] 15% lorsque [COLOR_POSITIVE_TEXT] Adjacent [ENDCOLOR] à une unité amie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] Attaques utilisent [COLOR_POSITIVE_TEXT] 1 Action [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] Peut se déplacer à travers [COLOR_POSITIVE_TEXT] Ice [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', 'Bonus vs navires de capitaux (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Battleships [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Missile Cruisers [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Carriers [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] peut transporter [COLOR_POSITIVE_TEXT] 1 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] peut transporter [COLOR_POSITIVE_TEXT] 2 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] peut transporter [COLOR_POSITIVE_TEXT] 3 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] peut transporter [COLOR_POSITIVE_TEXT] 4 [ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] +1 Mouvement [NEWLINE] [ICON_STRENGTH] 20% vs [COLOR_POSITIVE_TEXT] blessés [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] 30% vs [] COLOR_POSITIVE_TEXT unités fortifiées [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', 'Attaque vs Villes (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Attaque [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', 'Bonus vs Villes (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', 'Bonus vs Villes (200)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] 200% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', 'Bonus vs Villes (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] 25% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', 'Merchant Raider I', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes portuaires [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal or égale à 33% des dégâts infligés aux ports', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', 'Merchant Raider II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes portuaires [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal or égale à 33% des dégâts infligés aux ports', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', 'Merchant Raider III', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] Villes portuaires [ENDCOLOR] [NEWLINE] [ICON_GOLD] Steal or égale à 34% des dégâts infligés aux ports', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] 25% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Attaques à Distance [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Attaques à Distance [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', 'Pénalité vs distance (10)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] -10% [COLOR_NEGATIVE_TEXT] Défense [ENDCOLOR] contre tous [COLOR_NEGATIVE_TEXT] Attaques à Distance [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '-10% Vs [COLOR_NEGATIVE_TEXT] à distance [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH] 30% dans le [COLOR_POSITIVE_TEXT] Capital [ENDCOLOR]; prime tombe que l''appareil obtient plus loin', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Pénalité sur la Défense (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50% [COLOR_NEGATIVE_TEXT] Défense [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] Peut embarquer sur [COLOR_POSITIVE_TEXT] Tuiles eau [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 100%, tandis que [COLOR_POSITIVE_TEXT] Embarqué [ENDCOLOR].', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', 'Bonus sur la Défense (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] 25% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', 'Bonus sur la Défense (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', 'Pénalité sur la Défense (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25% [COLOR_NEGATIVE_TEXT] Défense [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', 'Desert Power', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] plus rapide dans [COLOR_POSITIVE_TEXT] Déserts [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] 15% lorsque [COLOR_POSITIVE_TEXT] adjacent [ENDCOLOR] à une unité amie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] balayages aériens [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] 33% [COLOR_POSITIVE_TEXT] balayages aériens [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] 34% [COLOR_POSITIVE_TEXT] balayages aériens [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS_HELP', '[ICON_WORKER] Construit améliorations 100% plus rapide', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS', 'Double vitesse de travail', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] BRUT [ENDCOLOR] terrain (collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] Peut embarquer sur [COLOR_POSITIVE_TEXT] Eau Carrelage [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Entrepris la défense (100)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] 100% lorsque [COLOR_POSITIVE_TEXT] Embarqués [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] une portée de vue lorsque [COLOR_POSITIVE_TEXT] Embarqué [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50% de chance de [COLOR_POSITIVE_TEXT] Esquive [ENDCOLOR] interception', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100% de chance de [COLOR_POSITIVE_TEXT] Esquive [ENDCOLOR] interception', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Mouvement [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] 2 [COLOR_POSITIVE_TEXT] Mouvement [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH] -10% pour [COLOR_POSITIVE_TEXT] unités ennemies adjacentes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', 'First Strike', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT] attaque gratuite [ENDCOLOR] avant le combat', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] 50% lorsque [COLOR_POSITIVE_TEXT] Débordement [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] Tout mouvement utilise [COLOR_PLAYER_ORANGE_TEXT] 1 Action [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Terres étrangères Bonus (20)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', 'Formation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] 35% vs [COLOR_POSITIVE_TEXT] Monté [ENDCOLOR] et [COLOR_POSITIVE_TEXT] Armored [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] 33% vs [COLOR_POSITIVE_TEXT] Les unités montées [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', 'Mises à jour gratuites', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', 'Mises à jour gratuites', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] Gagne expérience 50% plus rapide', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] 15% avec [COLOR_POSITIVE_TEXT] Grande général [ENDCOLOR] en même tuile', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', 'D''or', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '[ICON_GOLDEN_AGE] points de combat Golden Age', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] Améliore l''efficacité au combat de proximité [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] Améliore l''efficacité au combat de proximité [COLOR_POSITIVE_TEXT] Les unités terrestres [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1', 'Guerrilla je', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_1_HELP', '[ICON_STRENGTH] 15% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur Rough Terrain [NEWLINE] [ICON_DETECT] une Sight', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2', 'Guerrilla II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_2_HELP', '[ICON_STRENGTH] 15% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur Rough Terrain', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3', 'Guerrilla III', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GUERRILLA_3_HELP', '[ICON_STRENGTH] 20% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur Rough Terrain', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'AI Handicap je', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] une visibilité [NEWLINE] [ICON_WAR] 10% Expérience [NEWLINE] [ICON_STRENGTH] 10% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] +2 visibilité [NEWLINE] [ICON_WAR] 25% Expérience [NEWLINE] [ICON_STRENGTH] 25% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] +2 visibilité [NEWLINE] [ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] guérit 50 Dommages [ENDCOLOR] quand tue une unité non-Barbare', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] guérir cette unité [ENDCOLOR] 50 HP Cela sera [COLOR_POSITIVE_TEXT] Consommer cette possibilité [ENDCOLOR] pour choisir un Promotion', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', 'Colline Fighter', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] plus rapide dans [COLOR_POSITIVE_TEXT] Hills [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] Territoire Friendly [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', 'Tout Terrain', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] Peut traverser [COLOR_POSITIVE_TEXT] Montagnes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] Ignore les coûts de terrain', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] Peut attaquer [COLOR_POSITIVE_TEXT] sur les obstacles [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] 33% plus fortes [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] 33% plus fortes [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] 34% plus fortes [COLOR_POSITIVE_TEXT] Interceptions [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[ICON_AIR] 20% de chance de [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] avions', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[ICON_AIR] 40% de chance de [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] avions', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[ICON_AIR] 50% de chance de [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] avions', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[ICON_AIR] 100% de chance de [COLOR_POSITIVE_TEXT] Intercept [ENDCOLOR] avions', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', 'Interception', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] 100% de chances d''intercepter [COLOR_POSITIVE_TEXT] Unités Air [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] Ignore les frontières culturelles [NEWLINE] [ICON_DETECT] ne peuvent être vus par des unités avec Sonar ou une tuile loin', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] 33% dans [COLOR_POSITIVE_TEXT] Forêt / Jungle [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', 'Bonus vs Terrain (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] 25% vs [COLOR_POSITIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', 'Bonus vs Terrain (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', 'Pénalité contre terre (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH] -50% vs [COLOR_NEGATIVE_TEXT] Terrain [] ENDCOLOR unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] Attaquer et le déplacement ne l''empêche pas de guérison', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] 10 guérison [ENDCOLOR] pour les unités dans une tuile', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT] 5 guérison [ENDCOLOR] par tour pour les unités de tuiles adjacentes [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] 5 guérison [ENDCOLOR] par tour pour cet appareil lorsque [COLOR_POSITIVE_TEXT] hors du territoire Friendly [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', 'Mercenaire', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50% [COLOR_POSITIVE_TEXT] Coût de mise à niveau [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Mouvement [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] 33% dans [COLOR_POSITIVE_TEXT] Forêt / Jungle [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] 20% de la résistance', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', 'Alpiniste', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] Peut passer [COLOR_POSITIVE_TEXT] Montagnes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Pénalité vs Gendarmerie (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT] Grands Généraux [ENDCOLOR] se déplacent à vitesse de cet appareil si elles commencent le tour [COLOR_POSITIVE_TEXT] empilés [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] doit mettre en place pour attaque à distance', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] 15% [COLOR_POSITIVE_TEXT] Attaque [ENDCOLOR] en territoire ami', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', 'Protection nationale', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty Attaquer les navires (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', 'Naval Recon je', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] une vue [NEWLINE] [ICON_HEAL] peut [COLOR_POSITIVE_TEXT] guérir [ENDCOLOR] territoire en dehors amical', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', 'Naval Recon II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] +1 Mouvement [NEWLINE] [ICON_MOVES] Les tentatives de [COLOR_POSITIVE_TEXT] retirer [ENDCOLOR] de combat corps à corps', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', 'Naval siège', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] 30% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 30% vs [COLOR_POSITIVE_TEXT] Unités fortifiés [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] 1 [COLOR_POSITIVE_TEXT] Mouvement [ENDCOLOR] [NEWLINE] [ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', 'Nouvelle unité', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'Nouvelle unité', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] Impossible de capturer les villes', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', 'Pas de bonus de terrain défensif', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] Pas de bonus de terrain défensif', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] Vous ne pouvez pas entrer dans l''océan profond jusqu''à l''astronomie', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] Vous ne pouvez pas entrer dans l''océan profond', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] 33% dans [COLOR_POSITIVE_TEXT] Territoire Friendly [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] Unité ne peut pas attaquer [COLOR_NEGATIVE_TEXT] unités [ENDCOLOR], seuls les villes', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] peut ne pas attaque de mêlée', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', 'Canal de Panama', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Mouvement des navires', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', 'Parthénon', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] 10% Force de grands généraux et amiraux', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] Vous [COLOR_POSITIVE_TEXT] Parachutage [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '[ICON_HEAL] Soigne 25 Dommages Si élimine une unité', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', 'Phalange', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Monté [ENDCOLOR] et [COLOR_POSITIVE_TEXT] Soldier [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT] Captures [ENDCOLOR] ennemis vaincus [COLOR_POSITIVE_TEXT] navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] 1 [COLOR_POSITIVE_TEXT] Plage [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] peut [COLOR_POSITIVE_TEXT] attaque deux fois [ENDCOLOR] à 90% [ICON_RANGE_STRENGTH] allaient force', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', 'Défense vs distance (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] 50% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] vs [COLOR_POSITIVE_TEXT] Dégâts à distance [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] Peut entrer [COLOR_POSITIVE_TEXT] Territoire Rival [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', 'Je Recon', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] 2 Sight', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', 'Recon II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] +1 Mouvement [NEWLINE] [ICON_MOVES] peut utiliser les routes de l''ennemi', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', 'Recon III', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] Peut parachutage 10 tuiles.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', 'Bonus vs Mer (25)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] 25% vs [COLOR_POSITIVE_TEXT] mer [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', 'Bonus vs Mer (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] mer [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', 'Sonar', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] Peut voir [COLOR_POSITIVE_TEXT] Les sous-marins [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH] 15% dans [COLOR_POSITIVE_TEXT] OUVERT [ENDCOLOR] terrain (pas de collines, des forêts ou Jungle)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] 50% vs [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR] [NEWLINE] [ICON_STRENGTH] 30% vs [COLOR_POSITIVE_TEXT] Unités fortifiés [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', 'Escarmouche', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] Les tentatives de se retirer de la mêlée ou embarqués combat', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] +1 supplémentaire [COLOR_POSITIVE_TEXT] Interception [ENDCOLOR] peut être faite par tour', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] Combat de nature à créer [COLOR_POSITIVE_TEXT] Grands Généraux [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] Combat Très susceptible de créer [COLOR_POSITIVE_TEXT] Grands Généraux [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] attaque +15% [COLOR_POSITIVE_TEXT] Villes [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] 50% vs [] COLOR_POSITIVE_TEXT unités blessés [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] Peut guérir [COLOR_POSITIVE_TEXT] Territoire extérieur Friendly [ENDCOLOR] [NEWLINE] [ICON_HEAL] [COLOR_POSITIVE_TEXT] 20 guérison [ENDCOLOR] par tour', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] 5 [COLOR_POSITIVE_TEXT] guérison [ENDCOLOR] territoire en dehors amical [NEWLINE] [ICON_STRENGTH] 25% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] Unité [COLOR_POSITIVE_TEXT] Guérir Every Turn [ENDCOLOR], même si elle effectue une action [NEWLINE] [ICON_MOVES] Unité tentera de se retirer face à une attaque de mêlée', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', 'Suppression', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] 35% vs [COLOR_POSITIVE_TEXT] Vanguard [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', 'Survivant', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '[ICON_HEAL] 20 [COLOR_POSITIVE_TEXT] guérison [ENDCOLOR] territoire en dehors amical [NEWLINE] [ICON_MOVES] Non Mouvement Coût de pillage', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] une Sight [NEWLINE] [ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navales [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] +1 Mouvement [NEWLINE] [ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navales [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] une Sight [NEWLINE] [ICON_STRENGTH] 15% vs [COLOR_POSITIVE_TEXT] navales [ENDCOLOR] unités', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1', 'Je tranchées', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_1_HELP', '[ICON_STRENGTH] 15% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur terrain ouvert [NEWLINE] [ICON_DETECT] une Sight', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2', 'Tranchées II', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_2_HELP', '[ICON_STRENGTH] 15% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur terrain ouvert', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3', 'Tranchées III', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TRENCHES_3_HELP', '[ICON_STRENGTH] 20% [COLOR_POSITIVE_TEXT] Défense [ENDCOLOR] sur terrain ouvert', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', 'Peut entrer sur le territoire rival sans frontières ouvertes, mais perd 25% de la force religieuse d''origine pour chaque tour, ils finissent sur une telle tuile. Unité est éliminée lorsque la résistance religieuse est 0.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] 30% vs [] COLOR_POSITIVE_TEXT unités fortifiées [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] 100% lorsque [COLOR_POSITIVE_TEXT] Embarqué [ENDCOLOR] [NEWLINE] 1 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR] lorsque [COLOR_POSITIVE_TEXT] Embarqués [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', 'Attaque au sol de pénalité (50)', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[ICON_RANGE_STRENGTH] -50% vs attaque [COLOR_NEGATIVE_TEXT] Rez et navires [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] plus rapide dans [COLOR_POSITIVE_TEXT] Forêts et Jungle [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1 Mouvement', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT] 2 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT] Sight Portée [ENDCOLOR]', '', '');





UPDATE LoadedFile SET Value=1, FR_FR=1 Where Type='Promotions.sql';

