/* The sql commands and text below were formulated in the Research tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=1194171600
If you make any changes be sure to update the spreadsheet also.*/

REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING', 'Formation', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_PEDIA', 'La formation militaire est un processus qui établit et améliorer les capacités du personnel militaire. L''éducation militaire peut être devoir volontaire ou obligatoire. [NEWLINE] la formation de recrues tente d''enseigner l''information de base et de la formation dans les techniques nécessaires pour être un membre efficace de services. Pour ce faire, les membres du service sont percés physiquement, techniquement et psychologiquement. [NEWLINE] Après avoir terminé la formation de base, de nombreux membres de service suivent une formation avancée, plus en ligne avec leurs spécialités choisies ou attribuées. Dans la formation de pointe, la technologie et d''équipements militaires est souvent enseignées.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRAINING_QUOTE', '[NEWLINE] [TAB] [TAB] "La conscription si nécessaire, mais pas nécessairement la conscription." [NEWLINE] [TAB] [TAB] - William Lyon Mackenzie King [NEWLINE]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE', 'Sciences politiques', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_PEDIA', 'Au cours de la Renaissance italienne, Niccolò Machiavelli établi l''accent de la science politique moderne sur l''observation empirique directe des institutions et des acteurs politiques. [NEWLINE] [NEWLINE] philosophes tard européens comme Voltaire, Rousseau, Thomas Hobbes et John Locke principes appliqués dans les sciences de la matière à la société dans son ensemble, en créant les sciences sociales. Ces ouvert la voie à des politiques qui a souligné un contrat social entre gouvernants et gouvernés, la nécessité d''une séparation de l''Église et de l''État, et la diminution progressive du droit divin des rois.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_POLITICAL_SCIENCE_QUOTE', '[NEWLINE] [TAB] [TAB] "La politique n''ont aucun rapport avec la morale." [NEWLINE] [TAB] [TAB] - Niccolo Machiavelli [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_TITLE', 'Commerce', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_DESC', 'Commerce origine avec le début de la communication dans les temps préhistoriques. Il a stimulé la curiosité commune, l''ingéniosité et l''apprentissage des langues. En tant que tel, le commerce et la spécialisation qu''il a engendré a été crédité d''accélérer la croissance de la conscience humaine et le triomphe de l''homme sur les espèces de Néandertal. [NEWLINE] [NEWLINE] Il existe des preuves de l''échange d''obsidienne et de silex au cours de l''âge de pierre. Egypte négociés pour les matériaux utilisés pour la création de bijoux depuis 3000 avant notre ère. Routes commerciales à long terme sont apparus lorsque les Sumériens en Mésopotamie négociés avec la civilisation Harappa de la vallée de l''Indus. Les Phéniciens - ont noté les commerçants de la mer - voyage à travers la mer Méditerranée, et aussi loin au nord que la Grande-Bretagne pour les sources d''étain pour fabriquer le bronze. Ils ont établi le commerce colonies les Grecs appelaient emporia. [NEWLINE] [NEWLINE] Le commerce a continué à conduire la tendance humaine à explorer longtemps après la disparition des anciens empires maritimes de la Méditerranée. Longue distance propagation de commerce encore plus loin avec un énorme flotte de Zheng He, qui a atteint l''Inde, de l''Arabie et de l''Afrique de l''Est avant que Christophe Colomb a traversé l''océan.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_TRADE_QUOTE', '[NEWLINE] [TAB] [TAB] "Aucune raison existe aujourd''hui d''écarter la présence ou l''impact potentiel de l''économie dans l''aube pré-historique de l''humanité." [NEWLINE] [TAB] [TAB] - Jason Shogren [NEWLINE] [ TAB]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_DIPLO_NEED_WRITING_TT', '[NEWLINE] [NEWLINE] Aucun joueur n''a pas encore la technologie pour échanger cet objet (commerce).', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS', 'Carvel coques', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_PEDIA', 'Conception Carvel du navire était l''un des développements importants qui ont permis la domination des puissances navales d''Europe occidentale de 1400 à nos jours. Les planches de bois dans des coques de Carvel s''alignent les uns contre les autres, bord à bord, au lieu de la conception de la planche de recouvrement des coques de clinker. Cette conception de la coque fort soutient des navires et des voiles beaucoup plus grandes.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_CARVEL_HULLS_QUOTE', '[NEWLINE] [TAB] [TAB] "Un bateau est sûr dans le port, mais ce n''est pas ce que les navires sont pour." [NEWLINE] [TAB] [TAB] - William Shedd [NEWLINE]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_TITLE', 'Médias de masse', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_DESC', 'Le terme «médias de masse» a été inventé dans les années 1920 avec l''avènement de la radio, mais l''idée de médias pour une grande consommation d''audience a été autour depuis les drames et les jeux de l''Ancien Monde. Les médias de masse a été directement pilotée par la technologie, avec des progrès plus importants dans les techniques d''édition et de communication menant à même un plus vaste public possible atteints. [NEWLINE] [NEWLINE] À l''origine seulement appliquée aux dispositifs de communication tels que la radio, les journaux et les magazines, les médias de masse englobe maintenant télévision, films, musique, livres de poche, les jeux vidéo et Internet. Avec l''avènement de ces types de médias globe-enjambement s''est également posée la capacité à atteindre les masses comme jamais auparavant, et pas toujours dans le bon sens. La tentative de polarisation ou de contrôle de grandes quantités d''informations, que ce soit par le biais de la propagande nefariously esprit ou opinions personnelles plus innocents injectés dans les faits, est en train de devenir un grand problème pour certains gouvernements et organisations à traiter. Techniques publicitaires envahissantes sont aussi un sous-produit des médias, au grand dam des consommateurs partout dans le monde. Alors que le message peut être utile et il est de plus en plus facile pour le commun des mortels de publier leurs idées et leurs œuvres, se faire entendre dans la sortie torrentielle d''informations désormais disponibles peut vraiment être comme chercher que proverbiale aiguille dans une botte de foin.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_MEDIA_QUOTE', '[NEWLINE] [TAB] [TAB] "La vitesse de communication est merveilleuse à voir Il est vrai aussi que la vitesse peut multiplier la diffusion de l''information que nous savons être faux.". [NEWLINE] [TAB] [TAB] - Édouard R. Murrow [NEWLINE] [TAB] [TAB] [TAB]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_TITLE', 'Production en série', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_DESC', 'Production de masse moderne est la construction de grandes quantités de produits standardisés sur les lignes d''assemblage. Ingrédients importants pour la production de masse sont les machines-outils industriels, des pièces interchangeables, la gestion scientifique, et de l''électricité. [NEWLINE] [NEWLINE] La production de masse a été popularisé dans les années 1910 et 1920 par Ford Motor Company de Henry Ford, qui a introduit des moteurs électriques pour le bien- technique connue de la chaîne ou la production séquentielle. Ford a également acheté ou conçu et construit ad hoc des machines-outils et des accessoires. Toutes ces machines-outils ont été disposés de manière systématique dans le flux de production. La direction de Ford a effectué des études de temps et des expériences à mécaniser leurs procédés de l''usine, en se concentrant sur la réduction des mouvements de travailleurs.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_MASS_PRODUCTION_QUOTE', '[NEWLINE] [TAB] [TAB] "Il ya une règle pour l''industriel et qui est:. Faire la meilleure qualité de produits possibles au coût le plus bas possible, en payant les salaires les plus élevés possibles" [NEWLINE] [TAB] [TAB] - Henry Ford [NEWLINE] [TAB]', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_TITLE', 'Ion Propulsion', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_DESC', 'La propulsion de choix pour les auteurs de science-fiction est devenue la propulsion de choix pour les scientifiques et les ingénieurs de la NASA. L''utilisation efficace du système de propulsion ionique de carburant et la puissance électrique permettent vaisseau moderne de voyager loin, plus vite et moins cher que toute autre technologie de propulsion actuellement disponible. Propulseurs ioniques sont actuellement utilisés pour maintien à poste des satellites de communication et pour la propulsion principale sur sondes spatiales. Propulseurs ioniques expulser ions pour créer la poussée et peuvent fournir des vitesses de haut de l''engin spatial plus élevés que tout autre fusée actuellement disponible. [NEWLINE] Un ion est simplement un atome ou une molécule qui est chargé électriquement. Dans un propulseur ionique, les ions sont accélérés par des forces électrostatiques. Les champs électriques utilisés pour l''accélération sont générés par des électrodes placées à l''extrémité aval du propulseur. [NEWLINE] propulseurs ioniques modernes utilisent des gaz inertes pour propulseur. La majorité des propulseurs utiliser le xénon, qui est chimiquement inerte, incolore, inodore et sans saveur. Le gaz propulseur est injecté à partir de l''extrémité aval du propulseur et s''écoule vers l''extrémité en amont.', '', '');
REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TECH_ION_PROPULSION_QUOTE', '[NEWLINE] [TAB] [TAB] "Toutes les civilisations deviennent soit des activités spatiales ou éteint." [NEWLINE] [TAB] [TAB] - Carl Sagan [NEWLINE] [TAB]', '', '');




UPDATE Loaded File SET Value=1, FR_FR=1 Where Type='Research.sql';





