--· EN_US/TW_BuildingStats.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-27'), 'TXT_KEY_TOOLTIP_GOOD_FOR', 'Good for:', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-27'), 'TXT_KEY_TOOLTIP_ABILITIES', 'Abilities:', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-27'), 'TXT_KEY_TOOLTIP_REQUIREMENTS', 'Requirements:', '', '');
/* Units */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_MAINTENANCE', '[ICON_GOLD] Maintenance: {1_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_HURRY_COST_MODIFIER', '[ICON_GOLD] Purchase: {1_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HURRY_COST_MODIFIER', '[ICON_GOLD] Purchase: {3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_CATEGORY', '[ICON_BULLET] Category: {1_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_FOUND', '[ICON_TRADE] Founds Cities to expand your empire.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_FOOD', '[ICON_BULLET] Builds faster in high-growth cities by turning [ICON_FOOD] Food into [ICON_PRODUCTION] Production.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_WORK_RATE', '[ICON_WORKER] Improvement Rate: {1_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_OBSOLETE_TECH', '[ICON_PIRATE] Obsolete: {1_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_CARGO', '[ICON_AIR] Carries: {1_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_SUICIDE', '[ICON_PIRATE] One Shot', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_UNIT_NUKE_RADIUS', '[ICON_RES_URANIUM] [COLOR_POSITIVE_TEXT]Nuke Radius: {1_value}[ENDCOLOR]', '', '');
/* Buildings */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_COST', '[ICON_PRODUCTION] Cost: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NUM_CITY_COST_MOD', '[ICON_PRODUCTION] Cost: {2_sign}{3_value} for each city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_POP_COST_MOD', '[ICON_PRODUCTION] Cost per [ICON_CITIZEN] Citizen: {2_sign}{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GOLD_MAINTENANCE', '[ICON_GOLD] Maintenance: {3_value}', '', '');
/*  Yields  */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_IN_ALL_CITIES', 'in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_MILITARY_UNITS', 'Military Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_INSTANT', '{1_prefix} Instantly: {2_sign}{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_CHANGE', '{1_prefix}: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_CHANGE_FROM', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD', '{1_prefix}: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_FOR', '{1_prefix}: {2_sign}{3_value}% for {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_MILITARY', '{1_prefix}: {2_sign}{3_value}% for Military Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_DOMAIN', '{1_prefix}: {2_sign}{3_value}% for {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_COMBAT', '{1_prefix}: {2_sign}{3_value}% for {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_BUILDING', '{1_prefix}: {2_sign}{3_value}% for Buildings', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_WONDER', '{1_prefix}: {2_sign}{3_value}% for Wonders', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_SPACE', '{1_prefix}: {2_sign}{3_value}% for Spaceship Parts', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_SURPLUS', '{1_prefix} Surplus: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_FROM_BUILDINGS', '{1_prefix}: {2_sign}{3_value}% {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_IN_ALL_CITIES', '{1_prefix}: {2_sign}{3_value}% {TXT_KEY_IN_ALL_CITIES}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_STORAGE', '{1_prefix} Stored: {3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_PER_POP', '{1_prefix} per [ICON_CITIZEN] Citizen: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_LAKES', '{1_prefix}: {3_value} Lake Tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_SEA', '{1_prefix}: {3_value} Sea Tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RIVERS', '{1_prefix}: {3_value} River Tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_PLOTS', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_TERRAIN', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_FEATURES', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RESOURCES', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_RELIGION', '{1_prefix}: {3_value} {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_TECH', '{1_prefix}: {3_value} with {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_SPECIALISTS', '{1_prefix}: {3_value} {4_extra} in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_BUILDINGS', '{1_prefix}: {3_value} for {4_extra}s', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_FROM_USING_GREAT_PEOPLE', '{1_prefix} from using Great People: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_YIELD_MOD_HURRY', '{1_prefix} Costs: {2_sign}{3_value}% in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MEDIAN_TECH_PERCENT_CHANGE', '[ICON_RESEARCH] Research Agreement Reward: {2_sign}{3_value}%', '', '');
/* Other */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_SPECIALIST_TYPE', '{1_prefix}: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_SPECIALIST_POINTS', '{1_prefix}: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GREAT_PERSON_POINTS', '{1_prefix} Great {4_extra} Points: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GREAT_PEOPLE_RATE_MODIFIER', '[ICON_GREAT_PEOPLE] Great People Rate: {3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_GREAT_PEOPLE_RATE_MODIFIER', '[ICON_GREAT_PEOPLE] Great People Rate: {3_value}% in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_UNMODDED_HAPPINESS', '[ICON_HAPPINESS_1] National Happiness: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HAPPINESS', '[ICON_HAPPINESS_1] City Happiness: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HAPPINESS_FOOT', 'A city cannot create more [ICON_HAPPINESS_1] City Happiness than its [ICON_CITIZEN] Population.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HAPPINESS_PER_CITY', '[ICON_HAPPINESS_1] City Happiness: {3_value} in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HAPPINESS_PER_X_POLICIES', '[ICON_HAPPINESS_1] National Happiness: 1 per {3_value} Policies', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_UNHAPPINESS_MODIFIER', '{2_sign}{3_value}% [ICON_HAPPINESS_4] Unhappiness from [ICON_CITIZEN] Population in non-occupied Cities.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NO_OCCUPIED_UNHAPPINESS', '[ICON_OCCUPIED] Ends Occupation in this City', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NO_OCCUPIED_UNHAPPINESS_FOOT', '[ICON_OCCUPIED] Occupied and [ICON_PUPPET] Puppet cities have -25% lower yields than a normal city.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_DEFENSE', '[ICON_STRENGTH] Defense: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_DEFENSE_MOD', '[ICON_STRENGTH] Defense: {3_value}% in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXPERIENCE', '[ICON_WAR] Experience: {3_value} for all Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-28'), 'TXT_KEY_BUILDING_EFFECT_EXPERIENCE_DOMAIN', '[ICON_WAR] Experience: {3_value} for {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXPERIENCE_COMBAT', '[ICON_WAR] Experience: {3_value} for {4_extra}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_EXPERIENCE', '[ICON_WAR] Experience: {3_value} in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXPERIENCE_PER_TURN', '[ICON_WAR] Experience: {3_value} per turn in this City', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_PROMOTION', '{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_PROMOTION_ALL_COMBAT_UNITS', '{3_value} (All Units)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_TRAINED_FREE_PROMOTION', '{3_value} (Units Trained Here)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_UNITS', '[ICON_TEAM_2] Free {4_extra}: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_GREAT_PERSON', '[ICON_TEAM_7] Free {4_extra}: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_GREAT_PEOPLE', '[ICON_TEAM_7] Free Great People: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CAPITAL', '[ICON_CAPITAL] Capital City', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CAPITAL_FOOT', '{TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES_FOOT}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE', '[ICON_GOLDEN_AGE] Starts a Golden Age', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MAP_CENTERING', '[ICON_BULLET] Centers the World Map', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES', '[ICON_CONNECTED] Connects water to roads and railroads', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ALLOWS_WATER_ROUTES_FOOT', 'A [ICON_CONNECTED] connection of roads, railroads, or water to the Capital provides [ICON_GOLD] Gold.[NEWLINE][NEWLINE]A [ICON_CONNECTED_RAILROAD] connection of railroads or water to the Capital provides +25% [ICON_PRODUCTION] Production (with [COLOR_POSITIVE_TEXT]Railroads[ENDCOLOR] technology).[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Harbors[ENDCOLOR] connect water to roads and railroads.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXTRA_LUXURIES', '[ICON_CONNECTED] Doubles supply of luxuries near the city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_DIPLOMATIC_VOTING', '[ICON_FLOWER] [COLOR_POSITIVE_TEXT]Triggers voting for Diplomatic Victory![/COLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GREAT_GENERAL_RATE_MODIFIER', '[ICON_WAR] Great General Rate: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE_MODIFIER', '[ICON_GOLDEN_AGE] Golden Ages: {2_sign}{3_value}% duration', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_UNIT_UPGRADE_COST_MOD', '[ICON_GOLD] Upgrade Cost: {2_sign}{3_value}% for all Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CITY_COUNT_UNHAPPINESS_MOD', '[ICON_HAPPINESS_4] {2_sign}{3_value}% Unhappiness from number of Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_WORKER_SPEED_MODIFIER', '[ICON_WORKER] Worker Improvement Speed: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CITY_CONNECTION_TRADE_ROUTE_MODIFIER', '[ICON_GOLD] Gold from [ICON_CONNECTED] City Connections: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CAPTURE_PLUNDER_MODIFIER', '[ICON_RESISTANCE] Enemies plunder extra gold: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_POLICY_COST_MODIFIER', '[ICON_CULTURE] Culture Cost of Policies: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_PLOT_CULTURE_COST_MODIFIER', '[ICON_CULTURE] Border Expansion Cost: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_PLOT_CULTURE_COST_MODIFIER', '[ICON_CULTURE] Border Expansion Cost: {2_sign}{3_value}% in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_PLOT_BUY_COST_MODIFIER', '[ICON_GOLD] Border Expansion Cost: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_PLOT_BUY_COST_MODIFIER', '[ICON_GOLD] Border Expansion Cost: {2_sign}{3_value}% in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_POPULATION_INSTANT', '[ICON_CITIZEN] Population: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_POPULATION_CHANGE', '[ICON_CITIZEN] Population: {3_value} in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_TECHS', '[ICON_TEAM_5] Free Technologies: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_POLICIES', '[ICON_TEAM_6] Free Social Policies: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_BORDER_OBSTACLE', '[ICON_MOVES] Slows Enemies in Friendly Territory', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_AIR_MODIFIER', '[ICON_RANGE_STRENGTH] Damage: {2_sign}{3_value}% from Air Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NUKE_MODIFIER', '[ICON_RANGE_STRENGTH] Damage: {2_sign}{3_value}% from Nukes', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_BUILDING', '[ICON_TEAM_9] Free Building: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_BUILDING_THIS_CITY', '[ICON_TEAM_9] Free Building: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_WATER', '[ICON_LOCKED] Must be next to Coast.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_RIVER', '[ICON_LOCKED] Must be on a River.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FRESH_WATER', '[ICON_LOCKED] Must be next to a River or Lake.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MOUNTAIN', '[ICON_LOCKED] Must be next to a Mountain.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NEARBY_TERRAIN_REQUIRED', '[ICON_LOCKED] Must be on or next to {{3_value}}.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_PROHIBITED_CITY_TERRAIN', '[ICON_LOCKED] Must not be on {{3_value}}.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NEARBY_MOUNTAIN_REQUIRED', '[ICON_LOCKED] Must be within 2 tiles of a Mountain in cultural borders.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HILL', '[ICON_LOCKED] Must be on a Hill.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FLAT', '[ICON_LOCKED] Must not be on a Hill.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING', '[ICON_LOCKED] Requires: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING_IN_CITIES', '[ICON_LOCKED] Requires: {3_value} in {4_extra} Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_BUILDING_IN_PERCENT_CITIES', '[ICON_LOCKED] Requires: {3_value} in {4_extra}% of Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_NEAR_ALL', '[ICON_LOCKED] Requires Nearby: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_NEAR_ANY', '[ICON_LOCKED] Requires Any Nearby: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_RESOURCE_CONSUMPTION', '[ICON_LOCKED] Uses: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_PRODUCTION_RESOURCES_REQUIRED', '[ICON_LOCKED] Uses:', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_OBSOLETE_TECH', '[ICON_PIRATE] Obsolete: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NATIONAL_LIMIT', '[ICON_LOCKED] National Limit: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_TEAM_LIMIT', '[ICON_LOCKED] Team Limit: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_WORLD_LIMIT', '[ICON_LOCKED] World Limit: {3_value}', '', '');
/* Added by Cep */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NOT_FEATURE', '[ICON_MINUS] Does not improve {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HEAL_RATE_CHANGE', '[ICON_PLUS] Heal Rate: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MINOR_FRIENDSHIP_CHANGE', '[ICON_INFLUENCE] Influence: +{3_value}% with all City-States', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MINOR_FRIENDSHIP_FLAT_CHANGE', '[ICON_INFLUENCE] Influence: +{3_value} with all City-States', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REQUIRES_TECH', '[ICON_LOCKED] Requires: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CULTURE_FROM_LAKES', '[ICON_CULTURE] Culture: {3_value} on Lake Tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_INSTANT_BORDER_RADIUS', '[ICON_CULTURE] Border Expansion: {3_value} tile range', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_INSTANT_BORDER_RADIUS', '[ICON_CULTURE] Border Expansion: {3_value} in all Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MOUNTAIN_IMPROVEMENT', '[ICON_WORKER] Improves a Mountain', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CITY_CAPTURE_CULTURE', '[ICON_CULTURE] Culture Looted from Conquered Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GREAT_GENERAL_RATE_CHANGE', '[ICON_GREAT_PEOPLE] Great General Points: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_TRADE_DEAL_MODIFIER', '[ICON_TRADE] Trade Deal Rewards: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HAPPINESS_INSTANT', '[ICON_GOLDEN_AGE] Instant Golden Age Points: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GOLDEN_AGE_POINTS', '[ICON_GOLDEN_AGE] Golden Age Points: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ALREADY_BUILT', '[ICON_LOCKED] Already Built', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REPLACES', '[ICON_PLUS] Replaces: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_INSTANT_BORDER_PLOTS', '[ICON_CULTURE] Border Expansion: {3_value}', '', '');
/* Expansion */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FOUNDS_RELIGION', '[ICON_RELIGION] Founds Religion: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_IS_RELIGIOUS', '[ICON_RELIGION] Is Religious: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_PLAYER_BORDER_OBSTACLE', '[ICON_BULLET] Player Border Obstacle: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NUKE_IMMUNE', '[ICON_RES_URANIUM] Immune to Nukes: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_AFFECT_SPIES_NOW', '[ICON_SPY] Affect Spies Now: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_UNLOCKED_BY_BELIEF', '[ICON_PEACE] Can Purchase with Religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_MIN_AREA_SIZE', '[ICON_LOCKED] Minimum Sea Size: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_CITIES_PREREQ', '[ICON_LOCKED] Requires Cities: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_LEVEL_PREREQ', '[ICON_LOCKED] Requires Level: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_AIRLIFT', '[ICON_AIR] Allows airlifts to or from this city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_NUKE_EXPLOSION_RAND', '[ICON_RES_URANIUM] Can cause nuclear explosion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ALLOWS_RANGE_STRIKE', '[ICON_RANGE_STRENGTH] Allows city attacks', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ESPIONAGE', '[ICON_SPY] Espionage: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXTRA_CITY_HIT_POINTS', '[ICON_HEAL] City Hitpoints: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXTRA_MISSIONARY_SPREADS', '[ICON_MISSIONARY] {3_value} extra spread for Missionaries from here', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_ESPIONAGE_MODIFIER', '[ICON_SPY] Spy Steal Rate: {2_sign}{3_value}% in this city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_GLOBAL_ESPIONAGE_MODIFIER', '[ICON_SPY] Spy Steal Rate: {2_sign}{3_value}% in all cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_EXTRA_SPIES', '[ICON_SPY] Extra Spies: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_SPY_RANK_CHANGE', '[ICON_SPY] Spy Rank: {2_sign}{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_INSTANT_SPY_RANK_CHANGE', '[ICON_SPY] Instant Spy Rank: {2_sign}{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_REPLACEMENT_BUILDING_CLASS', '[ICON_CHECKBOX] Replaces Building: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_SPECIALIST_EXTRA_CULTURE', '[ICON_CULTURE] Specialist Extra Culture: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_RELIGIOUS_PRESSURE_MODIFIER', '[ICON_PEACE] Religious Pressure: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_HOLY_CITY', '[ICON_LOCKED] Requires: Holy City', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-24'), 'TXT_KEY_BUILDING_EFFECT_FREE_RESOURCES', '{1_prefix} Free {4_extra}: {3_value}', '', '');
/* Expansion2 */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_THEMING_BONUS_HELP', '[ICON_GREAT_WORK] {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_NULLIFY_INFLUENCE_MODIFIER', '[ICON_TOURISM] Negates the Tourism bonus from other players'' Internet technology.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_LEAGUE_COST', '[ICON_TROPHY_GOLD] Congress Cost: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_UNLOCKED_BY_LEAGUE', '[ICON_TROPHY_GOLD] Unlocked By Congress: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_AIRLIFT', '[ICON_AIR] Allows airlifts to or from this city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_ALLOWS_FOOD_TRADE_ROUTES', '[ICON_INTERNATIONAL_TRADE] Can trade food to friendly cities.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_ALLOWS_PRODUCTION_TRADE_ROUTES', '[ICON_INTERNATIONAL_TRADE] Can trade production to friendly cities.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_RECIPIENT_BONUS', '[ICON_GOLD] Gold: {3_value} for Trade Routes from here', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_TARGET_BONUS', '[ICON_GOLD] Gold: {3_value} for Trade Routes to here', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_NUM_TRADE_ROUTE_BONUS', '[ICON_INTERNATIONAL_TRADE] Max Trade Routes: {2_sign}{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_INSTANT_MILITARY_INCREASE', '[ICON_WAR] Copies all units you own', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_LANDMARKS_TOURISM_PERCENT', '[ICON_TOURISM] Tourism: {2_sign}{3_value}% of the [ICON_CULTURE] Culture of wonders and improvements in this city add to tourism', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_GREAT_WORKS_TOURISM_MODIFIER', '[ICON_TOURISM] Tourism: {2_sign}{3_value}% from Great Works', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_X_BUILT_TRIGGERS_IDEOLOGY_CHOICE', '[ICON_CULTURE] Building {3_value} unlocks Ideologies', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_SEA_DISTANCE_MODIFIER', '[ICON_INTERNATIONAL_TRADE] Sea Trade Distance: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_SEA_GOLD_BONUS', '[ICON_GOLD] Sea Trade Gold: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_LAND_DISTANCE_MODIFIER', '[ICON_INTERNATIONAL_TRADE] Land Trade Distance: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TRADE_ROUTE_LAND_GOLD_BONUS', '[ICON_GOLD] Land Trade Gold: {2_sign}{3_value}%', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_GREAT_SCIENTIST_BEAKER_MODIFIER', '[ICON_RESEARCH] Great Scientist Beaker Modifier: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_TECH_ENHANCED_TOURISM', '[ICON_TOURISM] Tourism: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_POLICY_BRANCH_TYPE', '[ICON_LOCKED] Requires Policy: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_GREAT_WORK_SLOT_TYPE', '{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_GREAT_WORK_COUNT', '{3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_FREE_GREAT_WORK', '[ICON_GREAT_WORK] Free Great Work: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_EXTRA_LEAGUE_VOTES', '[ICON_CHECKBOX] Congress Votes: {3_value}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-09'), 'TXT_KEY_BUILDING_EFFECT_EXPERIENCE_PER_GREAT_WORK', '[ICON_WAR] Experience: {3_value} per Great Work', '', '');



UPDATE LoadedFile SET Value=1 WHERE Type='Text_TW_BuildingStats.sql';
