--· EN_US/Trade.sql
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SORT_BY_TRAIT', 'Sort by Trait', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SORT_BY_CS_NAME', 'Sort by City State Name', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SORT_BY_CS_ALLY', 'Sort by City State Ally', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SORT_BY_INFLUENCE', 'Sort by Influence', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DIPLO_DISCUSS_MESSAGE_DEC_FRIENDSHIP_TT', 'Doubles income from [ICON_RESEARCH] Research Agreements with this leader.[NEWLINE][NEWLINE]An alliance promotes friendly diplomacy and deters outside aggressors. Allies may request diplomatic or economic assistance, and failure to support your ally may upset them.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DIPLO_OPEN_BORDERS_TT', 'With [COLOR_YIELD_GOLD]mutual open borders[/COLOR], both players can pass through the other''s territory.[NEWLINE][NEWLINE](Lasts {1_Num} turns.)', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DIPLO_RESCH_AGREEMENT_TT', '[ICON_GOLD] Cost: {1_cost}[NEWLINE][NEWLINE]4% of the combined research of both players adds to your [ICON_RESEARCH] Science at the end of the agreement (8% if Allied).[NEWLINE][NEWLINE](Lasts {2_turns} turns.)', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_REFRESH', 'Refresh', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS', 'Trade', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_RESOURCE', '{1_iconstring} {2_resource}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_FROM', '{1_iconstring} Buy {2_resource}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_TO', '{1_iconstring} Sell {2_resource}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RESOURCE_DEMANDED_BY', 'Demanded By', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_POSSIBLE_DEALS', '{1_iconstring} [COLOR_POSITIVE_TEXT]{2_num}[ENDCOLOR] possible {3_type}.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CIV_STATUS', '{1_status}[NEWLINE]{1_era}[NEWLINE]{2_Num} Score', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RATE', 'Rate', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CLICK_TO_TRADE', 'Click to Trade[COLOR_POSITIVE_TEXT][ENDCOLOR]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_LASTS_TURNS', 'Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_EMBASSIES', 'embassies', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BORDER_DEALS', 'border deals', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RESEARCH_DEALS', 'research deals', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEFENSE_PACTS', 'defense pacts', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_ALLIANCES', 'alliances', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_EMBASSY_AGREEMENT', '[COLOR_YIELD_GOLD]Embassy[ENDCOLOR][NEWLINE]Allows Open Borders, Research Agreements, and Defensive Pacts. Also reveals Capitals.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_EMBASSY_YES_TT', '[COLOR_YIELD_GOLD]Propose Embassies[ENDCOLOR][NEWLINE]Allows Open Borders, Research Agreements, and Defensive Pacts. Also reveals Capitals.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_EMBASSY_NO_TT', 'We both have embassies.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_EMBASSY_US_TT', 'We have an embassy in their capital.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_EMBASSY_THEM_TT', 'They have an embassy in our capital.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_BORDER_AGREEMENT', '[COLOR_YIELD_GOLD]Mutual Open Borders[ENDCOLOR][NEWLINE]Allows units to pass through each other''s territory.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_BORDERS_YES_TT', '[COLOR_YIELD_GOLD]Propose mutual open borders[ENDCOLOR][NEWLINE]Allows units to pass through each other''s territory.[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_BORDERS_NO_TT', 'Mutual open borders active.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_BORDERS_US_TT', 'They gave us open borders.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_BORDERS_THEM_TT', 'We gave them open borders.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_RESEARCH_AGREEMENT', '[COLOR_RESEARCH_STORED]Research Agreement[ENDCOLOR][NEWLINE]4% of the combined research of both players adds to your [ICON_RESEARCH] Science at the end of the agreement (8% if Allied).', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_RA_YES_TT', '[COLOR_RESEARCH_STORED]Propose Research Agreement[ENDCOLOR][NEWLINE]4% of the combined research of both players adds to your [ICON_RESEARCH] Science at the end of the agreement (8% if Allied).[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_RA_NO_TT', 'Research Agreement active.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_DEFENSIVE_PACT', '[COLOR_CITY_BROWN]Defensive Pact[ENDCOLOR][NEWLINE]If an outsider declares war on either player, both players declare war on the outsider.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_DEFENSE_YES_TT', '[COLOR_CITY_BROWN]Propose Defensive Pact[ENDCOLOR][NEWLINE]If an outsider declares war on either player, both players declare war on the outsider.[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_DEFENSE_NO_TT', 'Defensive Pact active.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_GOLD_STORED', 'Gold Stored', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_GOLD_PROFIT', 'Gold Profit', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_ALLIANCE', '[COLOR_GREEN]Ally[ENDCOLOR][NEWLINE]Promotes friendly relations.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_YES_TT', '[COLOR_GREEN]Propose Alliance[ENDCOLOR][NEWLINE]Promotes friendly relations.[NEWLINE][NEWLINE]Lasts {1_num} turns.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_STATUS_ALLIANCE_NO_TT', 'We are allied.', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_DENOUNCED_US', '[COLOR_ORANGE]They denounced us[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_DENOUNCED_THEM', '[COLOR_ORANGE]We denounced them[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_DENOUNCED_BOTH', '[COLOR_NEGATIVE_TEXT]We denounced them[NEWLINE]They denounced us[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_AT_WAR_LARGE', '[COLOR_NEGATIVE_TEXT]- AT WAR -[ENDCOLOR]', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEAL_PEACE_TREATY', 'Peace Treaty', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS', 'City States', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_CITY_STATE', 'City State', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_ALLIED_WITH', 'Allied With', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_PROTECTED_BY', 'Protected By', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUESTS', 'Quest(s)', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_INFLUENCE', 'Influence', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_WAR', 'War', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_GIFT_GOLD', 'Gift Gold', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_PROTECT_TT', '{1} is protected by[NEWLINE]{2}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_NO_PROTECT_TT', '{1} is protected by nobody', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_TT', '{1} has requested you to[NEWLINE]{2}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_NO_QUEST_TT', '{1} currently has no requests', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_WAR_WITH_PLAYERS', 'Fight {1_PlayerNames}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_BARBARIANS', 'Kill Barbarians', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_ROUTE', 'Construct Road', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_KILL_CAMP', 'Destroy Encampment', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_CONNECT_RESOURCE', 'Connect {1_ResourceName:textkey}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_CONSTRUCT_WONDER', 'Build {1_WonderName:textkey}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_GREAT_PERSON', 'Attract {1_UnitName:textkey}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_KILL_CITY_STATE', 'Destroy {1_CityStateName:textkey}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_FIND_PLAYER', 'Find {1_CivName:textkey}', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_QUEST_FIND_NATURAL_WONDER', 'Find Natural Wonder', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_PEACE_TT', 'At war, may make peace', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_WAR_TT', 'At war, peace blocked', '', '');
INSERT INTO Civup_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DO_CS_STATUS_GIFT_INFLUENCE_TT', '{1_Num}[ICON_GOLD] for [COLOR_POSITIVE_TEXT]+{2_Num} Influence[ENDCOLOR]', '', '');
